import type { WorkflowEntrypoint, WorkflowEntrypoints } from "./consolidation-types";
import { buildConsolidationStableKey } from "./consolidation-types";

const ITEMS: readonly Omit<WorkflowEntrypoint, "id">[] = [
  { label: "Product Simplification", route: "/start", readiness: "ready", missingPieces: [], safetyBoundary: "UX/product layer only; guided Start route, compact safety badges, collapsed advanced details, no command execution, no file writes, and no Brain graph mutation.", nextImplementationPhase: "Real Workflow Wizard v1", recommendedValidation: "Product Simplification smoke, build, managed smoke, and git diff --check." },
  { label: "File Reader v1", route: "/files", readiness: "ready", missingPieces: [], safetyBoundary: "File Reader v1 functional/read-only; no file writes without approval, no command execution, no Brain graph mutation, no auto-persistence.", nextImplementationPhase: "Phase 57 Real Patch Preview v1", recommendedValidation: "Local Project Reader smoke, Files smoke, and git diff --check." },
  { label: "Patch Preview v1", route: "/files", readiness: "ready", missingPieces: [], safetyBoundary: "Patch Preview v1 functional/preview-only; no apply, no file writes, no command execution, no Brain graph mutation, and Patch Application Gate before future apply.", nextImplementationPhase: "Phase 58 Approved Patch Apply v1", recommendedValidation: "Real Patch Preview smoke, Patch Preview smoke, Local Project Reader smoke, and git diff --check." },
  { label: "Approved Patch Apply v1", route: "/files", readiness: "needs-review", missingPieces: ["Guarded apply execution remains request-ready/blocked until safe API bridge is available"], safetyBoundary: "Approved Patch Apply v1 approval-gated/request-ready; no direct apply-diff from UI, no direct write-file call from UI, no command execution, rollback plan required, validation plan required.", nextImplementationPhase: "Phase 59 Validation Runner v1", recommendedValidation: "Approved Patch Apply smoke, build, server smoke, and git diff --check." },
  { label: "Validation Runner v1", route: "/validation", readiness: "needs-review", missingPieces: ["Guarded command execution remains request-ready/manual-only until a safe operator run API exists"], safetyBoundary: "Validation Runner v1 approval-gated/request-ready; allowlisted commands only, no arbitrary shell, no direct command execution from UI, no file writes, no Brain graph mutation.", nextImplementationPhase: "Phase 60 Closed Loop Fix Workflow", recommendedValidation: "Validation Runner smoke, build, server smoke, and git diff --check." },
  { label: "Apply Validation Hardening", route: "/apply-validation", readiness: "needs-review", missingPieces: ["Real apply guard review remains approval-gated"], safetyBoundary: "Reliability layer for reviewable diff, apply policy, rollback plan, validation command selection, output capture, result routing, and completion guidance; no auto-apply and no auto-run.", nextImplementationPhase: "Workflow Result Persistence or Real Apply Guard Review", recommendedValidation: "Apply Validation Hardening smoke, build, server smoke, and git diff --check." },
  { label: "Closed Loop Fix Workflow", route: "/ai", readiness: "needs-review", missingPieces: ["Regression triage to fix queue", "Fix queue to patch preview", "Post-apply verification"], safetyBoundary: "No auto-fix, no auto-rollback, and review before each handoff.", nextImplementationPhase: "Phase 58 Closed Loop Repair", recommendedValidation: "Regression triage and fix queue smoke." },
  { label: "Creative Local Bridge v1", route: "/creative-bridge", readiness: "needs-review", missingPieces: ["Future guarded executor for actual local renders"], safetyBoundary: "Preview-only/request-ready; no Blender, ComfyUI, Unreal, video render, command, provider, or artifact file execution from UI.", nextImplementationPhase: "Blender Adapter Preview v1", recommendedValidation: "Creative Local Bridge smoke, Creative Production Studio smoke, and Capability Cockpit smoke." },
  { label: "Blender Adapter Preview v1", route: "/blender", readiness: "needs-review", missingPieces: ["Future guarded creative executor for actual Blender execution"], safetyBoundary: "Preview-only/request-ready; no Blender execution, no Python execution, no render execution, no file writes, and future executor boundary required.", nextImplementationPhase: "ComfyUI Adapter Preview v1 or future guarded creative executor", recommendedValidation: "Blender Adapter Preview smoke, build, and git diff --check." },
  { label: "Unreal Adapter Preview v1", route: "/unreal", readiness: "needs-review", missingPieces: ["Future guarded creative executor for actual Unreal execution"], safetyBoundary: "Preview-only/request-ready; no Unreal execution, no Unreal Editor launch, no Python or Blueprint automation, no render execution, no package/build, no file writes, and future executor boundary required.", nextImplementationPhase: "Future Guarded Creative Executor or Video Render Job Preview", recommendedValidation: "Unreal Adapter Preview smoke, build, and git diff --check." },
  { label: "Video Render Job Preview v1", route: "/video-render", readiness: "needs-review", missingPieces: ["Future guarded creative executor for actual render execution"], safetyBoundary: "Preview-only/request-ready; no render execution, no Blender execution, no ComfyUI execution, no Unreal execution, no ffmpeg execution, no command execution, no file writes, and future executor boundary required.", nextImplementationPhase: "Future Guarded Creative Executor", recommendedValidation: "Video Render Job Preview smoke, build, and git diff --check." },
  { label: "Guarded Creative Executor", route: "/creative-executor", readiness: "needs-review", missingPieces: ["Future local execution sandbox remains disabled"], safetyBoundary: "Dry-run-first/request-ready; real execution disabled, approval packet required, kill-switch plan required, artifact capture plan required, no render execution, no command execution, and no file writes.", nextImplementationPhase: "Local Bridge Health Check v1 or Creative Execution Sandbox", recommendedValidation: "Guarded Creative Executor smoke, build, and git diff --check." },
  { label: "Creative Execution Sandbox", route: "/creative-sandbox", readiness: "needs-review", missingPieces: ["Future Guarded Health Probe", "Real Creative Executor MVP"], safetyBoundary: "Simulation-only; fake lifecycle, cancellation, artifact placeholders, logs, verification, and review handoff only. No real execution, no render execution, no command execution, no local HTTP calls, and no file writes.", nextImplementationPhase: "Future Guarded Health Probe or Real Creative Executor MVP", recommendedValidation: "Creative Execution Sandbox smoke, build, and git diff --check." },
  { label: "Real Creative Executor Readiness", route: "/creative-readiness", readiness: "needs-review", missingPieces: ["Phase 71 Future Guarded Health Probe"], safetyBoundary: "Audit-only readiness review; no Blender, ComfyUI, Unreal, ffmpeg, renderer, local HTTP, command, render, provider, artifact write, or local app execution from UI. Execution allowed false.", nextImplementationPhase: "Phase 71 Future Guarded Health Probe", recommendedValidation: "Real Creative Executor Readiness smoke, build, and git diff --check." },
  { label: "Local Bridge Health", route: "/local-bridge-health", readiness: "needs-review", missingPieces: ["Future guarded health probe remains disabled"], safetyBoundary: "Preview/manual-only/future-guarded; no Blender, ComfyUI, Unreal, ffmpeg, renderer, local HTTP, command, render, or artifact write execution from UI.", nextImplementationPhase: "Future Guarded Health Probe or Creative Execution Sandbox", recommendedValidation: "Local Bridge Health smoke, build, and git diff --check." },
  { label: "Future Guarded Health Probe", route: "/health-probe", readiness: "needs-review", missingPieces: ["Real probes disabled by default"], safetyBoundary: "Metadata/manual-first/request-ready; no creative job execution, no render execution, no arbitrary command, no arbitrary endpoint, no local HTTP call by default, no file writes, no Brain mutation, and no automatic persistence.", nextImplementationPhase: "Real Creative Executor MVP Design only if readiness passes", recommendedValidation: "Future Guarded Health Probe smoke, build, and git diff --check." },
  { label: "Real Creative Executor MVP Design", route: "/creative-mvp", readiness: "needs-review", missingPieces: ["Future implementation boundary remains blocked"], safetyBoundary: "Design-only; chooses artifact-capture-only as first safe MVP candidate, no real execution, no render execution, no command execution, no local HTTP calls, no file writes, and execution allowed false.", nextImplementationPhase: "Phase 73 User-Friendly Product Simplification or Phase 73.5 Real Executor MVP Implementation Plan", recommendedValidation: "Real Creative Executor MVP Design smoke, build, and git diff --check." },
  { label: "Runtime Memory Promotion v1", route: "/memory-inbox", readiness: "blocked", missingPieces: ["Promotion approval", "Runtime event executor", "Journal result review"], safetyBoundary: "No auto-promote memory and no appendEvent from UI.", nextImplementationPhase: "Future guarded runtime memory promotion", recommendedValidation: "Memory promotion gate and runtime journal smoke." },
];

export function buildWorkflowEntrypoint(input: Omit<WorkflowEntrypoint, "id">): WorkflowEntrypoint {
  return { id: buildConsolidationStableKey("workflow", input.label), ...input };
}

export function buildWorkflowEntrypoints(): WorkflowEntrypoints {
  const items = ITEMS.map(buildWorkflowEntrypoint);
  const readyCount = items.filter((item) => item.readiness === "ready").length;
  return {
    id: "workflow-entrypoints",
    items,
    readyCount,
    summary: summarizeWorkflowEntrypoints({ items, readyCount }),
  };
}

export function summarizeWorkflowEntrypoints(model: Pick<WorkflowEntrypoints, "items" | "readyCount">): string[] {
  return [
    `${model.items.length} workflow entrypoints are defined including File Reader v1 functional/read-only, Patch Preview v1 functional/preview-only, Approved Patch Apply v1 approval-gated/request-ready, Validation Runner v1, and Apply Validation Hardening.`,
    `${model.readyCount} workflows are ready; the rest remain review-required or blocked until approval boundaries exist.`,
    "Phase 60 Closed Loop Fix Workflow is the recommended next phase after Validation Runner v1 review; Creative Local Bridge v1 routes through /creative-bridge, Blender Adapter Preview v1 points to /blender, Unreal Adapter Preview v1 points to /unreal, Video Render Job Preview v1 points to /video-render, Guarded Creative Executor points to /creative-executor, Creative Execution Sandbox points to /creative-sandbox, Real Creative Executor Readiness should point to /creative-readiness, and Real Creative Executor MVP Design should point to /creative-mvp.",
  ];
}
