export const JARVIS_VIDEO_DRY_RUN_WORKSPACE_SHARED_MARKERS = [
  "3786-3817 - First Jarvis-Controlled Video Dry Run Workspace",
  "3786-3817 - First Jarvis-Controlled Video Dry Run Workspace Mega Batch v1",
  "First Jarvis-Controlled Video Dry Run Workspace",
  "Jarvis-controlled video dry-run workspace only",
  "/jarvis-video dry-run workspace remains review-only",
  "user goal review only",
  "video.generate dry-run request envelope review only",
  "video capability selection review only",
  "video adapter route review only",
  "video permission decision review only",
  "video approval requirement review only",
  "redacted prompt preview only",
  "provider reference review only",
  "credential reference review only",
  "token reference review only",
  "cost guard review only",
  "rate guard review only",
  "timeout guard review only",
  "duration guard review only",
  "resolution guard review only",
  "size guard review only",
  "privacy guard review only",
  "safety guard review only",
  "result placeholder only",
  "artifact handoff placeholder only",
  "audit preview only",
  "result ledger preview only",
  "status preview only",
  "memory boundary preview only",
  "kill switch check required",
  "lock manager check required",
  "idempotency check required",
  "replay block check required",
  "blocked action summary only",
  "operator review required before video execution",
  "video dry-run workspace completion does not enable provider/render/export/publish/workers/trading/automation",
  "disabled by default",
  "hard kill switch",
  "dry-run only",
  "dry-run required before execution",
  "backend-only execution path required",
  "no direct frontend execution",
  "no live provider call",
  "no provider execution",
  "no live provider execution",
  "no video provider execution",
  "no real video generation",
  "no live video generation",
  "no image provider execution",
  "no audio provider execution",
  "no website creation execution",
  "no avatar generation execution",
  "no chatbot autonomous execution",
  "no trading execution",
  "no paper trading execution",
  "no real-money trading execution",
  "no tool execution",
  "no autonomous tool execution",
  "no network execution",
  "no render execution",
  "no export execution",
  "no publish execution",
  "no worker dispatch",
  "no file export",
  "no download generation",
  "no archive creation",
  "no signed URL creation",
  "no platform upload",
  "no media upload",
  "no OAuth flow creation",
  "no webhook creation",
  "no schedule execution",
  "no account authorization execution",
  "no API route execution",
  "no service creation",
  "no runtime deploy",
  "no file writes from the app",
  "no shell/process/command execution from the app",
  "no fetch/network calls",
  "no provider SDK imports in frontend",
  "no frontend provider key reads",
  "no plaintext secrets",
  "no localStorage",
  "no sessionStorage",
  "no IndexedDB",
  "no cookies",
  "no browser storage for secrets",
  "next likely batch: 3818-3849 - First Jarvis-Controlled Video Approval Packet Workspace",
] as const;

export const JARVIS_VIDEO_DRY_RUN_WORKSPACE_DISPLAY_MARKERS = [
  "Jarvis-controlled video dry-run workspace only",
  "/jarvis-video dry-run workspace remains review-only",
  "video capability selection review only",
  "video adapter route review only",
  "video.generate dry-run request envelope review only",
  "audit preview only",
  "operator review required before video execution",
  "disabled by default",
  "hard kill switch",
  "dry-run only",
] as const;

export const JARVIS_VIDEO_DRY_RUN_WORKSPACE_EXECUTION_BLOCKS = [
  "no direct frontend execution",
  "no live provider call",
  "no provider execution",
  "no live provider execution",
  "no video provider execution",
  "no real video generation",
  "no live video generation",
  "no image provider execution",
  "no audio provider execution",
  "no website creation execution",
  "no avatar generation execution",
  "no chatbot autonomous execution",
  "no trading execution",
  "no paper trading execution",
  "no real-money trading execution",
  "no tool execution",
  "no autonomous tool execution",
  "no network execution",
  "no render execution",
  "no export execution",
  "no publish execution",
  "no worker dispatch",
  "no file export",
  "no download generation",
  "no archive creation",
  "no signed URL creation",
  "no platform upload",
  "no media upload",
  "no OAuth flow creation",
  "no webhook creation",
  "no schedule execution",
  "no account authorization execution",
  "no API route execution",
  "no service creation",
  "no runtime deploy",
] as const;

export const JARVIS_VIDEO_DRY_RUN_WORKSPACE_STORAGE_BOUNDARIES = [
  "no file writes from the app",
  "no shell/process/command execution from the app",
  "no fetch/network calls",
  "no provider SDK imports in frontend",
  "no frontend provider key reads",
  "no plaintext secrets",
  "no localStorage",
  "no sessionStorage",
  "no IndexedDB",
  "no cookies",
  "no browser storage for secrets",
] as const;
