export const UNIVERSAL_EXECUTION_REVIEW_SAFETY_MARKERS = [
  "review-only",
  "approval required",
  "approval required before execution",
  "not executable yet",
  "no action execution from UI",
  "no file write/delete/mutation",
  "no command execution",
  "no shell/git/test/build/smoke execution from UI",
  "no local runtime start",
  "no local bridge endpoint calls",
  "no provider/model calls",
  "no prompt sending",
  "no connector calls",
  "no connector fetch/mutation",
  "no connector data storage",
  "no automation/schedule/reminder/task/watch creation",
  "no polling loop creation",
  "no background job creation",
  "no notification sending",
  "no evidence capture/ingestion",
  "no memory/RAG ingestion",
  "no output/result storage",
  "no output storage",
  "no recovery/retry trigger",
  "no package/export/write behavior",
  "no creative asset generation",
  "no video generation",
  "no image generation",
  "no 3D generation",
  "no research browsing/searching/fetching",
  "no chatbot/agent creation/deployment",
  "no video-call joining/monitoring",
  "no monitoring job creation",
  "no Minecraft/project/server build execution",
  "no server launch",
  "no copyrighted franchise asset/name/logo/map/dialogue/music copying",
  "no approval automation",
  "no approval decision persistence",
  "no policy auto-apply",
  "no settings persistence",
  "no preference persistence",
  "no patch apply behavior",
  "no web/search API calls",
  "no GitHub API calls from UI",
  "no prompt/file/project/connector/provider/model/output/audit/evidence/automation/live/beta/policy/settings/daily/rollout/release/boundary/e2e/activation/launch data sending without approval",
  "no arbitrary project scanning",
  "no arbitrary local file browsing",
  "no arbitrary path crawling",
  "no arbitrary file read/open from UI",
  "no auto-open local files",
  "no memory auto-promotion",
  "no Brain graph mutation",
  "no appendEvent/saveBrainGraph calls from UI",
  "no direct appendEvent call from UI",
  "no direct saveBrainGraph call from UI",
  "no direct apply-diff call from UI",
  "no direct write-file call from UI",
  "no direct run-command call from UI",
  "no plugin execution",
  "no tool execution",
  "no agent execution",
  "no extension runtime executor",
  "no MCP runtime",
  "no MCP tool calls",
  "no localStorage API key storage",
  "no sessionStorage API key storage",
  "no token storage",
  "no endpoint storage",
  "no credential storage",
  "no process.env printing",
  "no API keys or secrets displayed",
  "no example real key/token/endpoint values",
  "no route coverage removal",
  "no duplicate route hrefs",
  "no duplicate shortLabel values",
  "no obvious duplicate React key patterns",
  "no Ruflo/Odysseus vendoring",
  "no package install behavior",
  "checkpoint documentation smoke still exists and remains registered",
  "server-only path boundary markers remain intact",
  "no Math.random",
  "no Date.now",
  "no Date.now for deterministic layout/ids",
  "no mojibake",
] as const;
