export const JARVIS_VIDEO_CONTROLLED_EXECUTION_TRIAL_SHARED_MARKERS = [
  "3946-3977 - First Jarvis-Controlled Video Controlled Execution Trial",
  "3946-3977 - First Jarvis-Controlled Video Controlled Execution Trial Mega Batch v1",
  "First Jarvis-Controlled Video Controlled Execution Trial",
  "Jarvis-controlled video controlled execution trial only",
  "controlled trial console only",
  "/jarvis-video controlled trial remains review-only",
  "controlled execution trial remains disabled",
  "controlled execution trial remains backend-owned",
  "controlled execution trial requires explicit operator approval",
  "approved dry-run reference required",
  "approved approval packet reference required",
  "approved video adapter reference required",
  "backend execution readiness reference required",
  "operator preflight checklist required",
  "provider reference review only",
  "credential reference review only",
  "token redaction review only",
  "request envelope review only",
  "response envelope review only",
  "error envelope review only",
  "prompt redaction review only",
  "cost rate timeout review only",
  "duration resolution size review only",
  "privacy safety gate review only",
  "audit observability review only",
  "result placeholder only",
  "artifact handoff placeholder only",
  "kill switch remains enforced",
  "single-call lock required",
  "idempotency required",
  "replay block required",
  "disabled launch lane",
  "blocked action summary only",
  "operator review required before video execution",
  "controlled execution trial completion does not enable provider/render/export/publish/workers/trading/automation",
  "disabled by default",
  "hard kill switch",
  "backend-only execution path required",
  "no direct frontend execution",
  "no live provider call",
  "no provider execution",
  "no live provider execution",
  "no video provider execution",
  "no real video generation",
  "no live video generation",
  "no image provider execution",
  "no audio provider execution",
  "no website creation execution",
  "no avatar generation execution",
  "no chatbot autonomous execution",
  "no trading execution",
  "no paper trading execution",
  "no real-money trading execution",
  "no financial advice",
  "no personalised recommendations",
  "no buy sell instructions",
  "no broker execution",
  "no live market data calls",
  "no tool execution",
  "no autonomous tool execution",
  "no network execution",
  "no render execution",
  "no export execution",
  "no publish execution",
  "no worker dispatch",
  "no file export",
  "no download generation",
  "no archive creation",
  "no signed URL creation",
  "no platform upload",
  "no media upload",
  "no OAuth flow creation",
  "no webhook creation",
  "no schedule execution",
  "no account authorization execution",
  "no API route execution",
  "no service creation",
  "no runtime deploy",
  "no file writes from the app",
  "no shell/process/command execution from the app",
  "no fetch/network calls",
  "no provider SDK imports in frontend",
  "no frontend provider key reads",
  "no plaintext secrets",
  "no localStorage",
  "no sessionStorage",
  "no IndexedDB",
  "no cookies",
  "no browser storage for secrets",
  "Controlled trial is locked",
  "Backend-owned execution required",
  "Operator approval required",
  "No provider call from frontend",
  "No real video generation yet",
  "next likely batch: 3978-4009 - First Jarvis-Controlled Video Backend Trial Runner Contract",
] as const;

export const JARVIS_VIDEO_CONTROLLED_EXECUTION_TRIAL_DISPLAY_MARKERS = [
  "Controlled trial is locked",
  "Backend-owned execution required",
  "Operator approval required",
  "No provider call from frontend",
  "No real video generation yet",
  "controlled trial console only",
  "disabled launch lane",
] as const;

export const JARVIS_VIDEO_CONTROLLED_EXECUTION_TRIAL_BLOCKED_POSTURES = [
  "no direct frontend execution",
  "no live provider call",
  "no provider execution",
  "no live provider execution",
  "no video provider execution",
  "no real video generation",
  "no live video generation",
  "no network execution",
  "no render execution",
  "no export execution",
  "no publish execution",
  "no worker dispatch",
] as const;

export const JARVIS_VIDEO_CONTROLLED_EXECUTION_TRIAL_EXECUTION_BLOCKS = [
  "no image provider execution",
  "no audio provider execution",
  "no website creation execution",
  "no avatar generation execution",
  "no chatbot autonomous execution",
  "no trading execution",
  "no paper trading execution",
  "no real-money trading execution",
  "no financial advice",
  "no personalised recommendations",
  "no buy sell instructions",
  "no broker execution",
  "no live market data calls",
  "no tool execution",
  "no autonomous tool execution",
  "no file export",
  "no download generation",
  "no archive creation",
  "no signed URL creation",
  "no platform upload",
  "no media upload",
  "no OAuth flow creation",
  "no webhook creation",
  "no schedule execution",
  "no account authorization execution",
  "no API route execution",
  "no service creation",
  "no runtime deploy",
  "controlled execution trial completion does not enable provider/render/export/publish/workers/trading/automation",
] as const;

export const JARVIS_VIDEO_CONTROLLED_EXECUTION_TRIAL_STORAGE_BOUNDARIES = [
  "no file writes from the app",
  "no shell/process/command execution from the app",
  "no fetch/network calls",
  "no provider SDK imports in frontend",
  "no frontend provider key reads",
  "no plaintext secrets",
  "no localStorage",
  "no sessionStorage",
  "no IndexedDB",
  "no cookies",
  "no browser storage for secrets",
] as const;
