import type { ReactNode } from "react";

export type CodexForgeNavigationRouteId =
  | "home"
  | "start"
  | "onboarding"
  | "first-task"
  | "safety-coach"
  | "help-empty-states"
  | "assisted-quality"
  | "assist"
  | "code-flow"
  | "code-flow-live-run"
  | "code-flow-manual-trial"
  | "code-flow-friction-fixes"
  | "code-flow-mvp-path"
  | "code-flow-release-audit"
  | "code-flow-rc"
  | "code-flow-final-polish"
  | "code-flow-trial"
  | "code-flow-trial-review"
  | "code-flow-ux-fixes"
  | "apply-guard-review"
  | "guarded-apply-candidate"
  | "guarded-apply-mvp"
  | "guarded-apply-trial-hardening"
  | "apply-evidence"
  | "apply-validation"
  | "validation-results"
  | "review-inbox"
  | "recovery"
  | "workflow-results"
  | "run-history"
  | "release-smoke"
  | "demo"
  | "product-trial"
  | "runbook"
  | "mvp-experience"
  | "ai"
  | "ai-router"
  | "ai-providers"
  | "provider-adapters"
  | "provider-health"
  | "local-machine"
  | "local-creative"
  | "comfyui-health"
  | "comfyui-health-gate"
  | "comfyui-real-health"
  | "comfyui-metadata"
  | "comfyui-metadata-reader"
  | "video-workflows"
  | "video-jobs"
  | "video-prompt"
  | "storyboard"
  | "keyframes"
  | "local-draft-review"
  | "local-image"
  | "local-keyframes"
  | "local-video-draft"
  | "comfyui-workflow-import"
  | "comfyui-workflow-safety"
  | "comfyui-workflow-parameters"
  | "comfyui-job-package"
  | "comfyui-workflow-dry-run"
  | "workflow-package-validator"
  | "comfyui-submit"
  | "comfyui-submit-trial"
  | "comfyui-workflow-library"
  | "workflow-template-import-shelf"
  | "workflow-compatibility-checker"
  | "missing-model-node-resolver"
  | "local-model-manager"
  | "ollama-model-planner"
  | "lm-studio-runtime-planner"
  | "local-llm-creative-assistant"
  | "local-image-trial"
  | "local-keyframe-trial"
  | "local-video-draft-trial"
  | "local-output-capture"
  | "video-capture"
  | "video-artifacts"
  | "video-review"
  | "creative-memory"
  | "style-presets"
  | "consistency-kit"
  | "shot-library"
  | "video-projects"
  | "video-assets"
  | "render-history"
  | "video-export"
  | "cloud-video-providers"
  | "cloud-final-render"
  | "local-vs-cloud"
  | "video-safety-audit"
  | "video-recovery"
  | "video-compare"
  | "video-upscale"
  | "video-interpolation"
  | "video-finishing"
  | "video-final-render"
  | "creative-cost-router"
  | "gpu-scheduler"
  | "dual-gpu"
  | "render-queue"
  | "local-render-queue-persistence"
  | "render-job-status"
  | "render-job-control-boundary"
  | "render-queue-recovery"
  | "local-video-preview"
  | "artifact-thumbnails"
  | "draft-playback-review"
  | "export-package-builder"
  | "env-readiness"
  | "local-provider-probes"
  | "provider-tests"
  | "provider-live-test-gate"
  | "openai-compatible-live-test"
  | "claude-anthropic-live-test"
  | "multi-provider-live-test"
  | "provider-test-results"
  | "provider-cost-latency-comparison"
  | "router-recommendation-review"
  | "provider-failure-recovery"
  | "provider-budget-guardrails"
  | "prompt-privacy-classifier"
  | "provider-audit-log"
  | "provider-settings-review"
  | "provider-policy-bundle"
  | "provider-runbook-generator"
  | "local-first-router-dry-run"
  | "provider-governance-release-audit"
  | "jarvisd-contract"
  | "jarvisd-health"
  | "jarvisd-capabilities"
  | "jarvisd-permissions"
  | "local-file-approval"
  | "local-command-approval"
  | "local-process-monitor"
  | "workspace-trust-policy"
  | "safe-project-indexer"
  | "project-file-search"
  | "project-dependency-map"
  | "project-risk-secrets-scan"
  | "model-capabilities"
  | "task-router"
  | "credentials"
  | "provider-setup"
  | "token-router"
  | "brain"
  | "files"
  | "tasks"
  | "closed-loop"
  | "memory"
  | "memory-inbox"
  | "runtime-journal"
  | "runtime-replay"
  | "brain-snapshots"
  | "snapshot-restore"
  | "brain-continuity"
  | "handoff"
  | "brain-governance"
  | "creative"
  | "artifacts-review"
  | "video-render"
  | "creative-executor"
  | "creative-sandbox"
  | "creative-readiness"
  | "creative-mvp"
  | "health-probe"
  | "local-bridge-health"
  | "blender"
  | "unreal"
  | "comfyui"
  | "creative-bridge"
  | "capabilities"
  | "activity"
  | "readiness"
  | "repo-hygiene"
  | "quality-audit"
  | "consolidation"
  | "validation"
  | "stabilization"
  | "history";

export type CodexForgeNavigationRouteHref =
  | "/"
  | "/start"
  | "/onboarding"
  | "/first-task"
  | "/safety-coach"
  | "/help-empty-states"
  | "/assisted-quality"
  | "/assist"
  | "/code-flow"
  | "/code-flow/live-run"
  | "/code-flow/manual-trial"
  | "/code-flow/friction-fixes"
  | "/code-flow/mvp-path"
  | "/code-flow/release-audit"
  | "/code-flow/rc"
  | "/code-flow/final-polish"
  | "/code-flow/trial"
  | "/code-flow/trial-review"
  | "/code-flow/ux-fixes"
  | "/apply-guard-review"
  | "/guarded-apply-candidate"
  | "/guarded-apply-mvp"
  | "/guarded-apply-mvp/trial-hardening"
  | "/apply-evidence"
  | "/apply-validation"
  | "/validation-results"
  | "/review-inbox"
  | "/recovery"
  | "/workflow-results"
  | "/run-history"
  | "/release-smoke"
  | "/demo"
  | "/product-trial"
  | "/runbook"
  | "/mvp-experience"
  | "/ai"
  | "/ai-router"
  | "/ai-providers"
  | "/provider-adapters"
  | "/provider-health"
  | "/local-machine"
  | "/local-creative"
  | "/comfyui-health"
  | "/comfyui-health/gate"
  | "/comfyui-real-health"
  | "/comfyui-metadata"
  | "/comfyui-metadata-reader"
  | "/video-workflows"
  | "/video-jobs"
  | "/video-prompt"
  | "/storyboard"
  | "/keyframes"
  | "/local-draft-review"
  | "/local-image"
  | "/local-keyframes"
  | "/local-video-draft"
  | "/comfyui-workflows/import"
  | "/comfyui-workflows/safety"
  | "/comfyui-workflows/parameters"
  | "/comfyui-jobs/package"
  | "/comfyui-workflows/dry-run"
  | "/workflow-package-validator"
  | "/comfyui-submit"
  | "/comfyui-submit-trial"
  | "/comfyui-workflow-library"
  | "/workflow-template-import-shelf"
  | "/workflow-compatibility-checker"
  | "/missing-model-node-resolver"
  | "/local-model-manager"
  | "/ollama-model-planner"
  | "/lm-studio-runtime-planner"
  | "/local-llm-creative-assistant"
  | "/local-image-trial"
  | "/local-keyframe-trial"
  | "/local-video-draft-trial"
  | "/local-output-capture"
  | "/video-capture"
  | "/video-artifacts"
  | "/video-review"
  | "/creative-memory"
  | "/style-presets"
  | "/consistency-kit"
  | "/shot-library"
  | "/video-projects"
  | "/video-assets"
  | "/render-history"
  | "/video-export"
  | "/cloud-video-providers"
  | "/cloud-final-render"
  | "/local-vs-cloud"
  | "/video-safety-audit"
  | "/video-recovery"
  | "/video-compare"
  | "/video-upscale"
  | "/video-interpolation"
  | "/video-finishing"
  | "/video-final-render"
  | "/creative-cost-router"
  | "/gpu-scheduler"
  | "/dual-gpu"
  | "/render-queue"
  | "/local-render-queue-persistence"
  | "/render-job-status"
  | "/render-job-control-boundary"
  | "/render-queue-recovery"
  | "/local-video-preview"
  | "/artifact-thumbnails"
  | "/draft-playback-review"
  | "/export-package-builder"
  | "/env-readiness"
  | "/local-provider-probes"
  | "/provider-tests"
  | "/provider-live-test-gate"
  | "/openai-compatible-live-test"
  | "/claude-anthropic-live-test"
  | "/multi-provider-live-test"
  | "/provider-test-results"
  | "/provider-cost-latency-comparison"
  | "/router-recommendation-review"
  | "/provider-failure-recovery"
  | "/provider-budget-guardrails"
  | "/prompt-privacy-classifier"
  | "/provider-audit-log"
  | "/provider-settings-review"
  | "/provider-policy-bundle"
  | "/provider-runbook-generator"
  | "/local-first-router-dry-run"
  | "/provider-governance-release-audit"
  | "/jarvisd-contract"
  | "/jarvisd-health"
  | "/jarvisd-capabilities"
  | "/jarvisd-permissions"
  | "/local-file-approval"
  | "/local-command-approval"
  | "/local-process-monitor"
  | "/workspace-trust-policy"
  | "/safe-project-indexer"
  | "/project-file-search"
  | "/project-dependency-map"
  | "/project-risk-secrets-scan"
  | "/model-capabilities"
  | "/task-router"
  | "/credentials"
  | "/provider-setup"
  | "/token-router"
  | "/brain"
  | "/files"
  | "/tasks"
  | "/closed-loop"
  | "/memory"
  | "/memory-inbox"
  | "/runtime-journal"
  | "/runtime-replay"
  | "/brain-snapshots"
  | "/snapshot-restore"
  | "/brain-continuity"
  | "/handoff"
  | "/brain-governance"
  | "/creative"
  | "/artifacts/review"
  | "/video-render"
  | "/creative-executor"
  | "/creative-sandbox"
  | "/creative-readiness"
  | "/creative-mvp"
  | "/health-probe"
  | "/local-bridge-health"
  | "/blender"
  | "/unreal"
  | "/comfyui"
  | "/creative-bridge"
  | "/capabilities"
  | "/activity"
  | "/readiness"
  | "/repo-hygiene"
  | "/quality-audit"
  | "/consolidation"
  | "/validation"
  | "/stabilization"
  | "/history";

export type CodexForgeNavigationGroup =
  | "Start"
  | "Build"
  | "Fix"
  | "Brain"
  | "Memory"
  | "Creative"
  | "Audit"
  | "Advanced";

export type CodexForgeNavigationReadiness =
  | "available"
  | "review-required"
  | "preview-only"
  | "blocked";

export type CodexForgeNavigationSafetyPosture =
  | "local-first"
  | "operator-safe"
  | "review-gated"
  | "read-only"
  | "approval-gated";

export type CodexForgeCommandDeckRole =
  | "overview"
  | "start"
  | "code-flow"
  | "code-flow-live-run"
  | "code-flow-manual-trial"
  | "code-flow-friction-fixes"
  | "code-flow-mvp-path"
  | "code-flow-release-audit"
  | "code-flow-rc"
  | "code-flow-final-polish"
  | "code-flow-trial"
  | "code-flow-trial-review"
  | "code-flow-ux-fixes"
  | "apply-guard-review"
  | "guarded-apply-candidate"
  | "guarded-apply-mvp"
  | "guarded-apply-trial-hardening"
  | "apply-evidence"
  | "apply-validation"
  | "validation-results"
  | "workflow-results"
  | "run-history"
  | "release-smoke"
  | "demo"
  | "product-trial"
  | "runbook"
  | "mvp-experience"
  | "workspace"
  | "ai-router"
  | "ai-provider-registry"
  | "provider-adapters"
  | "provider-health"
  | "local-machine"
  | "local-creative"
  | "comfyui-health"
  | "comfyui-health-gate"
  | "comfyui-real-health"
  | "comfyui-metadata"
  | "comfyui-metadata-reader"
  | "video-workflows"
  | "video-jobs"
  | "video-prompt"
  | "storyboard"
  | "keyframes"
  | "local-draft-review"
  | "local-image"
  | "local-keyframes"
  | "local-video-draft"
  | "comfyui-workflow-import"
  | "comfyui-workflow-safety"
  | "comfyui-workflow-parameters"
  | "comfyui-job-package"
  | "comfyui-workflow-dry-run"
  | "workflow-package-validator"
  | "comfyui-submit"
  | "comfyui-submit-trial"
  | "comfyui-workflow-library"
  | "workflow-template-import-shelf"
  | "workflow-compatibility-checker"
  | "missing-model-node-resolver"
  | "local-model-manager"
  | "ollama-model-planner"
  | "lm-studio-runtime-planner"
  | "local-llm-creative-assistant"
  | "local-image-trial"
  | "local-keyframe-trial"
  | "local-video-draft-trial"
  | "local-output-capture"
  | "video-capture"
  | "video-artifacts"
  | "video-review"
  | "creative-memory"
  | "style-presets"
  | "consistency-kit"
  | "shot-library"
  | "video-projects"
  | "video-assets"
  | "render-history"
  | "video-export"
  | "cloud-video-providers"
  | "cloud-final-render"
  | "local-vs-cloud"
  | "video-safety-audit"
  | "video-recovery"
  | "video-compare"
  | "video-upscale"
  | "video-interpolation"
  | "video-finishing"
  | "video-final-render"
  | "creative-cost-router"
  | "gpu-scheduler"
  | "dual-gpu"
  | "render-queue"
  | "local-render-queue-persistence"
  | "render-job-status"
  | "render-job-control-boundary"
  | "render-queue-recovery"
  | "local-video-preview"
  | "artifact-thumbnails"
  | "draft-playback-review"
  | "export-package-builder"
  | "env-readiness"
  | "local-provider-probes"
  | "provider-tests"
  | "provider-live-test-gate"
  | "openai-compatible-live-test"
  | "claude-anthropic-live-test"
  | "multi-provider-live-test"
  | "provider-test-results"
  | "provider-cost-latency-comparison"
  | "router-recommendation-review"
  | "provider-failure-recovery"
  | "provider-budget-guardrails"
  | "prompt-privacy-classifier"
  | "provider-audit-log"
  | "provider-settings-review"
  | "provider-policy-bundle"
  | "provider-runbook-generator"
  | "local-first-router-dry-run"
  | "provider-governance-release-audit"
  | "jarvisd-contract"
  | "jarvisd-health"
  | "jarvisd-capabilities"
  | "jarvisd-permissions"
  | "local-file-approval"
  | "local-command-approval"
  | "local-process-monitor"
  | "workspace-trust-policy"
  | "safe-project-indexer"
  | "project-file-search"
  | "project-dependency-map"
  | "project-risk-secrets-scan"
  | "model-capabilities"
  | "task-router"
  | "credential-strategy"
  | "provider-setup"
  | "token-router"
  | "graph"
  | "file-work"
  | "task-flow"
  | "closed-loop"
  | "memory-review"
  | "memory-inbox"
  | "runtime-journal"
  | "runtime-replay"
  | "brain-snapshots"
  | "snapshot-restore"
  | "brain-continuity"
  | "handoff"
  | "brain-governance"
  | "production"
  | "video-render-preview"
  | "creative-executor"
  | "creative-sandbox"
  | "creative-readiness"
  | "creative-mvp"
  | "health-probe"
  | "local-bridge-health"
  | "blender-preview"
  | "unreal-preview"
  | "comfyui-preview"
  | "creative-bridge"
  | "artifact-review"
  | "capability"
  | "activity-feed"
  | "readiness-audit"
  | "repo-hygiene"
  | "quality-audit"
  | "consolidation-pass"
  | "validation-runner"
  | "stabilization"
  | "timeline";

export type CodexForgeNavigationRoute = {
  id: CodexForgeNavigationRouteId;
  href: CodexForgeNavigationRouteHref;
  label: string;
  shortLabel: string;
  description: string;
  group: CodexForgeNavigationGroup;
  readiness: CodexForgeNavigationReadiness;
  safetyPosture: CodexForgeNavigationSafetyPosture;
  badge: string;
  priority: number;
  requiresReview: boolean;
  noMutation: boolean;
  commandDeckRole: CodexForgeCommandDeckRole;
};

export type CodexForgeNavigationRouteAvailability = Partial<
  Record<CodexForgeNavigationRouteHref, boolean>
>;

export type CodexForgeNavigationRouteInput =
  Partial<Omit<CodexForgeNavigationRoute, "href">> & {
    href: CodexForgeNavigationRouteHref;
  };

export type CodexForgeNavigationSection = {
  id: string;
  group: CodexForgeNavigationGroup;
  label: string;
  description: string;
  priority: number;
  routes: CodexForgeNavigationRoute[];
};

export type CodexForgeNavigationSectionInput = {
  group: CodexForgeNavigationGroup;
  routes: CodexForgeNavigationRoute[];
  label?: string;
  description?: string;
  priority?: number;
};

export type CodexForgeSafetyPostureItem = {
  id: string;
  label: string;
  summary: string;
  state: "enforced" | "review-required" | "visible";
  priority: number;
};

export type CodexForgeSafetyPostureInput = Partial<CodexForgeSafetyPostureItem> & {
  id: string;
};

export type CodexForgeShellNextActionReason =
  | "stabilization-blockers"
  | "operator-home-overview"
  | "file-work"
  | "memory-review"
  | "regression-or-fix"
  | "creative-work"
  | "clean-checkpoint"
  | "continue-next-phase";

export type CodexForgeShellNextAction = {
  id: string;
  label: string;
  description: string;
  href?: CodexForgeNavigationRouteHref;
  reason: CodexForgeShellNextActionReason;
  noMutation: boolean;
  requiresApproval: boolean;
};

export type CodexForgeShellNextActionContext = {
  activeHref?: string;
  hasStabilizationBlockers?: boolean;
  wantsOperatorOverview?: boolean;
  hasFileWork?: boolean;
  hasMemoryReview?: boolean;
  hasRegressionOrFixWork?: boolean;
  hasCreativeWork?: boolean;
  cleanCheckpointRecommended?: boolean;
  routeAvailability?: CodexForgeNavigationRouteAvailability;
};

export type CodexForgeShellNextActionPlan = {
  selected: CodexForgeShellNextAction;
  candidates: CodexForgeShellNextAction[];
  summary: string;
};

export type CodexForgeRouteBreadcrumb = {
  label: string;
  href: CodexForgeNavigationRouteHref;
};

export type CodexForgeRouteState = {
  activeRoute: CodexForgeNavigationRoute;
  activeGroup: CodexForgeNavigationGroup;
  breadcrumbs: CodexForgeRouteBreadcrumb[];
  siblingRoutes: CodexForgeNavigationRoute[];
  nextRouteSuggestion?: CodexForgeNavigationRoute;
  currentSafetyPosture: CodexForgeSafetyPostureItem[];
  workspaceLabel: string;
};

export type CodexForgeNavigationShellSummary = {
  routeCount: number;
  groupCount: number;
  activeRoute: string;
  activeGroup: CodexForgeNavigationGroup;
  safetyPostureCount: number;
  nextAction: string;
  noMutationStatus: "all-routes-no-mutation" | "review-required";
};

export type CodexForgeAppShellProps = {
  children: ReactNode;
  activePath?: string;
  workspaceLabel?: string;
  routeAvailability?: CodexForgeNavigationRouteAvailability;
  nextActionContext?: CodexForgeShellNextActionContext;
  sidebarMode?: "full" | "compact" | "collapsed";
  defaultSidebarCollapsed?: boolean;
  focusMode?: boolean;
  showSidebarBadges?: boolean;
  showSidebarSafetyNotice?: boolean;
  showRightRail?: boolean;
  contentMaxWidth?: number | "standard" | "wide" | "full";
  pageChrome?: "minimal" | "standard" | "dashboard";
  showRouteTray?: boolean;
  routeTrayDefaultOpen?: boolean;
  showHeroRouteChips?: boolean;
  showRightRailRouteGroups?: boolean;
  showSafetyStrip?: boolean;
  pageDensity?: "compact" | "standard" | "focus";
};
