import type {
  CodexForgeNavigationRoute,
  CodexForgeNavigationRouteAvailability,
  CodexForgeNavigationRouteHref,
  CodexForgeNavigationRouteId,
  CodexForgeNavigationRouteInput,
} from "./navigation-shell-types";

const ROUTE_ORDER: readonly CodexForgeNavigationRouteHref[] = [
  "/",
  "/start",
  "/onboarding",
  "/first-task",
  "/safety-coach",
  "/help-empty-states",
  "/assisted-quality",
  "/assist",
  "/code-flow",
  "/code-flow/mvp-path",
  "/code-flow/live-run",
  "/code-flow/manual-trial",
  "/code-flow/friction-fixes",
  "/code-flow/release-audit",
  "/code-flow/rc",
  "/code-flow/final-polish",
  "/code-flow/trial",
  "/code-flow/trial-review",
  "/code-flow/ux-fixes",
  "/apply-guard-review",
  "/guarded-apply-candidate",
  "/guarded-apply-mvp",
  "/guarded-apply-mvp/trial-hardening",
  "/apply-evidence",
  "/apply-validation",
  "/validation-results",
  "/review-inbox",
  "/recovery",
  "/workflow-results",
  "/run-history",
  "/release-smoke",
  "/demo",
  "/product-trial",
  "/runbook",
  "/mvp-experience",
  "/ai",
  "/ai-router",
  "/ai-providers",
  "/provider-adapters",
  "/provider-health",
  "/local-machine",
  "/local-creative",
  "/comfyui-health",
  "/comfyui-health/gate",
  "/comfyui-real-health",
  "/comfyui-metadata",
  "/comfyui-metadata-reader",
  "/video-workflows",
  "/video-jobs",
  "/video-prompt",
  "/storyboard",
  "/keyframes",
  "/local-draft-review",
  "/comfyui-workflows/import",
  "/comfyui-workflows/safety",
  "/comfyui-workflows/parameters",
  "/comfyui-jobs/package",
  "/comfyui-workflows/dry-run",
  "/workflow-package-validator",
  "/comfyui-submit",
  "/comfyui-submit-trial",
  "/local-image-trial",
  "/local-keyframe-trial",
  "/local-video-draft-trial",
  "/local-output-capture",
  "/local-image",
  "/local-keyframes",
  "/local-video-draft",
  "/video-capture",
  "/video-artifacts",
  "/video-review",
  "/creative-memory",
  "/style-presets",
  "/consistency-kit",
  "/shot-library",
  "/video-projects",
  "/video-assets",
  "/render-history",
  "/video-export",
  "/cloud-video-providers",
  "/cloud-final-render",
  "/local-vs-cloud",
  "/video-safety-audit",
  "/video-recovery",
  "/video-compare",
  "/video-upscale",
  "/video-interpolation",
  "/video-finishing",
  "/video-final-render",
  "/creative-cost-router",
  "/gpu-scheduler",
  "/dual-gpu",
  "/render-queue",
  "/local-render-queue-persistence",
  "/render-job-status",
  "/render-job-control-boundary",
  "/render-queue-recovery",
  "/local-video-preview",
  "/artifact-thumbnails",
  "/draft-playback-review",
  "/export-package-builder",
  "/env-readiness",
  "/local-provider-probes",
  "/provider-tests",
  "/model-capabilities",
  "/task-router",
  "/credentials",
  "/provider-setup",
  "/token-router",
  "/brain",
  "/files",
  "/tasks",
  "/closed-loop",
  "/memory",
  "/memory-inbox",
  "/runtime-journal",
  "/runtime-replay",
  "/brain-snapshots",
  "/snapshot-restore",
  "/brain-continuity",
  "/handoff",
  "/brain-governance",
  "/creative",
  "/artifacts/review",
  "/video-render",
  "/creative-executor",
  "/creative-sandbox",
  "/creative-readiness",
  "/creative-mvp",
  "/local-bridge-health",
  "/blender",
  "/unreal",
  "/comfyui",
  "/creative-bridge",
  "/capabilities",
  "/activity",
  "/readiness",
  "/repo-hygiene",
  "/quality-audit",
  "/consolidation",
  "/validation",
  "/stabilization",
  "/history",
] as const;

const ROUTE_DEFAULTS: Record<CodexForgeNavigationRouteHref, CodexForgeNavigationRoute> = {
  "/": {
    id: "home",
    href: "/",
    label: "Operator Home",
    shortLabel: "Home",
    description: "Command overview for CodexForge readiness, launch surfaces, and next safe action.",
    group: "Start",
    readiness: "available",
    safetyPosture: "local-first",
    badge: "Command",
    priority: 10,
    requiresReview: false,
    noMutation: true,
    commandDeckRole: "overview",
  },
  "/start": {
    id: "start",
    href: "/start",
    label: "Start",
    shortLabel: "Start",
    description: "Plain-English guided entrypoint for choosing the next safe CodexForge workflow.",
    group: "Start",
    readiness: "available",
    safetyPosture: "local-first",
    badge: "Guide",
    priority: 12,
    requiresReview: false,
    noMutation: true,
    commandDeckRole: "start",
  },
  "/onboarding": {
    id: "onboarding",
    href: "/onboarding",
    label: "Start with CodexForge",
    shortLabel: "Onboarding",
    description: "First-run guide for the safe coding flow, manual boundaries, evidence, validation, review, recovery, and demo.",
    group: "Start",
    readiness: "available",
    safetyPosture: "local-first",
    badge: "Guide",
    priority: 12.05,
    requiresReview: false,
    noMutation: true,
    commandDeckRole: "start",
  },
  "/first-task": {
    id: "first-task",
    href: "/first-task",
    label: "First Safe Task",
    shortLabel: "First Task",
    description: "Guided first tiny wording change with preview, approval, evidence, validation, review, and recovery handoff.",
    group: "Start",
    readiness: "available",
    safetyPosture: "approval-gated",
    badge: "First",
    priority: 12.06,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "start",
  },
  "/safety-coach": {
    id: "safety-coach",
    href: "/safety-coach",
    label: "Safety Coach",
    shortLabel: "Safety",
    description: "Plain-English explanations for preview, apply, approval, evidence, validation, recovery, rollback, and safe files.",
    group: "Start",
    readiness: "available",
    safetyPosture: "read-only",
    badge: "Coach",
    priority: 12.065,
    requiresReview: false,
    noMutation: true,
    commandDeckRole: "start",
  },
  "/help-empty-states": {
    id: "help-empty-states",
    href: "/help-empty-states",
    label: "Helpful Empty States",
    shortLabel: "Empty States",
    description: "Checklist for helpful empty states across the novice assisted path.",
    group: "Start",
    readiness: "available",
    safetyPosture: "read-only",
    badge: "Help",
    priority: 12.07,
    requiresReview: false,
    noMutation: true,
    commandDeckRole: "start",
  },
  "/assisted-quality": {
    id: "assisted-quality",
    href: "/assisted-quality",
    label: "Assisted MVP Quality",
    shortLabel: "Quality",
    description: "Read-only quality sweep for the novice assisted MVP path.",
    group: "Start",
    readiness: "available",
    safetyPosture: "read-only",
    badge: "Sweep",
    priority: 12.075,
    requiresReview: false,
    noMutation: true,
    commandDeckRole: "start",
  },
  "/assist": {
    id: "assist",
    href: "/assist",
    label: "Assisted Coding",
    shortLabel: "Assist",
    description: "Choose a coding goal and get the next safe route without auto-apply or auto-run.",
    group: "Start",
    readiness: "available",
    safetyPosture: "review-gated",
    badge: "Assist",
    priority: 12.08,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "start",
  },
  "/code-flow": {
    id: "code-flow",
    href: "/code-flow",
    label: "Fix code safely",
    shortLabel: "Code Flow",
    description: "End-to-end code fix flow: pick a file, describe change, preview patch, review apply, prepare checks, and review result.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "approval-gated",
    badge: "Flow",
    priority: 13,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "code-flow",
  },
  "/code-flow/mvp-path": {
    id: "code-flow-mvp-path",
    href: "/code-flow/mvp-path",
    label: "Coding MVP Path",
    shortLabel: "MVP Path",
    description: "Locked coding MVP path from start through release audit.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "approval-gated",
    badge: "Path",
    priority: 13.01,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "code-flow-mvp-path",
  },
  "/code-flow/live-run": {
    id: "code-flow-live-run",
    href: "/code-flow/live-run",
    label: "Coding Live Run",
    shortLabel: "Live Run",
    description: "Guided coding flow from safe file choice to validation result.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "approval-gated",
    badge: "Live",
    priority: 13.02,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "code-flow-live-run",
  },
  "/code-flow/manual-trial": {
    id: "code-flow-manual-trial",
    href: "/code-flow/manual-trial",
    label: "Manual Coding Trial",
    shortLabel: "Manual Trial",
    description: "Manual coding trial checklist for one harmless change.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "approval-gated",
    badge: "Trial",
    priority: 13.03,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "code-flow-manual-trial",
  },
  "/code-flow/friction-fixes": {
    id: "code-flow-friction-fixes",
    href: "/code-flow/friction-fixes",
    label: "Trial Friction Fixes",
    shortLabel: "Friction",
    description: "Small copy, layout, route, validation, and safety-copy fixes from manual trial findings.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "review-gated",
    badge: "Fix",
    priority: 13.04,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "code-flow-friction-fixes",
  },
  "/code-flow/release-audit": {
    id: "code-flow-release-audit",
    href: "/code-flow/release-audit",
    label: "Coding Release Audit",
    shortLabel: "Release Audit",
    description: "Coding MVP release audit and go/no-go review.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "review-gated",
    badge: "Audit",
    priority: 13.05,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "code-flow-release-audit",
  },
  "/code-flow/rc": {
    id: "code-flow-rc",
    href: "/code-flow/rc",
    label: "Coding MVP Release Candidate",
    shortLabel: "RC Gate",
    description: "Release-candidate review for the coding MVP path, manual safety, validation, and demo readiness.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "review-gated",
    badge: "RC",
    priority: 13.06,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "code-flow-rc",
  },
  "/code-flow/final-polish": {
    id: "code-flow-final-polish",
    href: "/code-flow/final-polish",
    label: "Final Polish",
    shortLabel: "Final Polish",
    description: "Final demo polish review for the coding MVP route, copy, layout, and safe handoffs.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "review-gated",
    badge: "Polish",
    priority: 13.07,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "code-flow-final-polish",
  },
  "/code-flow/trial": {
    id: "code-flow-trial",
    href: "/code-flow/trial",
    label: "Coding Trial",
    shortLabel: "Trial",
    description: "Guided coding-flow live trial pack with checklist, safe file choices, validation guide, troubleshooting, and handoff.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "approval-gated",
    badge: "Trial",
    priority: 13.1,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "code-flow-trial",
  },
  "/code-flow/trial-review": {
    id: "code-flow-trial-review",
    href: "/code-flow/trial-review",
    label: "Coding Trial Review",
    shortLabel: "Trial Review",
    description: "Review coding-flow trial notes, friction, pass/fail checklist, validation, safety, UX fixes, and go/no-go.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "review-gated",
    badge: "Review",
    priority: 13.15,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "code-flow-trial-review",
  },
  "/code-flow/ux-fixes": {
    id: "code-flow-ux-fixes",
    href: "/code-flow/ux-fixes",
    label: "Coding UX Fixes",
    shortLabel: "UX Fixes",
    description: "Copy-only UX fix pack for coding-flow wording, primary actions, panel priority, empty states, validation copy, and route handoffs.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "review-gated",
    badge: "UX",
    priority: 13.18,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "code-flow-ux-fixes",
  },
  "/apply-guard-review": {
    id: "apply-guard-review",
    href: "/apply-guard-review",
    label: "Apply Guard Review",
    shortLabel: "Guard Review",
    description: "Review approval packet enforcement, diff/path boundaries, rollback, command/write separation, validation, and go/no-go before a real apply path.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "approval-gated",
    badge: "Phase 82",
    priority: 13.19,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "apply-guard-review",
  },
  "/guarded-apply-candidate": {
    id: "guarded-apply-candidate",
    href: "/guarded-apply-candidate",
    label: "Guarded Apply Candidate",
    shortLabel: "Apply Candidate",
    description: "Design-only plan for the first one-file guarded apply candidate: one diff, one approval, rollback, validation, result handoff, and execution blocked.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "approval-gated",
    badge: "Phase 83",
    priority: 13.195,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "guarded-apply-candidate",
  },
  "/guarded-apply-mvp": {
    id: "guarded-apply-mvp",
    href: "/guarded-apply-mvp",
    label: "Guarded Apply MVP",
    shortLabel: "Apply",
    description: "One file, one diff, one explicit approval, then separate validation.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "approval-gated",
    badge: "Apply",
    priority: 13.2,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "guarded-apply-mvp",
  },
  "/guarded-apply-mvp/trial-hardening": {
    id: "guarded-apply-trial-hardening",
    href: "/guarded-apply-mvp/trial-hardening",
    label: "First Apply Trial Hardening",
    shortLabel: "Apply Trial",
    description: "Review first guarded apply readiness, risk, approval, boundary, rollback, evidence, and validation handoff.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "approval-gated",
    badge: "Trial",
    priority: 13.21,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "guarded-apply-trial-hardening",
  },
  "/apply-evidence": {
    id: "apply-evidence",
    href: "/apply-evidence",
    label: "Apply Evidence",
    shortLabel: "Evidence",
    description: "Capture apply evidence after approval without running commands or mutating files from the UI.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "review-gated",
    badge: "Evidence",
    priority: 13.25,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "apply-evidence",
  },
  "/apply-validation": {
    id: "apply-validation",
    href: "/apply-validation",
    label: "Apply safely, then validate",
    shortLabel: "Apply + Validate",
    description: "Reviewable diff, approval policy, rollback plan, validation checklist, output review, and result routing for the coding flow.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "approval-gated",
    badge: "Hardening",
    priority: 14,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "apply-validation",
  },
  "/validation-results": {
    id: "validation-results",
    href: "/validation-results",
    label: "Validation Results",
    shortLabel: "Validation",
    description: "Capture and review validation output separately from apply execution.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "review-gated",
    badge: "Validate",
    priority: 14.25,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "validation-results",
  },
  "/review-inbox": {
    id: "review-inbox",
    href: "/review-inbox",
    label: "Review Inbox",
    shortLabel: "Result Inbox",
    description: "One place to review evidence, validation, workflow results, recovery items, run history handoffs, and demo notes.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "review-gated",
    badge: "Inbox",
    priority: 14.3,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "run-history",
  },
  "/recovery": {
    id: "recovery",
    href: "/recovery",
    label: "Recovery Flow",
    shortLabel: "Recovery",
    description: "Guided recovery for failed validation, blocked apply, unknown results, and unclear next steps.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "review-gated",
    badge: "Recovery",
    priority: 14.35,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "closed-loop",
  },
  "/workflow-results": {
    id: "workflow-results",
    href: "/workflow-results",
    label: "Review workflow results",
    shortLabel: "Results",
    description: "Review workflow outcomes, capped validation output, copyable handoffs, and optional memory candidates without auto-persistence.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "review-gated",
    badge: "Persistence",
    priority: 14.5,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "workflow-results",
  },
  "/run-history": {
    id: "run-history",
    href: "/run-history",
    label: "Run History",
    shortLabel: "Runs",
    description: "Review recent workflow runs, copy handoffs, choose next actions, and prepare optional memory candidates without hidden persistence.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "review-gated",
    badge: "Timeline",
    priority: 14.7,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "run-history",
  },
  "/release-smoke": {
    id: "release-smoke",
    href: "/release-smoke",
    label: "Release Smoke Pack",
    shortLabel: "Release Smoke",
    description: "Copy-only smoke checklist for the coding MVP release path.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "read-only",
    badge: "Smoke",
    priority: 14.1,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "release-smoke",
  },
  "/demo": {
    id: "demo",
    href: "/demo",
    label: "Operator Demo Mode",
    shortLabel: "Demo",
    description: "Plain-English demo script for the safe coding MVP path.",
    group: "Start",
    readiness: "available",
    safetyPosture: "read-only",
    badge: "Demo",
    priority: 12.2,
    requiresReview: false,
    noMutation: true,
    commandDeckRole: "demo",
  },
  "/product-trial": {
    id: "product-trial",
    href: "/product-trial",
    label: "Manual Product Trial",
    shortLabel: "Product Trial",
    description: "Manual MVP path trial with route checks, friction capture, validation, result, and handoff.",
    group: "Start",
    readiness: "review-required",
    safetyPosture: "review-gated",
    badge: "Trial",
    priority: 12.3,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "product-trial",
  },
  "/runbook": {
    id: "runbook",
    href: "/runbook",
    label: "Operator Runbook",
    shortLabel: "Runbook",
    description: "Operator runbook and recovery playbook for running, validating, recovering, and demoing the coding MVP.",
    group: "Start",
    readiness: "available",
    safetyPosture: "read-only",
    badge: "Runbook",
    priority: 12.4,
    requiresReview: false,
    noMutation: true,
    commandDeckRole: "runbook",
  },
  "/mvp-experience": {
    id: "mvp-experience",
    href: "/mvp-experience",
    label: "MVP Experience Lock",
    shortLabel: "MVP Lock",
    description: "Final experience lock for route clarity, copy, navigation, safety, demo readiness, and release handoff.",
    group: "Start",
    readiness: "review-required",
    safetyPosture: "review-gated",
    badge: "Lock",
    priority: 12.5,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "mvp-experience",
  },
  "/ai": {
    id: "ai",
    href: "/ai",
    label: "AI Workspace",
    shortLabel: "AI",
    description: "Conversation, planning, memory context, and reviewed execution handoffs.",
    group: "Start",
    readiness: "review-required",
    safetyPosture: "approval-gated",
    badge: "Workspace",
    priority: 20,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "workspace",
  },
  "/ai-router": {
    id: "ai-router",
    href: "/ai-router",
    label: "AI Router",
    shortLabel: "Router",
    description: "Preview-only provider and model route planning with no API keys stored and no provider calls.",
    group: "Start",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Router",
    priority: 25,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "ai-router",
  },
  "/ai-providers": {
    id: "ai-providers",
    href: "/ai-providers",
    label: "AI Provider Registry",
    shortLabel: "Providers",
    description: "Profile-only provider account registry with manual handoff and no credential storage.",
    group: "Start",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Profiles",
    priority: 25.1,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "ai-provider-registry",
  },
  "/provider-adapters": {
    id: "provider-adapters",
    href: "/provider-adapters",
    label: "Provider Adapters",
    shortLabel: "Adapters",
    description: "Definition-only provider adapter contracts, capability metadata, readiness, and safety boundaries.",
    group: "Start",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Adapters",
    priority: 25.15,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "provider-adapters",
  },
  "/provider-health": {
    id: "provider-health",
    href: "/provider-health",
    label: "Provider Health",
    shortLabel: "Health",
    description: "Plain-English provider readiness, manual-only, planned, and blocked setup states with no provider calls.",
    group: "Start",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Health",
    priority: 25.16,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "provider-health",
  },
  "/local-machine": {
    id: "local-machine",
    href: "/local-machine",
    label: "Local Machine",
    shortLabel: "Local Machine",
    description: "Manual workstation capability profile for local-first AI, creative generation, and future video workflows.",
    group: "Start",
    readiness: "preview-only",
    safetyPosture: "local-first",
    badge: "Local",
    priority: 25.165,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "local-machine",
  },
  "/local-creative": {
    id: "local-creative",
    href: "/local-creative",
    label: "Local Creative Providers",
    shortLabel: "Local Creative",
    description: "Local-first creative provider registry for drafts, keyframes, video jobs, and cost-saving planning without generation.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 130",
    priority: 25.1651,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "local-creative",
  },
  "/comfyui-health": {
    id: "comfyui-health",
    href: "/comfyui-health",
    label: "ComfyUI Health",
    shortLabel: "ComfyUI Health",
    description: "Preview-only local ComfyUI health check model with no workflow run and no prompt sent.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 131",
    priority: 25.1652,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "comfyui-health",
  },
  "/comfyui-health/gate": {
    id: "comfyui-health-gate",
    href: "/comfyui-health/gate",
    label: "ComfyUI Health Gate",
    shortLabel: "Health Gate",
    description: "Preview-only gate for deciding whether a future local metadata-only ComfyUI health probe may be approved.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "approval-gated",
    badge: "Phase 154",
    priority: 25.16521,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "comfyui-health-gate",
  },
  "/comfyui-real-health": {
    id: "comfyui-real-health",
    href: "/comfyui-real-health",
    label: "Real ComfyUI Health",
    shortLabel: "Real Health",
    description: "Real local ComfyUI health probe readiness for localhost-only checks with approved local boundary required and no UI-side live probe.",
    group: "Creative",
    readiness: "review-required",
    safetyPosture: "approval-gated",
    badge: "Phase 174",
    priority: 25.1629001,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "comfyui-real-health",
  },
  "/comfyui-metadata": {
    id: "comfyui-metadata",
    href: "/comfyui-metadata",
    label: "ComfyUI Metadata",
    shortLabel: "Metadata",
    description: "Metadata-only ComfyUI readiness contract with no prompts, workflows, queue submit, or live call by default.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 155",
    priority: 25.16522,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "comfyui-metadata",
  },
  "/comfyui-metadata-reader": {
    id: "comfyui-metadata-reader",
    href: "/comfyui-metadata-reader",
    label: "ComfyUI Metadata Reader",
    shortLabel: "Metadata Reader",
    description: "Safe local ComfyUI metadata reader model with summarized node/model hints, no arbitrary file browsing, no secrets, and advanced metadata kept secondary.",
    group: "Creative",
    readiness: "review-required",
    safetyPosture: "read-only",
    badge: "Phase 175",
    priority: 25.1629002,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "comfyui-metadata-reader",
  },
  "/video-workflows": {
    id: "video-workflows",
    href: "/video-workflows",
    label: "Video Workflows",
    shortLabel: "Workflows",
    description: "Beginner-friendly local video workflow catalog for planning drafts before cloud spend.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 132",
    priority: 25.1653,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "video-workflows",
  },
  "/video-jobs": {
    id: "video-jobs",
    href: "/video-jobs",
    label: "Video Job Queue",
    shortLabel: "Video Jobs",
    description: "Safe video job queue preview for requests, review, statuses, resources, and artifacts without rendering.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 133",
    priority: 25.1654,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "video-jobs",
  },
  "/video-prompt": {
    id: "video-prompt",
    href: "/video-prompt",
    label: "Video Prompt Builder",
    shortLabel: "Video Prompt",
    description: "Turn a rough video idea into a structured prompt before any image, video, workflow, or provider call.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Plan",
    priority: 25.1619,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "video-prompt",
  },
  "/storyboard": {
    id: "storyboard",
    href: "/storyboard",
    label: "Storyboard Planner",
    shortLabel: "Storyboard",
    description: "Plan video shots, timing, continuity, and keyframe handoff before local generation.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Shots",
    priority: 25.162,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "storyboard",
  },
  "/keyframes": {
    id: "keyframes",
    href: "/keyframes",
    label: "Keyframe Plan",
    shortLabel: "Keyframes",
    description: "Plan still-frame anchors for a future video draft without generating images.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Frames",
    priority: 25.1621,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "keyframes",
  },
  "/local-draft-review": {
    id: "local-draft-review",
    href: "/local-draft-review",
    label: "Local Draft Review",
    shortLabel: "Draft Review",
    description: "Review a future local video draft request for prompt, storyboard, keyframes, workflow, resources, approval, artifacts, and recovery.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Review",
    priority: 25.1622,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "local-draft-review",
  },
  "/comfyui-workflows/import": {
    id: "comfyui-workflow-import",
    href: "/comfyui-workflows/import",
    label: "ComfyUI Workflow Import",
    shortLabel: "Workflow Import",
    description: "Preview ComfyUI workflow metadata safely before safety inspection, parameter mapping, or packaging.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 138",
    priority: 25.1623,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "comfyui-workflow-import",
  },
  "/comfyui-workflows/safety": {
    id: "comfyui-workflow-safety",
    href: "/comfyui-workflows/safety",
    label: "Workflow Safety",
    shortLabel: "Workflow Safety",
    description: "Inspect ComfyUI workflow risks in plain English before any future render is allowed.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 139",
    priority: 25.1624,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "comfyui-workflow-safety",
  },
  "/comfyui-workflows/parameters": {
    id: "comfyui-workflow-parameters",
    href: "/comfyui-workflows/parameters",
    label: "Workflow Parameters",
    shortLabel: "Parameters",
    description: "Map technical workflow values into safe, understandable parameter choices without mutating workflow JSON.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 140",
    priority: 25.1625,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "comfyui-workflow-parameters",
  },
  "/comfyui-jobs/package": {
    id: "comfyui-job-package",
    href: "/comfyui-jobs/package",
    label: "ComfyUI Job Package",
    shortLabel: "Job Package",
    description: "Build a reviewed future ComfyUI local video job package without submitting or running it.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 141",
    priority: 25.1626,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "comfyui-job-package",
  },
  "/comfyui-workflows/dry-run": {
    id: "comfyui-workflow-dry-run",
    href: "/comfyui-workflows/dry-run",
    label: "Workflow Dry Run",
    shortLabel: "Dry Run",
    description: "ComfyUI workflow dry run contract for package, safety, parameters, metadata, queue, artifact, recovery, and approval review without running ComfyUI.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "approval-gated",
    badge: "Phase 156",
    priority: 25.16261,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "comfyui-workflow-dry-run",
  },
  "/workflow-package-validator": {
    id: "workflow-package-validator",
    href: "/workflow-package-validator",
    label: "Workflow Package Validator",
    shortLabel: "Package Validator",
    description: "Validate a prepared local ComfyUI workflow package contract before any approved submit trial; unsafe targets and missing approval block submit.",
    group: "Creative",
    readiness: "review-required",
    safetyPosture: "approval-gated",
    badge: "Phase 176",
    priority: 25.1629003,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "workflow-package-validator",
  },
  "/comfyui-submit": {
    id: "comfyui-submit",
    href: "/comfyui-submit",
    label: "ComfyUI Submit Boundary",
    shortLabel: "Submit Boundary",
    description: "Approved submit boundary model for a future local ComfyUI workflow submit, with execution blocked until a guarded executor exists.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "approval-gated",
    badge: "Phase 157",
    priority: 25.16262,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "comfyui-submit",
  },
  "/comfyui-submit-trial": {
    id: "comfyui-submit-trial",
    href: "/comfyui-submit-trial",
    label: "ComfyUI Submit Trial",
    shortLabel: "Submit Trial",
    description: "Gated readiness and handoff for the first real approved local ComfyUI submit trial; final live queue call remains behind the approved local boundary.",
    group: "Creative",
    readiness: "review-required",
    safetyPosture: "approval-gated",
    badge: "Phase 177",
    priority: 25.1629004,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "comfyui-submit-trial",
  },
  "/local-image-trial": {
    id: "local-image-trial",
    href: "/local-image-trial",
    label: "Local Image Trial",
    shortLabel: "Image Trial",
    description: "Guarded local-only image generation trial readiness with explicit approval, Local ComfyUI only, artifact capture, review, and recovery handoff.",
    group: "Creative",
    readiness: "review-required",
    safetyPosture: "approval-gated",
    badge: "Phase 178",
    priority: 25.1629005,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "local-image-trial",
  },
  "/local-keyframe-trial": {
    id: "local-keyframe-trial",
    href: "/local-keyframe-trial",
    label: "Local Keyframe Trial",
    shortLabel: "Keyframe Trial",
    description: "Guarded local-only keyframe generation trial with shot and scene linkage, approved workflow package, explicit approval, capture, and recovery handoff.",
    group: "Creative",
    readiness: "review-required",
    safetyPosture: "approval-gated",
    badge: "Phase 179",
    priority: 25.1629006,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "local-keyframe-trial",
  },
  "/local-video-draft-trial": {
    id: "local-video-draft-trial",
    href: "/local-video-draft-trial",
    label: "Local Video Draft Trial",
    shortLabel: "Video Trial",
    description: "Guarded local-only video draft trial with bounded duration, dual-GPU worker guidance, explicit approval, capture, review, and recovery handoff.",
    group: "Creative",
    readiness: "review-required",
    safetyPosture: "approval-gated",
    badge: "Phase 180",
    priority: 25.1629007,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "local-video-draft-trial",
  },
  "/local-output-capture": {
    id: "local-output-capture",
    href: "/local-output-capture",
    label: "Local Output Capture",
    shortLabel: "Output Capture",
    description: "Real artifact capture from local output with review inbox, recovery, export handoff, retention notes, no deletion, and no memory auto-promotion.",
    group: "Creative",
    readiness: "review-required",
    safetyPosture: "read-only",
    badge: "Phase 181",
    priority: 25.1629008,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "local-output-capture",
  },
  "/local-image": {
    id: "local-image",
    href: "/local-image",
    label: "Local Image MVP",
    shortLabel: "Local Image",
    description: "Prepare and review a local image request before anything generates, with supplied result capture only.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "approval-gated",
    badge: "Phase 158",
    priority: 25.16263,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "local-image",
  },
  "/local-keyframes": {
    id: "local-keyframes",
    href: "/local-keyframes",
    label: "Local Keyframes MVP",
    shortLabel: "Local Keyframes",
    description: "Prepare still-frame keyframe image requests that guide a future local video draft.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "approval-gated",
    badge: "Phase 159",
    priority: 25.16264,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "local-keyframes",
  },
  "/local-video-draft": {
    id: "local-video-draft",
    href: "/local-video-draft",
    label: "Local Video Draft MVP",
    shortLabel: "Video Draft MVP",
    description: "Prepare a short local video draft request before anything renders, with supplied draft capture only.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "approval-gated",
    badge: "Phase 160",
    priority: 25.16265,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "local-video-draft",
  },
  "/video-capture": {
    id: "video-capture",
    href: "/video-capture",
    label: "Video Artifact Capture",
    shortLabel: "Video Capture",
    description: "Record supplied local image, keyframe, video draft, failed result, or final candidate metadata for review.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 161",
    priority: 25.16266,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "video-capture",
  },
  "/video-artifacts": {
    id: "video-artifacts",
    href: "/video-artifacts",
    label: "Video Artifacts",
    shortLabel: "Artifacts",
    description: "Review future local video artifacts and handoffs without file browsing, deletion, or generation.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 142",
    priority: 25.1627,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "video-artifacts",
  },
  "/video-review": {
    id: "video-review",
    href: "/video-review",
    label: "Video Review",
    shortLabel: "Video Review",
    description: "Review future video results, keep or retry drafts, compare, upscale later, or route to recovery.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 143",
    priority: 25.1628,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "video-review",
  },
  "/creative-memory": {
    id: "creative-memory",
    href: "/creative-memory",
    label: "Creative Prompt Memory",
    shortLabel: "Creative Memory",
    description: "Review useful prompt ideas before reusing or saving them, with no automatic memory promotion.",
    group: "Creative",
    readiness: "review-required",
    safetyPosture: "review-gated",
    badge: "Phase 162",
    priority: 25.16284,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "creative-memory",
  },
  "/style-presets": {
    id: "style-presets",
    href: "/style-presets",
    label: "Style Presets",
    shortLabel: "Style Presets",
    description: "Reusable local style definitions for prompts, keyframes, and drafts without generation.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 163",
    priority: 25.16285,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "style-presets",
  },
  "/consistency-kit": {
    id: "consistency-kit",
    href: "/consistency-kit",
    label: "Consistency Kit",
    shortLabel: "Consistency",
    description: "Notes-only consistency planning for characters, brands, products, and recurring subjects.",
    group: "Creative",
    readiness: "review-required",
    safetyPosture: "review-gated",
    badge: "Phase 164",
    priority: 25.16286,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "consistency-kit",
  },
  "/shot-library": {
    id: "shot-library",
    href: "/shot-library",
    label: "Shot Library",
    shortLabel: "Shot Library",
    description: "Reusable shot templates for storyboards and local video drafts without render execution.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 165",
    priority: 25.16287,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "shot-library",
  },
  "/video-projects": {
    id: "video-projects",
    href: "/video-projects",
    label: "Video Projects",
    shortLabel: "Projects",
    description: "Group prompts, styles, shots, keyframes, drafts, artifacts, reviews, and export readiness in one preview workspace.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 166",
    priority: 25.16288,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "video-projects",
  },
  "/video-assets": {
    id: "video-assets",
    href: "/video-assets",
    label: "Video Assets",
    shortLabel: "Assets",
    description: "Track project assets needed before draft, finishing, or export handoff without file browsing.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 167",
    priority: 25.16289,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "video-assets",
  },
  "/render-history": {
    id: "render-history",
    href: "/render-history",
    label: "Render History",
    shortLabel: "Versions",
    description: "Track render versions, changes, lineage, review decisions, and copy-only handoff packets.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 168",
    priority: 25.162895,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "render-history",
  },
  "/video-export": {
    id: "video-export",
    href: "/video-export",
    label: "Video Export Handoff",
    shortLabel: "Export",
    description: "Prepare final video delivery notes before any export, upload, or file write runs.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 169",
    priority: 25.162896,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "video-export",
  },
  "/cloud-video-providers": {
    id: "cloud-video-providers",
    href: "/cloud-video-providers",
    label: "Cloud Video Providers",
    shortLabel: "Cloud Providers",
    description: "Review optional cloud video fallback profiles without calling providers, uploading assets, or spending credits.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 170",
    priority: 25.162897,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "cloud-video-providers",
  },
  "/cloud-final-render": {
    id: "cloud-final-render",
    href: "/cloud-final-render",
    label: "Cloud Final Render Review",
    shortLabel: "Cloud Render",
    description: "Review whether a manual cloud final render is worth the cost before anything is sent.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 171",
    priority: 25.162898,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "cloud-final-render",
  },
  "/local-vs-cloud": {
    id: "local-vs-cloud",
    href: "/local-vs-cloud",
    label: "Local vs Cloud",
    shortLabel: "Local/Cloud",
    description: "Explain the safest and cheapest route for video work before any provider call or generation path.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 172",
    priority: 25.162899,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "local-vs-cloud",
  },
  "/video-safety-audit": {
    id: "video-safety-audit",
    href: "/video-safety-audit",
    label: "Video Safety Audit",
    shortLabel: "Safety Audit",
    description: "Audit whether the video generation path is safe enough for future real local trial planning.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 173",
    priority: 25.1628995,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "video-safety-audit",
  },
  "/video-recovery": {
    id: "video-recovery",
    href: "/video-recovery",
    label: "Video Recovery",
    shortLabel: "Video Recovery",
    description: "Recover safely from failed or confusing local video results without automatic retry.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 144",
    priority: 25.1629,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "video-recovery",
  },
  "/video-compare": {
    id: "video-compare",
    href: "/video-compare",
    label: "Video Draft Compare",
    shortLabel: "Compare",
    description: "Compare future video drafts by prompt, workflow, keyframes, settings, quality, artifacts, and next action.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 145",
    priority: 25.163,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "video-compare",
  },
  "/video-upscale": {
    id: "video-upscale",
    href: "/video-upscale",
    label: "Video Upscale Plan",
    shortLabel: "Upscale",
    description: "Plan local draft upscaling before any future approved final-quality video work.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 146",
    priority: 25.1631,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "video-upscale",
  },
  "/video-interpolation": {
    id: "video-interpolation",
    href: "/video-interpolation",
    label: "Frame Interpolation Plan",
    shortLabel: "Interpolation",
    description: "Plan FPS and motion smoothing choices without creating frames or processing video.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 147",
    priority: 25.1632,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "video-interpolation",
  },
  "/video-finishing": {
    id: "video-finishing",
    href: "/video-finishing",
    label: "Video Finishing",
    shortLabel: "Finishing",
    description: "Plan final polish steps after choosing a draft, with no render or export execution.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 148",
    priority: 25.1633,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "video-finishing",
  },
  "/video-final-render": {
    id: "video-final-render",
    href: "/video-final-render",
    label: "Draft to Final",
    shortLabel: "Draft to Final",
    description: "Review readiness for a future approved final render without calling ComfyUI or providers.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "approval-gated",
    badge: "Phase 149",
    priority: 25.1634,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "video-final-render",
  },
  "/creative-cost-router": {
    id: "creative-cost-router",
    href: "/creative-cost-router",
    label: "Creative Cost Saver",
    shortLabel: "Cost Saver",
    description: "Local-first creative cost routing so drafts, review, upscale planning, and cloud fallback stay safe and credit-aware.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 150",
    priority: 25.1635,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "creative-cost-router",
  },
  "/gpu-scheduler": {
    id: "gpu-scheduler",
    href: "/gpu-scheduler",
    label: "GPU Job Scheduler",
    shortLabel: "GPU Scheduler",
    description: "Preview local GPU job ordering, priority, resource posture, and heavy queue guidance without scheduling real jobs.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 151",
    priority: 25.1636,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "gpu-scheduler",
  },
  "/dual-gpu": {
    id: "dual-gpu",
    href: "/dual-gpu",
    label: "Dual-GPU Strategy",
    shortLabel: "Dual-GPU",
    description: "Treat two local GPUs as reviewed parallel workers unless a workflow explicitly supports multi-GPU.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 152",
    priority: 25.1637,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "dual-gpu",
  },
  "/render-queue": {
    id: "render-queue",
    href: "/render-queue",
    label: "Render Queue",
    shortLabel: "Render Queue",
    description: "Preview local render queue states and controls before anything runs, with no queue mutation or process control.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Phase 153",
    priority: 25.1638,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "render-queue",
  },
  "/local-render-queue-persistence": {
    id: "local-render-queue-persistence",
    href: "/local-render-queue-persistence",
    label: "Queue Memory",
    shortLabel: "Queue Memory",
    description: "Local render queue persistence contract for remembered approved jobs without secrets, prompt/file storage, artifact deletion, or silent queue mutation.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "approval-gated",
    badge: "Phase 182",
    priority: 25.16381,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "local-render-queue-persistence",
  },
  "/render-job-status": {
    id: "render-job-status",
    href: "/render-job-status",
    label: "Render Job Status",
    shortLabel: "Job Status",
    description: "Local render job status polling contract with bounded cadence, timeout policy, no cloud polling, no secret exposure, and no queue mutation.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "approval-gated",
    badge: "Phase 183",
    priority: 25.16382,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "render-job-status",
  },
  "/render-job-control-boundary": {
    id: "render-job-control-boundary",
    href: "/render-job-control-boundary",
    label: "Hold or Cancel",
    shortLabel: "Hold/Cancel",
    description: "Explicit render job cancel and hold boundary: hold prevents next step, cancel requests stop through approved boundary, and neither deletes artifacts.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "approval-gated",
    badge: "Phase 184",
    priority: 25.16383,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "render-job-control-boundary",
  },
  "/render-queue-recovery": {
    id: "render-queue-recovery",
    href: "/render-queue-recovery",
    label: "Recovery and Retry",
    shortLabel: "Retry",
    description: "Safe render queue recovery and retry model where retry is explicit, reviewed, local-only, never automatic, and failed artifacts are retained.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "approval-gated",
    badge: "Phase 185",
    priority: 25.16384,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "render-queue-recovery",
  },
  "/local-video-preview": {
    id: "local-video-preview",
    href: "/local-video-preview",
    label: "Local Video Preview",
    shortLabel: "Preview",
    description: "Local video preview player for reviewed captured draft outputs with playback behind the approved local artifact boundary.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "review-gated",
    badge: "Phase 186",
    priority: 25.16385,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "local-video-preview",
  },
  "/artifact-thumbnails": {
    id: "artifact-thumbnails",
    href: "/artifact-thumbnails",
    label: "Artifact Thumbnails",
    shortLabel: "Thumbnails",
    description: "Artifact thumbnail generator readiness for local outputs without browsing folders, overwriting sources, uploading, or deleting artifacts.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "review-gated",
    badge: "Phase 187",
    priority: 25.16386,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "artifact-thumbnails",
  },
  "/draft-playback-review": {
    id: "draft-playback-review",
    href: "/draft-playback-review",
    label: "Draft Playback Review",
    shortLabel: "Draft Review",
    description: "Side-by-side local draft playback review with explicit decision, no automatic promotion, and no deletion of rejected drafts.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "review-gated",
    badge: "Phase 188",
    priority: 25.16387,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "draft-playback-review",
  },
  "/export-package-builder": {
    id: "export-package-builder",
    href: "/export-package-builder",
    label: "Export Package Builder",
    shortLabel: "Export Package",
    description: "Export package builder MVP for locally reviewed outputs with local-by-default packaging, no upload, no secrets, and no deletion.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "review-gated",
    badge: "Phase 189",
    priority: 25.16388,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "export-package-builder",
  },
  "/env-readiness": {
    id: "env-readiness",
    href: "/env-readiness",
    label: "Env Readiness",
    shortLabel: "Env",
    description: "Safe provider env-key readiness design with booleans and no secret display.",
    group: "Start",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Env",
    priority: 25.166,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "env-readiness",
  },
  "/local-provider-probes": {
    id: "local-provider-probes",
    href: "/local-provider-probes",
    label: "Local Provider Probes",
    shortLabel: "Local Probes",
    description: "Preview safe metadata-only local provider probe plans for Ollama, LM Studio, ComfyUI, and compatible servers.",
    group: "Start",
    readiness: "preview-only",
    safetyPosture: "local-first",
    badge: "Probes",
    priority: 25.167,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "local-provider-probes",
  },
  "/provider-tests": {
    id: "provider-tests",
    href: "/provider-tests",
    label: "Provider Tests",
    shortLabel: "Tests",
    description: "Safe provider connection test UX that separates profile, env, local preview, future live, and blocked cloud checks.",
    group: "Start",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Tests",
    priority: 25.168,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "provider-tests",
  },
  "/model-capabilities": {
    id: "model-capabilities",
    href: "/model-capabilities",
    label: "Model Capabilities",
    shortLabel: "Models",
    description: "Approximate model family comparison for coding, reasoning, long context, local privacy, cost efficiency, and manual routes.",
    group: "Start",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Models",
    priority: 25.17,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "model-capabilities",
  },
  "/task-router": {
    id: "task-router",
    href: "/task-router",
    label: "Task Router",
    shortLabel: "Task Router",
    description: "Deterministic task-to-model recommendations using provider health, model capability, and token budget context.",
    group: "Start",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Routes",
    priority: 25.18,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "task-router",
  },
  "/credentials": {
    id: "credentials",
    href: "/credentials",
    label: "Credential Strategy",
    shortLabel: "Credentials",
    description: "Secure credential strategy for metadata-only profiles and blocked secret storage.",
    group: "Start",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Safety",
    priority: 25.2,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "credential-strategy",
  },
  "/provider-setup": {
    id: "provider-setup",
    href: "/provider-setup",
    label: "Provider Setup",
    shortLabel: "Setup",
    description: "Step-by-step provider setup wizard for profile planning without provider calls.",
    group: "Start",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Wizard",
    priority: 25.3,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "provider-setup",
  },
  "/token-router": {
    id: "token-router",
    href: "/token-router",
    label: "Token Router",
    shortLabel: "Tokens",
    description: "Deterministic token-efficiency routing recommendations with manual handoff only.",
    group: "Start",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Tokens",
    priority: 25.4,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "token-router",
  },
  "/brain": {
    id: "brain",
    href: "/brain",
    label: "Brain Command Center",
    shortLabel: "Brain",
    description: "Graph inspection, recall context, topology, and mutation-review boundaries.",
    group: "Brain",
    readiness: "review-required",
    safetyPosture: "review-gated",
    badge: "Cognition",
    priority: 30,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "graph",
  },
  "/files": {
    id: "files",
    href: "/files",
    label: "Files Command Center",
    shortLabel: "Files",
    description: "Read-only project tree, file preview, purpose, risk, and preview-only diff handoff.",
    group: "Build",
    readiness: "available",
    safetyPosture: "read-only",
    badge: "Reader + Preview",
    priority: 40,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "file-work",
  },
  "/tasks": {
    id: "tasks",
    href: "/tasks",
    label: "Tasks Workflow",
    shortLabel: "Tasks",
    description: "Reviewed task activation, readiness previews, and copy-only handoffs.",
    group: "Build",
    readiness: "review-required",
    safetyPosture: "approval-gated",
    badge: "Tasks",
    priority: 50,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "task-flow",
  },
  "/closed-loop": {
    id: "closed-loop",
    href: "/closed-loop",
    label: "Closed Loop Fix",
    shortLabel: "Fix",
    description: "Preview-only regression-to-fix workflow map with approval required before patch apply or command execution.",
    group: "Fix",
    readiness: "preview-only",
    safetyPosture: "approval-gated",
    badge: "Preview-only",
    priority: 55,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "closed-loop",
  },
  "/memory": {
    id: "memory",
    href: "/memory",
    label: "Memory Review",
    shortLabel: "Memory",
    description: "Deterministic memory candidate review with explicit promotion boundaries.",
    group: "Memory",
    readiness: "review-required",
    safetyPosture: "review-gated",
    badge: "Memory",
    priority: 60,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "memory-review",
  },
  "/memory-inbox": {
    id: "memory-inbox",
    href: "/memory-inbox",
    label: "Memory Inbox",
    shortLabel: "Inbox",
    description: "Review-first Personal Operator Memory Inbox with Memory Promotion Gate approval, policy, memory.promoted event preview, and blocked execution bridge.",
    group: "Memory",
    readiness: "review-required",
    safetyPosture: "review-gated",
    badge: "Inbox",
    priority: 65,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "memory-inbox",
  },
  "/runtime-journal": {
    id: "runtime-journal",
    href: "/runtime-journal",
    label: "Runtime Journal",
    shortLabel: "Journal",
    description: "Read-only Runtime Event Journal for requests, approvals, policy, validation, reducer previews, blocked or ready results, and append-only audit handoffs.",
    group: "Audit",
    readiness: "review-required",
    safetyPosture: "read-only",
    badge: "Audit",
    priority: 67,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "runtime-journal",
  },
  "/runtime-replay": {
    id: "runtime-replay",
    href: "/runtime-replay",
    label: "Runtime Replay",
    shortLabel: "Replay",
    description: "Preview-only Runtime Event Replay Simulator for selected journal events, graph snapshot reducer preview, impact analysis, risk detection, and rollback guidance.",
    group: "Audit",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Replay",
    priority: 67.5,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "runtime-replay",
  },
  "/brain-snapshots": {
    id: "brain-snapshots",
    href: "/brain-snapshots",
    label: "Brain Snapshots",
    shortLabel: "Snapshots",
    description: "Read-only Brain Snapshot Manager for summary, comparison, integrity review, replay source selection, rollback planning, and memory governance review.",
    group: "Brain",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Snapshots",
    priority: 67.8,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "brain-snapshots",
  },
  "/snapshot-restore": {
    id: "snapshot-restore",
    href: "/snapshot-restore",
    label: "Snapshot Restore Gate",
    shortLabel: "Restore",
    description: "Preview-only Snapshot Restore Approval Gate for restore candidate evidence, approval packet, and future executor request preview.",
    group: "Brain",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Restore Gate",
    priority: 67.9,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "snapshot-restore",
  },
  "/brain-continuity": {
    id: "brain-continuity",
    href: "/brain-continuity",
    label: "Brain Continuity",
    shortLabel: "Continuity",
    description: "Read-only Brain Continuity Dashboard for memory growth, runtime journal health, snapshot posture, replay readiness, restore risk, governance posture, and next safe action.",
    group: "Brain",
    readiness: "review-required",
    safetyPosture: "read-only",
    badge: "Continuity",
    priority: 67.95,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "brain-continuity",
  },
  "/handoff": {
    id: "handoff",
    href: "/handoff",
    label: "Continuity Handoff",
    shortLabel: "Handoff",
    description: "Read-only Continuity Handoff Packet for current state, risks, validation, rollback posture, memory posture, Brain continuity posture, and next safe actions.",
    group: "Audit",
    readiness: "review-required",
    safetyPosture: "read-only",
    badge: "Handoff",
    priority: 67.97,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "handoff",
  },
  "/brain-governance": {
    id: "brain-governance",
    href: "/brain-governance",
    label: "Brain Governance",
    shortLabel: "Governance",
    description: "Read-only Brain Mutation Governance Console for approved boundaries, direct mutation signals, reducer impact, integrity posture, and risk review.",
    group: "Brain",
    readiness: "review-required",
    safetyPosture: "read-only",
    badge: "Governance",
    priority: 68,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "brain-governance",
  },
  "/creative": {
    id: "creative",
    href: "/creative",
    label: "Creative Production Studio",
    shortLabel: "Creative",
    description: "Preview-only creative briefs, production planning, render queues, and artifact handoffs.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "operator-safe",
    badge: "Creative",
    priority: 70,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "production",
  },
  "/artifacts/review": {
    id: "artifacts-review",
    href: "/artifacts/review",
    label: "Artifact Review",
    shortLabel: "Review",
    description: "Preview-only creative artifact review board with gallery, provenance, inspector, and copy-only handoff.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "review-gated",
    badge: "Review-only",
    priority: 70.25,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "artifact-review",
  },
  "/video-render": {
    id: "video-render",
    href: "/video-render",
    label: "Video Render Job Preview",
    shortLabel: "Video Render",
    description: "Preview-only render input, timeline, shot plan, provider plan, queue preview, artifact expectations, approval packet, policy, and future executor packet.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "operator-safe",
    badge: "Phase 66",
    priority: 70.35,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "video-render-preview",
  },
  "/creative-executor": {
    id: "creative-executor",
    href: "/creative-executor",
    label: "Guarded Creative Executor",
    shortLabel: "Executor",
    description: "Dry-run-first/request-ready creative execution boundary with approval, preflight, kill-switch policy, artifact capture, and execution disabled.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "operator-safe",
    badge: "Phase 67",
    priority: 70.4,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "creative-executor",
  },
  "/creative-sandbox": {
    id: "creative-sandbox",
    href: "/creative-sandbox",
    label: "Creative Execution Sandbox",
    shortLabel: "Sandbox",
    description: "Simulation-only creative executor lifecycle with fake artifacts, cancellation, verification, and review handoff.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "operator-safe",
    badge: "Phase 69",
    priority: 70.42,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "creative-sandbox",
  },
  "/creative-readiness": {
    id: "creative-readiness",
    href: "/creative-readiness",
    label: "Real Creative Executor Readiness",
    shortLabel: "Creative Readiness",
    description: "Audit-only readiness review for local bridge profiles, adapter allowlists, path boundaries, artifact output, dry-run evidence, approval, kill-switch, and future health probe posture.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "operator-safe",
    badge: "Phase 70",
    priority: 70.43,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "creative-readiness",
  },
  "/creative-mvp": {
    id: "creative-mvp",
    href: "/creative-mvp",
    label: "Real Creative Executor MVP Design",
    shortLabel: "Creative MVP",
    description: "Design-only first real creative executor MVP selection with approval, output boundary, kill-switch, and artifact review criteria. Execution allowed false.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "operator-safe",
    badge: "Phase 72",
    priority: 70.435,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "creative-mvp",
  },
  "/health-probe": {
    id: "health-probe",
    href: "/health-probe",
    label: "Future Guarded Health Probe",
    shortLabel: "Health Probe",
    description: "Metadata-only/manual-first guarded health probe request, allowlist, approval, preflight, bridge, result, and readiness update review.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "operator-safe",
    badge: "Phase 71",
    priority: 70.44,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "health-probe",
  },
  "/local-bridge-health": {
    id: "local-bridge-health",
    href: "/local-bridge-health",
    label: "Local Bridge Health",
    shortLabel: "Bridge Health",
    description: "Preview/manual-only local bridge health target, profile, policy, probe preview, setup guide, and next action review.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "operator-safe",
    badge: "Phase 68",
    priority: 70.45,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "local-bridge-health",
  },
  "/blender": {
    id: "blender",
    href: "/blender",
    label: "Blender Adapter Preview",
    shortLabel: "Blender",
    description: "Preview-only Blender scene model, Python script preview, safety policy, and future executor packet.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "operator-safe",
    badge: "Phase 62",
    priority: 70.5,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "blender-preview",
  },
  "/unreal": {
    id: "unreal",
    href: "/unreal",
    label: "Unreal Adapter Preview",
    shortLabel: "Unreal",
    description: "Preview-only Unreal level model, actor/asset/material/Blueprint/Sequencer plans, command preview, safety policy, and future executor packet.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "operator-safe",
    badge: "Phase 65",
    priority: 70.62,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "unreal-preview",
  },
  "/comfyui": {
    id: "comfyui",
    href: "/comfyui",
    label: "ComfyUI Adapter Preview",
    shortLabel: "ComfyUI",
    description: "Preview-only ComfyUI workflow manifest, prompt nodes, approval packet, and future executor handoff.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "operator-safe",
    badge: "Preview",
    priority: 70.75,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "comfyui-preview",
  },
  "/creative-bridge": {
    id: "creative-bridge",
    href: "/creative-bridge",
    label: "Creative Bridge",
    shortLabel: "Bridge",
    description: "Preview-only creative bridge profiles, adapter readiness, job request, approval packet, artifact capture plan, and handoff.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "operator-safe",
    badge: "Bridge",
    priority: 71,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "creative-bridge",
  },
  "/capabilities": {
    id: "capabilities",
    href: "/capabilities",
    label: "Capability Cockpit",
    shortLabel: "Capabilities",
    description: "Tool readiness, policy boundaries, consent posture, and blocked execution visibility.",
    group: "Advanced",
    readiness: "available",
    safetyPosture: "operator-safe",
    badge: "Capability",
    priority: 80,
    requiresReview: false,
    noMutation: true,
    commandDeckRole: "capability",
  },
  "/activity": {
    id: "activity",
    href: "/activity",
    label: "Global Activity Feed",
    shortLabel: "Activity",
    description: "Read-only activity feed for verification, regression, patch workflow, apply gates, memory review, creative planning, stabilization, and next safe action.",
    group: "Audit",
    readiness: "available",
    safetyPosture: "read-only",
    badge: "Activity",
    priority: 85,
    requiresReview: false,
    noMutation: true,
    commandDeckRole: "activity-feed",
  },
  "/readiness": {
    id: "readiness",
    href: "/readiness",
    label: "Product Readiness Audit",
    shortLabel: "Readiness",
    description: "Read-only product readiness audit cockpit for route, smoke, safety, UX, consolidation, and functional workflow posture.",
    group: "Audit",
    readiness: "review-required",
    safetyPosture: "read-only",
    badge: "Readiness",
    priority: 87,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "readiness-audit",
  },
  "/repo-hygiene": {
    id: "repo-hygiene",
    href: "/repo-hygiene",
    label: "Repo Hygiene",
    shortLabel: "Repo Hygiene",
    description: "Read-only cleanup cockpit for generated files, secrets, tests, workspace maps, and reviewable source boundaries.",
    group: "Audit",
    readiness: "review-required",
    safetyPosture: "read-only",
    badge: "Hygiene",
    priority: 87.25,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "repo-hygiene",
  },
  "/quality-audit": {
    id: "quality-audit",
    href: "/quality-audit",
    label: "System Quality Audit",
    shortLabel: "Quality Audit",
    description: "Read-only full system quality audit for bugs, routes, safety, smokes, and the coding MVP path.",
    group: "Audit",
    readiness: "review-required",
    safetyPosture: "read-only",
    badge: "Audit",
    priority: 87.5,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "quality-audit",
  },
  "/consolidation": {
    id: "consolidation",
    href: "/consolidation",
    label: "Consolidation",
    shortLabel: "Consolidation",
    description: "Read-only consolidation cockpit for route prominence, shared readiness, safety copy, workflow entrypoints, and Phase 56 planning.",
    group: "Audit",
    readiness: "review-required",
    safetyPosture: "read-only",
    badge: "Phase 55",
    priority: 88,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "consolidation-pass",
  },
  "/validation": {
    id: "validation",
    href: "/validation",
    label: "Validation Runner",
    shortLabel: "Validate",
    description: "Approval-gated Validation Runner v1 for allowlisted build, smoke, and git-check commands with output capture and result routing.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "approval-gated",
    badge: "Phase 59",
    priority: 89,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "validation-runner",
  },
  "/stabilization": {
    id: "stabilization",
    href: "/stabilization",
    label: "Stabilization Command Center",
    shortLabel: "Stabilize",
    description: "Build posture, smoke posture, regression queues, apply gates, and next safest action.",
    group: "Fix",
    readiness: "available",
    safetyPosture: "operator-safe",
    badge: "Safety",
    priority: 90,
    requiresReview: false,
    noMutation: true,
    commandDeckRole: "stabilization",
  },
  "/history": {
    id: "history",
    href: "/history",
    label: "History",
    shortLabel: "History",
    description: "Local timeline for activity, notes, decisions, and export context.",
    group: "Advanced",
    readiness: "available",
    safetyPosture: "local-first",
    badge: "History",
    priority: 100,
    requiresReview: false,
    noMutation: true,
    commandDeckRole: "timeline",
  },
};

export function buildCodexForgeNavigationRoute(
  input: CodexForgeNavigationRouteInput
): CodexForgeNavigationRoute {
  const fallback = ROUTE_DEFAULTS[input.href];
  return {
    ...fallback,
    ...input,
    id: (input.id ?? fallback.id) as CodexForgeNavigationRouteId,
    href: input.href,
    noMutation: input.noMutation ?? true,
  };
}

export function buildCodexForgeNavigationRoutes(
  availability: CodexForgeNavigationRouteAvailability = Object.fromEntries(
    ROUTE_ORDER.map((href) => [href, true])
  ) as CodexForgeNavigationRouteAvailability,
  suppliedRoutes: readonly CodexForgeNavigationRouteInput[] = []
): CodexForgeNavigationRoute[] {
  const suppliedByHref = new Map(dedupeCodexForgeNavigationRouteInputs(suppliedRoutes).map((route) => [route.href, route]));
  const knownRoutes = ROUTE_ORDER.filter((href) => availability[href] === true).map((href) =>
    buildCodexForgeNavigationRoute(suppliedByHref.get(href) ?? { href })
  );
  const explicitUnknown = suppliedRoutes
    .filter((route) => !ROUTE_ORDER.includes(route.href) && availability[route.href] === true)
    .map(buildCodexForgeNavigationRoute);

  return dedupeCodexForgeNavigationRoutes([...knownRoutes, ...explicitUnknown]).sort((a, b) => a.priority - b.priority || a.href.localeCompare(b.href));
}

export function dedupeCodexForgeNavigationRouteInputs(
  routes: readonly CodexForgeNavigationRouteInput[]
): CodexForgeNavigationRouteInput[] {
  const byHref = new Map<CodexForgeNavigationRouteHref, CodexForgeNavigationRouteInput>();
  for (const route of routes) {
    byHref.set(route.href, route);
  }

  return [...byHref.values()];
}

export function dedupeCodexForgeNavigationRoutes(
  routes: readonly CodexForgeNavigationRoute[]
): CodexForgeNavigationRoute[] {
  const byHref = new Map<CodexForgeNavigationRouteHref, CodexForgeNavigationRoute>();
  for (const route of routes) {
    byHref.set(route.href, route);
  }

  return [...byHref.values()];
}

export function summarizeCodexForgeNavigationRoutes(
  routes: readonly CodexForgeNavigationRoute[]
): string {
  return `${routes.length} routes: ${routes.map((route) => `${route.label} (${route.href})`).join(", ")}`;
}
