import type {
  CodexForgeNavigationRoute,
  CodexForgeNavigationRouteAvailability,
  CodexForgeNavigationRouteHref,
  CodexForgeNavigationRouteId,
  CodexForgeNavigationRouteInput,
} from "./navigation-shell-types";

const ROUTE_ORDER: readonly CodexForgeNavigationRouteHref[] = [
  "/",
  "/start",
  "/code-flow",
  "/code-flow/trial",
  "/code-flow/trial-review",
  "/code-flow/ux-fixes",
  "/apply-guard-review",
  "/apply-validation",
  "/workflow-results",
  "/run-history",
  "/ai",
  "/ai-router",
  "/brain",
  "/files",
  "/tasks",
  "/closed-loop",
  "/memory",
  "/memory-inbox",
  "/runtime-journal",
  "/runtime-replay",
  "/brain-snapshots",
  "/snapshot-restore",
  "/brain-continuity",
  "/handoff",
  "/brain-governance",
  "/creative",
  "/artifacts/review",
  "/video-render",
  "/creative-executor",
  "/creative-sandbox",
  "/creative-readiness",
  "/creative-mvp",
  "/local-bridge-health",
  "/blender",
  "/unreal",
  "/comfyui",
  "/creative-bridge",
  "/capabilities",
  "/activity",
  "/readiness",
  "/consolidation",
  "/validation",
  "/stabilization",
  "/history",
] as const;

const ROUTE_DEFAULTS: Record<CodexForgeNavigationRouteHref, CodexForgeNavigationRoute> = {
  "/": {
    id: "home",
    href: "/",
    label: "Operator Home",
    shortLabel: "Home",
    description: "Command overview for CodexForge readiness, launch surfaces, and next safe action.",
    group: "Start",
    readiness: "available",
    safetyPosture: "local-first",
    badge: "Command",
    priority: 10,
    requiresReview: false,
    noMutation: true,
    commandDeckRole: "overview",
  },
  "/start": {
    id: "start",
    href: "/start",
    label: "Start",
    shortLabel: "Start",
    description: "Plain-English guided entrypoint for choosing the next safe CodexForge workflow.",
    group: "Start",
    readiness: "available",
    safetyPosture: "local-first",
    badge: "Guide",
    priority: 12,
    requiresReview: false,
    noMutation: true,
    commandDeckRole: "start",
  },
  "/code-flow": {
    id: "code-flow",
    href: "/code-flow",
    label: "Fix code safely",
    shortLabel: "Code Flow",
    description: "End-to-end code fix flow: pick a file, describe change, preview patch, review apply, prepare checks, and review result.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "approval-gated",
    badge: "Flow",
    priority: 13,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "code-flow",
  },
  "/code-flow/trial": {
    id: "code-flow-trial",
    href: "/code-flow/trial",
    label: "Coding Trial",
    shortLabel: "Trial",
    description: "Guided coding-flow live trial pack with checklist, safe file choices, validation guide, troubleshooting, and handoff.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "approval-gated",
    badge: "Trial",
    priority: 13.1,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "code-flow-trial",
  },
  "/code-flow/trial-review": {
    id: "code-flow-trial-review",
    href: "/code-flow/trial-review",
    label: "Coding Trial Review",
    shortLabel: "Trial Review",
    description: "Review coding-flow trial notes, friction, pass/fail checklist, validation, safety, UX fixes, and go/no-go.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "review-gated",
    badge: "Review",
    priority: 13.15,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "code-flow-trial-review",
  },
  "/code-flow/ux-fixes": {
    id: "code-flow-ux-fixes",
    href: "/code-flow/ux-fixes",
    label: "Coding UX Fixes",
    shortLabel: "UX Fixes",
    description: "Copy-only UX fix pack for coding-flow wording, primary actions, panel priority, empty states, validation copy, and route handoffs.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "review-gated",
    badge: "UX",
    priority: 13.18,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "code-flow-ux-fixes",
  },
  "/apply-guard-review": {
    id: "apply-guard-review",
    href: "/apply-guard-review",
    label: "Apply Guard Review",
    shortLabel: "Guard Review",
    description: "Review approval packet enforcement, diff/path boundaries, rollback, command/write separation, validation, and go/no-go before a real apply path.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "approval-gated",
    badge: "Phase 82",
    priority: 13.19,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "apply-guard-review",
  },
  "/apply-validation": {
    id: "apply-validation",
    href: "/apply-validation",
    label: "Apply safely, then validate",
    shortLabel: "Apply + Validate",
    description: "Reviewable diff, approval policy, rollback plan, validation checklist, output review, and result routing for the coding flow.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "approval-gated",
    badge: "Hardening",
    priority: 14,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "apply-validation",
  },
  "/workflow-results": {
    id: "workflow-results",
    href: "/workflow-results",
    label: "Review workflow results",
    shortLabel: "Results",
    description: "Review workflow outcomes, capped validation output, copyable handoffs, and optional memory candidates without auto-persistence.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "review-gated",
    badge: "Persistence",
    priority: 14.5,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "workflow-results",
  },
  "/run-history": {
    id: "run-history",
    href: "/run-history",
    label: "Run History",
    shortLabel: "Runs",
    description: "Review recent workflow runs, copy handoffs, choose next actions, and prepare optional memory candidates without hidden persistence.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "review-gated",
    badge: "Timeline",
    priority: 14.7,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "run-history",
  },
  "/ai": {
    id: "ai",
    href: "/ai",
    label: "AI Workspace",
    shortLabel: "AI",
    description: "Conversation, planning, memory context, and reviewed execution handoffs.",
    group: "Start",
    readiness: "review-required",
    safetyPosture: "approval-gated",
    badge: "Workspace",
    priority: 20,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "workspace",
  },
  "/ai-router": {
    id: "ai-router",
    href: "/ai-router",
    label: "AI Router",
    shortLabel: "Router",
    description: "Preview-only provider and model route planning with no API keys stored and no provider calls.",
    group: "Start",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Router",
    priority: 25,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "ai-router",
  },
  "/brain": {
    id: "brain",
    href: "/brain",
    label: "Brain Command Center",
    shortLabel: "Brain",
    description: "Graph inspection, recall context, topology, and mutation-review boundaries.",
    group: "Brain",
    readiness: "review-required",
    safetyPosture: "review-gated",
    badge: "Cognition",
    priority: 30,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "graph",
  },
  "/files": {
    id: "files",
    href: "/files",
    label: "Files Command Center",
    shortLabel: "Files",
    description: "Read-only project tree, file preview, purpose, risk, and preview-only diff handoff.",
    group: "Build",
    readiness: "available",
    safetyPosture: "read-only",
    badge: "Reader + Preview",
    priority: 40,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "file-work",
  },
  "/tasks": {
    id: "tasks",
    href: "/tasks",
    label: "Tasks Workflow",
    shortLabel: "Tasks",
    description: "Reviewed task activation, readiness previews, and copy-only handoffs.",
    group: "Build",
    readiness: "review-required",
    safetyPosture: "approval-gated",
    badge: "Tasks",
    priority: 50,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "task-flow",
  },
  "/closed-loop": {
    id: "closed-loop",
    href: "/closed-loop",
    label: "Closed Loop Fix",
    shortLabel: "Fix",
    description: "Preview-only regression-to-fix workflow map with approval required before patch apply or command execution.",
    group: "Fix",
    readiness: "preview-only",
    safetyPosture: "approval-gated",
    badge: "Preview-only",
    priority: 55,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "closed-loop",
  },
  "/memory": {
    id: "memory",
    href: "/memory",
    label: "Memory Review",
    shortLabel: "Memory",
    description: "Deterministic memory candidate review with explicit promotion boundaries.",
    group: "Memory",
    readiness: "review-required",
    safetyPosture: "review-gated",
    badge: "Memory",
    priority: 60,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "memory-review",
  },
  "/memory-inbox": {
    id: "memory-inbox",
    href: "/memory-inbox",
    label: "Memory Inbox",
    shortLabel: "Inbox",
    description: "Review-first Personal Operator Memory Inbox with Memory Promotion Gate approval, policy, memory.promoted event preview, and blocked execution bridge.",
    group: "Memory",
    readiness: "review-required",
    safetyPosture: "review-gated",
    badge: "Inbox",
    priority: 65,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "memory-inbox",
  },
  "/runtime-journal": {
    id: "runtime-journal",
    href: "/runtime-journal",
    label: "Runtime Journal",
    shortLabel: "Journal",
    description: "Read-only Runtime Event Journal for requests, approvals, policy, validation, reducer previews, blocked or ready results, and append-only audit handoffs.",
    group: "Audit",
    readiness: "review-required",
    safetyPosture: "read-only",
    badge: "Audit",
    priority: 67,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "runtime-journal",
  },
  "/runtime-replay": {
    id: "runtime-replay",
    href: "/runtime-replay",
    label: "Runtime Replay",
    shortLabel: "Replay",
    description: "Preview-only Runtime Event Replay Simulator for selected journal events, graph snapshot reducer preview, impact analysis, risk detection, and rollback guidance.",
    group: "Audit",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Replay",
    priority: 67.5,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "runtime-replay",
  },
  "/brain-snapshots": {
    id: "brain-snapshots",
    href: "/brain-snapshots",
    label: "Brain Snapshots",
    shortLabel: "Snapshots",
    description: "Read-only Brain Snapshot Manager for summary, comparison, integrity review, replay source selection, rollback planning, and memory governance review.",
    group: "Brain",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Snapshots",
    priority: 67.8,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "brain-snapshots",
  },
  "/snapshot-restore": {
    id: "snapshot-restore",
    href: "/snapshot-restore",
    label: "Snapshot Restore Gate",
    shortLabel: "Restore",
    description: "Preview-only Snapshot Restore Approval Gate for restore candidate evidence, approval packet, and future executor request preview.",
    group: "Brain",
    readiness: "preview-only",
    safetyPosture: "read-only",
    badge: "Restore Gate",
    priority: 67.9,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "snapshot-restore",
  },
  "/brain-continuity": {
    id: "brain-continuity",
    href: "/brain-continuity",
    label: "Brain Continuity",
    shortLabel: "Continuity",
    description: "Read-only Brain Continuity Dashboard for memory growth, runtime journal health, snapshot posture, replay readiness, restore risk, governance posture, and next safe action.",
    group: "Brain",
    readiness: "review-required",
    safetyPosture: "read-only",
    badge: "Continuity",
    priority: 67.95,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "brain-continuity",
  },
  "/handoff": {
    id: "handoff",
    href: "/handoff",
    label: "Continuity Handoff",
    shortLabel: "Handoff",
    description: "Read-only Continuity Handoff Packet for current state, risks, validation, rollback posture, memory posture, Brain continuity posture, and next safe actions.",
    group: "Audit",
    readiness: "review-required",
    safetyPosture: "read-only",
    badge: "Handoff",
    priority: 67.97,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "handoff",
  },
  "/brain-governance": {
    id: "brain-governance",
    href: "/brain-governance",
    label: "Brain Governance",
    shortLabel: "Governance",
    description: "Read-only Brain Mutation Governance Console for approved boundaries, direct mutation signals, reducer impact, integrity posture, and risk review.",
    group: "Brain",
    readiness: "review-required",
    safetyPosture: "read-only",
    badge: "Governance",
    priority: 68,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "brain-governance",
  },
  "/creative": {
    id: "creative",
    href: "/creative",
    label: "Creative Production Studio",
    shortLabel: "Creative",
    description: "Preview-only creative briefs, production planning, render queues, and artifact handoffs.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "operator-safe",
    badge: "Creative",
    priority: 70,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "production",
  },
  "/artifacts/review": {
    id: "artifacts-review",
    href: "/artifacts/review",
    label: "Artifact Review",
    shortLabel: "Review",
    description: "Preview-only creative artifact review board with gallery, provenance, inspector, and copy-only handoff.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "review-gated",
    badge: "Review-only",
    priority: 70.25,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "artifact-review",
  },
  "/video-render": {
    id: "video-render",
    href: "/video-render",
    label: "Video Render Job Preview",
    shortLabel: "Video Render",
    description: "Preview-only render input, timeline, shot plan, provider plan, queue preview, artifact expectations, approval packet, policy, and future executor packet.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "operator-safe",
    badge: "Phase 66",
    priority: 70.35,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "video-render-preview",
  },
  "/creative-executor": {
    id: "creative-executor",
    href: "/creative-executor",
    label: "Guarded Creative Executor",
    shortLabel: "Executor",
    description: "Dry-run-first/request-ready creative execution boundary with approval, preflight, kill-switch policy, artifact capture, and execution disabled.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "operator-safe",
    badge: "Phase 67",
    priority: 70.4,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "creative-executor",
  },
  "/creative-sandbox": {
    id: "creative-sandbox",
    href: "/creative-sandbox",
    label: "Creative Execution Sandbox",
    shortLabel: "Sandbox",
    description: "Simulation-only creative executor lifecycle with fake artifacts, cancellation, verification, and review handoff.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "operator-safe",
    badge: "Phase 69",
    priority: 70.42,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "creative-sandbox",
  },
  "/creative-readiness": {
    id: "creative-readiness",
    href: "/creative-readiness",
    label: "Real Creative Executor Readiness",
    shortLabel: "Creative Readiness",
    description: "Audit-only readiness review for local bridge profiles, adapter allowlists, path boundaries, artifact output, dry-run evidence, approval, kill-switch, and future health probe posture.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "operator-safe",
    badge: "Phase 70",
    priority: 70.43,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "creative-readiness",
  },
  "/creative-mvp": {
    id: "creative-mvp",
    href: "/creative-mvp",
    label: "Real Creative Executor MVP Design",
    shortLabel: "Creative MVP",
    description: "Design-only first real creative executor MVP selection with approval, output boundary, kill-switch, and artifact review criteria. Execution allowed false.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "operator-safe",
    badge: "Phase 72",
    priority: 70.435,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "creative-mvp",
  },
  "/health-probe": {
    id: "health-probe",
    href: "/health-probe",
    label: "Future Guarded Health Probe",
    shortLabel: "Health Probe",
    description: "Metadata-only/manual-first guarded health probe request, allowlist, approval, preflight, bridge, result, and readiness update review.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "operator-safe",
    badge: "Phase 71",
    priority: 70.44,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "health-probe",
  },
  "/local-bridge-health": {
    id: "local-bridge-health",
    href: "/local-bridge-health",
    label: "Local Bridge Health",
    shortLabel: "Bridge Health",
    description: "Preview/manual-only local bridge health target, profile, policy, probe preview, setup guide, and next action review.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "operator-safe",
    badge: "Phase 68",
    priority: 70.45,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "local-bridge-health",
  },
  "/blender": {
    id: "blender",
    href: "/blender",
    label: "Blender Adapter Preview",
    shortLabel: "Blender",
    description: "Preview-only Blender scene model, Python script preview, safety policy, and future executor packet.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "operator-safe",
    badge: "Phase 62",
    priority: 70.5,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "blender-preview",
  },
  "/unreal": {
    id: "unreal",
    href: "/unreal",
    label: "Unreal Adapter Preview",
    shortLabel: "Unreal",
    description: "Preview-only Unreal level model, actor/asset/material/Blueprint/Sequencer plans, command preview, safety policy, and future executor packet.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "operator-safe",
    badge: "Phase 65",
    priority: 70.62,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "unreal-preview",
  },
  "/comfyui": {
    id: "comfyui",
    href: "/comfyui",
    label: "ComfyUI Adapter Preview",
    shortLabel: "ComfyUI",
    description: "Preview-only ComfyUI workflow manifest, prompt nodes, approval packet, and future executor handoff.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "operator-safe",
    badge: "Preview",
    priority: 70.75,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "comfyui-preview",
  },
  "/creative-bridge": {
    id: "creative-bridge",
    href: "/creative-bridge",
    label: "Creative Bridge",
    shortLabel: "Bridge",
    description: "Preview-only creative bridge profiles, adapter readiness, job request, approval packet, artifact capture plan, and handoff.",
    group: "Creative",
    readiness: "preview-only",
    safetyPosture: "operator-safe",
    badge: "Bridge",
    priority: 71,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "creative-bridge",
  },
  "/capabilities": {
    id: "capabilities",
    href: "/capabilities",
    label: "Capability Cockpit",
    shortLabel: "Capabilities",
    description: "Tool readiness, policy boundaries, consent posture, and blocked execution visibility.",
    group: "Advanced",
    readiness: "available",
    safetyPosture: "operator-safe",
    badge: "Capability",
    priority: 80,
    requiresReview: false,
    noMutation: true,
    commandDeckRole: "capability",
  },
  "/activity": {
    id: "activity",
    href: "/activity",
    label: "Global Activity Feed",
    shortLabel: "Activity",
    description: "Read-only activity feed for verification, regression, patch workflow, apply gates, memory review, creative planning, stabilization, and next safe action.",
    group: "Audit",
    readiness: "available",
    safetyPosture: "read-only",
    badge: "Activity",
    priority: 85,
    requiresReview: false,
    noMutation: true,
    commandDeckRole: "activity-feed",
  },
  "/readiness": {
    id: "readiness",
    href: "/readiness",
    label: "Product Readiness Audit",
    shortLabel: "Readiness",
    description: "Read-only product readiness audit cockpit for route, smoke, safety, UX, consolidation, and functional workflow posture.",
    group: "Audit",
    readiness: "review-required",
    safetyPosture: "read-only",
    badge: "Readiness",
    priority: 87,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "readiness-audit",
  },
  "/consolidation": {
    id: "consolidation",
    href: "/consolidation",
    label: "Consolidation",
    shortLabel: "Consolidation",
    description: "Read-only consolidation cockpit for route prominence, shared readiness, safety copy, workflow entrypoints, and Phase 56 planning.",
    group: "Audit",
    readiness: "review-required",
    safetyPosture: "read-only",
    badge: "Phase 55",
    priority: 88,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "consolidation-pass",
  },
  "/validation": {
    id: "validation",
    href: "/validation",
    label: "Validation Runner",
    shortLabel: "Validate",
    description: "Approval-gated Validation Runner v1 for allowlisted build, smoke, and git-check commands with output capture and result routing.",
    group: "Fix",
    readiness: "review-required",
    safetyPosture: "approval-gated",
    badge: "Phase 59",
    priority: 89,
    requiresReview: true,
    noMutation: true,
    commandDeckRole: "validation-runner",
  },
  "/stabilization": {
    id: "stabilization",
    href: "/stabilization",
    label: "Stabilization Command Center",
    shortLabel: "Stabilize",
    description: "Build posture, smoke posture, regression queues, apply gates, and next safest action.",
    group: "Fix",
    readiness: "available",
    safetyPosture: "operator-safe",
    badge: "Safety",
    priority: 90,
    requiresReview: false,
    noMutation: true,
    commandDeckRole: "stabilization",
  },
  "/history": {
    id: "history",
    href: "/history",
    label: "History",
    shortLabel: "History",
    description: "Local timeline for activity, notes, decisions, and export context.",
    group: "Advanced",
    readiness: "available",
    safetyPosture: "local-first",
    badge: "History",
    priority: 100,
    requiresReview: false,
    noMutation: true,
    commandDeckRole: "timeline",
  },
};

export function buildCodexForgeNavigationRoute(
  input: CodexForgeNavigationRouteInput
): CodexForgeNavigationRoute {
  const fallback = ROUTE_DEFAULTS[input.href];
  return {
    ...fallback,
    ...input,
    id: (input.id ?? fallback.id) as CodexForgeNavigationRouteId,
    href: input.href,
    noMutation: input.noMutation ?? true,
  };
}

export function buildCodexForgeNavigationRoutes(
  availability: CodexForgeNavigationRouteAvailability = Object.fromEntries(
    ROUTE_ORDER.map((href) => [href, true])
  ) as CodexForgeNavigationRouteAvailability,
  suppliedRoutes: readonly CodexForgeNavigationRouteInput[] = []
): CodexForgeNavigationRoute[] {
  const suppliedByHref = new Map(dedupeCodexForgeNavigationRouteInputs(suppliedRoutes).map((route) => [route.href, route]));
  const knownRoutes = ROUTE_ORDER.filter((href) => availability[href] === true).map((href) =>
    buildCodexForgeNavigationRoute(suppliedByHref.get(href) ?? { href })
  );
  const explicitUnknown = suppliedRoutes
    .filter((route) => !ROUTE_ORDER.includes(route.href) && availability[route.href] === true)
    .map(buildCodexForgeNavigationRoute);

  return dedupeCodexForgeNavigationRoutes([...knownRoutes, ...explicitUnknown]).sort((a, b) => a.priority - b.priority || a.href.localeCompare(b.href));
}

export function dedupeCodexForgeNavigationRouteInputs(
  routes: readonly CodexForgeNavigationRouteInput[]
): CodexForgeNavigationRouteInput[] {
  const byHref = new Map<CodexForgeNavigationRouteHref, CodexForgeNavigationRouteInput>();
  for (const route of routes) {
    byHref.set(route.href, route);
  }

  return [...byHref.values()];
}

export function dedupeCodexForgeNavigationRoutes(
  routes: readonly CodexForgeNavigationRoute[]
): CodexForgeNavigationRoute[] {
  const byHref = new Map<CodexForgeNavigationRouteHref, CodexForgeNavigationRoute>();
  for (const route of routes) {
    byHref.set(route.href, route);
  }

  return [...byHref.values()];
}

export function summarizeCodexForgeNavigationRoutes(
  routes: readonly CodexForgeNavigationRoute[]
): string {
  return `${routes.length} routes: ${routes.map((route) => `${route.label} (${route.href})`).join(", ")}`;
}
