import type { FunctionalWorkflowStatus, ProductFunctionalWorkflowAudit, ProductFunctionalWorkflowItem, ProductRoutePath } from "./product-readiness-types";
import { buildProductReadinessStableKey } from "./product-readiness-types";

const WORKFLOWS: readonly Omit<ProductFunctionalWorkflowItem, "id">[] = [
  { label: "project file read", status: "functional", missingPieces: [], safetyBlockers: ["no source file mutation from UI"], nextFunctionalPhase: "Phase 57 Real Patch Preview v1", routeEntryPoints: ["/files"], validationNeeded: ["Local Project Reader smoke", "read-only safety assertions"], },
  { label: "File Reader v1 functional/read-only", status: "functional", missingPieces: [], safetyBlockers: ["no source file mutation from UI", "no command execution from UI"], nextFunctionalPhase: "Phase 57 Real Patch Preview v1", routeEntryPoints: ["/files"], validationNeeded: ["Local Project Reader smoke", "Files smoke"], },
  { label: "Patch Preview v1 functional/preview-only", status: "functional", missingPieces: [], safetyBlockers: ["no apply from UI", "no file writes from UI", "no command execution from UI"], nextFunctionalPhase: "Phase 58 Approved Patch Apply v1", routeEntryPoints: ["/files"], validationNeeded: ["Real Patch Preview smoke", "Local Project Reader smoke", "git diff --check"] },
  { label: "Approved Patch Apply v1 request-ready", status: "preview-only", missingPieces: ["guarded apply execution remains blocked until safe API bridge is available"], safetyBlockers: ["explicit approval required", "dry-run/preflight required", "rollback plan required", "validation plan required", "no direct apply-diff from UI"], nextFunctionalPhase: "Phase 59 Validation Runner v1", routeEntryPoints: ["/files"], validationNeeded: ["Approved Patch Apply smoke", "git diff --check"] },
  { label: "Real Apply Guard Review safety/reliability gate", status: "preview-only", missingPieces: ["Guarded Apply Candidate Implementation only if go/no-go permits"], safetyBlockers: ["executionAllowed false in Phase 82", "no auto-apply", "no auto-run", "approval required", "rollback required", "validation required"], nextFunctionalPhase: "Guarded Apply Candidate Implementation only if go/no-go permits", routeEntryPoints: ["/apply-guard-review"], validationNeeded: ["Real Apply Guard Review smoke", "build", "server smoke", "git diff --check"] },
  { label: "Guarded Apply Candidate Implementation Plan safety/reliability planning layer", status: "preview-only", missingPieces: ["Guarded Apply Candidate MVP only if blocker gaps are cleared"], safetyBlockers: ["executionAllowed false in Phase 83", "one file only", "one diff only", "explicit approval required", "rollback contract required", "validation contract required", "no direct UI write-file/apply-diff/run-command"], nextFunctionalPhase: "Guarded Apply Candidate MVP only if gaps are cleared", routeEntryPoints: ["/guarded-apply-candidate"], validationNeeded: ["Guarded Apply Candidate smoke", "build", "server smoke", "git diff --check"] },
  { label: "Validation Runner v1 request-ready/manual-only", status: "preview-only", missingPieces: ["guarded command API remains absent, so bridge is request-ready/manual-only"], safetyBlockers: ["explicit approval required", "allowlisted commands only", "no arbitrary shell", "no command execution from UI", "no Brain graph mutation"], nextFunctionalPhase: "Phase 60 Closed Loop Fix Workflow", routeEntryPoints: ["/validation"], validationNeeded: ["Validation Runner smoke", "build", "server smoke", "git diff --check"] },
  { label: "Creative Local Bridge v1 preview-only/request-ready", status: "preview-only", missingPieces: ["future guarded executor for Blender Adapter Preview v1"], safetyBlockers: ["no render execution", "no command execution from UI", "no file writes from UI", "no external provider calls"], nextFunctionalPhase: "Blender Adapter Preview v1", routeEntryPoints: ["/creative-bridge"], validationNeeded: ["Creative Local Bridge smoke", "Creative Production Studio smoke"] },
  { label: "Blender Adapter Preview v1 preview-only", status: "preview-only", missingPieces: ["future guarded creative executor for approved Blender execution"], safetyBlockers: ["no Blender execution", "no render execution", "no file writes from UI", "operator review required"], nextFunctionalPhase: "ComfyUI Adapter Preview v1 or future guarded creative executor", routeEntryPoints: ["/blender"], validationNeeded: ["Blender Adapter Preview smoke", "build", "git diff --check"] },
  { label: "Unreal Adapter Preview v1 preview-only", status: "preview-only", missingPieces: ["Future Guarded Creative Executor for approved Unreal execution"], safetyBlockers: ["no Unreal execution", "no Unreal Editor launch", "no render execution", "no package/build", "no file writes from UI", "operator review required"], nextFunctionalPhase: "Future Guarded Creative Executor or Video Render Job Preview", routeEntryPoints: ["/unreal"], validationNeeded: ["Unreal Adapter Preview smoke", "build", "git diff --check"] },
  { label: "Video Render Job Preview v1 preview-only", status: "preview-only", missingPieces: ["Future Guarded Creative Executor for approved render execution"], safetyBlockers: ["no render execution", "no Blender execution", "no ComfyUI execution", "no Unreal execution", "no ffmpeg execution", "no file writes from UI", "operator review required"], nextFunctionalPhase: "Future Guarded Creative Executor", routeEntryPoints: ["/video-render"], validationNeeded: ["Video Render Job Preview smoke", "build", "git diff --check"] },
  { label: "Guarded Creative Executor dry-run-first/request-ready", status: "preview-only", missingPieces: ["Local Bridge Health Check v1", "Creative Execution Sandbox"], safetyBlockers: ["real execution blocked by default", "approval required", "kill-switch plan required", "artifact capture plan required", "no command execution from UI"], nextFunctionalPhase: "Local Bridge Health Check v1 or Creative Execution Sandbox", routeEntryPoints: ["/creative-executor"], validationNeeded: ["Guarded Creative Executor smoke", "build", "git diff --check"] },
  { label: "Local Bridge Health Check v1 preview/manual-only", status: "preview-only", missingPieces: ["Future Guarded Health Probe", "Creative Execution Sandbox"], safetyBlockers: ["probes blocked by default", "no command execution from UI", "no local HTTP calls by default", "no file writes from UI", "no render execution"], nextFunctionalPhase: "Future Guarded Health Probe or Creative Execution Sandbox", routeEntryPoints: ["/local-bridge-health"], validationNeeded: ["Local Bridge Health smoke", "build", "git diff --check"] },
  { label: "Future Guarded Health Probe metadata/manual-first", status: "preview-only", missingPieces: ["Real probes disabled by default", "Real Creative Executor MVP Design after readiness passes"], safetyBlockers: ["metadata/manual-first", "no creative job execution", "no render execution", "no arbitrary command", "no arbitrary endpoint", "no file writes from UI"], nextFunctionalPhase: "Real Creative Executor MVP Design only if readiness passes", routeEntryPoints: ["/health-probe"], validationNeeded: ["Future Guarded Health Probe smoke", "build", "git diff --check"] },
  { label: "Real Creative Executor MVP Design design-only", status: "preview-only", missingPieces: ["Phase 73 User-Friendly Product Simplification or Phase 73.5 Real Executor MVP Implementation Plan"], safetyBlockers: ["design-only", "execution allowed false", "no real execution", "no render execution", "no command execution from UI", "no file writes from UI"], nextFunctionalPhase: "Phase 73 User-Friendly Product Simplification if UX is still too busy, otherwise Phase 73.5 Real Executor MVP Implementation Plan", routeEntryPoints: ["/creative-mvp"], validationNeeded: ["Real Creative Executor MVP Design smoke", "build", "git diff --check"] },
  { label: "Creative Execution Sandbox simulation-only", status: "preview-only", missingPieces: ["Future Guarded Health Probe", "Real Creative Executor MVP"], safetyBlockers: ["simulation-only", "no real execution", "no render execution", "no command execution from UI", "no local HTTP calls", "no file writes from UI"], nextFunctionalPhase: "Future Guarded Health Probe or Real Creative Executor MVP", routeEntryPoints: ["/creative-sandbox"], validationNeeded: ["Creative Execution Sandbox smoke", "build", "git diff --check"] },
  { label: "Real Creative Executor Readiness Audit audit-only", status: "preview-only", missingPieces: ["Phase 71 Future Guarded Health Probe"], safetyBlockers: ["audit-only", "execution allowed false", "no real execution", "no render execution", "no command execution from UI", "no local HTTP calls", "no file writes from UI"], nextFunctionalPhase: "Phase 71 Future Guarded Health Probe", routeEntryPoints: ["/creative-readiness"], validationNeeded: ["Real Creative Executor Readiness smoke", "build", "git diff --check"] },
  { label: "file-to-brain context", status: "scaffolded", missingPieces: ["visible selected file to Brain context handoff"], safetyBlockers: ["no graph mutation"], nextFunctionalPhase: "Make Files real read-only workflow", routeEntryPoints: ["/files", "/brain"], validationNeeded: ["Brain context smoke"] },
  { label: "chat-to-task", status: "scaffolded", missingPieces: ["single reviewed task creation path"], safetyBlockers: ["latest-message authority preserved"], nextFunctionalPhase: "Functional workflow pass", routeEntryPoints: ["/jarvis", "/tasks"], validationNeeded: ["task activation smoke"] },
  { label: "task-to-patch-preview", status: "preview-only", missingPieces: ["task output to patch preview queue"], safetyBlockers: ["no apply without approval"], nextFunctionalPhase: "Make Patch Preview real", routeEntryPoints: ["/tasks", "/files"], validationNeeded: ["patch preview queue smoke"] },
  { label: "patch-preview-to-apply-gate", status: "preview-only", missingPieces: ["approved apply request model"], safetyBlockers: ["no direct apply-diff from UI"], nextFunctionalPhase: "implement approved patch apply", routeEntryPoints: ["/files", "/stabilization"], validationNeeded: ["apply gate smoke"] },
  { label: "apply-gate-to-validation", status: "blocked", missingPieces: ["validation runner", "operator approval boundary"], safetyBlockers: ["no command execution without approval"], nextFunctionalPhase: "implement validation runner", routeEntryPoints: ["/stabilization"], validationNeeded: ["manual validation checklist"] },
  { label: "validation-to-regression-triage", status: "preview-only", missingPieces: ["validation result ingestion"], safetyBlockers: ["evidence is context, not authority"], nextFunctionalPhase: "close loop regression repair", routeEntryPoints: ["/stabilization", "/activity"], validationNeeded: ["regression triage smoke"] },
  { label: "regression-to-fix-queue", status: "preview-only", missingPieces: ["fix queue to patch preview handoff"], safetyBlockers: ["no auto-fix"], nextFunctionalPhase: "close loop regression repair", routeEntryPoints: ["/stabilization", "/files"], validationNeeded: ["regression fix queue smoke"] },
  { label: "memory-inbox-to-promotion-gate", status: "preview-only", missingPieces: ["single memory review lane"], safetyBlockers: ["no auto-promote memory"], nextFunctionalPhase: "Memory review consolidation", routeEntryPoints: ["/memory-inbox", "/memory"], validationNeeded: ["memory promotion gate smoke"] },
  { label: "runtime-event-to-journal", status: "preview-only", missingPieces: ["guarded runtime event result review"], safetyBlockers: ["no appendEvent from UI"], nextFunctionalPhase: "Runtime audit consolidation", routeEntryPoints: ["/runtime-journal"], validationNeeded: ["runtime journal smoke"] },
  { label: "snapshot-to-replay", status: "preview-only", missingPieces: ["clear snapshot replay source selection"], safetyBlockers: ["no graph mutation"], nextFunctionalPhase: "Brain continuity consolidation", routeEntryPoints: ["/brain-snapshots", "/runtime-replay"], validationNeeded: ["snapshot and replay smoke"] },
  { label: "replay-to-restore-gate", status: "preview-only", missingPieces: ["restore approval evidence chain"], safetyBlockers: ["snapshot restore blocked by default"], nextFunctionalPhase: "Brain continuity consolidation", routeEntryPoints: ["/runtime-replay", "/snapshot-restore"], validationNeeded: ["snapshot restore gate smoke"] },
  { label: "creative-plan-to-render-queue", status: "preview-only", missingPieces: ["render queue execution boundary"], safetyBlockers: ["no external execution from audit"], nextFunctionalPhase: "Creative workflow pass", routeEntryPoints: ["/creative"], validationNeeded: ["creative production smoke"] },
] as const;

export function buildFunctionalWorkflowItem(input: Partial<ProductFunctionalWorkflowItem> & Pick<ProductFunctionalWorkflowItem, "label">): ProductFunctionalWorkflowItem {
  const definition = WORKFLOWS.find((workflow) => workflow.label === input.label);
  return {
    id: input.id ?? buildProductReadinessStableKey("functional-workflow", input.label),
    status: "unknown" as FunctionalWorkflowStatus,
    missingPieces: [],
    safetyBlockers: [],
    nextFunctionalPhase: "Review workflow",
    routeEntryPoints: [] as ProductRoutePath[],
    validationNeeded: [],
    ...definition,
    ...input,
  };
}

export function buildFunctionalWorkflowAudit(items: readonly Partial<ProductFunctionalWorkflowItem>[] = WORKFLOWS): ProductFunctionalWorkflowAudit {
  const workflows = items.map((item) => buildFunctionalWorkflowItem(item as ProductFunctionalWorkflowItem));
  const functionalCount = workflows.filter((item) => item.status === "functional").length;
  const blockedCount = workflows.filter((item) => item.status === "blocked").length;
  return {
    id: "product-functional-workflow-audit",
    items: workflows,
    functionalCount,
    blockedCount,
    summary: summarizeFunctionalWorkflowAudit({ items: workflows, functionalCount, blockedCount }),
  };
}

export function summarizeFunctionalWorkflowAudit(audit: Pick<ProductFunctionalWorkflowAudit, "items" | "functionalCount" | "blockedCount">): string[] {
  return [
    `${audit.functionalCount}/${audit.items.length} workflows are fully functional.`,
    `${audit.blockedCount} workflows are blocked; most remain preview-only or scaffolded.`,
    "Approved Patch Apply v1 request-ready can now recommend Real Apply Guard Review before Guarded Apply Candidate Implementation Plan; Guarded Apply Candidate MVP is only recommended if blocker gaps are cleared. Validation Runner v1 can recommend Phase 60 Closed Loop Fix Workflow; Creative Local Bridge v1 can recommend Blender Adapter Preview v1, Unreal Adapter Preview v1, Video Render Job Preview v1, then ComfyUI Adapter Preview v1, Guarded Creative Executor, Creative Execution Sandbox simulation-only review, Real Creative Executor Readiness Audit audit-only review, or Real Creative Executor MVP Design design-only review.",
  ];
}
