"use client";

import { CodexForgeAppShell } from "@/lib/codexforge/navigation-shell";
import { PROVIDER_ADAPTER_REGISTRY_BACKEND_CONTRACT_BLOCKED_ACTION_ITEMS, PROVIDER_ADAPTER_REGISTRY_BACKEND_CONTRACT_PIPELINE_ITEMS, PROVIDER_ADAPTER_REGISTRY_BACKEND_CONTRACT_PROTECTED_BOUNDARY_ITEMS, PROVIDER_ADAPTER_REGISTRY_BACKEND_CONTRACT_SHARED_MARKERS, buildProviderAdapterRegistryBackendContractModel, buildProviderAdapterRegistryBackendContractStableKey, type ProviderAdapterRegistryBackendContractRouteSlug } from "../provider-adapter-registry-backend-contract-model";
import styles from "../../jarvis-cockpit-visual-system/components/JarvisCockpitVisualPanel.module.css";

export function ProviderAdapterRegistryBackendContractPageClientShell({ routeSlug }: { routeSlug: ProviderAdapterRegistryBackendContractRouteSlug }) {
  const model = buildProviderAdapterRegistryBackendContractModel(routeSlug);
  return (
    <CodexForgeAppShell activePath={model.route.href} workspaceLabel={model.route.title} nextActionContext={{ wantsOperatorOverview: false }} focusMode contentMaxWidth="wide" pageChrome="minimal" showRightRail={false} showSidebarSafetyNotice={false} showHeroRouteChips={false}>
      <ProviderAdapterRegistryBackendContractRoutePanel routeSlug={routeSlug} />
    </CodexForgeAppShell>
  );
}

export function ProviderAdapterRegistryBackendContractCockpitSection() {
  return <ProviderAdapterRegistryBackendContractRoutePanel routeSlug="provider-adapter-registry-backend-contract-completion" embedded />;
}

export function ProviderAdapterRegistryBackendContractRoutePanel({ routeSlug, embedded = false }: { routeSlug: ProviderAdapterRegistryBackendContractRouteSlug; embedded?: boolean }) {
  const model = buildProviderAdapterRegistryBackendContractModel(routeSlug);
  return (
    <section className={embedded ? styles.cockpitShell : styles.routeShell} data-codexforge-provider-adapter-registry-backend-contract={PROVIDER_ADAPTER_REGISTRY_BACKEND_CONTRACT_SHARED_MARKERS.join(" | ")} data-codexforge-provider-adapter-registry-backend-contract-route={model.route.markerPhrases.join(" | ")} data-codexforge-provider-adapter-registry-backend-contract-pipeline={PROVIDER_ADAPTER_REGISTRY_BACKEND_CONTRACT_PIPELINE_ITEMS.map((item) => item.label).join(" | ")}>
      <header className={styles.heroPanel}>
        <div className={styles.heroGlow} aria-hidden="true" />
        <div className={styles.heroContent}>
          <div className={styles.eyebrowRow}><span className={styles.phaseBadge}>{embedded ? "Provider Adapter Registry Backend Contract" : model.route.phase}</span><span className={styles.safeBadge}>review-only provider adapter registry contract</span><span className={styles.blockedBadge}>operator-approved only</span></div>
          <h1 className={styles.heroTitle}>{embedded ? "Provider Adapter Registry Backend Contract" : model.route.title}</h1>
          <p className={styles.heroLead}>This route is a review-only provider adapter registry contract with synthetic provider adapter registry data only. The provider adapter registry remains disabled until explicit operator approval. It defines the disabled provider adapter catalog, provider capability map, credential and token boundaries, request response and error envelopes, approval audit redaction envelopes, cost rate privacy safety guards, region retention retry fallback policies, observability trace, runner handoff, readiness gate, and completion checks without provider calls, model calls, prompt sending, streaming, provider SDK imports, network egress, frontend persistence, credential storage, token storage, provider key storage, worker dispatch, render execution, exports, publishing, or runtime deploy.</p>
          <div className={styles.heroMetricGrid}><MetricCard label="Route slug" value={model.route.slug} detail={model.route.href} /><MetricCard label="Data" value="Synthetic" detail="synthetic provider adapter registry data only" /><MetricCard label="Approval" value="Required" detail="provider adapter registry remains disabled until explicit operator approval" /><MetricCard label="Execution" value="Blocked" detail="provider adapter registry completion does not call providers" /></div>
        </div>
        <div className={styles.missionPreview} aria-label="Provider Adapter Registry Backend Contract preview"><p className={styles.missionLabel}>Adapter registry</p><p className={styles.missionDetail}>Review-only. Disabled by default. No live provider calls. No model calls. No prompt sending. No streaming. No provider SDK imports. No network egress. No frontend persistence. No credential storage. No token storage. No provider key storage.</p></div>
      </header>
      <section className={styles.markerBand} aria-label="Provider Adapter Registry Backend Contract shared markers">{model.safetyMarkers.map((marker, index) => <span key={buildProviderAdapterRegistryBackendContractStableKey(["shared-marker", String(index), marker])} className={styles.markerPill}>{marker}</span>)}</section>
      <section className={styles.glassPanel} aria-label="Review-only provider adapter registry contract pipeline"><PanelHeading eyebrow="Review-only provider adapter registry contract" title="Backend-owned provider adapter registry surface remains disabled until explicit operator approval" badge="Static only" /><p className={styles.bodyText}>This provider adapter registry surface is synthetic provider adapter registry data only. It does not call providers, call models, send prompts, stream tokens, import provider SDKs, upload or download files, execute render queues, dispatch workers, export artifacts, publish content, create OAuth flows, create webhooks, create signed URLs, store credentials, store tokens, store provider keys, write browser storage, call connectors, create APIs, bind ports, deploy runtimes, or use network egress.</p><div className={styles.systemsGrid}>{PROVIDER_ADAPTER_REGISTRY_BACKEND_CONTRACT_PIPELINE_ITEMS.map((item) => <article key={buildProviderAdapterRegistryBackendContractStableKey(["pipeline", item.id])} className={styles.systemCard}><span className={styles.systemTier}>Provider adapter contract path</span><strong>{item.label}</strong><p className={styles.systemStatus}>{item.state}</p></article>)}</div></section>
      <section className={styles.glassPanel} aria-label="Provider Adapter Registry Backend Contract route map"><PanelHeading eyebrow="Provider Adapter Registry Backend Contract" title={model.route.title} badge={model.route.phase} /><p className={styles.bodyText}>{model.route.summary}</p><div className={styles.contractGrid}>{model.route.markerPhrases.map((marker, index) => <span key={buildProviderAdapterRegistryBackendContractStableKey(["route-marker", model.route.slug, String(index), marker])} className={styles.contractChip}>{marker}</span>)}</div></section>
      <section className={styles.glassPanel} aria-label="Provider adapter registry blocked execution matrix"><PanelHeading eyebrow="Blocked Execution Matrix" title="Provider model prompt network storage media worker export publish runtime and credential execution stay blocked" badge="Actions disabled" /><div className={styles.blockedDeckGrid}>{PROVIDER_ADAPTER_REGISTRY_BACKEND_CONTRACT_BLOCKED_ACTION_ITEMS.map((item) => <button key={buildProviderAdapterRegistryBackendContractStableKey(["blocked", item.id])} type="button" disabled className={styles.blockedCommandButton}><strong>{item.label}</strong><span>{item.state}</span><small>review-only provider adapter registry contract</small></button>)}</div></section>
      <section className={styles.cockpitGrid} aria-label="Provider adapter registry protected boundaries"><CatalogPanel eyebrow="Protected Provider Adapter Boundaries" title="Capability mapping credential isolation approval audit redaction observability policy and guard controls" items={PROVIDER_ADAPTER_REGISTRY_BACKEND_CONTRACT_PROTECTED_BOUNDARY_ITEMS} /><CatalogPanel eyebrow="Provider Adapter Control Coverage" title="Blocked provider model prompt SDK network storage render worker export publish runtime credential and token controls" items={PROVIDER_ADAPTER_REGISTRY_BACKEND_CONTRACT_BLOCKED_ACTION_ITEMS} /></section>
      <section className={styles.glassPanel} aria-label="Provider Adapter Registry Backend Contract completion guard"><PanelHeading eyebrow="Completion Guard" title="2922-2953 - Provider Adapter Registry Backend Contract" badge="Phase 2953" /><p className={styles.mutedText}>Provider Adapter Registry Backend Contract is a review-only provider adapter registry contract with synthetic provider adapter registry data only. The provider adapter registry remains disabled until explicit operator approval. The disabled provider adapter catalog, provider capability map, text image audio video transcription editing metadata and safety capability entries, credential and token boundaries, request response error approval audit redaction envelopes, cost rate privacy safety guards, region retention retry fallback policies, observability trace, provider runner handoff remains review-only, provider adapter readiness gate, and provider adapter registry completion does not call providers. Next likely batch: 2954-2985 - First Approved Provider Execution Bridge.</p></section>
      <section className={styles.diagnosticPanel} aria-label="Provider Adapter Registry Backend Contract diagnostics"><PanelHeading eyebrow="Diagnostics" title="2922-2953 provider adapter registry contract coverage" badge="Phase pages secondary" /><div className={styles.diagnosticGrid}>{model.routes.map((item) => <a key={buildProviderAdapterRegistryBackendContractStableKey(["provider-adapter-registry-contract-route", item.slug])} className={styles.diagnosticLink} href={item.href}><span>{item.phase}</span><strong>{item.title}</strong></a>)}</div></section>
    </section>
  );
}

function MetricCard({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className={styles.metricCard}><span className={styles.metricLabel}>{label}</span><strong className={styles.metricValue}>{value}</strong><span className={styles.metricDetail}>{detail}</span></article>; }

function CatalogPanel({ eyebrow, title, items }: { eyebrow: string; title: string; items: readonly { id: string; label: string; state: string }[] }) { return <article className={styles.glassPanel}><PanelHeading eyebrow={eyebrow} title={title} badge="Review only" /><div className={styles.systemsGrid}>{items.map((item) => <article key={buildProviderAdapterRegistryBackendContractStableKey(["catalog", eyebrow, item.id])} className={styles.systemCard}><span className={styles.systemTier}>Protected boundary</span><strong>{item.label}</strong><p className={styles.systemStatus}>{item.state}</p></article>)}</div></article>; }

function PanelHeading({ eyebrow, title, badge }: { eyebrow: string; title: string; badge: string }) { return <div className={styles.panelHeader}><div><p className={styles.eyebrow}>{eyebrow}</p><h2 className={styles.sectionTitle}>{title}</h2></div><span className={styles.safeBadge}>{badge}</span></div>; }
