import type { HealthProbeTarget, HealthProbeTargetId } from "./future-health-probe-types";

export function buildHealthProbeTarget(target: HealthProbeTarget): HealthProbeTarget {
  return target;
}

export function buildDefaultHealthProbeTargets(): HealthProbeTarget[] {
  const targets: HealthProbeTarget[] = [
    {
      id: "blender-version",
      bridgeTargetId: "blender-local",
      label: "Blender version label",
      targetKind: "executable-version",
      executorKind: "blender",
      probeType: "command-version-future",
      expectedInput: "Allowlisted Blender executable path plus future version command packet.",
      expectedOutput: "Operator-supplied or future metadata-only version label.",
      sideEffectProfile: "Future command packet only; no Blender launch, no render, no scene load.",
      defaultStatus: "blocked",
      riskLevel: "high",
      requiresApproval: true,
      requiresAllowlist: true,
    },
    {
      id: "blender-path-presence",
      bridgeTargetId: "blender-local",
      label: "Blender path presence",
      targetKind: "executable-path",
      executorKind: "blender",
      probeType: "path-presence-future",
      expectedInput: "Configured path string or manual presence confirmation.",
      expectedOutput: "Path status supplied manually or by future guarded metadata probe.",
      sideEffectProfile: "Metadata path presence only; no filesystem read in target builder.",
      defaultStatus: "manual-only",
      riskLevel: "medium",
      requiresApproval: true,
      requiresAllowlist: true,
    },
    {
      id: "comfyui-health-endpoint",
      bridgeTargetId: "comfyui-local",
      label: "ComfyUI local health endpoint",
      targetKind: "local-http-health",
      executorKind: "comfyui",
      probeType: "local-http-health-future",
      expectedInput: "Allowlisted local endpoint health packet.",
      expectedOutput: "Reachable status supplied manually or by future guarded local health packet.",
      sideEffectProfile: "Future local HTTP health packet only; no endpoint call by default.",
      defaultStatus: "blocked",
      riskLevel: "high",
      requiresApproval: true,
      requiresAllowlist: true,
    },
    {
      id: "comfyui-endpoint-config",
      bridgeTargetId: "comfyui-local",
      label: "ComfyUI endpoint configuration",
      targetKind: "config-presence",
      executorKind: "comfyui",
      probeType: "metadata-only",
      expectedInput: "Configured endpoint string presence.",
      expectedOutput: "Configured or missing metadata status.",
      sideEffectProfile: "Metadata-only config presence; no local HTTP call.",
      defaultStatus: "request-ready",
      riskLevel: "low",
      requiresApproval: false,
      requiresAllowlist: true,
    },
    {
      id: "unreal-editor-path-presence",
      bridgeTargetId: "unreal-local",
      label: "Unreal Editor path presence",
      targetKind: "executable-path",
      executorKind: "unreal",
      probeType: "path-presence-future",
      expectedInput: "Configured Unreal Editor path string or manual confirmation.",
      expectedOutput: "Path status supplied manually or by future guarded metadata probe.",
      sideEffectProfile: "Metadata path presence only; no Unreal Editor launch.",
      defaultStatus: "manual-only",
      riskLevel: "medium",
      requiresApproval: true,
      requiresAllowlist: true,
    },
    {
      id: "unreal-version-label",
      bridgeTargetId: "unreal-local",
      label: "Unreal version label",
      targetKind: "manual",
      executorKind: "unreal",
      probeType: "manual-confirmation",
      expectedInput: "Operator supplied Unreal version label.",
      expectedOutput: "Manual version label only.",
      sideEffectProfile: "Manual metadata only; no Unreal execution.",
      defaultStatus: "manual-only",
      riskLevel: "low",
      requiresApproval: false,
      requiresAllowlist: true,
    },
    {
      id: "ffmpeg-version",
      bridgeTargetId: "ffmpeg-local",
      label: "ffmpeg version label",
      targetKind: "executable-version",
      executorKind: "ffmpeg",
      probeType: "command-version-future",
      expectedInput: "Allowlisted ffmpeg executable path plus future version command packet.",
      expectedOutput: "Operator-supplied or future metadata-only version label.",
      sideEffectProfile: "Future command packet only; no ffmpeg execution by default.",
      defaultStatus: "blocked",
      riskLevel: "high",
      requiresApproval: true,
      requiresAllowlist: true,
    },
    {
      id: "ffmpeg-path-presence",
      bridgeTargetId: "ffmpeg-local",
      label: "ffmpeg path presence",
      targetKind: "executable-path",
      executorKind: "ffmpeg",
      probeType: "path-presence-future",
      expectedInput: "Configured ffmpeg path string or manual confirmation.",
      expectedOutput: "Path status supplied manually or by future guarded metadata probe.",
      sideEffectProfile: "Metadata path presence only; no command execution.",
      defaultStatus: "manual-only",
      riskLevel: "medium",
      requiresApproval: true,
      requiresAllowlist: true,
    },
    {
      id: "artifact-output-boundary",
      bridgeTargetId: "artifact-output-root",
      label: "Artifact output boundary",
      targetKind: "directory-boundary",
      executorKind: "artifact",
      probeType: "directory-boundary-future",
      expectedInput: "Configured output root and intended boundary label.",
      expectedOutput: "Boundary status supplied manually or by future guarded boundary packet.",
      sideEffectProfile: "Metadata boundary check only; no artifact writes.",
      defaultStatus: "request-ready",
      riskLevel: "medium",
      requiresApproval: true,
      requiresAllowlist: true,
    },
    {
      id: "custom-local-service-health",
      bridgeTargetId: "custom-local-service",
      label: "Custom local service health",
      targetKind: "local-http-health",
      executorKind: "custom-local-service",
      probeType: "local-http-health-future",
      expectedInput: "Explicit allowlisted local health endpoint packet.",
      expectedOutput: "Reachable status supplied manually or by future guarded local health packet.",
      sideEffectProfile: "Future local HTTP health packet only; no arbitrary endpoint.",
      defaultStatus: "blocked",
      riskLevel: "high",
      requiresApproval: true,
      requiresAllowlist: true,
    },
    {
      id: "manual-confirmation",
      bridgeTargetId: "manual-export",
      label: "Manual confirmation",
      targetKind: "manual",
      executorKind: "manual",
      probeType: "manual-confirmation",
      expectedInput: "Operator supplied status note.",
      expectedOutput: "Manual-only readiness note.",
      sideEffectProfile: "Manual metadata only.",
      defaultStatus: "manual-only",
      riskLevel: "low",
      requiresApproval: false,
      requiresAllowlist: true,
    },
  ];
  return targets.map(buildHealthProbeTarget);
}

export function summarizeHealthProbeTarget(target: HealthProbeTarget): string[] {
  return [
    `${target.label} maps ${target.id as HealthProbeTargetId} to bridge target ${target.bridgeTargetId}.`,
    `Probe type ${target.probeType}; default status ${target.defaultStatus}; risk ${target.riskLevel}.`,
    target.sideEffectProfile,
  ];
}
