import type { AiProviderProfile } from "./ai-router-types";

export function buildAiProviderProfile(
  profile: Partial<AiProviderProfile> & Pick<AiProviderProfile, "id" | "label" | "kind">
): AiProviderProfile {
  return {
    connectionMode: "planned",
    secretStrategy: "not-configured",
    privacyPosture: "unknown",
    latencyExpectation: "variable",
    reliabilityExpectation: "variable",
    supportsStreaming: false,
    supportsToolUse: false,
    supportsVision: false,
    supportsCode: false,
    supportsLongContext: false,
    supportsLocalOffline: false,
    notes: [],
    status: "planned",
    ...profile,
  };
}

export function buildDefaultAiProviderProfiles(): AiProviderProfile[] {
  return [
    buildAiProviderProfile({
      id: "local",
      label: "Local deterministic fallback",
      kind: "local",
      connectionMode: "local",
      secretStrategy: "not-configured",
      privacyPosture: "local",
      latencyExpectation: "high",
      reliabilityExpectation: "high",
      supportsCode: true,
      supportsLocalOffline: true,
      notes: ["Control-plane only profile for local preprocessing and fallback-safe drafts."],
      status: "configured",
    }),
    buildAiProviderProfile({
      id: "openai-compatible",
      label: "OpenAI-compatible API",
      kind: "openai-compatible",
      connectionMode: "api",
      secretStrategy: "env-only",
      privacyPosture: "external",
      latencyExpectation: "high",
      reliabilityExpectation: "high",
      supportsStreaming: true,
      supportsToolUse: true,
      supportsVision: true,
      supportsCode: true,
      supportsLongContext: true,
      notes: ["API key must stay outside browser storage; use server env configuration only."],
      status: "missing-secret",
    }),
    buildAiProviderProfile({
      id: "anthropic-compatible",
      label: "Anthropic-compatible API",
      kind: "anthropic-compatible",
      connectionMode: "api",
      secretStrategy: "env-only",
      privacyPosture: "external",
      latencyExpectation: "high",
      reliabilityExpectation: "high",
      supportsStreaming: true,
      supportsToolUse: true,
      supportsVision: true,
      supportsCode: true,
      supportsLongContext: true,
      notes: ["Metadata profile only; deterministic router does not call provider APIs."],
      status: "missing-secret",
    }),
    buildAiProviderProfile({
      id: "google-gemini-compatible",
      label: "Google/Gemini-compatible API",
      kind: "google-gemini-compatible",
      connectionMode: "api",
      secretStrategy: "env-only",
      privacyPosture: "external",
      latencyExpectation: "high",
      reliabilityExpectation: "high",
      supportsStreaming: true,
      supportsToolUse: true,
      supportsVision: true,
      supportsCode: true,
      supportsLongContext: true,
      notes: ["Manual cost and quota metadata can be attached later."],
      status: "missing-secret",
    }),
    buildAiProviderProfile({
      id: "openrouter-compatible",
      label: "OpenRouter-compatible API",
      kind: "openrouter-compatible",
      connectionMode: "api",
      secretStrategy: "env-only",
      privacyPosture: "external",
      latencyExpectation: "variable",
      reliabilityExpectation: "variable",
      supportsStreaming: true,
      supportsToolUse: true,
      supportsVision: true,
      supportsCode: true,
      supportsLongContext: true,
      notes: ["Use as a provider aggregator only after explicit server-side configuration."],
      status: "missing-secret",
    }),
    buildAiProviderProfile({
      id: "ollama",
      label: "Ollama local server",
      kind: "ollama-local-server",
      connectionMode: "local",
      secretStrategy: "local-server",
      privacyPosture: "private",
      latencyExpectation: "medium",
      reliabilityExpectation: "medium",
      supportsStreaming: true,
      supportsCode: true,
      supportsLocalOffline: true,
      notes: ["Local server availability is not probed by deterministic routing."],
      status: "local-unavailable",
    }),
    buildAiProviderProfile({
      id: "lm-studio",
      label: "LM Studio local server",
      kind: "lm-studio-local-server",
      connectionMode: "local",
      secretStrategy: "local-server",
      privacyPosture: "private",
      latencyExpectation: "medium",
      reliabilityExpectation: "medium",
      supportsStreaming: true,
      supportsCode: true,
      supportsLocalOffline: true,
      notes: ["Configured locally by operator; no browser key storage."],
      status: "local-unavailable",
    }),
    buildAiProviderProfile({
      id: "custom-http",
      label: "Custom HTTP-compatible provider",
      kind: "custom-http-compatible",
      connectionMode: "planned",
      secretStrategy: "not-configured",
      privacyPosture: "unknown",
      notes: ["Reserved for future user-defined server-side provider adapters."],
      status: "planned",
    }),
    buildAiProviderProfile({
      id: "manual-subscription",
      label: "Manual subscription profile",
      kind: "manual-subscription",
      connectionMode: "manual",
      secretStrategy: "manual",
      privacyPosture: "unknown",
      notes: ["Tracks subscription value without secrets or provider API calls."],
      status: "configured",
    }),
  ];
}

export function isAiProviderConfigured(profile: AiProviderProfile): boolean {
  return profile.status === "configured";
}

export function summarizeAiProviderProfile(profile: AiProviderProfile): string {
  return `${profile.label}: ${profile.status}, ${profile.connectionMode}, ${profile.secretStrategy}, privacy ${profile.privacyPosture}.`;
}
