"use client";

import { CodexForgeAppShell } from "@/lib/codexforge/navigation-shell";
import { CONTROLLED_WORKFLOW_TRIAL_RUNNER_BACKEND_CONTRACT_BLOCKED_ACTION_ITEMS, CONTROLLED_WORKFLOW_TRIAL_RUNNER_BACKEND_CONTRACT_PIPELINE_ITEMS, CONTROLLED_WORKFLOW_TRIAL_RUNNER_BACKEND_CONTRACT_PROTECTED_BOUNDARY_ITEMS, CONTROLLED_WORKFLOW_TRIAL_RUNNER_BACKEND_CONTRACT_SHARED_MARKERS, buildControlledWorkflowTrialRunnerBackendContractModel, buildControlledWorkflowTrialRunnerBackendContractStableKey, type ControlledWorkflowTrialRunnerBackendContractRouteSlug } from "../controlled-workflow-trial-runner-backend-contract-model";
import styles from "../../jarvis-cockpit-visual-system/components/JarvisCockpitVisualPanel.module.css";

export function ControlledWorkflowTrialRunnerBackendContractPageClientShell({ routeSlug }: { routeSlug: ControlledWorkflowTrialRunnerBackendContractRouteSlug }) {
  const model = buildControlledWorkflowTrialRunnerBackendContractModel(routeSlug);
  return (
    <CodexForgeAppShell activePath={model.route.href} workspaceLabel={model.route.title} nextActionContext={{ wantsOperatorOverview: false }} focusMode contentMaxWidth="wide" pageChrome="minimal" showRightRail={false} showSidebarSafetyNotice={false} showHeroRouteChips={false}>
      <ControlledWorkflowTrialRunnerBackendContractRoutePanel routeSlug={routeSlug} />
    </CodexForgeAppShell>
  );
}

export function ControlledWorkflowTrialRunnerBackendContractCockpitSection() {
  return <ControlledWorkflowTrialRunnerBackendContractRoutePanel routeSlug="controlled-workflow-trial-runner-backend-contract-completion" embedded />;
}

export function ControlledWorkflowTrialRunnerBackendContractRoutePanel({ routeSlug, embedded = false }: { routeSlug: ControlledWorkflowTrialRunnerBackendContractRouteSlug; embedded?: boolean }) {
  const model = buildControlledWorkflowTrialRunnerBackendContractModel(routeSlug);
  return (
    <section className={embedded ? styles.cockpitShell : styles.routeShell} data-codexforge-controlled-workflow-trial-runner-backend-contract={CONTROLLED_WORKFLOW_TRIAL_RUNNER_BACKEND_CONTRACT_SHARED_MARKERS.join(" | ")} data-codexforge-controlled-workflow-trial-runner-backend-contract-route={model.route.markerPhrases.join(" | ")} data-codexforge-controlled-workflow-trial-runner-backend-contract-pipeline={CONTROLLED_WORKFLOW_TRIAL_RUNNER_BACKEND_CONTRACT_PIPELINE_ITEMS.map((item) => item.label).join(" | ")}>
      <header className={styles.heroPanel}>
        <div className={styles.heroGlow} aria-hidden="true" />
        <div className={styles.heroContent}>
          <div className={styles.eyebrowRow}><span className={styles.phaseBadge}>{embedded ? "Controlled Workflow Trial Runner Backend Contract" : model.route.phase}</span><span className={styles.safeBadge}>review-only workflow trial runner contract</span><span className={styles.blockedBadge}>operator-approved only</span></div>
          <h1 className={styles.heroTitle}>{embedded ? "Controlled Workflow Trial Runner Backend Contract" : model.route.title}</h1>
          <p className={styles.heroLead}>This route is a review-only workflow trial runner contract with synthetic workflow trial runner data only. The backend-owned runner contract remains blocked until explicit operator approval. It defines runner input envelope, runner output envelope, runner state machine, runner approval lock, runner execution block, runner replay block, runner idempotency contract, runner audit envelope, runner redaction envelope, runner observability envelope, runner cost envelope, runner rate envelope, runner privacy envelope, runner safety envelope, retry, fallback, recovery, dry result, readiness gate, and handoff contracts without executing providers, models, rendering, workers, exports, publishing, storage, network, or frontend persistence.</p>
          <div className={styles.heroMetricGrid}><MetricCard label="Route slug" value={model.route.slug} detail={model.route.href} /><MetricCard label="Data" value="Synthetic" detail="synthetic workflow trial runner data only" /><MetricCard label="Approval" value="Required" detail="backend-owned runner contract remains blocked until explicit operator approval" /><MetricCard label="Execution" value="Blocked" detail="controlled workflow trial runner completion does not execute workflow" /></div>
        </div>
        <div className={styles.missionPreview} aria-label="Controlled Workflow Trial Runner Backend Contract preview"><p className={styles.missionLabel}>Runner contract</p><p className={styles.missionDetail}>Review-only. No live workflow execution. No provider calls. No model calls. No prompt sending. Provider gateway runner contract remains review-only. Render queue runner contract remains review-only. Worker orchestration runner contract remains review-only. Publish gateway runner contract remains review-only.</p></div>
      </header>
      <section className={styles.markerBand} aria-label="Controlled Workflow Trial Runner Backend Contract shared markers">{model.safetyMarkers.map((marker, index) => <span key={buildControlledWorkflowTrialRunnerBackendContractStableKey(["shared-marker", String(index), marker])} className={styles.markerPill}>{marker}</span>)}</section>
      <section className={styles.glassPanel} aria-label="Review-only workflow trial runner contract pipeline"><PanelHeading eyebrow="Review-only workflow trial runner contract" title="Backend-owned runner contract surface remains blocked until explicit operator approval" badge="Static only" /><p className={styles.bodyText}>This runner contract surface is synthetic workflow trial runner data only. It does not execute workflows, send prompts, call models, call providers, dispatch render queues, execute workers, export artifacts, create files, create signed URLs, execute publish gateways, upload to platforms, store credentials or tokens, write browser storage, call connectors, or use network egress.</p><div className={styles.systemsGrid}>{CONTROLLED_WORKFLOW_TRIAL_RUNNER_BACKEND_CONTRACT_PIPELINE_ITEMS.map((item) => <article key={buildControlledWorkflowTrialRunnerBackendContractStableKey(["pipeline", item.id])} className={styles.systemCard}><span className={styles.systemTier}>Runner contract path</span><strong>{item.label}</strong><p className={styles.systemStatus}>{item.state}</p></article>)}</div></section>
      <section className={styles.glassPanel} aria-label="Controlled Workflow Trial Runner Backend Contract route map"><PanelHeading eyebrow="Controlled Workflow Trial Runner Backend Contract" title={model.route.title} badge={model.route.phase} /><p className={styles.bodyText}>{model.route.summary}</p><div className={styles.contractGrid}>{model.route.markerPhrases.map((marker, index) => <span key={buildControlledWorkflowTrialRunnerBackendContractStableKey(["route-marker", model.route.slug, String(index), marker])} className={styles.contractChip}>{marker}</span>)}</div></section>
      <section className={styles.glassPanel} aria-label="Workflow trial runner blocked execution matrix"><PanelHeading eyebrow="Blocked Execution Matrix" title="Workflow provider model prompt storage render worker export publish network persistence runtime and credential execution stay blocked" badge="Actions disabled" /><div className={styles.blockedDeckGrid}>{CONTROLLED_WORKFLOW_TRIAL_RUNNER_BACKEND_CONTRACT_BLOCKED_ACTION_ITEMS.map((item) => <button key={buildControlledWorkflowTrialRunnerBackendContractStableKey(["blocked", item.id])} type="button" disabled className={styles.blockedCommandButton}><strong>{item.label}</strong><span>{item.state}</span><small>review-only workflow trial runner contract</small></button>)}</div></section>
      <section className={styles.cockpitGrid} aria-label="Workflow trial runner protected boundaries"><CatalogPanel eyebrow="Protected Runner Boundaries" title="Approval lock state machine audit redaction observability cost rate privacy safety and review-only handoff controls" items={CONTROLLED_WORKFLOW_TRIAL_RUNNER_BACKEND_CONTRACT_PROTECTED_BOUNDARY_ITEMS} /><CatalogPanel eyebrow="Runner Control Coverage" title="Blocked live workflow provider prompt storage render worker export publish network persistence credential token service and runtime controls" items={CONTROLLED_WORKFLOW_TRIAL_RUNNER_BACKEND_CONTRACT_BLOCKED_ACTION_ITEMS} /></section>
      <section className={styles.glassPanel} aria-label="Controlled Workflow Trial Runner Backend Contract completion guard"><PanelHeading eyebrow="Completion Guard" title="2890-2921 - Controlled Workflow Trial Runner Backend Contract" badge="Phase 2921" /><p className={styles.mutedText}>Controlled Workflow Trial Runner Backend Contract is a review-only workflow trial runner contract with synthetic workflow trial runner data only. The backend-owned runner contract remains blocked until explicit operator approval. Provider gateway runner contract remains review-only, asset storage runner contract remains review-only, audio storage runner contract remains review-only, storyboard runner contract remains review-only, keyframe runner contract remains review-only, timeline runner contract remains review-only, render queue runner contract remains review-only, worker orchestration runner contract remains review-only, artifact export runner contract remains review-only, publish gateway runner contract remains review-only, and controlled workflow trial runner completion does not execute workflow. Next likely batch: 2922-2953 - Provider Adapter Registry Backend Contract.</p></section>
      <section className={styles.diagnosticPanel} aria-label="Controlled Workflow Trial Runner Backend Contract diagnostics"><PanelHeading eyebrow="Diagnostics" title="2890-2921 workflow trial runner contract coverage" badge="Phase pages secondary" /><div className={styles.diagnosticGrid}>{model.routes.map((item) => <a key={buildControlledWorkflowTrialRunnerBackendContractStableKey(["workflow-trial-runner-contract-route", item.slug])} className={styles.diagnosticLink} href={item.href}><span>{item.phase}</span><strong>{item.title}</strong></a>)}</div></section>
    </section>
  );
}

function MetricCard({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className={styles.metricCard}><span className={styles.metricLabel}>{label}</span><strong className={styles.metricValue}>{value}</strong><span className={styles.metricDetail}>{detail}</span></article>; }

function CatalogPanel({ eyebrow, title, items }: { eyebrow: string; title: string; items: readonly { id: string; label: string; state: string }[] }) { return <article className={styles.glassPanel}><PanelHeading eyebrow={eyebrow} title={title} badge="Review only" /><div className={styles.systemsGrid}>{items.map((item) => <article key={buildControlledWorkflowTrialRunnerBackendContractStableKey(["catalog", eyebrow, item.id])} className={styles.systemCard}><span className={styles.systemTier}>Protected boundary</span><strong>{item.label}</strong><p className={styles.systemStatus}>{item.state}</p></article>)}</div></article>; }

function PanelHeading({ eyebrow, title, badge }: { eyebrow: string; title: string; badge: string }) { return <div className={styles.panelHeader}><div><p className={styles.eyebrow}>{eyebrow}</p><h2 className={styles.sectionTitle}>{title}</h2></div><span className={styles.safeBadge}>{badge}</span></div>; }
