export const JARVIS_UNIFIED_WORKSPACE_SHELLS_SHARED_MARKERS = [
  "3722-3753 - Jarvis Unified Workspace Shells",
  "3722-3753 - Jarvis Unified Workspace Shells Mega Batch v1",
  "Jarvis Unified Workspace Shells",
  "Jarvis unified workspace shells only",
  "one Jarvis command center",
  "one shared workspace shell model",
  "one Jarvis brain with specialist workspaces",
  "Jarvis operating system with feature workspaces",
  "Jarvis command center route",
  "video workspace shell only",
  "website creation workspace shell only",
  "avatar workspace shell only",
  "chatbot brain workspace shell only",
  "trading workspace shell only",
  "workflow workspace shell only",
  "render publish workspace shell only",
  "audit status workspace shell only",
  "safety settings workspace shell only",
  "trading workspace has dedicated page",
  "specialist pages remain review-only",
  "shared capability grid only",
  "shared planner panel only",
  "shared permission panel only",
  "shared approval panel only",
  "shared audit panel only",
  "shared result ledger panel only",
  "shared memory boundary panel only",
  "shared kill switch panel only",
  "shared blocked action panel only",
  "shared dry-run panel only",
  "shared adapter status panel only",
  "shared risk tier panel only",
  "specialist navigation review only",
  "operator review required before any execution",
  "unified workspace shells completion does not enable provider/render/export/publish/workers/trading/automation",
  "disabled by default",
  "hard kill switch",
  "no direct frontend execution",
  "no live provider call",
  "no provider execution",
  "no video provider execution",
  "no image provider execution",
  "no audio provider execution",
  "no website creation execution",
  "no avatar generation execution",
  "no chatbot autonomous execution",
  "no trading execution",
  "no paper trading execution",
  "no real-money trading execution",
  "no tool execution",
  "no autonomous tool execution",
  "no network execution",
  "no render execution",
  "no export execution",
  "no publish execution",
  "no worker dispatch",
  "no file export",
  "no download generation",
  "no archive creation",
  "no signed URL creation",
  "no platform upload",
  "no media upload",
  "no OAuth flow creation",
  "no webhook creation",
  "no schedule execution",
  "no account authorization execution",
  "no API route execution",
  "no service creation",
  "no runtime deploy",
  "no file writes from the app",
  "no shell/process/command execution from the app",
  "no fetch/network calls",
  "no provider SDK imports in frontend",
  "no frontend provider key reads",
  "no plaintext secrets",
  "no localStorage",
  "no sessionStorage",
  "no IndexedDB",
  "no cookies",
  "no browser storage for secrets",
  "next likely batch: 3754-3785 - First Jarvis-Controlled Video Adapter Plug-in",
] as const;

export const JARVIS_UNIFIED_WORKSPACE_SHELLS_DISPLAY_MARKERS = [
  "Jarvis unified workspace shells only",
  "one Jarvis command center",
  "one shared workspace shell model",
  "one Jarvis brain with specialist workspaces",
  "Jarvis operating system with feature workspaces",
  "specialist pages remain review-only",
  "shared capability grid only",
  "shared planner panel only",
  "shared approval panel only",
  "shared audit panel only",
  "shared result ledger panel only",
  "shared memory boundary panel only",
  "shared kill switch panel only",
  "shared blocked action panel only",
  "shared dry-run panel only",
  "shared adapter status panel only",
  "shared risk tier panel only",
  "operator review required before any execution",
  "disabled by default",
  "hard kill switch",
] as const;

export const JARVIS_UNIFIED_WORKSPACE_SHELLS_EXECUTION_BLOCKS = [
  "no direct frontend execution",
  "no live provider call",
  "no provider execution",
  "no video provider execution",
  "no image provider execution",
  "no audio provider execution",
  "no website creation execution",
  "no avatar generation execution",
  "no chatbot autonomous execution",
  "no trading execution",
  "no paper trading execution",
  "no real-money trading execution",
  "no tool execution",
  "no autonomous tool execution",
  "no network execution",
  "no render execution",
  "no export execution",
  "no publish execution",
  "no worker dispatch",
  "no file export",
  "no download generation",
  "no archive creation",
  "no signed URL creation",
  "no platform upload",
  "no media upload",
  "no OAuth flow creation",
  "no webhook creation",
  "no schedule execution",
  "no account authorization execution",
  "no API route execution",
  "no service creation",
  "no runtime deploy",
  "no file writes from the app",
  "no shell/process/command execution from the app",
  "no fetch/network calls",
] as const;

export const JARVIS_UNIFIED_WORKSPACE_SHELLS_STORAGE_BOUNDARIES = [
  "no provider SDK imports in frontend",
  "no frontend provider key reads",
  "no plaintext secrets",
  "no localStorage",
  "no sessionStorage",
  "no IndexedDB",
  "no cookies",
  "no browser storage for secrets",
] as const;
