export const PROVIDER_GATEWAY_WIRING_SHARED_MARKERS = [
  "Provider Gateway Wiring",
  "Provider Gateway Wiring Map",
  "Provider Request Envelope",
  "Provider Response Envelope",
  "Provider Capability Catalog",
  "Provider Model Family Catalog",
  "Provider Selection Policy",
  "Provider Privacy Class Boundary",
  "Provider Cost Class Boundary",
  "Provider Rate Limit Boundary",
  "Provider Error Taxonomy",
  "Provider Audit Envelope",
  "Provider Approval Gate",
  "Disabled Provider Adapter Registry",
  "Provider Gateway Cockpit Readiness Rail",
  "Provider Gateway Prompt Boundary",
  "Provider Gateway Credential Boundary",
  "Provider Gateway Token Boundary",
  "Provider Gateway Streaming Boundary",
  "Provider Gateway Retry Boundary",
  "Provider Gateway Timeout Boundary",
  "Provider Gateway Fallback Boundary",
  "Provider Gateway Observability Boundary",
  "First Provider Gateway Wiring Candidate",
  "Provider Gateway Backend Readiness Preview",
  "Provider Gateway Adapter Implementation Readiness",
  "Provider Gateway Execution Still Blocked Guard",
  "Controlled Provider Gateway Wiring Release Candidate",
  "Controlled Provider Gateway Wiring Completion Candidate",
  "Review-only provider gateway wiring",
  "Synthetic provider data only",
  "No live provider execution",
  "No provider calls",
  "No model calls",
  "No prompt sending",
  "No credential storage",
  "No token storage",
  "No streaming",
  "No frontend persistence",
  "No browser storage writes",
  "No connector calls",
  "No upload",
  "No download",
  "No render",
  "No export",
  "No publish",
  "No schedule",
  "No queue dispatch",
  "No worker dispatch",
  "No database writes",
  "No command execution",
  "No service creation",
  "No API creation from frontend",
  "Backend-owned provider gateway remains required",
  "Explicit operator approval required",
  "Audit trail required",
] as const;

export const PROVIDER_GATEWAY_WIRING_ROUTES = [
  {
    slug: "provider-gateway-wiring-map",
    href: "/provider-gateway-wiring-map",
    phase: "Phase 2282",
    phaseNumber: 2282,
    title: "Provider Gateway Wiring Map",
    commandLabel: "Go to Provider Gateway Wiring Map",
    summary: "Maps safe review-only provider gateway wiring between CodexForge cockpit surfaces and future backend-owned provider execution.",
    markerPhrases: [
      "Provider gateway wiring map",
      "Provider gateway wiring map defines safe review-only boundaries between CodexForge cockpit surfaces and future backend-owned provider gateway execution",
      "Provider gateway wiring map does not call providers call models send prompts store credentials store tokens stream responses persist outputs dispatch queues spawn workers or call connectors",
      "Provider gateway wiring map keeps provider execution blocked pending backend-owned implementation",
      "Denied provider gateway wiring map paths remain blocked",
      "Provider gateway wiring map checklist",
    ],
  },
  {
    slug: "provider-request-envelope-preview",
    href: "/provider-request-envelope-preview",
    phase: "Phase 2283",
    phaseNumber: 2283,
    title: "Provider Request Envelope Preview",
    commandLabel: "Go to Provider Request Envelope Preview",
    summary: "Defines the future backend-owned provider request shape without sending prompts or making network calls.",
    markerPhrases: [
      "Provider request envelope preview",
      "Provider request envelope preview defines future backend-owned request shape for provider operations without sending prompts or making network calls",
      "Provider request envelope preview includes task intent model family privacy class cost class approval gate audit envelope and blocked execution state",
      "Provider request envelope preview keeps prompt payloads review-only and synthetic",
      "Denied provider request envelope paths remain blocked",
      "Provider request envelope checklist",
    ],
  },
  {
    slug: "provider-response-envelope-preview",
    href: "/provider-response-envelope-preview",
    phase: "Phase 2284",
    phaseNumber: 2284,
    title: "Provider Response Envelope Preview",
    commandLabel: "Go to Provider Response Envelope Preview",
    summary: "Defines the future backend-owned provider response shape without receiving model output or streaming tokens.",
    markerPhrases: [
      "Provider response envelope preview",
      "Provider response envelope preview defines future backend-owned response shape without receiving model output or streaming tokens",
      "Provider response envelope preview uses synthetic status metadata only and does not persist outputs",
      "Provider response envelope preview keeps provider result capture backend-owned",
      "Denied provider response envelope paths remain blocked",
      "Provider response envelope checklist",
    ],
  },
  {
    slug: "provider-capability-catalog-preview",
    href: "/provider-capability-catalog-preview",
    phase: "Phase 2285",
    phaseNumber: 2285,
    title: "Provider Capability Catalog Preview",
    commandLabel: "Go to Provider Capability Catalog Preview",
    summary: "Lists synthetic provider capability classes without probing providers, credentials, or health endpoints.",
    markerPhrases: [
      "Provider capability catalog preview",
      "Provider capability catalog preview lists synthetic capability classes for text image audio video code research and planning without probing providers",
      "Provider capability catalog preview does not call provider health endpoints or inspect credentials",
      "Provider capability catalog preview keeps capability discovery backend-owned",
      "Denied provider capability catalog paths remain blocked",
      "Provider capability catalog checklist",
    ],
  },
  {
    slug: "provider-model-family-catalog-preview",
    href: "/provider-model-family-catalog-preview",
    phase: "Phase 2286",
    phaseNumber: 2286,
    title: "Provider Model Family Catalog Preview",
    commandLabel: "Go to Provider Model Family Catalog Preview",
    summary: "Lists synthetic model family buckets without querying providers, reading credentials, or storing tokens.",
    markerPhrases: [
      "Provider model family catalog preview",
      "Provider model family catalog preview lists synthetic model family buckets without querying providers or storing tokens",
      "Provider model family catalog preview does not call model APIs read credentials fetch remote catalogs or persist provider metadata",
      "Provider model family catalog preview keeps model discovery backend-owned",
      "Denied provider model family catalog paths remain blocked",
      "Provider model family catalog checklist",
    ],
  },
  {
    slug: "provider-selection-policy-preview",
    href: "/provider-selection-policy-preview",
    phase: "Phase 2287",
    phaseNumber: 2287,
    title: "Provider Selection Policy Preview",
    commandLabel: "Go to Provider Selection Policy Preview",
    summary: "Defines provider selection criteria as policy preview only, with no real prompt routing or provider execution.",
    markerPhrases: [
      "Provider selection policy preview",
      "Provider selection policy preview defines safe provider selection criteria without routing real prompts or executing providers",
      "Provider selection policy preview uses synthetic criteria for privacy cost latency quality capability and approval state",
      "Provider selection policy preview keeps routing backend-owned",
      "Denied provider selection policy paths remain blocked",
      "Provider selection policy checklist",
    ],
  },
  {
    slug: "provider-privacy-class-boundary-preview",
    href: "/provider-privacy-class-boundary-preview",
    phase: "Phase 2288",
    phaseNumber: 2288,
    title: "Provider Privacy Class Boundary Preview",
    commandLabel: "Go to Provider Privacy Class Boundary Preview",
    summary: "Defines future privacy classification requirements without inspecting real prompts or transmitting data.",
    markerPhrases: [
      "Provider privacy class boundary preview",
      "Provider privacy class boundary preview defines future privacy classification requirements for provider calls without inspecting real prompts or transmitting data",
      "Provider privacy class boundary preview keeps sensitive prompt handling backend-owned and approval-gated",
      "Provider privacy class boundary preview blocks unsafe privacy classes by default",
      "Denied provider privacy class paths remain blocked",
      "Provider privacy class checklist",
    ],
  },
  {
    slug: "provider-cost-class-boundary-preview",
    href: "/provider-cost-class-boundary-preview",
    phase: "Phase 2289",
    phaseNumber: 2289,
    title: "Provider Cost Class Boundary Preview",
    commandLabel: "Go to Provider Cost Class Boundary Preview",
    summary: "Defines future cost classification requirements without billing endpoint or provider access.",
    markerPhrases: [
      "Provider cost class boundary preview",
      "Provider cost class boundary preview defines future cost classification requirements without calling billing endpoints or providers",
      "Provider cost class boundary preview keeps spend controls backend-owned and approval-gated",
      "Provider cost class boundary preview blocks paid execution by default",
      "Denied provider cost class paths remain blocked",
      "Provider cost class checklist",
    ],
  },
  {
    slug: "provider-rate-limit-boundary-preview",
    href: "/provider-rate-limit-boundary-preview",
    phase: "Phase 2290",
    phaseNumber: 2290,
    title: "Provider Rate Limit Boundary Preview",
    commandLabel: "Go to Provider Rate Limit Boundary Preview",
    summary: "Defines future rate limit expectations without storing counters or sending traffic.",
    markerPhrases: [
      "Provider rate limit boundary preview",
      "Provider rate limit boundary preview defines future rate limit expectations without storing counters or sending traffic",
      "Provider rate limit boundary preview keeps rate limiting backend-owned and auditable",
      "Provider rate limit boundary preview blocks live traffic by default",
      "Denied provider rate limit paths remain blocked",
      "Provider rate limit checklist",
    ],
  },
  {
    slug: "provider-error-taxonomy-preview",
    href: "/provider-error-taxonomy-preview",
    phase: "Phase 2291",
    phaseNumber: 2291,
    title: "Provider Error Taxonomy Preview",
    commandLabel: "Go to Provider Error Taxonomy Preview",
    summary: "Defines provider error categories as synthetic review-only data with no provider calls or induced failures.",
    markerPhrases: [
      "Provider error taxonomy preview",
      "Provider error taxonomy preview defines future provider error categories without calling providers or throwing runtime errors intentionally",
      "Provider error taxonomy preview keeps provider failures synthetic and review-only",
      "Provider error taxonomy preview supports future safe retry/fallback policy",
      "Denied provider error taxonomy paths remain blocked",
      "Provider error taxonomy checklist",
    ],
  },
  {
    slug: "provider-audit-envelope-preview",
    href: "/provider-audit-envelope-preview",
    phase: "Phase 2292",
    phaseNumber: 2292,
    title: "Provider Audit Envelope Preview",
    commandLabel: "Go to Provider Audit Envelope Preview",
    summary: "Defines provider audit metadata without writing audit logs or transmitting telemetry.",
    markerPhrases: [
      "Provider audit envelope preview",
      "Provider audit envelope preview defines future provider audit metadata without writing audit logs or transmitting telemetry",
      "Provider audit envelope preview includes operator approval id privacy class model family policy decision and denied execution state",
      "Provider audit envelope preview keeps audit persistence backend-owned",
      "Denied provider audit envelope paths remain blocked",
      "Provider audit envelope checklist",
    ],
  },
  {
    slug: "provider-approval-gate-preview",
    href: "/provider-approval-gate-preview",
    phase: "Phase 2293",
    phaseNumber: 2293,
    title: "Provider Approval Gate Preview",
    commandLabel: "Go to Provider Approval Gate Preview",
    summary: "Defines explicit operator approval requirements without approving or enabling provider execution.",
    markerPhrases: [
      "Provider approval gate preview",
      "Provider approval gate preview defines future explicit operator approval requirements without approving provider execution",
      "Provider approval gate preview does not persist approvals verify identity or authorize accounts",
      "Provider approval gate preview keeps provider execution blocked until approval and backend audit exist",
      "Denied provider approval gate paths remain blocked",
      "Provider approval gate checklist",
    ],
  },
  {
    slug: "disabled-provider-adapter-registry-preview",
    href: "/disabled-provider-adapter-registry-preview",
    phase: "Phase 2294",
    phaseNumber: 2294,
    title: "Disabled Provider Adapter Registry Preview",
    commandLabel: "Go to Disabled Provider Adapter Registry Preview",
    summary: "Lists synthetic provider adapter names in disabled states without SDK imports, clients, or API calls.",
    markerPhrases: [
      "Disabled provider adapter registry preview",
      "Disabled provider adapter registry preview lists synthetic adapter names and disabled states without importing SDKs or creating clients",
      "Disabled provider adapter registry preview does not create provider clients store credentials call APIs or fetch remote data",
      "Disabled provider adapter registry preview keeps all adapters disabled",
      "Denied disabled provider adapter paths remain blocked",
      "Disabled provider adapter registry checklist",
    ],
  },
  {
    slug: "provider-gateway-cockpit-readiness-rail",
    href: "/provider-gateway-cockpit-readiness-rail",
    phase: "Phase 2295",
    phaseNumber: 2295,
    title: "Provider Gateway Cockpit Readiness Rail",
    commandLabel: "Go to Provider Gateway Cockpit Readiness Rail",
    summary: "Shows cockpit provider gateway readiness with deterministic synthetic data and disabled actions only.",
    markerPhrases: [
      "Provider gateway cockpit readiness rail",
      "Provider gateway cockpit readiness rail shows which cockpit surfaces are ready for provider gateway wiring without calling providers",
      "Provider gateway cockpit readiness rail uses deterministic synthetic data and disabled actions only",
      "Provider gateway cockpit readiness rail keeps provider execution blocked",
      "Denied provider cockpit readiness paths remain blocked",
      "Provider gateway cockpit readiness checklist",
    ],
  },
  {
    slug: "provider-gateway-prompt-boundary-preview",
    href: "/provider-gateway-prompt-boundary-preview",
    phase: "Phase 2296",
    phaseNumber: 2296,
    title: "Provider Gateway Prompt Boundary Preview",
    commandLabel: "Go to Provider Gateway Prompt Boundary Preview",
    summary: "Defines future prompt handling safeguards without transmitting prompt text to any provider.",
    markerPhrases: [
      "Provider gateway prompt boundary preview",
      "Provider gateway prompt boundary preview defines future prompt handling safeguards without sending prompt text to any provider",
      "Provider gateway prompt boundary preview keeps prompt preview synthetic and redaction backend-owned",
      "Provider gateway prompt boundary preview blocks prompt transmission",
      "Denied provider prompt boundary paths remain blocked",
      "Provider gateway prompt boundary checklist",
    ],
  },
  {
    slug: "provider-gateway-credential-boundary-preview",
    href: "/provider-gateway-credential-boundary-preview",
    phase: "Phase 2297",
    phaseNumber: 2297,
    title: "Provider Gateway Credential Boundary Preview",
    commandLabel: "Go to Provider Gateway Credential Boundary Preview",
    summary: "Defines future credential handling requirements without reading, storing, exposing, or validating credentials.",
    markerPhrases: [
      "Provider gateway credential boundary preview",
      "Provider gateway credential boundary preview defines future credential handling requirements without reading storing exposing or validating credentials",
      "Provider gateway credential boundary preview keeps credentials server-only and outside frontend bundles",
      "Provider gateway credential boundary preview blocks credential storage",
      "Denied provider credential boundary paths remain blocked",
      "Provider gateway credential boundary checklist",
    ],
  },
  {
    slug: "provider-gateway-token-boundary-preview",
    href: "/provider-gateway-token-boundary-preview",
    phase: "Phase 2298",
    phaseNumber: 2298,
    title: "Provider Gateway Token Boundary Preview",
    commandLabel: "Go to Provider Gateway Token Boundary Preview",
    summary: "Defines future token handling requirements without storing tokens, authorizing accounts, or calling providers.",
    markerPhrases: [
      "Provider gateway token boundary preview",
      "Provider gateway token boundary preview defines future token handling requirements without storing tokens authorizing accounts or calling providers",
      "Provider gateway token boundary preview keeps tokens backend-owned and never available to frontend code",
      "Provider gateway token boundary preview blocks token storage",
      "Denied provider token boundary paths remain blocked",
      "Provider gateway token boundary checklist",
    ],
  },
  {
    slug: "provider-gateway-streaming-boundary-preview",
    href: "/provider-gateway-streaming-boundary-preview",
    phase: "Phase 2299",
    phaseNumber: 2299,
    title: "Provider Gateway Streaming Boundary Preview",
    commandLabel: "Go to Provider Gateway Streaming Boundary Preview",
    summary: "Defines future streaming requirements without opening streams or receiving tokens.",
    markerPhrases: [
      "Provider gateway streaming boundary preview",
      "Provider gateway streaming boundary preview defines future streaming response requirements without opening streams or receiving tokens",
      "Provider gateway streaming boundary preview keeps streaming backend-owned and approval-gated",
      "Provider gateway streaming boundary preview blocks live streams",
      "Denied provider streaming boundary paths remain blocked",
      "Provider gateway streaming boundary checklist",
    ],
  },
  {
    slug: "provider-gateway-retry-boundary-preview",
    href: "/provider-gateway-retry-boundary-preview",
    phase: "Phase 2300",
    phaseNumber: 2300,
    title: "Provider Gateway Retry Boundary Preview",
    commandLabel: "Go to Provider Gateway Retry Boundary Preview",
    summary: "Defines future retry requirements without retrying provider calls or storing retry state.",
    markerPhrases: [
      "Provider gateway retry boundary preview",
      "Provider gateway retry boundary preview defines future retry requirements without retrying provider calls or storing retry state",
      "Provider gateway retry boundary preview keeps retries backend-owned and auditable",
      "Provider gateway retry boundary preview blocks live retry execution",
      "Denied provider retry boundary paths remain blocked",
      "Provider gateway retry boundary checklist",
    ],
  },
  {
    slug: "provider-gateway-timeout-boundary-preview",
    href: "/provider-gateway-timeout-boundary-preview",
    phase: "Phase 2301",
    phaseNumber: 2301,
    title: "Provider Gateway Timeout Boundary Preview",
    commandLabel: "Go to Provider Gateway Timeout Boundary Preview",
    summary: "Defines future timeout requirements without provider calls or live-work timers.",
    markerPhrases: [
      "Provider gateway timeout boundary preview",
      "Provider gateway timeout boundary preview defines future timeout requirements without calling providers or scheduling timers for live work",
      "Provider gateway timeout boundary preview keeps timeouts backend-owned and deterministic",
      "Provider gateway timeout boundary preview blocks live timeout handling",
      "Denied provider timeout boundary paths remain blocked",
      "Provider gateway timeout boundary checklist",
    ],
  },
  {
    slug: "provider-gateway-fallback-boundary-preview",
    href: "/provider-gateway-fallback-boundary-preview",
    phase: "Phase 2302",
    phaseNumber: 2302,
    title: "Provider Gateway Fallback Boundary Preview",
    commandLabel: "Go to Provider Gateway Fallback Boundary Preview",
    summary: "Defines future fallback routing requirements without routing real prompts or calling fallback providers.",
    markerPhrases: [
      "Provider gateway fallback boundary preview",
      "Provider gateway fallback boundary preview defines future fallback routing requirements without routing real prompts or calling fallback providers",
      "Provider gateway fallback boundary preview keeps fallback selection backend-owned and approval-gated",
      "Provider gateway fallback boundary preview blocks live fallback execution",
      "Denied provider fallback boundary paths remain blocked",
      "Provider gateway fallback boundary checklist",
    ],
  },
  {
    slug: "provider-gateway-observability-boundary-preview",
    href: "/provider-gateway-observability-boundary-preview",
    phase: "Phase 2303",
    phaseNumber: 2303,
    title: "Provider Gateway Observability Boundary Preview",
    commandLabel: "Go to Provider Gateway Observability Boundary Preview",
    summary: "Defines future telemetry categories without sending telemetry or persisting logs.",
    markerPhrases: [
      "Provider gateway observability boundary preview",
      "Provider gateway observability boundary preview defines future telemetry categories without sending telemetry or persisting logs",
      "Provider gateway observability boundary preview keeps observability backend-owned and redacted",
      "Provider gateway observability boundary preview blocks telemetry transmission",
      "Denied provider observability boundary paths remain blocked",
      "Provider gateway observability boundary checklist",
    ],
  },
  {
    slug: "provider-gateway-safety-regression-guard",
    href: "/provider-gateway-safety-regression-guard",
    phase: "Phase 2304",
    phaseNumber: 2304,
    title: "Provider Gateway Safety Regression Guard",
    commandLabel: "Go to Provider Gateway Safety Regression Guard",
    summary: "Guards provider gateway wiring against hidden provider execution, model calls, prompt sending, storage, streaming, or hidden execution.",
    markerPhrases: [
      "Provider gateway safety regression guard",
      "Provider gateway safety regression guard verifies provider gateway wiring remains review-only with no provider calls no model calls no prompt sending no credential storage no token storage no streaming and no hidden execution",
      "Provider gateway safety regression guard preserves backend wiring and Jarvis cockpit safety",
      "Provider gateway safety regression guard blocks hidden provider execution affordances",
      "Denied provider gateway safety regression paths remain blocked",
      "Provider gateway safety regression checklist",
    ],
  },
  {
    slug: "provider-gateway-navigation-regression-guard",
    href: "/provider-gateway-navigation-regression-guard",
    phase: "Phase 2305",
    phaseNumber: 2305,
    title: "Provider Gateway Navigation Regression Guard",
    commandLabel: "Go to Provider Gateway Navigation Regression Guard",
    summary: "Guards provider gateway route registration, command coverage, and valid navigation metadata values.",
    markerPhrases: [
      "Provider gateway navigation regression guard",
      "Provider gateway navigation regression guard verifies provider gateway routes are registered without duplicate hrefs invalid route hrefs invalid navigation groups invalid safety posture values invalid commandDeckRole values or broken cockpit links",
      "Provider gateway navigation regression guard preserves backend wiring and Jarvis cockpit navigation coverage",
      "Provider gateway navigation regression guard keeps provider diagnostics review-only",
      "Denied provider gateway navigation regression paths remain blocked",
      "Provider gateway navigation regression checklist",
    ],
  },
  {
    slug: "provider-gateway-smoke-coverage-guard",
    href: "/provider-gateway-smoke-coverage-guard",
    phase: "Phase 2306",
    phaseNumber: 2306,
    title: "Provider Gateway Smoke Coverage Guard",
    commandLabel: "Go to Provider Gateway Smoke Coverage Guard",
    summary: "Guards provider gateway smoke script and all-smoke coverage without removing previous coverage.",
    markerPhrases: [
      "Provider gateway smoke coverage guard",
      "Provider gateway smoke coverage guard verifies provider gateway batch has targeted smoke scripts and all-smoke registration without removing previous coverage",
      "Provider gateway smoke coverage guard keeps smoke scanning scoped to provider gateway batch-owned files to avoid old helper false positives",
      "Provider gateway smoke coverage guard preserves checkpoint smoke coverage",
      "Denied provider gateway smoke coverage regression paths remain blocked",
      "Provider gateway smoke coverage checklist",
    ],
  },
  {
    slug: "provider-gateway-checkpoint-completion-guard",
    href: "/provider-gateway-checkpoint-completion-guard",
    phase: "Phase 2307",
    phaseNumber: 2307,
    title: "Provider Gateway Checkpoint Completion Guard",
    commandLabel: "Go to Provider Gateway Checkpoint Completion Guard",
    summary: "Updates checkpoint docs through phase 2313 while keeping live provider execution absent.",
    markerPhrases: [
      "Provider gateway checkpoint completion guard",
      "Provider gateway checkpoint completion guard updates checkpoint docs through phase 2313 without claiming live provider execution exists",
      "Provider gateway checkpoint completion guard records next likely batch as Provider Gateway Backend Adapter Contract Mega Batch v1",
      "Provider gateway checkpoint completion guard states provider execution remains blocked pending backend-owned adapter implementation",
      "Denied provider checkpoint regression paths remain blocked",
      "Provider gateway checkpoint completion checklist",
    ],
  },
  {
    slug: "first-provider-gateway-wiring-candidate",
    href: "/first-provider-gateway-wiring-candidate",
    phase: "Phase 2308",
    phaseNumber: 2308,
    title: "First Provider Gateway Wiring Candidate",
    commandLabel: "Go to First Provider Gateway Wiring Candidate",
    summary: "Assembles review-only request envelope, response envelope, policy catalog, approval gate, audit envelope, and disabled adapter registry.",
    markerPhrases: [
      "First provider gateway wiring candidate",
      "First provider gateway wiring candidate assembles provider request envelope response envelope policy catalog approval gate audit envelope and disabled adapter registry into one review-only candidate",
      "First provider gateway wiring candidate does not call providers call models send prompts store credentials store tokens stream responses persist data or dispatch workers",
      "First provider gateway wiring candidate keeps provider execution blocked",
      "Denied first provider gateway wiring paths remain blocked",
      "First provider gateway wiring checklist",
    ],
  },
  {
    slug: "provider-gateway-backend-readiness-preview",
    href: "/provider-gateway-backend-readiness-preview",
    phase: "Phase 2309",
    phaseNumber: 2309,
    title: "Provider Gateway Backend Readiness Preview",
    commandLabel: "Go to Provider Gateway Backend Readiness Preview",
    summary: "Lists backend prerequisites for future provider execution without creating APIs, services, SDK clients, or route handlers.",
    markerPhrases: [
      "Provider gateway backend readiness preview",
      "Provider gateway backend readiness preview lists backend prerequisites for future provider execution without creating APIs services SDK clients or route handlers",
      "Provider gateway backend readiness preview requires server-only credentials approval enforcement audit persistence retry fallback timeout and observability",
      "Provider gateway backend readiness preview keeps execution deferred",
      "Denied provider backend readiness paths remain blocked",
      "Provider gateway backend readiness checklist",
    ],
  },
  {
    slug: "provider-gateway-adapter-implementation-readiness",
    href: "/provider-gateway-adapter-implementation-readiness",
    phase: "Phase 2310",
    phaseNumber: 2310,
    title: "Provider Gateway Adapter Implementation Readiness",
    commandLabel: "Go to Provider Gateway Adapter Implementation Readiness",
    summary: "Lists adapter prerequisites without implementing adapters, clients, SDKs, or provider calls.",
    markerPhrases: [
      "Provider gateway adapter implementation readiness",
      "Provider gateway adapter implementation readiness lists adapter implementation prerequisites without implementing adapters clients SDKs or provider calls",
      "Provider gateway adapter implementation readiness keeps adapter creation blocked until future backend-owned batch",
      "Provider gateway adapter implementation readiness requires explicit approval and audit",
      "Denied provider adapter readiness paths remain blocked",
      "Provider gateway adapter readiness checklist",
    ],
  },
  {
    slug: "provider-gateway-execution-still-blocked-guard",
    href: "/provider-gateway-execution-still-blocked-guard",
    phase: "Phase 2311",
    phaseNumber: 2311,
    title: "Provider Gateway Execution Still Blocked Guard",
    commandLabel: "Go to Provider Gateway Execution Still Blocked Guard",
    summary: "Verifies cockpit and diagnostic pages expose no live provider execution affordance.",
    markerPhrases: [
      "Provider gateway execution still blocked guard",
      "Provider gateway execution still blocked guard verifies no live provider execution is exposed by the cockpit or diagnostic pages",
      "Provider gateway execution still blocked guard confirms prompt sending credential storage token storage streaming and provider calls remain blocked",
      "Provider gateway execution still blocked guard keeps protected actions disabled",
      "Denied provider execution still blocked paths remain blocked",
      "Provider gateway execution still blocked checklist",
    ],
  },
  {
    slug: "controlled-provider-gateway-wiring-release-candidate",
    href: "/controlled-provider-gateway-wiring-release-candidate",
    phase: "Phase 2312",
    phaseNumber: 2312,
    title: "Controlled Provider Gateway Wiring Release Candidate",
    commandLabel: "Go to Controlled Provider Gateway Wiring Release Candidate",
    summary: "Release candidate for review-only provider gateway contracts and disabled adapter registry.",
    markerPhrases: [
      "Controlled provider gateway wiring release candidate",
      "Controlled provider gateway wiring release candidate does not call providers call models send prompts stream responses store credentials store tokens persist outputs write browser storage upload download render export publish schedule dispatch queues spawn workers run commands create APIs create services or call connectors",
      "Controlled provider gateway wiring release candidate adds review-only provider gateway contracts and disabled adapter registry",
      "Controlled provider gateway wiring release candidate requires backend-owned provider gateway explicit operator approval and audit trail before live execution",
      "Denied controlled provider gateway wiring paths remain blocked",
      "Controlled provider gateway wiring checklist",
    ],
  },
  {
    slug: "controlled-provider-gateway-wiring-completion-candidate",
    href: "/controlled-provider-gateway-wiring-completion-candidate",
    phase: "Phase 2313",
    phaseNumber: 2313,
    title: "Controlled Provider Gateway Wiring Completion Candidate",
    commandLabel: "Go to Controlled Provider Gateway Wiring Completion Candidate",
    summary: "Completion candidate for the provider gateway wiring batch, keeping execution blocked and readiness pointed at the backend adapter contract batch.",
    markerPhrases: [
      "Controlled provider gateway wiring completion candidate",
      "Controlled provider gateway wiring completion candidate does not implement live provider execution model calls prompt transmission streaming credential storage token storage persistence queue dispatch worker dispatch connector access or telemetry transmission",
      "Controlled provider gateway wiring completion candidate closes the provider gateway wiring batch and marks readiness for Provider Gateway Backend Adapter Contract Mega Batch v1",
      "Controlled provider gateway wiring completion candidate keeps all provider actions blocked pending backend-owned adapter implementation",
      "Denied provider gateway completion paths remain blocked",
      "Controlled provider gateway completion checklist",
    ],
  },
] as const;

export type ProviderGatewayWiringRouteSlug = (typeof PROVIDER_GATEWAY_WIRING_ROUTES)[number]["slug"];
export type ProviderGatewayWiringRouteDefinition = (typeof PROVIDER_GATEWAY_WIRING_ROUTES)[number];

export type ProviderGatewayWiringModel = {
  route: ProviderGatewayWiringRouteDefinition;
  routes: readonly ProviderGatewayWiringRouteDefinition[];
  safetyMarkers: readonly string[];
};

export const PROVIDER_GATEWAY_READINESS_ITEMS = [
  "Provider Gateway Wiring status",
  "request envelope: review-only",
  "response envelope: synthetic only",
  "provider capability catalog: preview only",
  "model family catalog: preview only",
  "approval gate: required",
  "audit envelope: required",
  "credential boundary: backend-only",
  "token boundary: backend-only",
  "streaming boundary: blocked",
  "fallback/retry/timeout: policy-only",
  "adapter registry: disabled",
  "execution state: blocked",
  "next batch: 2314-2345 - Provider Gateway Backend Adapter Contract Mega Batch v1",
] as const;

export const PROVIDER_GATEWAY_REQUEST_ENVELOPE = [
  { id: "task-intent", label: "Task intent", state: "review-only synthetic intent" },
  { id: "model-family", label: "Model family", state: "preview catalog only" },
  { id: "privacy-class", label: "Privacy class", state: "backend-owned classification" },
  { id: "cost-class", label: "Cost class", state: "approval-gated policy" },
  { id: "approval-gate", label: "Approval gate", state: "explicit operator approval required" },
  { id: "audit-envelope", label: "Audit envelope", state: "audit trail required" },
  { id: "execution-state", label: "Execution state", state: "blocked" },
] as const;

export const PROVIDER_GATEWAY_RESPONSE_ENVELOPE = [
  { id: "synthetic-status", label: "Synthetic status", state: "metadata only" },
  { id: "result-capture", label: "Result capture", state: "backend-owned future contract" },
  { id: "streaming-state", label: "Streaming state", state: "blocked" },
  { id: "persistence-state", label: "Persistence state", state: "not stored from frontend" },
  { id: "audit-state", label: "Audit state", state: "required before execution" },
] as const;

export const PROVIDER_GATEWAY_CAPABILITY_CATALOG = [
  { id: "text", label: "Text", state: "preview only" },
  { id: "image", label: "Image", state: "preview only" },
  { id: "audio", label: "Audio", state: "preview only" },
  { id: "video", label: "Video", state: "preview only" },
  { id: "code", label: "Code", state: "preview only" },
  { id: "research", label: "Research", state: "preview only" },
  { id: "planning", label: "Planning", state: "preview only" },
] as const;

export const PROVIDER_GATEWAY_MODEL_FAMILIES = [
  { id: "local-private", label: "Local private", state: "backend-owned discovery required" },
  { id: "cloud-text", label: "Cloud text", state: "blocked pending approval" },
  { id: "cloud-multimodal", label: "Cloud multimodal", state: "blocked pending approval" },
  { id: "creative-generation", label: "Creative generation", state: "blocked pending approval" },
  { id: "research-planning", label: "Research planning", state: "blocked pending approval" },
] as const;

export const DISABLED_PROVIDER_ADAPTER_REGISTRY = [
  { id: "openai-compatible", label: "OpenAI-compatible", state: "disabled" },
  { id: "anthropic-compatible", label: "Anthropic-compatible", state: "disabled" },
  { id: "gemini-compatible", label: "Gemini-compatible", state: "disabled" },
  { id: "local-runtime", label: "Local runtime", state: "disabled" },
  { id: "creative-video", label: "Creative video", state: "disabled" },
  { id: "research-provider", label: "Research provider", state: "disabled" },
] as const;

export const PROVIDER_GATEWAY_BOUNDARY_POLICIES = [
  { id: "privacy", label: "Provider Privacy Class Boundary", state: "unsafe classes blocked by default" },
  { id: "cost", label: "Provider Cost Class Boundary", state: "paid execution blocked by default" },
  { id: "rate-limit", label: "Provider Rate Limit Boundary", state: "live traffic blocked" },
  { id: "retry", label: "Provider Gateway Retry Boundary", state: "policy-only" },
  { id: "timeout", label: "Provider Gateway Timeout Boundary", state: "policy-only" },
  { id: "fallback", label: "Provider Gateway Fallback Boundary", state: "policy-only" },
  { id: "observability", label: "Provider Gateway Observability Boundary", state: "telemetry transmission blocked" },
] as const;

export const PROVIDER_GATEWAY_WIRING_DENIALS = [
  "No live provider execution",
  "No provider calls",
  "No model calls",
  "No prompt sending",
  "No credential storage",
  "No token storage",
  "No streaming",
  "No frontend persistence",
  "No browser storage writes",
  "No connector calls",
  "No upload",
  "No download",
  "No render",
  "No export",
  "No publish",
  "No schedule",
  "No queue dispatch",
  "No worker dispatch",
  "No database writes",
  "No command execution",
  "No service creation",
  "No API creation from frontend",
] as const;

export function buildProviderGatewayWiringStableKey(parts: readonly string[]) {
  return parts
    .map((part) => part.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, ""))
    .filter(Boolean)
    .join("__");
}

export function buildProviderGatewayWiringModel(
  routeSlug: ProviderGatewayWiringRouteSlug = "provider-gateway-wiring-map"
): ProviderGatewayWiringModel {
  const route =
    PROVIDER_GATEWAY_WIRING_ROUTES.find((candidate) => candidate.slug === routeSlug) ?? PROVIDER_GATEWAY_WIRING_ROUTES[0];
  return {
    route,
    routes: PROVIDER_GATEWAY_WIRING_ROUTES,
    safetyMarkers: PROVIDER_GATEWAY_WIRING_SHARED_MARKERS,
  };
}
