"use client";

import { CodexForgeAppShell } from "@/lib/codexforge/navigation-shell";
import { FIRST_APPROVED_PROVIDER_EXECUTION_BRIDGE_BLOCKED_ACTION_ITEMS, FIRST_APPROVED_PROVIDER_EXECUTION_BRIDGE_PIPELINE_ITEMS, FIRST_APPROVED_PROVIDER_EXECUTION_BRIDGE_PROTECTED_BOUNDARY_ITEMS, FIRST_APPROVED_PROVIDER_EXECUTION_BRIDGE_SHARED_MARKERS, buildFirstApprovedProviderExecutionBridgeModel, buildFirstApprovedProviderExecutionBridgeStableKey, type FirstApprovedProviderExecutionBridgeRouteSlug } from "../first-approved-provider-execution-bridge-model";
import styles from "../../jarvis-cockpit-visual-system/components/JarvisCockpitVisualPanel.module.css";

export function FirstApprovedProviderExecutionBridgePageClientShell({ routeSlug }: { routeSlug: FirstApprovedProviderExecutionBridgeRouteSlug }) {
  const model = buildFirstApprovedProviderExecutionBridgeModel(routeSlug);
  return (
    <CodexForgeAppShell activePath={model.route.href} workspaceLabel={model.route.title} nextActionContext={{ wantsOperatorOverview: false }} focusMode contentMaxWidth="wide" pageChrome="minimal" showRightRail={false} showSidebarSafetyNotice={false} showHeroRouteChips={false}>
      <FirstApprovedProviderExecutionBridgeRoutePanel routeSlug={routeSlug} />
    </CodexForgeAppShell>
  );
}

export function FirstApprovedProviderExecutionBridgeCockpitSection() {
  return <FirstApprovedProviderExecutionBridgeRoutePanel routeSlug="first-approved-provider-execution-bridge-completion" embedded />;
}

export function FirstApprovedProviderExecutionBridgeRoutePanel({ routeSlug, embedded = false }: { routeSlug: FirstApprovedProviderExecutionBridgeRouteSlug; embedded?: boolean }) {
  const model = buildFirstApprovedProviderExecutionBridgeModel(routeSlug);
  return (
    <section className={embedded ? styles.cockpitShell : styles.routeShell} data-codexforge-first-approved-provider-execution-bridge={FIRST_APPROVED_PROVIDER_EXECUTION_BRIDGE_SHARED_MARKERS.join(" | ")} data-codexforge-first-approved-provider-execution-bridge-route={model.route.markerPhrases.join(" | ")} data-codexforge-first-approved-provider-execution-bridge-pipeline={FIRST_APPROVED_PROVIDER_EXECUTION_BRIDGE_PIPELINE_ITEMS.map((item) => item.label).join(" | ")}>
      <header className={styles.heroPanel}>
        <div className={styles.heroGlow} aria-hidden="true" />
        <div className={styles.heroContent}>
          <div className={styles.eyebrowRow}><span className={styles.phaseBadge}>{embedded ? "First Approved Provider Execution Bridge" : model.route.phase}</span><span className={styles.safeBadge}>review-only approved provider execution bridge</span><span className={styles.blockedBadge}>operator-approved only</span></div>
          <h1 className={styles.heroTitle}>{embedded ? "First Approved Provider Execution Bridge" : model.route.title}</h1>
          <p className={styles.heroLead}>This route is a review-only approved provider execution bridge with synthetic approved provider execution bridge data only. The approved provider execution bridge remains disabled until explicit operator approval. It defines execution intent, approval packet, credential and token reference boundaries, request response and error envelopes, dry execution lock, blocked execution and replay, idempotency, audit, redaction, observability, cost rate privacy safety guards, region retention retry fallback recovery timeout policies, result review, runner and adapter registry handoffs, operator review, readiness gate, disabled execution candidate, and completion checks without provider calls, model calls, prompt sending, streaming, provider SDK imports, network egress, frontend persistence, credential storage, token storage, provider key storage, worker dispatch, render execution, exports, publishing, or runtime deploy.</p>
          <div className={styles.heroMetricGrid}><MetricCard label="Route slug" value={model.route.slug} detail={model.route.href} /><MetricCard label="Data" value="Synthetic" detail="synthetic approved provider execution bridge data only" /><MetricCard label="Approval" value="Required" detail="approved provider execution bridge remains disabled until explicit operator approval" /><MetricCard label="Execution" value="Blocked" detail="first approved provider execution bridge completion does not call providers" /></div>
        </div>
        <div className={styles.missionPreview} aria-label="First Approved Provider Execution Bridge preview"><p className={styles.missionLabel}>Approved bridge</p><p className={styles.missionDetail}>Review-only. Disabled by default. No live provider calls. No model calls. No prompt sending. No streaming. No provider SDK imports. No network egress. No frontend persistence. No credential storage. No token storage. No provider key storage.</p></div>
      </header>
      <section className={styles.markerBand} aria-label="First Approved Provider Execution Bridge shared markers">{model.safetyMarkers.map((marker, index) => <span key={buildFirstApprovedProviderExecutionBridgeStableKey(["shared-marker", String(index), marker])} className={styles.markerPill}>{marker}</span>)}</section>
      <section className={styles.glassPanel} aria-label="Review-only approved provider execution bridge pipeline"><PanelHeading eyebrow="Review-only approved provider execution bridge" title="Future backend-owned approved provider execution bridge remains disabled until explicit operator approval" badge="Static only" /><p className={styles.bodyText}>This first approved provider execution bridge surface is synthetic approved provider execution bridge data only. It does not call providers, call models, send prompts, stream tokens, import provider SDKs, upload or download files, execute render queues, dispatch workers, export artifacts, publish content, create OAuth flows, create webhooks, create signed URLs, store credentials, store tokens, store provider keys, write browser storage, call connectors, create APIs, bind ports, deploy runtimes, or use network egress.</p><div className={styles.systemsGrid}>{FIRST_APPROVED_PROVIDER_EXECUTION_BRIDGE_PIPELINE_ITEMS.map((item) => <article key={buildFirstApprovedProviderExecutionBridgeStableKey(["pipeline", item.id])} className={styles.systemCard}><span className={styles.systemTier}>Approved provider bridge path</span><strong>{item.label}</strong><p className={styles.systemStatus}>{item.state}</p></article>)}</div></section>
      <section className={styles.glassPanel} aria-label="First Approved Provider Execution Bridge route map"><PanelHeading eyebrow="First Approved Provider Execution Bridge" title={model.route.title} badge={model.route.phase} /><p className={styles.bodyText}>{model.route.summary}</p><div className={styles.contractGrid}>{model.route.markerPhrases.map((marker, index) => <span key={buildFirstApprovedProviderExecutionBridgeStableKey(["route-marker", model.route.slug, String(index), marker])} className={styles.contractChip}>{marker}</span>)}</div></section>
      <section className={styles.glassPanel} aria-label="Approved provider bridge blocked execution matrix"><PanelHeading eyebrow="Blocked Execution Matrix" title="Provider model prompt network storage media worker export publish runtime and credential execution stay blocked" badge="Actions disabled" /><div className={styles.blockedDeckGrid}>{FIRST_APPROVED_PROVIDER_EXECUTION_BRIDGE_BLOCKED_ACTION_ITEMS.map((item) => <button key={buildFirstApprovedProviderExecutionBridgeStableKey(["blocked", item.id])} type="button" disabled className={styles.blockedCommandButton}><strong>{item.label}</strong><span>{item.state}</span><small>review-only approved provider execution bridge</small></button>)}</div></section>
      <section className={styles.cockpitGrid} aria-label="Approved provider bridge protected boundaries"><CatalogPanel eyebrow="Protected Approved Provider Boundaries" title="Intent approval credential token envelope audit redaction observability policy guard handoff and review controls" items={FIRST_APPROVED_PROVIDER_EXECUTION_BRIDGE_PROTECTED_BOUNDARY_ITEMS} /><CatalogPanel eyebrow="Approved Provider Control Coverage" title="Blocked provider model prompt SDK network storage render worker export publish runtime credential and token controls" items={FIRST_APPROVED_PROVIDER_EXECUTION_BRIDGE_BLOCKED_ACTION_ITEMS} /></section>
      <section className={styles.glassPanel} aria-label="First Approved Provider Execution Bridge completion guard"><PanelHeading eyebrow="Completion Guard" title="2954-2985 - First Approved Provider Execution Bridge" badge="Phase 2985" /><p className={styles.mutedText}>First Approved Provider Execution Bridge is a review-only approved provider execution bridge with synthetic approved provider execution bridge data only. The approved provider execution bridge remains disabled until explicit operator approval. The approved provider execution intent, approval packet, credential reference boundary, token reference boundary, request response error envelopes, dry execution lock, blocked execution, blocked replay, idempotency key, audit packet, redaction packet, observability trace, cost rate privacy safety guards, region data retention retry fallback recovery timeout policies, result review, runner handoff remains review-only, adapter registry handoff remains review-only, operator review remains required, readiness gate, disabled approved provider execution candidate, and first approved provider execution bridge completion does not call providers. Next likely batch: 2986-3017 - Multi-Provider Capability Routing.</p></section>
      <section className={styles.diagnosticPanel} aria-label="First Approved Provider Execution Bridge diagnostics"><PanelHeading eyebrow="Diagnostics" title="2954-2985 approved provider execution bridge coverage" badge="Phase pages secondary" /><div className={styles.diagnosticGrid}>{model.routes.map((item) => <a key={buildFirstApprovedProviderExecutionBridgeStableKey(["first-approved-provider-execution-bridge-route", item.slug])} className={styles.diagnosticLink} href={item.href}><span>{item.phase}</span><strong>{item.title}</strong></a>)}</div></section>
    </section>
  );
}

function MetricCard({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className={styles.metricCard}><span className={styles.metricLabel}>{label}</span><strong className={styles.metricValue}>{value}</strong><span className={styles.metricDetail}>{detail}</span></article>; }

function CatalogPanel({ eyebrow, title, items }: { eyebrow: string; title: string; items: readonly { id: string; label: string; state: string }[] }) { return <article className={styles.glassPanel}><PanelHeading eyebrow={eyebrow} title={title} badge="Review only" /><div className={styles.systemsGrid}>{items.map((item) => <article key={buildFirstApprovedProviderExecutionBridgeStableKey(["catalog", eyebrow, item.id])} className={styles.systemCard}><span className={styles.systemTier}>Protected boundary</span><strong>{item.label}</strong><p className={styles.systemStatus}>{item.state}</p></article>)}</div></article>; }

function PanelHeading({ eyebrow, title, badge }: { eyebrow: string; title: string; badge: string }) { return <div className={styles.panelHeader}><div><p className={styles.eyebrow}>{eyebrow}</p><h2 className={styles.sectionTitle}>{title}</h2></div><span className={styles.safeBadge}>{badge}</span></div>; }
