import type { ProductSimplificationRoute, SimplifiedPageCopy } from "./product-simplification-types";

export function buildSimplifiedPageCopy(input: SimplifiedPageCopy): SimplifiedPageCopy {
  return { ...input };
}

const COPY: readonly SimplifiedPageCopy[] = [
  { route: "/", title: "Operator Home", subtitle: "Use Start for the simplest path, or open advanced operator surfaces when needed.", primaryActionLabel: "Go to Start", emptyStateTitle: "Choose your next task.", emptyStateBody: "Start guides you to the right page without needing internal phase knowledge.", safetyBadgeText: "Review first", advancedDetailsLabel: "Advanced operator surfaces", nextStepLabel: "Open Start" },
  { route: "/start", title: "Start", subtitle: "Choose what you want to do and CodexForge will point you to the right safe surface.", primaryActionLabel: "Choose an intent", emptyStateTitle: "What do you want to do?", emptyStateBody: "Pick a simple goal like fix code, run checks, or plan creative work.", safetyBadgeText: "No auto-run", advancedDetailsLabel: "Advanced links", nextStepLabel: "Select a workflow" },
  { route: "/ai", title: "Ask CodexForge", subtitle: "Describe what you want to inspect, fix, or plan.", primaryActionLabel: "Ask CodexForge", emptyStateTitle: "Ready for your request.", emptyStateBody: "Describe the file, failure, or creative idea you want help with.", safetyBadgeText: "Review first", advancedDetailsLabel: "Advanced settings", nextStepLabel: "Send message" },
  { route: "/files", title: "Inspect a file", subtitle: "Browse the project and read files before planning a change.", primaryActionLabel: "Inspect a file", emptyStateTitle: "Select a file to inspect it.", emptyStateBody: "Choose a file from the explorer to preview code and prepare safe context.", safetyBadgeText: "No file writes", advancedDetailsLabel: "Patch and apply details", nextStepLabel: "Preview change" },
  { route: "/validation", title: "Prepare checks", subtitle: "Choose validation checks and review the plan before anything runs.", primaryActionLabel: "Prepare checks", emptyStateTitle: "Choose checks to prepare.", emptyStateBody: "Start with build and smoke checks, then paste results back for review.", safetyBadgeText: "Approval required", advancedDetailsLabel: "Policy and output routing", nextStepLabel: "Review validation plan" },
  { route: "/closed-loop", title: "Start fix loop", subtitle: "Paste validation output or choose a failure, then route the next fix step.", primaryActionLabel: "Start fix loop", emptyStateTitle: "Paste validation output to start a fix loop.", emptyStateBody: "A failure becomes a reviewed path through files, patch preview, and checks.", safetyBadgeText: "Review first", advancedDetailsLabel: "Bridge and triage details", nextStepLabel: "Choose failure" },
  { route: "/creative", title: "Plan creative work", subtitle: "Choose a creative path and review the planned artifact before any execution boundary.", primaryActionLabel: "Plan creative work", emptyStateTitle: "Choose a creative path to plan your first artifact.", emptyStateBody: "Start with Blender, ComfyUI, Unreal, video render, or artifact review.", safetyBadgeText: "Preview only", advancedDetailsLabel: "Adapter details", nextStepLabel: "Pick creative path" },
  { route: "/creative-mvp", title: "Review MVP candidate", subtitle: "Review the recommended design-only creative execution candidate.", primaryActionLabel: "Review MVP candidate", emptyStateTitle: "Review the recommended MVP candidate before enabling anything real.", emptyStateBody: "The MVP remains design-only and requires approval before implementation.", safetyBadgeText: "Design only", advancedDetailsLabel: "Requirements and boundaries", nextStepLabel: "Review candidate" },
  { route: "/creative-executor", title: "Review dry run", subtitle: "Review the guarded creative executor dry-run packet.", primaryActionLabel: "Review dry run", emptyStateTitle: "Review dry-run details first.", emptyStateBody: "No real creative execution starts from this page.", safetyBadgeText: "No auto-run", advancedDetailsLabel: "Executor packet", nextStepLabel: "Review dry run" },
  { route: "/creative-sandbox", title: "Run simulation", subtitle: "Simulate the creative execution lifecycle with fake artifacts only.", primaryActionLabel: "Run simulation", emptyStateTitle: "Run a safe simulation first.", emptyStateBody: "The sandbox uses fake outputs and review handoffs only.", safetyBadgeText: "Simulation only", advancedDetailsLabel: "Simulation details", nextStepLabel: "Review simulation" },
  { route: "/local-bridge-health", title: "Check setup", subtitle: "Review local tool readiness before planning execution.", primaryActionLabel: "Check setup", emptyStateTitle: "Add setup details to check local tool readiness.", emptyStateBody: "Confirm which local tools are configured and what remains blocked.", safetyBadgeText: "Review first", advancedDetailsLabel: "Probe policy", nextStepLabel: "Review setup" },
  { route: "/health-probe", title: "Prepare probe", subtitle: "Review a metadata-only health probe packet.", primaryActionLabel: "Prepare probe", emptyStateTitle: "Prepare probe review.", emptyStateBody: "Probe execution remains disabled until guarded approval exists.", safetyBadgeText: "No auto-run", advancedDetailsLabel: "Probe packet", nextStepLabel: "Review probe" },
  { route: "/creative-readiness", title: "Audit readiness", subtitle: "Check creative executor readiness before implementation.", primaryActionLabel: "Audit readiness", emptyStateTitle: "Audit creative readiness first.", emptyStateBody: "Review allowlists, path boundaries, approvals, and kill-switch posture.", safetyBadgeText: "Preview only", advancedDetailsLabel: "Audit details", nextStepLabel: "Review readiness" },
  { route: "/artifacts/review", title: "Review artifact", subtitle: "Inspect artifacts, provenance, and handoff notes.", primaryActionLabel: "Review artifact", emptyStateTitle: "Select an artifact to review.", emptyStateBody: "Review output quality and provenance before handoff.", safetyBadgeText: "Review first", advancedDetailsLabel: "Provenance details", nextStepLabel: "Open review" },
  { route: "/blender", title: "Blender scene", subtitle: "Preview a Blender scene plan without launching Blender.", primaryActionLabel: "Review Blender plan", emptyStateTitle: "Plan a Blender scene.", emptyStateBody: "Review scene objects, camera, lights, and future executor packet.", safetyBadgeText: "Preview only", advancedDetailsLabel: "Blender adapter details", nextStepLabel: "Review plan" },
  { route: "/comfyui", title: "ComfyUI workflow", subtitle: "Preview an image workflow without calling ComfyUI.", primaryActionLabel: "Review ComfyUI plan", emptyStateTitle: "Plan an image workflow.", emptyStateBody: "Review nodes, prompts, and approval packet.", safetyBadgeText: "Preview only", advancedDetailsLabel: "ComfyUI adapter details", nextStepLabel: "Review plan" },
  { route: "/unreal", title: "Unreal cinematic", subtitle: "Preview a level and cinematic plan without launching Unreal.", primaryActionLabel: "Review Unreal plan", emptyStateTitle: "Plan an Unreal cinematic.", emptyStateBody: "Review actors, materials, sequencer, and command preview.", safetyBadgeText: "Preview only", advancedDetailsLabel: "Unreal adapter details", nextStepLabel: "Review plan" },
  { route: "/video-render", title: "Video render plan", subtitle: "Preview a render plan and queue packet without running ffmpeg or render tools.", primaryActionLabel: "Review render plan", emptyStateTitle: "Plan a video render.", emptyStateBody: "Review shots, timeline, expected artifacts, and future executor packet.", safetyBadgeText: "Preview only", advancedDetailsLabel: "Render packet details", nextStepLabel: "Review plan" },
] as const;

export function buildDefaultSimplifiedPageCopy(): SimplifiedPageCopy[] {
  return COPY.map(buildSimplifiedPageCopy);
}

export function getSimplifiedPageCopy(route: ProductSimplificationRoute): SimplifiedPageCopy {
  return buildDefaultSimplifiedPageCopy().find((copy) => copy.route === route) ?? buildDefaultSimplifiedPageCopy()[1];
}

export function summarizeSimplifiedPageCopy(copy: SimplifiedPageCopy): string {
  return `${copy.route}: ${copy.title}. Primary action: ${copy.primaryActionLabel}. Next: ${copy.nextStepLabel}.`;
}
