import {
  buildRealApplyGuardReviewStableKey,
  countApplyGuardStatus,
  deriveApplyGuardOverallStatus,
  hasApplyGuardParentTraversal,
  isApplyGuardAbsolutePath,
  normalizeApplyGuardPath,
  type ApplyGuardReviewCheck,
  type ApplyGuardReviewInput,
  type ApplyGuardReviewStatus,
  type ApplyPathBoundaryReview,
} from "./real-apply-guard-review-types";

export function buildApplyPathBoundaryReviewCheck(input: {
  id: string;
  label: string;
  status: ApplyGuardReviewStatus;
  detail: string;
  blocksApply?: boolean;
}): ApplyGuardReviewCheck {
  return { blocksApply: input.status === "blocker", ...input };
}

export function buildApplyPathBoundaryReview(input: ApplyGuardReviewInput): ApplyPathBoundaryReview {
  const paths = [input.selectedFilePath, ...input.touchedFiles].filter((path): path is string => !!path).map(normalizeApplyGuardPath);
  const hasPaths = paths.length > 0;
  const hasTraversal = paths.some(hasApplyGuardParentTraversal);
  const hasAbsolute = paths.some(isApplyGuardAbsolutePath);
  const systemTarget = paths.some((path) => /^(windows|program files|users\/public|etc|var|usr|system32)\//i.test(path));
  const hiddenOutside = paths.some((path) => /(^|\/)\.\.(\/|$)|(^|\/)\.codexforge\/(?!memory-events)/i.test(path));
  const executable = paths.some((path) => /\.(exe|cmd|bat|ps1|sh)$/i.test(path));
  const checks = [
    buildApplyPathBoundaryReviewCheck({ id: "project-root-known", label: "Project root known or supplied", status: input.source.projectRootKnown === true || !!input.source.projectRoot ? "pass" : "warning", detail: "Project root known or supplied; no path probing is performed." }),
    buildApplyPathBoundaryReviewCheck({ id: "target-path-relative-root", label: "Target path relative to project root", status: hasPaths && !hasAbsolute ? "pass" : "blocker", detail: "Target path relative to project root is required." }),
    buildApplyPathBoundaryReviewCheck({ id: "no-parent-traversal", label: "No parent traversal", status: hasTraversal ? "blocker" : "pass", detail: "Path boundary checks no parent traversal." }),
    buildApplyPathBoundaryReviewCheck({ id: "no-absolute-unreviewed-write-path", label: "No absolute unreviewed write path", status: hasAbsolute ? "blocker" : "pass", detail: "Path boundary checks no absolute unreviewed write path." }),
    buildApplyPathBoundaryReviewCheck({ id: "no-system-directory-target", label: "No system directory target", status: systemTarget ? "blocker" : "pass", detail: "System directory targets are blocked." }),
    buildApplyPathBoundaryReviewCheck({ id: "no-hidden-output-outside-source-tree", label: "No hidden output outside source tree", status: hiddenOutside ? "blocker" : "pass", detail: "Hidden output outside source tree is blocked." }),
    buildApplyPathBoundaryReviewCheck({ id: "no-executable-generated-default", label: "No executable generated by default", status: executable ? "warning" : "pass", detail: "Executable generation is not default and requires review." }),
    buildApplyPathBoundaryReviewCheck({ id: "windows-path-normalization-considered", label: "Windows path normalization considered", status: "pass", detail: "Windows path normalization considered by converting backslashes to slash display." }),
    buildApplyPathBoundaryReviewCheck({ id: "path-display-readable", label: "Path display is readable", status: hasPaths ? "pass" : "unknown", detail: "Path display is readable and reviewable." }),
    buildApplyPathBoundaryReviewCheck({ id: "output-apply-scope-explicit", label: "Output/apply scope explicit", status: input.touchedFiles.length > 0 ? "pass" : "warning", detail: "Output/apply scope is explicit via touched files." }),
  ];
  const review: ApplyPathBoundaryReview = {
    id: buildRealApplyGuardReviewStableKey("apply-path-boundary-review", input.reviewId),
    checks,
    overallStatus: deriveApplyGuardOverallStatus(checks),
    blockerCount: countApplyGuardStatus(checks, "blocker"),
    warningCount: countApplyGuardStatus(checks, "warning"),
    summary: [],
  };
  return { ...review, summary: summarizeApplyPathBoundaryReview(review) };
}

export function summarizeApplyPathBoundaryReview(review: ApplyPathBoundaryReview): string[] {
  return [
    `Path boundary review status ${review.overallStatus}.`,
    "No filesystem writes and no path probing; checks root knowledge, relative paths, traversal, absolute write paths, system directories, hidden output, executable outputs, Windows normalization, readable display, and explicit scope.",
  ];
}
