export const JARVIS_VIDEO_ADAPTER_PLUGIN_SHARED_MARKERS = [
  "3754-3785 - First Jarvis-Controlled Video Adapter Plug-in",
  "3754-3785 - First Jarvis-Controlled Video Adapter Plug-in Mega Batch v1",
  "First Jarvis-Controlled Video Adapter Plug-in",
  "Jarvis-controlled video adapter plug-in only",
  "video.generate plugs into Jarvis",
  "video workspace plugs into Jarvis control plane",
  "video adapter plugs into shared backend adapter contract",
  "video permission policy plugs into Jarvis permission engine",
  "video planner route plugs into Jarvis task planner",
  "video audit status plugs into Jarvis status dashboard",
  "/jarvis-video workspace remains review-only",
  "backend-owned video runtime readiness reference only",
  "video dry-run reference only",
  "video approval packet reference only",
  "video adapter readiness reference only",
  "provider reference review only",
  "credential reference review only",
  "token reference review only",
  "request envelope review only",
  "response envelope review only",
  "error envelope review only",
  "prompt redaction review only",
  "guard snapshot review only",
  "cost rate timeout review only",
  "duration resolution size review only",
  "privacy safety review only",
  "result placeholder only",
  "artifact handoff placeholder only",
  "kill switch remains enforced",
  "lock manager required",
  "idempotency required",
  "replay block required",
  "blocked action summary only",
  "operator review required before video execution",
  "video adapter plugin completion does not enable provider/render/export/publish/workers/trading/automation",
  "disabled by default",
  "hard kill switch",
  "dry-run required before execution",
  "backend-only execution path required",
  "no direct frontend execution",
  "no live provider call",
  "no provider execution",
  "no live provider execution",
  "no video provider execution",
  "no real video generation",
  "no live video generation",
  "no image provider execution",
  "no audio provider execution",
  "no website creation execution",
  "no avatar generation execution",
  "no chatbot autonomous execution",
  "no trading execution",
  "no paper trading execution",
  "no real-money trading execution",
  "no tool execution",
  "no autonomous tool execution",
  "no network execution",
  "no render execution",
  "no export execution",
  "no publish execution",
  "no worker dispatch",
  "no file export",
  "no download generation",
  "no archive creation",
  "no signed URL creation",
  "no platform upload",
  "no media upload",
  "no OAuth flow creation",
  "no webhook creation",
  "no schedule execution",
  "no account authorization execution",
  "no API route execution",
  "no service creation",
  "no runtime deploy",
  "no file writes from the app",
  "no shell/process/command execution from the app",
  "no fetch/network calls",
  "no provider SDK imports in frontend",
  "no frontend provider key reads",
  "no plaintext secrets",
  "no localStorage",
  "no sessionStorage",
  "no IndexedDB",
  "no cookies",
  "no browser storage for secrets",
  "next likely batch: 3786-3817 - First Jarvis-Controlled Video Dry Run Workspace",
] as const;

export const JARVIS_VIDEO_ADAPTER_PLUGIN_DISPLAY_MARKERS = [
  "video.generate plugs into Jarvis",
  "video workspace plugs into Jarvis control plane",
  "video adapter plugs into shared backend adapter contract",
  "video dry-run reference only",
  "video approval packet reference only",
  "video adapter readiness reference only",
  "/jarvis-video workspace remains review-only",
  "operator review required before video execution",
  "disabled by default",
  "hard kill switch",
] as const;

export const JARVIS_VIDEO_ADAPTER_PLUGIN_EXECUTION_BLOCKS = [
  "no direct frontend execution",
  "no live provider call",
  "no provider execution",
  "no live provider execution",
  "no video provider execution",
  "no real video generation",
  "no live video generation",
  "no image provider execution",
  "no audio provider execution",
  "no website creation execution",
  "no avatar generation execution",
  "no chatbot autonomous execution",
  "no trading execution",
  "no paper trading execution",
  "no real-money trading execution",
  "no tool execution",
  "no autonomous tool execution",
  "no network execution",
  "no render execution",
  "no export execution",
  "no publish execution",
  "no worker dispatch",
  "no file export",
  "no download generation",
  "no archive creation",
  "no signed URL creation",
  "no platform upload",
  "no media upload",
  "no OAuth flow creation",
  "no webhook creation",
  "no schedule execution",
  "no account authorization execution",
  "no API route execution",
  "no service creation",
  "no runtime deploy",
] as const;

export const JARVIS_VIDEO_ADAPTER_PLUGIN_STORAGE_BOUNDARIES = [
  "no file writes from the app",
  "no shell/process/command execution from the app",
  "no fetch/network calls",
  "no provider SDK imports in frontend",
  "no frontend provider key reads",
  "no plaintext secrets",
  "no localStorage",
  "no sessionStorage",
  "no IndexedDB",
  "no cookies",
  "no browser storage for secrets",
] as const;
