import {
  buildArtifactIngestionStableKey,
  type ArtifactBrainSignal,
  type ArtifactBrainSignalKind,
  type ArtifactIngestionInput,
  type ArtifactIngestionSource,
} from "./artifact-ingestion-types";
import { buildArtifactIngestionSources } from "./artifact-ingestion-events";

export function buildArtifactBrainSignal(args: {
  source: ArtifactIngestionSource;
  kind: ArtifactBrainSignalKind;
}): ArtifactBrainSignal {
  const source = args.source;
  const targetId = buildTargetId(source, args.kind);
  const signal: ArtifactBrainSignal = {
    id: buildArtifactIngestionStableKey("artifact-brain-signal", args.kind, source.sourcePackId, source.artifactId),
    kind: args.kind,
    artifactId: source.artifactId,
    sourceId: source.artifactId,
    targetId,
    label: buildSignalLabel(args.kind, source),
    readiness: source.validationResult === "blocked" ? "blocked" : source.exported ? "ready" : "needs-review",
    confidence: buildSignalConfidence(source, args.kind),
    reasons: buildSignalReasons(source, args.kind),
    summary: [],
  };

  return { ...signal, summary: summarizeSingleSignal(signal) };
}

export function buildArtifactBrainSignals(input: ArtifactIngestionInput): ArtifactBrainSignal[] {
  return buildArtifactIngestionSources(input).flatMap((source) =>
    ([
      "artifact-node-candidate",
      ...(source.sourcePackId ? ["production-pack-node-candidate" as const] : []),
      "run-relationship-candidate",
      "source-surface-relationship",
      "validation-relationship",
      "replay-relationship",
    ] satisfies ArtifactBrainSignalKind[]).map((kind) => buildArtifactBrainSignal({ source, kind }))
  );
}

export function summarizeArtifactBrainSignals(signals: ArtifactBrainSignal[]): string[] {
  const ready = signals.filter((signal) => signal.readiness === "ready").length;
  const blocked = signals.filter((signal) => signal.readiness === "blocked").length;

  return [
    `${signals.length} brain signals prepared as future graph candidates.`,
    `${ready} signal(s) are ready for review; ${blocked} signal(s) are blocked.`,
    "Signals describe artifact, pack, run, source, validation, and replay relationships without writing graph data.",
  ];
}

function buildTargetId(source: ArtifactIngestionSource, kind: ArtifactBrainSignalKind): string {
  const packId = source.sourcePackId ?? "workspace";
  const targets: Record<ArtifactBrainSignalKind, string> = {
    "artifact-node-candidate": buildArtifactIngestionStableKey("artifact", source.artifactId),
    "production-pack-node-candidate": buildArtifactIngestionStableKey("production-pack", packId),
    "run-relationship-candidate": buildArtifactIngestionStableKey("run", source.sourceRunId),
    "source-surface-relationship": buildArtifactIngestionStableKey("surface", source.sourceSurface),
    "validation-relationship": buildArtifactIngestionStableKey("validation", source.validationResult),
    "replay-relationship": buildArtifactIngestionStableKey("replay", packId, source.sourceRunId),
  };

  return targets[kind];
}

function buildSignalLabel(kind: ArtifactBrainSignalKind, source: ArtifactIngestionSource): string {
  const labels: Record<ArtifactBrainSignalKind, string> = {
    "artifact-node-candidate": `${source.title} artifact node candidate`,
    "production-pack-node-candidate": `${source.sourcePackId ?? "workspace"} production pack node candidate`,
    "run-relationship-candidate": `${source.title} generated by run ${source.sourceRunId}`,
    "source-surface-relationship": `${source.title} came from ${source.sourceSurface}`,
    "validation-relationship": `${source.title} validation is ${source.validationResult}`,
    "replay-relationship": `${source.title} has replay context`,
  };

  return labels[kind];
}

function buildSignalConfidence(source: ArtifactIngestionSource, kind: ArtifactBrainSignalKind): number {
  const base = source.exported ? 0.74 : 0.58;
  const pathBoost = source.targetWorkspacePath ? 0.08 : -0.08;
  const replayBoost = kind === "replay-relationship" && source.replaySummary.length > 0 ? 0.08 : 0;
  const validationPenalty = source.validationResult === "blocked" ? -0.38 : source.validationResult === "unknown" ? -0.12 : 0;
  return clamp01(base + pathBoost + replayBoost + validationPenalty);
}

function buildSignalReasons(source: ArtifactIngestionSource, kind: ArtifactBrainSignalKind): string[] {
  return [
    kind,
    source.exported ? "artifact-exported" : "review-before-promotion",
    source.targetWorkspacePath ? "workspace-path-present" : "workspace-path-missing",
    `validation:${source.validationResult}`,
    "no-direct-graph-mutation",
  ];
}

function summarizeSingleSignal(signal: ArtifactBrainSignal): string[] {
  return [
    `${signal.kind} for artifact ${signal.artifactId}.`,
    `readiness: ${signal.readiness}; confidence: ${signal.confidence.toFixed(2)}.`,
  ];
}

function clamp01(value: number): number {
  if (!Number.isFinite(value)) return 0;
  return Math.min(1, Math.max(0, value));
}
