param(
  [Parameter(Mandatory = $true)][string]$PhaseName,
  [Parameter(Mandatory = $true)][string]$ScriptFile,
  [Parameter(Mandatory = $true)][string]$Domain,
  [Parameter(Mandatory = $true)][string]$Route,
  [Parameter(Mandatory = $true)][string]$MainPanel,
  [Parameter(Mandatory = $true)][string]$CommandLabel,
  [Parameter(Mandatory = $true)][string[]]$Modules,
  [Parameter(Mandatory = $true)][string[]]$Components,
  [Parameter(Mandatory = $true)][string[]]$Exports,
  [Parameter(Mandatory = $true)][string[]]$PhaseMarkers,
  [Parameter(Mandatory = $true)][string[]]$PlainEnglish,
  [Parameter(Mandatory = $true)][string]$RouteHref
)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

$protectedRoutes = @(
  "/first-controlled-launch-review",
  "/first-controlled-launch-evidence-review",
  "/first-controlled-launch-result-review",
  "/first-controlled-launch-recovery-review",
  "/first-controlled-launch-hardening",
  "/daily-beta-1-controlled-launch-candidate",
  "/daily-beta-1-controlled-launch-handoff",
  "/daily-beta-1-controlled-launch-readiness-lock",
  "/universal-execution-boundary-inventory",
  "/file-write-approval-boundary",
  "/command-execution-approval-boundary",
  "/local-runtime-approval-boundary",
  "/provider-model-call-approval-boundary",
  "/connector-access-approval-boundary",
  "/automation-schedule-approval-boundary",
  "/evidence-capture-boundary",
  "/result-review-boundary",
  "/recovery-retry-boundary",
  "/packaging-export-boundary",
  "/workflow-profile-registry",
  "/creative-workflow-profile",
  "/research-workflow-profile",
  "/chatbot-workflow-profile",
  "/game-server-workflow-profile",
  "/project-scaffold-dry-run-plan",
  "/project-scaffold-evidence-review",
  "/project-scaffold-result-review",
  "/project-scaffold-recovery-review",
  "/project-scaffold-hardening-pass",
  "/file-write-controlled-trial-plan",
  "/file-write-controlled-trial-review",
  "/command-execution-controlled-trial-plan",
  "/command-execution-controlled-trial-review",
  "/local-runtime-controlled-trial-plan",
  "/local-runtime-controlled-trial-review",
  "/provider-model-controlled-trial-plan",
  "/connector-controlled-trial-plan",
  "/automation-controlled-trial-plan",
  "/packaging-export-controlled-trial-plan",
  "/universal-builder-controlled-trial-candidate",
  "/first-project-scaffold-controlled-trial",
  "/first-project-scaffold-trial-review",
  "/first-file-write-controlled-trial",
  "/first-file-write-trial-review",
  "/first-command-execution-controlled-trial",
  "/first-command-execution-trial-review",
  "/first-local-runtime-controlled-trial",
  "/first-local-runtime-trial-review",
  "/first-provider-model-controlled-trial",
  "/first-connector-controlled-trial",
  "/first-automation-controlled-trial",
  "/first-packaging-export-controlled-trial",
  "/universal-builder-evidence-review",
  "/universal-builder-result-review",
  "/universal-builder-recovery-review",
  "/universal-builder-mvp-candidate",
  "/execution-adapter-contract-inventory",
  "/file-write-adapter-contract-review",
  "/command-runner-adapter-contract-review",
  "/local-runtime-adapter-contract-review",
  "/provider-model-adapter-contract-review",
  "/connector-adapter-contract-review",
  "/automation-adapter-contract-review",
  "/evidence-store-adapter-contract-review",
  "/result-store-adapter-contract-review",
  "/recovery-adapter-contract-review",
  "/packaging-adapter-contract-review",
  "/creative-adapter-contract-review",
  "/research-adapter-contract-review",
  "/chatbot-adapter-contract-review",
  "/game-server-adapter-contract-review",
  "/universal-execution-adapter-mvp-candidate",
  "/adapter-backed-execution-preview-inventory",
  "/file-write-adapter-preview",
  "/command-runner-adapter-preview",
  "/local-runtime-adapter-preview",
  "/provider-model-adapter-preview",
  "/connector-adapter-preview",
  "/automation-adapter-preview",
  "/evidence-store-adapter-preview",
  "/result-store-adapter-preview",
  "/recovery-adapter-preview",
  "/packaging-adapter-preview",
  "/creative-adapter-preview",
  "/research-adapter-preview",
  "/chatbot-adapter-preview",
  "/game-server-adapter-preview",
  "/universal-adapter-backed-execution-preview-candidate",
  "/bounded-adapter-implementation-readiness",
  "/file-write-adapter-implementation-plan",
  "/command-runner-adapter-implementation-plan",
  "/local-runtime-adapter-implementation-plan",
  "/provider-model-adapter-implementation-plan",
  "/connector-adapter-implementation-plan",
  "/automation-adapter-implementation-plan",
  "/evidence-store-adapter-implementation-plan",
  "/result-store-adapter-implementation-plan",
  "/recovery-adapter-implementation-plan",
  "/packaging-adapter-implementation-plan",
  "/creative-adapter-implementation-plan",
  "/research-adapter-implementation-plan",
  "/chatbot-adapter-implementation-plan",
  "/game-server-adapter-implementation-plan",
  "/first-bounded-adapter-implementation-candidate",
  "/first-file-write-adapter-mvp-design",
  "/first-command-runner-adapter-mvp-design",
  "/first-local-runtime-adapter-mvp-design",
  "/first-evidence-store-adapter-mvp-design",
  "/first-result-store-adapter-mvp-design",
  "/first-recovery-adapter-mvp-design",
  "/first-packaging-adapter-mvp-design",
  "/first-project-scaffold-adapter-mvp-design",
  "/first-creative-adapter-mvp-design",
  "/first-research-adapter-mvp-design",
  "/first-chatbot-adapter-mvp-design",
  "/first-game-server-adapter-mvp-design",
  "/first-adapter-implementation-guardrails",
  "/first-adapter-implementation-test-harness",
  "/first-adapter-implementation-operator-handoff",
  "/first-real-adapter-mvp-candidate",
  "/bounded-adapter-implementation-slice-inventory",
  "/file-write-adapter-implementation-slice",
  "/command-runner-adapter-implementation-slice",
  "/local-runtime-adapter-implementation-slice",
  "/evidence-store-adapter-implementation-slice",
  "/result-store-adapter-implementation-slice",
  "/recovery-adapter-implementation-slice",
  "/packaging-adapter-implementation-slice",
  "/project-scaffold-adapter-implementation-slice",
  "/adapter-implementation-approval-gate",
  "/adapter-implementation-audit-trail",
  "/adapter-implementation-failure-modes",
  "/adapter-implementation-sandbox-boundary",
  "/adapter-implementation-validation-matrix",
  "/adapter-implementation-release-handoff",
  "/first-bounded-adapter-implementation-layer-candidate",
  "/first-file-write-adapter-implementation-review",
  "/first-command-runner-adapter-implementation-review",
  "/first-local-runtime-adapter-implementation-review",
  "/first-evidence-store-adapter-implementation-review",
  "/first-result-store-adapter-implementation-review",
  "/first-recovery-adapter-implementation-review",
  "/first-packaging-adapter-implementation-review",
  "/first-project-scaffold-adapter-implementation-review",
  "/adapter-implementation-harness-review",
  "/adapter-implementation-sandbox-review",
  "/adapter-implementation-audit-review",
  "/adapter-implementation-recovery-review",
  "/adapter-implementation-packaging-review",
  "/adapter-implementation-operator-trial-review",
  "/first-adapter-implementation-evidence-review",
  "/first-useful-controlled-adapter-mvp-candidate",
  "/actual-file-write-adapter-boundary",
  "/actual-command-runner-adapter-boundary",
  "/actual-local-runtime-adapter-boundary",
  "/actual-evidence-store-boundary",
  "/actual-result-store-boundary",
  "/actual-recovery-boundary",
  "/actual-packaging-boundary",
  "/actual-project-scaffold-boundary",
  "/adapter-execution-approval-packet",
  "/adapter-execution-dry-run-packet",
  "/adapter-execution-audit-packet",
  "/adapter-execution-failure-packet",
  "/adapter-execution-sandbox-packet",
  "/adapter-execution-validation-packet",
  "/adapter-execution-operator-runbook",
  "/first-adapter-execution-beta-candidate",
  "/real-file-write-adapter-wiring-plan",
  "/real-command-runner-adapter-wiring-plan",
  "/real-local-runtime-adapter-wiring-plan",
  "/real-evidence-store-wiring-plan",
  "/real-result-store-wiring-plan",
  "/real-recovery-wiring-plan",
  "/real-packaging-wiring-plan",
  "/real-project-scaffold-wiring-plan",
  "/real-adapter-approval-wiring-plan",
  "/real-adapter-audit-wiring-plan",
  "/real-adapter-sandbox-wiring-plan",
  "/real-adapter-validation-wiring-plan",
  "/real-adapter-operator-trial-plan",
  "/first-real-adapter-wiring-candidate",
  "/first-adapter-execution-beta-review",
  "/broad-controlled-builder-beta-candidate",
  "/backend-adapter-boundary-contract",
  "/local-bridge-adapter-boundary-contract",
  "/file-write-adapter-backend-contract",
  "/command-runner-adapter-backend-contract",
  "/local-runtime-adapter-backend-contract",
  "/evidence-store-backend-contract",
  "/result-store-backend-contract",
  "/recovery-backend-contract",
  "/packaging-backend-contract",
  "/project-scaffold-backend-contract",
  "/adapter-backend-approval-contract",
  "/adapter-backend-audit-contract",
  "/adapter-backend-sandbox-contract",
  "/adapter-backend-validation-contract",
  "/adapter-backend-operator-trial-contract",
  "/first-backend-adapter-contract-candidate",
  "/backend-adapter-implementation-scaffold",
  "/file-write-backend-adapter-preview",
  "/command-runner-backend-adapter-preview",
  "/local-runtime-backend-adapter-preview",
  "/evidence-store-backend-adapter-preview",
  "/result-store-backend-adapter-preview",
  "/recovery-backend-adapter-preview",
  "/packaging-backend-adapter-preview",
  "/project-scaffold-backend-adapter-preview",
  "/backend-adapter-approval-preview",
  "/backend-adapter-audit-preview",
  "/backend-adapter-sandbox-preview",
  "/backend-adapter-validation-preview",
  "/backend-adapter-operator-trial-preview",
  "/backend-adapter-dry-run-candidate",
  "/first-backend-adapter-implementation-preview-candidate",
  "/backend-adapter-dry-run-packet-inventory",
  "/file-write-backend-dry-run-packet",
  "/command-runner-backend-dry-run-packet",
  "/local-runtime-backend-dry-run-packet",
  "/evidence-store-backend-dry-run-packet",
  "/result-store-backend-dry-run-packet",
  "/recovery-backend-dry-run-packet",
  "/packaging-backend-dry-run-packet",
  "/project-scaffold-backend-dry-run-packet",
  "/model-router-selection-preview",
  "/model-capability-registry-preview",
  "/model-cost-quality-policy-preview",
  "/model-privacy-locality-policy-preview",
  "/model-fallback-chain-preview",
  "/model-selection-approval-packet",
  "/backend-dry-run-model-router-candidate",
  "/shared-model-brain-context-contract",
  "/shared-model-memory-access-preview",
  "/shared-model-knowledge-access-preview",
  "/model-task-classification-matrix",
  "/model-efficiency-scoring-preview",
  "/free-model-routing-policy-preview",
  "/paid-model-routing-policy-preview",
  "/pro-model-routing-policy-preview",
  "/local-model-routing-policy-preview",
  "/specialist-model-routing-policy-preview",
  "/model-continuity-handoff-packet",
  "/cross-model-result-comparison-preview",
  "/cross-model-failure-recovery-preview",
  "/model-spend-guardrail-preview",
  "/model-routing-audit-trail-preview",
  "/shared-brain-model-router-candidate",
  "/model-provider-registry-preview",
  "/openai-compatible-model-provider-preview",
  "/local-model-provider-preview",
  "/free-model-provider-preview",
  "/paid-model-provider-preview",
  "/pro-model-provider-preview",
  "/specialist-video-model-provider-preview",
  "/specialist-image-model-provider-preview",
  "/specialist-coding-model-provider-preview",
  "/specialist-research-model-provider-preview",
  "/specialist-trading-model-provider-preview",
  "/model-credential-boundary-preview",
  "/model-usage-budget-preview",
  "/model-context-sync-packet",
  "/model-output-evidence-packet",
  "/controlled-model-use-candidate",
  "/model-provider-connection-boundary-preview",
  "/openai-compatible-connection-test-preview",
  "/local-model-connection-test-preview",
  "/free-model-connection-test-preview",
  "/paid-model-connection-test-preview",
  "/pro-model-connection-test-preview",
  "/specialist-model-connection-test-preview",
  "/model-health-probe-preview",
  "/model-latency-score-preview",
  "/model-quality-score-preview",
  "/model-cost-efficiency-score-preview",
  "/model-privacy-risk-score-preview",
  "/model-tool-support-score-preview",
  "/model-selection-dry-run-result-preview",
  "/first-controlled-model-use-trial-packet",
  "/controlled-model-router-readiness-candidate",
  "/controlled-model-use-dry-run-inventory",
  "/openai-compatible-model-use-dry-run",
  "/local-model-use-dry-run",
  "/free-model-use-dry-run",
  "/paid-model-use-dry-run",
  "/pro-model-use-dry-run",
  "/specialist-video-model-use-dry-run",
  "/specialist-image-model-use-dry-run",
  "/specialist-coding-model-use-dry-run",
  "/specialist-research-model-use-dry-run",
  "/specialist-trading-model-use-dry-run",
  "/shared-context-packet-validation",
  "/shared-memory-handoff-validation",
  "/model-router-decision-explanation-review",
  "/first-controlled-model-router-trial-review",
  "/controlled-model-use-release-candidate",
  "/live-provider-readiness-boundary",
  "/approved-provider-test-packet",
  "/openai-compatible-provider-test-packet",
  "/local-model-bridge-dry-run",
  "/free-model-provider-trial-packet",
  "/paid-model-provider-trial-packet",
  "/pro-model-provider-trial-packet",
  "/specialist-model-provider-trial-packet",
  "/model-router-trial-cockpit",
  "/model-router-candidate-ranking-review",
  "/model-router-budget-decision-review",
  "/model-router-privacy-decision-review",
  "/model-router-shared-context-review",
  "/model-router-evidence-capture-review",
  "/first-controlled-provider-trial-candidate",
  "/model-router-execution-readiness-candidate",
  "/approved-provider-health-check-boundary",
  "/provider-health-check-request-packet",
  "/provider-health-check-result-packet",
  "/local-model-bridge-readiness-review",
  "/local-model-bridge-context-packet",
  "/local-model-bridge-evidence-packet",
  "/openai-compatible-router-trial-result",
  "/free-model-router-trial-result",
  "/paid-model-router-trial-result",
  "/pro-model-router-trial-result",
  "/specialist-model-router-trial-result",
  "/model-router-trial-summary",
  "/model-router-trial-regression-guard",
  "/model-router-trial-operator-review",
  "/first-model-router-beta-candidate",
  "/controlled-model-router-beta-release-candidate",
  "/backend-execution-router-integration-boundary",
  "/file-write-model-routed-execution-preview",
  "/command-runner-model-routed-execution-preview",
  "/local-runtime-model-routed-execution-preview",
  "/evidence-store-model-routed-execution-preview",
  "/result-store-model-routed-execution-preview",
  "/recovery-model-routed-execution-preview",
  "/packaging-model-routed-execution-preview",
  "/project-scaffold-model-routed-execution-preview",
  "/model-routed-execution-approval-packet",
  "/model-routed-execution-audit-packet",
  "/model-routed-execution-sandbox-review",
  "/model-routed-execution-validation-review",
  "/model-routed-execution-operator-trial",
  "/first-model-routed-backend-execution-candidate",
  "/controlled-backend-model-router-release-candidate",
  "/project-builder-mvp-integration-boundary",
  "/project-goal-intake-packet",
  "/project-domain-classifier-preview",
  "/project-plan-model-routing-preview",
  "/project-file-plan-preview",
  "/project-command-plan-preview",
  "/project-runtime-plan-preview",
  "/project-evidence-plan-preview",
  "/project-result-plan-preview",
  "/project-recovery-plan-preview",
  "/project-packaging-plan-preview",
  "/project-approval-plan-preview",
  "/project-builder-operator-review",
  "/first-useful-project-builder-candidate",
  "/project-builder-mvp-trial-packet",
  "/controlled-project-builder-release-candidate",
  "/universal-game-builder-boundary",
  "/game-target-intake-packet",
  "/game-platform-classifier-preview",
  "/game-server-plan-preview",
  "/game-modpack-plan-preview",
  "/game-content-plan-preview",
  "/game-automation-plan-preview",
  "/game-asset-pipeline-plan-preview",
  "/game-deployment-plan-preview",
  "/game-safety-approval-plan",
  "/game-evidence-capture-plan",
  "/game-result-review-plan",
  "/game-recovery-plan-preview",
  "/game-packaging-plan-preview",
  "/first-universal-game-builder-candidate",
  "/controlled-universal-game-builder-release-candidate"
)

& (Join-Path $PSScriptRoot "codexforge-daily-beta-one-release-review-smoke-helper.ps1") `
  -PhaseName $PhaseName `
  -ScriptFile $ScriptFile `
  -Domain $Domain `
  -Route $Route `
  -MainPanel $MainPanel `
  -CommandLabel $CommandLabel `
  -Modules $Modules `
  -Components $Components `
  -Exports $Exports `
  -PhaseMarkers $PhaseMarkers `
  -PlainEnglish $PlainEnglish `
  -RouteHref $RouteHref `
  -ProtectedRoutes $protectedRoutes

function Assert-Contains {
  param([AllowEmptyString()][string]$Haystack, [string]$Needle, [string]$Name)
  if (-not $Haystack.Contains($Needle)) { throw "[FAIL] Missing $Name`: $Needle" }
  Write-Host "[PASS] $Name"
}

function Assert-NotMatches {
  param([AllowEmptyString()][string]$Haystack, [string]$Pattern, [string]$Name)
  if ($Haystack -match $Pattern) { throw "[FAIL] Unexpected $Name`: $Pattern" }
  Write-Host "[PASS] $Name"
}

function Assert-CountExactly {
  param([AllowEmptyString()][string]$Haystack, [string]$Needle, [int]$Expected, [string]$Name)
  $count = ([regex]::Matches($Haystack, [regex]::Escape($Needle))).Count
  if ($count -ne $Expected) { throw "[FAIL] $Name expected $Expected found $count" }
  Write-Host "[PASS] $Name"
}

$shared = "src\lib\codexforge\daily-beta-1-release-review-kit"
$universalShared = "src\lib\codexforge\universal-execution-review-kit"
$sourceParts = @()
$adapterPreviewShared = "src\lib\codexforge\adapter-backed-execution-preview-kit"
$boundedImplementationShared = "src\lib\codexforge\bounded-adapter-implementation-plan-kit"
$boundedImplementationSliceShared = "src\lib\codexforge\bounded-adapter-implementation-slice-kit"
$adapterImplementationReviewShared = "src\lib\codexforge\adapter-implementation-review-kit"
$adapterExecutionBetaBoundaryShared = "src\lib\codexforge\adapter-execution-beta-boundary-kit"
$backendAdapterContractShared = "src\lib\codexforge\backend-adapter-boundary-contract-kit"
$backendAdapterImplementationPreviewShared = "src\lib\codexforge\backend-adapter-implementation-preview-kit"
$backendDryRunModelRouterPreviewShared = "src\lib\codexforge\backend-dry-run-model-router-preview-kit"
$modelRouterProviderReadinessReviewShared = "src\lib\codexforge\model-router-provider-readiness-review-kit"
$firstRealAdapterMvpDesignShared = "src\lib\codexforge\first-real-adapter-mvp-design-kit"
$projectBuilderMvpPreviewShared = "src\lib\codexforge\project-builder-mvp-preview-kit"
$universalGameBuilderPreviewShared = "src\lib\codexforge\universal-game-builder-preview-kit"
foreach ($scanRoot in @($Domain, $Route, $shared, $universalShared, $adapterPreviewShared, $boundedImplementationShared, $boundedImplementationSliceShared, $adapterImplementationReviewShared, $adapterExecutionBetaBoundaryShared, $backendAdapterContractShared, $backendAdapterImplementationPreviewShared, $backendDryRunModelRouterPreviewShared, $modelRouterProviderReadinessReviewShared, $firstRealAdapterMvpDesignShared, $projectBuilderMvpPreviewShared, $universalGameBuilderPreviewShared)) {
  $sourceParts += Get-ChildItem -Recurse -File $scanRoot | ForEach-Object { Get-Content -Raw $_.FullName }
}
foreach ($sharedFile in @("src\lib\codexforge\video-foundation-ui.tsx")) {
  if (Test-Path $sharedFile) { $sourceParts += Get-Content -Raw $sharedFile }
}
$source = $sourceParts -join "`n"
$allSmoke = Get-Content -Raw "scripts\smoke-codexforge-all.ps1"
$packageSource = Get-Content -Raw "package.json"

$universalMarkers = @(
  "UniversalExecutionReviewSurface",
  "review-only",
  "approval required",
  "approval required before execution",
  "not executable yet",
  "no action execution from UI",
  "no live adapter implementation",
  "no adapter execution",
  "no adapter preview execution",
  "no project scaffold creation",
  "no file write/delete/mutation",
  "no command execution",
  "no shell/git/test/build/smoke execution from UI",
  "no local runtime start/stop",
  "no local runtime start",
  "no local bridge endpoint calls",
  "no provider/model calls",
  "no prompt sending",
  "no connector access/fetch/mutation",
  "no connector calls",
  "no connector fetch/mutation",
  "no connector data storage",
  "no automation/schedule/reminder/task/watch creation",
  "no polling loop creation",
  "no background job creation",
  "no notification sending",
  "no evidence capture/ingestion/storage",
  "no evidence capture/ingestion",
  "no memory/RAG ingestion",
  "no output/result storage or reuse",
  "no output/result storage",
  "no output storage",
  "no recovery/retry trigger",
  "no package/export/write behavior",
  "no creative/video/image/3D generation",
  "no creative asset generation",
  "no video generation",
  "no image generation",
  "no 3D generation",
  "no research browsing/searching/fetching",
  "no chatbot/agent creation/deployment",
  "no video-call joining/monitoring",
  "no monitoring job creation",
  "no Minecraft/project/server build or launch execution",
  "no Minecraft/project/server build execution",
  "no server launch",
  "no copyrighted franchise asset/name/logo/map/dialogue/music copying",
  "no approval automation",
  "no approval decision persistence",
  "no policy auto-apply",
  "no settings persistence",
  "no preference persistence",
  "no patch apply behavior",
  "no web/search/GitHub API calls from UI",
  "no web/search API calls",
  "no GitHub API calls from UI",
  "no prompt/file/project/connector/provider/model/output/audit/evidence/automation/live/beta/policy/settings/daily/rollout/release/boundary/e2e/activation/launch data sending without approval",
  "no arbitrary project scanning",
  "no arbitrary local file browsing",
  "no arbitrary path crawling",
  "no arbitrary project scanning/local file browsing/path crawling",
  "no arbitrary file read/open from UI",
  "no auto-open local files",
  "no memory/RAG ingestion or memory auto-promotion",
  "no memory auto-promotion",
  "no Brain graph mutation",
  "no appendEvent/saveBrainGraph calls from UI",
  "no direct appendEvent call from UI",
  "no direct saveBrainGraph call from UI",
  "no direct apply-diff call from UI",
  "no direct write-file call from UI",
  "no direct run-command call from UI",
  "no plugin execution",
  "no tool execution",
  "no agent execution",
  "no plugin/tool/agent/MCP execution",
  "no extension runtime executor",
  "no MCP runtime",
  "no MCP tool calls",
  "no localStorage API key storage",
  "no sessionStorage API key storage",
  "no token storage",
  "no endpoint storage",
  "no credential storage",
  "no credential/key/token/endpoint/output storage",
  "no process.env printing",
  "no API keys or secrets displayed",
  "no example real key/token/endpoint values",
  "no route coverage removal",
  "no duplicate route hrefs",
  "no duplicate shortLabel values",
  "no duplicate route hrefs or shortLabels",
  "no obvious duplicate React key patterns",
  "no Ruflo/Odysseus vendoring",
  "no package install behavior",
  "checkpoint documentation smoke still exists and remains registered",
  "server-only path boundary markers remain intact",
  "no Math.random",
  "no Date.now",
  "no Date.now for deterministic layout/ids",
  "no mojibake"
)

foreach ($needle in $universalMarkers) {
  Assert-Contains $source $needle "universal execution marker $needle"
}

Assert-Contains $allSmoke "Checkpoint Documentation Consistency" "checkpoint documentation smoke still exists and remains registered"
Assert-Contains $allSmoke "smoke-codexforge-checkpoint-docs.ps1" "checkpoint documentation smoke script remains registered"
Assert-CountExactly $allSmoke $ScriptFile 1 "all-smoke includes $ScriptFile exactly once"
Assert-CountExactly $allSmoke $PhaseName 1 "all-smoke includes $PhaseName exactly once"

$deterministicSource = $source
foreach ($marker in @($PhaseMarkers + $PlainEnglish + $universalMarkers)) {
  $deterministicSource = $deterministicSource.Replace($marker, "")
}

$blockedPatterns = @{
  "no action workflow approval automation or persistence" = "actionsExecutedFromUi:\s*true|workflowExecutionAllowedFromUi:\s*true|approvalAutomationAllowedFromUi:\s*true|approvalDecisionPersistenceAllowedFromUi:\s*true|approveAction\s*\(|grantApproval\s*\(|executeAction\s*\(|runWorkflow\s*\(|executeWorkflow\s*\("
  "no file write delete mutation patch export behavior" = "fileMutationAllowedFromUi:\s*true|fileWriteAllowedFromUi:\s*true|fileDeletionAllowedFromUi:\s*true|patchApplyAllowedFromUi:\s*true|packageExportAllowedFromUi:\s*true|writeFile\s*\(|deleteFile\s*\(|mutateFiles\s*\(|applyPatch\s*\(|exportFile\s*\(|downloadFile\s*\("
  "no command shell git test build smoke package server execution" = "commandExecutionAllowedFromUi:\s*true|shellExecutionAllowedFromUi:\s*true|gitCommandExecutionAllowedFromUi:\s*true|testBuildSmokeExecutionAllowedFromUi:\s*true|runCommand\s*\(|runGit\s*\(|runTests\s*\(|runBuild\s*\(|runSmoke\s*\(|child_process|execSync|spawn\s*\("
  "no local runtime bridge provider model prompt connector behavior" = "localRuntimeStartAllowedFromUi:\s*true|localBridgeEndpointCallsAllowedFromUi:\s*true|providerModelCallsAllowedFromUi:\s*true|providerApiCallsAllowedFromUi:\s*true|promptSendingAllowedFromUi:\s*true|connectorAccountConnectionAllowedFromUi:\s*true|connectorDataFetchAllowedFromUi:\s*true|connectorDataMutationAllowedFromUi:\s*true|fetch\s*\(|XMLHttpRequest|axios|api\.github|octokit|callProvider\s*\(|callModel\s*\(|sendPrompt\s*\(|callConnector\s*\(|connectAccount\s*\("
  "no automation schedule reminders watches polling jobs notifications" = "automationCreationAllowedFromUi:\s*true|scheduleCreationAllowedFromUi:\s*true|reminderCreationAllowedFromUi:\s*true|taskSchedulingAllowedFromUi:\s*true|conditionalWatchCreationAllowedFromUi:\s*true|pollingLoopAllowedFromUi:\s*true|backgroundJobCreationAllowedFromUi:\s*true|notificationSendingAllowedFromUi:\s*true|createAutomation\s*\(|createSchedule\s*\(|createReminder\s*\(|scheduleTask\s*\(|createWatch\s*\(|setInterval\s*\(|setTimeout\s*\(|createBackgroundJob\s*\(|sendNotification\s*\("
  "no evidence result recovery package creative research chatbot game meeting monitoring execution" = "evidenceCaptureAllowedFromUi:\s*true|evidenceIngestionAllowedFromUi:\s*true|resultStorageAllowedFromUi:\s*true|recoveryRetryAllowedFromUi:\s*true|creativeGenerationAllowedFromUi:\s*true|researchFetchAllowedFromUi:\s*true|chatbotAgentCreationAllowedFromUi:\s*true|gameServerBuildAllowedFromUi:\s*true|videoCallJoinAllowedFromUi:\s*true|monitoringJobCreationAllowedFromUi:\s*true|captureEvidence\s*\(|ingestEvidence\s*\(|storeResult\s*\(|triggerRecovery\s*\(|triggerRetry\s*\(|generateImage\s*\(|generateVideo\s*\(|generate3D\s*\(|createAgent\s*\(|deployBot\s*\(|buildServer\s*\(|launchServer\s*\(|joinVideoCall\s*\("
  "no arbitrary project file browsing or memory Brain mutation" = "arbitraryProjectScanningAllowed:\s*true|arbitraryLocalFileBrowsingAllowed:\s*true|arbitraryPathCrawlingAllowed:\s*true|arbitraryFileReadOpenAllowed:\s*true|autoOpenLocalFilesAllowed:\s*true|memoryMutationAllowedFromUi:\s*true|memoryIngestionAllowedFromUi:\s*true|memoryAutoPromotionAllowed:\s*true|brainGraphMutationAllowed:\s*true|appendEventAllowedFromUi:\s*true|saveBrainGraphAllowedFromUi:\s*true|readFile\s*\(|openFile\s*\(|crawlPath\s*\(|ingestMemory\s*\(|ingestRag\s*\(|promoteMemory\s*\(|appendEvent\s*\(|saveBrainGraph\s*\("
  "no plugin tool agent extension MCP runtime execution" = "pluginExecutionAllowedFromUi:\s*true|toolExecutionAllowedFromUi:\s*true|agentExecutionAllowedFromUi:\s*true|extensionRuntimeExecutorCreated:\s*true|mcpRuntimeCreated:\s*true|mcpToolCallsAllowedFromUi:\s*true|executePlugin\s*\(|executeTool\s*\(|executeAgent\s*\(|createExtensionRuntimeExecutor\s*\(|createMcpServer\s*\(|createMcpClient\s*\(|callMcpTool\s*\("
  "no credentials tokens endpoints storage or env exposure" = "localStorageApiKeyStorageAllowed:\s*true|sessionStorageApiKeyStorageAllowed:\s*true|tokenStorageAllowed:\s*true|endpointStorageAllowed:\s*true|credentialStorageAllowed:\s*true|outputStorageAllowed:\s*true|localStorage\.setItem|sessionStorage\.setItem|accessToken\s*[:=]|refreshToken\s*[:=]|processEnvDisplayAllowed:\s*true|process\.env\.[A-Za-z0-9_]+|console\.(log|warn|error)\s*\([^\r\n]*process\.env|secretsDisplayedAllowed:\s*true|sk-[A-Za-z0-9_-]{16,}|AIza[0-9A-Za-z_-]{20,}|xox[baprs]-[A-Za-z0-9-]{20,}|gh[pousr]_[A-Za-z0-9_]{20,}"
  "no package install vendoring duplicate React key patterns" = "packageInstallAllowedFromUi:\s*true|thirdPartyCodeVendoredOrCopied:\s*true|npm\s+install|pnpm\s+add|yarn\s+add|bun\s+add|vendor[/\\](ruflo|odysseus)|key=\{label\}|key=\{summary\}|key=\{item\}|key=\{constraint\}|key=\{badge\}|key=\{title\}|key=\{entry\}|key=\{step\}|key=\{phase\}|key=\{route\}"
  "no deterministic API misuse" = "Math\.random\s*\(|Date\.now\s*\(|crypto\.randomUUID\s*\("
  "no mojibake" = "$([char]0x00C3)|$([char]0x00C2)|$([char]0xFFFD)"
}

foreach ($name in $blockedPatterns.Keys) {
  $haystack = if ($name -eq "no deterministic API misuse") {
    $deterministicSource
  } elseif ($name -eq "no credentials tokens endpoints storage or env exposure") {
    $source.Replace("model-task-classification-matrix", "model task classification matrix").Replace("model-privacy-risk-score-preview", "model privacy risk score preview")
  } else {
    $source
  }
  Assert-NotMatches $haystack $blockedPatterns[$name] $name
}

Assert-NotMatches $packageSource '"ruflo"|"@ruflo/|"odysseus"|"@odysseus/|"@modelcontextprotocol/' "no Ruflo/Odysseus/MCP dependency references in package manifest"
Write-Host "[PASS] universal controlled execution boundary safety helper checks passed."
