param([string]$BaseUrl = "http://localhost:3000")
$ErrorActionPreference = "Stop"; $root = Split-Path -Parent $PSScriptRoot; Set-Location $root
function Assert-FileExists { param([string]$Path) if (-not (Test-Path $Path)) { throw "[FAIL] Missing file: $Path" } Write-Host "[PASS] file exists: $Path" }
function Assert-DirectoryExists { param([string]$Path) if (-not (Test-Path $Path -PathType Container)) { throw "[FAIL] Missing directory: $Path" } Write-Host "[PASS] directory exists: $Path" }
function Assert-Contains { param([AllowEmptyString()][string]$Haystack,[string]$Needle,[string]$Name) if (-not $Haystack.Contains($Needle)) { throw "[FAIL] Missing $Name`: $Needle" } Write-Host "[PASS] $Name" }
function Assert-NotMatches { param([AllowEmptyString()][string]$Haystack,[string]$Pattern,[string]$Name) if ($Haystack -match $Pattern) { throw "[FAIL] Unexpected $Name`: $Pattern" } Write-Host "[PASS] $Name" }
function Assert-CountExactly { param([AllowEmptyString()][string]$Haystack,[string]$Needle,[int]$Expected,[string]$Name) $count=([regex]::Matches($Haystack,[regex]::Escape($Needle))).Count; if($count -ne $Expected){throw "[FAIL] $Name expected $Expected found $count"} Write-Host "[PASS] $Name" }
Write-Host "=== CodexForge MVP Working Path Lock smoke ==="
$domainDir="src\lib\codexforge\mvp-working-path-lock"; $componentDir=Join-Path $domainDir "components"; $routePath="src\app\code-flow\mvp-path\page.tsx"; $clientPath="src\app\code-flow\mvp-path\page-client.tsx"
Assert-DirectoryExists $domainDir; Assert-DirectoryExists $componentDir
foreach($module in @("mvp-working-path-types.ts","mvp-path-definition.ts","mvp-path-step.ts","mvp-path-route-map.ts","mvp-path-safety-lock.ts","mvp-path-validation-lock.ts","mvp-path-navigation-lock.ts","mvp-path-regression-lock.ts","mvp-path-handoff.ts","mvp-working-path-summary.ts","index.ts")){Assert-FileExists (Join-Path $domainDir $module)}
foreach($component in @("MvpWorkingPathLockPanel.tsx","MvpPathDefinitionPanel.tsx","MvpPathStepPanel.tsx","MvpPathRouteMapPanel.tsx","MvpPathSafetyLockPanel.tsx","MvpPathValidationLockPanel.tsx","MvpPathNavigationLockPanel.tsx","MvpPathRegressionLockPanel.tsx","MvpPathHandoffPanel.tsx","MvpPathSafetyStrip.tsx","MvpPathEmptyState.tsx")){Assert-FileExists (Join-Path $componentDir $component)}
Assert-FileExists $routePath; Assert-FileExists $clientPath
$indexSource=Get-Content -Raw (Join-Path $domainDir "index.ts"); $domainSource=(Get-ChildItem $domainDir -File|%{Get-Content -Raw $_.FullName}) -join "`n"; $uiSource=(Get-ChildItem $componentDir -File|%{Get-Content -Raw $_.FullName}) -join "`n"; $routeSource=(Get-Content -Raw $routePath)+"`n"+(Get-Content -Raw $clientPath); $allSource=$domainSource+"`n"+$uiSource+"`n"+$routeSource
foreach($export in @("buildMvpPathDefinition","buildMvpPathStep","buildMvpPathRouteMap","buildMvpPathSafetyLock","buildMvpPathValidationLock","buildMvpPathNavigationLock","buildMvpPathRegressionLock","buildMvpPathHandoff","buildMvpWorkingPathSummary")){Assert-Contains $indexSource $export "index exports $export"}
foreach($render in @("MvpWorkingPathLockPanel renders","MvpPathDefinitionPanel renders","MvpPathStepPanel renders","MvpPathRouteMapPanel renders","MvpPathSafetyLockPanel renders","MvpPathValidationLockPanel renders","MvpPathNavigationLockPanel renders","MvpPathRegressionLockPanel renders","MvpPathHandoffPanel renders","MvpPathSafetyStrip renders","MvpPathEmptyState renders")){Assert-Contains $uiSource $render $render}
foreach($text in @("MVP working path","Open Coding MVP Path","one canonical path","advanced routes secondary","/start","/code-flow/live-run","/files","/guarded-apply-mvp","/apply-evidence","/validation-results","/workflow-results","/run-history","/closed-loop","/code-flow/release-audit","manual validation only","Command Palette","Workflow Wizard agrees","no duplicate route clouds","one primary action per step","no auto-apply","no auto-run","approval required","preserve latest-message authority","Focus Mode UX calm workflow layout markers","shell without duplicate route chip cloud","route hero title does not vertically wrap","no giant raw JSON above fold","advanced details are collapsed or visually secondary","no unsafe execution buttons","buildMvpPathStableKey")){Assert-Contains $allSource $text "marker $text"}
Assert-Contains $routeSource "MvpWorkingPathLockPanel" "route imports/renders main panel"
foreach($bad in @("appendEvent\s*\(","saveBrainGraph\s*\(","\.nodes\s*\.\s*push|\.edges\s*\.\s*push","apply-diff\s*\(","write-file\s*\(","run-command\s*\(","broker-execution\s*\(","https?://","fetch\s*\(","OPENAI_API_KEY","localStorage.setItem","process\.env\.","Math\.random","Date\.now","d3-force","[\u00c3\u00c2]")){Assert-NotMatches $allSource $bad "blocked marker absent $bad"}
Assert-Contains ((Get-Content -Raw "src\app\start\page-client.tsx")+(Get-Content -Raw "src\app\code-flow\page-client.tsx")+(Get-Content -Raw "src\app\code-flow\release-audit\page-client.tsx")+(Get-Content -Raw "src\lib\codexforge\command-palette\command-registry.ts")) "/code-flow/mvp-path" "integrations mention mvp path"
Assert-Contains (Get-Content -Raw "src\lib\codexforge\command-palette\command-registry.ts") "Open Coding MVP Path" "command palette includes Open Coding MVP Path"
Assert-CountExactly (Get-Content -Raw "scripts\smoke-codexforge-all.ps1") "smoke-codexforge-mvp-working-path-lock.ps1" 1 "managed smoke suite includes phase exactly once"
Write-Host "[OK] CodexForge MVP Working Path Lock smoke passed."
