param([string]$BaseUrl = "http://localhost:3000")
$ErrorActionPreference = "Stop"; $root = Split-Path -Parent $PSScriptRoot; Set-Location $root
function Assert-FileExists { param([string]$Path) if (-not (Test-Path $Path)) { throw "[FAIL] Missing file: $Path" } Write-Host "[PASS] file exists: $Path" }
function Assert-DirectoryExists { param([string]$Path) if (-not (Test-Path $Path -PathType Container)) { throw "[FAIL] Missing directory: $Path" } Write-Host "[PASS] directory exists: $Path" }
function Assert-Contains { param([AllowEmptyString()][string]$Haystack,[string]$Needle,[string]$Name) if (-not $Haystack.Contains($Needle)) { throw "[FAIL] Missing $Name`: $Needle" } Write-Host "[PASS] $Name" }
function Assert-NotMatches { param([AllowEmptyString()][string]$Haystack,[string]$Pattern,[string]$Name) if ($Haystack -match $Pattern) { throw "[FAIL] Unexpected $Name`: $Pattern" } Write-Host "[PASS] $Name" }
function Assert-CountExactly { param([AllowEmptyString()][string]$Haystack,[string]$Needle,[int]$Expected,[string]$Name) $count=([regex]::Matches($Haystack,[regex]::Escape($Needle))).Count; if($count -ne $Expected){throw "[FAIL] $Name expected $Expected found $count"} Write-Host "[PASS] $Name" }
Write-Host "=== CodexForge Trial Friction Fix Pass smoke ==="
$domainDir="src\lib\codexforge\trial-friction-fix-pass"; $componentDir=Join-Path $domainDir "components"; $routePath="src\app\code-flow\friction-fixes\page.tsx"; $clientPath="src\app\code-flow\friction-fixes\page-client.tsx"
Assert-DirectoryExists $domainDir; Assert-DirectoryExists $componentDir
foreach($module in @("trial-friction-fix-types.ts","friction-finding.ts","friction-priority.ts","friction-copy-fix.ts","friction-layout-fix.ts","friction-route-fix.ts","friction-validation-fix.ts","friction-safety-copy-fix.ts","friction-fix-handoff.ts","friction-fix-summary.ts","index.ts")){Assert-FileExists (Join-Path $domainDir $module)}
foreach($component in @("TrialFrictionFixPassPanel.tsx","FrictionFindingPanel.tsx","FrictionPriorityPanel.tsx","FrictionCopyFixPanel.tsx","FrictionLayoutFixPanel.tsx","FrictionRouteFixPanel.tsx","FrictionValidationFixPanel.tsx","FrictionSafetyCopyFixPanel.tsx","FrictionFixHandoffPanel.tsx","FrictionFixSafetyStrip.tsx","FrictionFixEmptyState.tsx")){Assert-FileExists (Join-Path $componentDir $component)}
Assert-FileExists $routePath; Assert-FileExists $clientPath
$indexSource=Get-Content -Raw (Join-Path $domainDir "index.ts"); $domainSource=(Get-ChildItem $domainDir -File|%{Get-Content -Raw $_.FullName}) -join "`n"; $uiSource=(Get-ChildItem $componentDir -File|%{Get-Content -Raw $_.FullName}) -join "`n"; $routeSource=(Get-Content -Raw $routePath)+"`n"+(Get-Content -Raw $clientPath); $allSource=$domainSource+"`n"+$uiSource+"`n"+$routeSource
foreach($export in @("buildFrictionFinding","buildDefaultFrictionFindings","prioritizeFrictionFindings","buildFrictionCopyFix","buildFrictionLayoutFix","buildFrictionRouteFix","buildFrictionValidationFix","buildFrictionSafetyCopyFix","buildFrictionFixHandoff","buildFrictionFixSummary")){Assert-Contains $indexSource $export "index exports $export"}
foreach($render in @("TrialFrictionFixPassPanel renders","FrictionFindingPanel renders","FrictionPriorityPanel renders","FrictionCopyFixPanel renders","FrictionLayoutFixPanel renders","FrictionRouteFixPanel renders","FrictionValidationFixPanel renders","FrictionSafetyCopyFixPanel renders","FrictionFixHandoffPanel renders","FrictionFixSafetyStrip renders","FrictionFixEmptyState renders")){Assert-Contains $uiSource $render $render}
foreach($text in @("Fix trial friction","Copy friction fix plan","unclear next step","too many panels","wording too technical","validation unclear","apply blocked unclear","route handoff confusing","safety warning noisy","empty state unhelpful","result capture unclear","manual trial hard to follow","fix now items first","prefer small copy/layout/handoff fixes","no broad rewrites","no unsafe execution","no auto-apply","no auto-run","approval required","preserve latest-message authority","Focus Mode UX calm workflow layout markers","shell without duplicate route chip cloud","route hero title does not vertically wrap","no giant raw JSON above fold","advanced details are collapsed or visually secondary","buildFrictionFixStableKey")){Assert-Contains $allSource $text "marker $text"}
Assert-Contains $routeSource "TrialFrictionFixPassPanel" "route imports/renders main panel"
foreach($bad in @("appendEvent\s*\(","saveBrainGraph\s*\(","\.nodes\s*\.\s*push|\.edges\s*\.\s*push","apply-diff\s*\(","write-file\s*\(","run-command\s*\(","broker-execution\s*\(","https?://","fetch\s*\(","OPENAI_API_KEY","localStorage.setItem","process\.env\.","Math\.random","Date\.now","d3-force","[\u00c3\u00c2]")){Assert-NotMatches $allSource $bad "blocked marker absent $bad"}
Assert-Contains ((Get-Content -Raw "src\app\guarded-apply-mvp\page-client.tsx")+(Get-Content -Raw "src\app\validation-results\page-client.tsx")+(Get-Content -Raw "src\app\code-flow\manual-trial\page-client.tsx")) "/code-flow/friction-fixes" "integrations mention friction fixes"
Assert-CountExactly (Get-Content -Raw "scripts\smoke-codexforge-all.ps1") "smoke-codexforge-trial-friction-fix-pass.ps1" 1 "managed smoke suite includes phase exactly once"
Write-Host "[OK] CodexForge Trial Friction Fix Pass smoke passed."
