$ErrorActionPreference = 'Stop'
$scriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-boundary-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-intent-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-home-order-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-cockpit-order-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-jarvis-command-center-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-primary-workspace-navigation-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-video-workspace-polish-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-trading-workspace-polish-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-website-workspace-placeholder-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-avatar-workspace-placeholder-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-workflow-workspace-placeholder-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-audit-workspace-polish-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-safety-workspace-polish-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-next-action-rail-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-capability-grid-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-approval-summary-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-readiness-summary-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-blocked-action-simplification-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-placeholder-state-system-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-developer-diagnostics-secondary-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-command-palette-order-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-navigation-shell-order-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-mobile-responsive-polish-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-accessibility-guard-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-motion-safety-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-performance-budget-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-no-execution-guard-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-regression-coverage-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-checkpoint-alignment-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-operator-review-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-readiness-wiring.ps1')
& (Join-Path $scriptRoot 'smoke-codexforge-jarvis-unified-product-ia-completion.ps1')
Write-Host '[OK] CodexForge Jarvis Unified Product IA and God-Tier UX Polish Mega Batch smoke passed.'