param([string]$BaseUrl = "http://localhost:3000")
$ErrorActionPreference = "Stop"; $root = Split-Path -Parent $PSScriptRoot; Set-Location $root
function Assert-FileExists { param([string]$Path) if (-not (Test-Path $Path)) { throw "[FAIL] Missing file: $Path" } Write-Host "[PASS] file exists: $Path" }
function Assert-DirectoryExists { param([string]$Path) if (-not (Test-Path $Path -PathType Container)) { throw "[FAIL] Missing directory: $Path" } Write-Host "[PASS] directory exists: $Path" }
function Assert-Contains { param([AllowEmptyString()][string]$Haystack, [string]$Needle, [string]$Name) if (-not $Haystack.Contains($Needle)) { throw "[FAIL] Missing $Name`: $Needle" } Write-Host "[PASS] $Name" }
function Assert-NotMatches { param([AllowEmptyString()][string]$Haystack, [string]$Pattern, [string]$Name) if ($Haystack -match $Pattern) { throw "[FAIL] Unexpected $Name`: $Pattern" } Write-Host "[PASS] $Name" }
Write-Host "=== Keyframe Plan Builder smoke ==="
$domain = "src\lib\codexforge\keyframe-plan-builder"; $components = Join-Path $domain "components"; $route = "src\app\keyframes"
Assert-DirectoryExists $domain; Assert-DirectoryExists $components
foreach ($file in @("keyframe-plan-types.ts","keyframe-plan.ts","keyframe-entry.ts","keyframe-prompt.ts","keyframe-consistency-note.ts","keyframe-generation-readiness.ts","keyframe-handoff.ts","keyframe-plan-summary.ts","index.ts")) { Assert-FileExists (Join-Path $domain $file) }
foreach ($file in @("KeyframePlanBuilderPanel.tsx","KeyframePlanPanel.tsx","KeyframeEntryPanel.tsx","KeyframePromptPanel.tsx","KeyframeConsistencyNotePanel.tsx","KeyframeGenerationReadinessPanel.tsx","KeyframeHandoffPanel.tsx","KeyframePlanSummaryPanel.tsx","KeyframePlanSafetyStrip.tsx","KeyframePlanEmptyState.tsx","index.ts")) { Assert-FileExists (Join-Path $components $file) }
Assert-FileExists "$route\page.tsx"; Assert-FileExists "$route\page-client.tsx"
$source = (Get-ChildItem -Recurse -File $domain, $route | ForEach-Object { Get-Content -Raw $_.FullName }) -join "`n"; $routeSource = Get-Content -Raw "$route\page-client.tsx"; $commands = Get-Content -Raw "src\lib\codexforge\command-palette\command-registry.ts"; $nav = Get-Content -Raw "src\lib\codexforge\navigation-shell\navigation-route-registry.ts"; $allSmoke = Get-Content -Raw "scripts\smoke-codexforge-all.ps1"
foreach ($export in @("buildKeyframePlan","buildDefaultKeyframePlan","buildKeyframeEntry","buildDefaultKeyframeEntries","buildKeyframePrompt","buildKeyframeConsistencyNote","buildKeyframeGenerationReadiness","buildKeyframeHandoff","buildKeyframePlanSummary","summarizeKeyframePlan")) { Assert-Contains $source $export "expected export $export" }
foreach ($needle in @("Keyframe plan","Plan the still frames that guide your future video draft.","Plan keyframes","keyframe id","shot id","order","frame purpose","visual prompt","style reference note","subject consistency note","camera note","readiness status","local generation suitability","next action","needs-prompt","ready-for-review","ready-for-local-image-generation-later","blocked","not-needed","Copy keyframe prompts allowed","Copy video draft handoff allowed")) { Assert-Contains $source $needle "plain English/source includes $needle" }
Assert-Contains $routeSource "KeyframePlanBuilderPanel" "route imports/renders main panel"; Assert-Contains $routeSource "CodexForgeAppShell" "route uses home-grade/unified shell marker"; Assert-Contains $commands "Go to Keyframes" "command palette includes Go to Keyframes"; Assert-Contains $nav "/keyframes" "navigation includes /keyframes"
if (([regex]::Matches($allSmoke, "smoke-codexforge-keyframe-plan-builder\.ps1")).Count -ne 1) { throw "[FAIL] managed smoke suite includes phase exactly once" }
foreach ($required in @("plain English","no duplicate route chip cloud","hero title does not vertically wrap","no giant raw JSON above fold","advanced details collapsed/secondary","no unsafe execution buttons","no real video generation","no image generation","no ComfyUI workflow run","no prompt payload sent to providers","no cloud provider API calls","no password storage","no API key localStorage","no raw secret display","no process.env value printed in UI","no hardcoded API keys","no direct appendEvent call from UI","no direct saveBrainGraph call from UI","no direct graph mutation from UI","no memory auto-promotion","no direct apply-diff call from UI","no direct write-file call from UI","no direct run-command call from UI","no broker-execution call except blocked-policy text","no Math.random","no Date.now","no d3-force","no mojibake","no obvious duplicate React key patterns")) { Assert-Contains $source $required "UI marker $required" }
$deterministicSource = $source -replace "no Math.random", "" -replace "no Date.now", "" -replace "no d3-force", "" -replace "no broker-execution call except blocked-policy text", ""; $networkPattern = "fetch\s*\(|XMLHttpRequest|axios|Invoke-" + "WebRequest|Invoke-" + "RestMethod"
Assert-NotMatches $deterministicSource $networkPattern "no external network dependency"; Assert-NotMatches $deterministicSource "sk-[A-Za-z0-9]{20,}|AIza[0-9A-Za-z_-]{20,}" "no hardcoded API keys"; Assert-NotMatches $deterministicSource "localStorage\.setItem|password\s*[:=]|process\.env\.[A-Za-z0-9_]+|appendEvent\s*\(|saveBrainGraph\s*\(|applyDiff\s*\(|writeFile\s*\(|runCommand\s*\(|broker-execution\s*\(" "no unsafe storage, execution, graph mutation, raw env print"; Assert-NotMatches $deterministicSource "Math\.random|Date\.now|d3-force" "deterministic ids/layout"; Assert-NotMatches $source "$([char]0x00C3)|$([char]0x00C2)|$([char]0xFFFD)" "no mojibake"
Write-Host "[OK] Keyframe Plan Builder smoke passed."
