param([string]$BaseUrl = "http://localhost:3000")
$ErrorActionPreference = "Stop"; $root = Split-Path -Parent $PSScriptRoot; Set-Location $root
function Assert-FileExists { param([string]$Path) if (-not (Test-Path $Path)) { throw "[FAIL] Missing file: $Path" } Write-Host "[PASS] file exists: $Path" }
function Assert-DirectoryExists { param([string]$Path) if (-not (Test-Path $Path -PathType Container)) { throw "[FAIL] Missing directory: $Path" } Write-Host "[PASS] directory exists: $Path" }
function Assert-Contains { param([AllowEmptyString()][string]$Haystack,[string]$Needle,[string]$Name) if (-not $Haystack.Contains($Needle)) { throw "[FAIL] Missing $Name`: $Needle" } Write-Host "[PASS] $Name" }
function Assert-NotMatches { param([AllowEmptyString()][string]$Haystack,[string]$Pattern,[string]$Name) if ($Haystack -match $Pattern) { throw "[FAIL] Unexpected $Name`: $Pattern" } Write-Host "[PASS] $Name" }
function Assert-CountExactly { param([AllowEmptyString()][string]$Haystack,[string]$Needle,[int]$Expected,[string]$Name) $count=([regex]::Matches($Haystack,[regex]::Escape($Needle))).Count; if($count -ne $Expected){throw "[FAIL] $Name expected $Expected found $count"} Write-Host "[PASS] $Name" }
Write-Host "=== CodexForge Validation Capture Hardening smoke ==="
$domainDir="src\lib\codexforge\validation-capture-hardening"; $componentDir=Join-Path $domainDir "components"; $routePath="src\app\validation-results\hardening\page.tsx"; $clientPath="src\app\validation-results\hardening\page-client.tsx"
Assert-DirectoryExists $domainDir; Assert-DirectoryExists $componentDir
foreach($module in @("validation-capture-hardening-types.ts","validation-paste-guide.ts","validation-output-summarizer.ts","validation-failure-classifier.ts","validation-next-route.ts","validation-handoff-hardening.ts","validation-copy-guidance.ts","validation-capture-hardening-summary.ts")){Assert-FileExists (Join-Path $domainDir $module)}
foreach($component in @("ValidationCaptureHardeningPanel.tsx","ValidationPasteGuidePanel.tsx","ValidationOutputSummarizerPanel.tsx","ValidationFailureClassifierPanel.tsx","ValidationNextRoutePanel.tsx","ValidationHandoffHardeningPanel.tsx","ValidationCopyGuidancePanel.tsx","ValidationCaptureHardeningSafetyStrip.tsx","ValidationCaptureHardeningEmptyState.tsx")){Assert-FileExists (Join-Path $componentDir $component)}
Assert-FileExists $routePath; Assert-FileExists $clientPath
$indexSource=Get-Content -Raw (Join-Path $domainDir "index.ts"); $domainSource=(Get-ChildItem $domainDir -File|%{Get-Content -Raw $_.FullName}) -join "`n"; $uiSource=(Get-ChildItem $componentDir -File|%{Get-Content -Raw $_.FullName}) -join "`n"; $routeSource=(Get-Content -Raw $routePath)+"`n"+(Get-Content -Raw $clientPath); $allSource=$domainSource+"`n"+$uiSource+"`n"+$routeSource
foreach($export in @("buildValidationPasteGuide","buildValidationOutputSummarizer","summarizeValidationOutputSafely","buildValidationFailureClassifier","classifyValidationFailure","selectValidationNextRoute","buildValidationHandoffHardening","buildValidationCopyGuidance","buildValidationCaptureHardeningSummary")){Assert-Contains $indexSource $export "index exports $export"}
Assert-Contains $routeSource "ValidationCaptureHardeningPanel" "route imports/renders main panel"
foreach($text in @("Paste validation output to review it","copy commands only","passed / failed / unknown","failures route to /closed-loop","pass routes to /workflow-results and /run-history","no fake pass","no auto-run","preserve latest-message authority","Plain English","Focus Mode UX calm workflow layout markers","shell without duplicate route chip cloud","route hero title does not vertically wrap","no giant raw JSON above fold","advanced details are collapsed or visually secondary","no unsafe execution buttons","no direct appendEvent call from UI","no direct saveBrainGraph call from UI","no direct graph mutation from UI","no memory auto-promotion","no direct apply-diff call from UI","no direct write-file call from UI","no direct run-command call from UI","no broker-execution call","no external network dependency","no vector database dependency","no OpenAI/API-key dependency","no hardcoded API keys","no localStorage API key storage","buildValidationCaptureHardeningStableKey","Harden validation capture","Review validation handoff")){Assert-Contains $allSource $text "marker $text"}
foreach($bad in @("appendEvent\s*\(","saveBrainGraph\s*\(","\.nodes\s*\.\s*push|\.edges\s*\.\s*push","apply-diff\s*\(","write-file\s*\(","run-command\s*\(","broker-execution\s*\(","https?://","fetch\s*\(","OPENAI_API_KEY","localStorage.setItem","process\.env\.","Math\.random","Date\.now","d3-force","[ÃÂ]")){Assert-NotMatches $allSource $bad "blocked marker absent $bad"}
Assert-CountExactly (Get-Content -Raw "scripts\smoke-codexforge-all.ps1") "smoke-codexforge-validation-capture-hardening.ps1" 1 "managed smoke suite includes phase exactly once"
Write-Host "[OK] CodexForge Validation Capture Hardening smoke passed."
