param([string]$BaseUrl = "http://localhost:3000")
$ErrorActionPreference = "Stop"; $root = Split-Path -Parent $PSScriptRoot; Set-Location $root
function Assert-FileExists { param([string]$Path) if (-not (Test-Path $Path)) { throw "[FAIL] Missing file: $Path" } Write-Host "[PASS] file exists: $Path" }
function Assert-DirectoryExists { param([string]$Path) if (-not (Test-Path $Path -PathType Container)) { throw "[FAIL] Missing directory: $Path" } Write-Host "[PASS] directory exists: $Path" }
function Assert-Contains { param([AllowEmptyString()][string]$Haystack,[string]$Needle,[string]$Name) if (-not $Haystack.Contains($Needle)) { throw "[FAIL] Missing $Name`: $Needle" } Write-Host "[PASS] $Name" }
function Assert-NotMatches { param([AllowEmptyString()][string]$Haystack,[string]$Pattern,[string]$Name) if ($Haystack -match $Pattern) { throw "[FAIL] Unexpected $Name`: $Pattern" } Write-Host "[PASS] $Name" }
function Assert-CountExactly { param([AllowEmptyString()][string]$Haystack,[string]$Needle,[int]$Expected,[string]$Name) $count=([regex]::Matches($Haystack,[regex]::Escape($Needle))).Count; if($count -ne $Expected){throw "[FAIL] $Name expected $Expected found $count"} Write-Host "[PASS] $Name" }
Write-Host "=== CodexForge MVP Polish Demo Final smoke ==="
$domainDir="src\lib\codexforge\mvp-polish-demo-final"; $componentDir=Join-Path $domainDir "components"; $routePath="src\app\code-flow\final-polish\page.tsx"; $clientPath="src\app\code-flow\final-polish\page-client.tsx"
Assert-DirectoryExists $domainDir; Assert-DirectoryExists $componentDir
foreach($module in @("mvp-polish-types.ts","polish-check.ts","demo-final-script.ts","demo-final-screen.ts","polish-copy-upgrade.ts","polish-navigation-upgrade.ts","polish-readiness-summary.ts","polish-final-handoff.ts","mvp-polish-summary.ts")){Assert-FileExists (Join-Path $domainDir $module)}
foreach($component in @("MvpPolishDemoFinalPanel.tsx","PolishCheckPanel.tsx","DemoFinalScriptPanel.tsx","DemoFinalScreenPanel.tsx","PolishCopyUpgradePanel.tsx","PolishNavigationUpgradePanel.tsx","PolishReadinessSummaryPanel.tsx","PolishFinalHandoffPanel.tsx","PolishSafetyStrip.tsx","PolishEmptyState.tsx")){Assert-FileExists (Join-Path $componentDir $component)}
Assert-FileExists $routePath; Assert-FileExists $clientPath
$indexSource=Get-Content -Raw (Join-Path $domainDir "index.ts"); $domainSource=(Get-ChildItem $domainDir -File|%{Get-Content -Raw $_.FullName}) -join "`n"; $uiSource=(Get-ChildItem $componentDir -File|%{Get-Content -Raw $_.FullName}) -join "`n"; $routeSource=(Get-Content -Raw $routePath)+"`n"+(Get-Content -Raw $clientPath); $allSource=$domainSource+"`n"+$uiSource+"`n"+$routeSource
foreach($export in @("buildPolishCheck","buildDemoFinalScript","buildDemoFinalScreen","buildPolishCopyUpgrade","buildPolishNavigationUpgrade","buildPolishReadinessSummary","buildPolishFinalHandoff","buildMvpPolishSummary")){Assert-Contains $indexSource $export "index exports $export"}
Assert-Contains $routeSource "MvpPolishDemoFinalPanel" "route imports/renders main panel"
foreach($text in @("no duplicate menus","no giant route chip cloud","no cramped top sections","no repeated safety essays","one primary CTA","clear next step","premium layout","no auto-apply","no auto-run","approval required","preserve latest-message authority","Plain English","Focus Mode UX calm workflow layout markers","shell without duplicate route chip cloud","route hero title does not vertically wrap","no giant raw JSON above fold","advanced details are collapsed or visually secondary","no unsafe execution buttons","no direct appendEvent call from UI","no direct saveBrainGraph call from UI","no direct graph mutation from UI","no memory auto-promotion","no direct apply-diff call from UI","no direct write-file call from UI","no direct run-command call from UI","no broker-execution call","no external network dependency","no vector database dependency","no OpenAI/API-key dependency","no hardcoded API keys","no localStorage API key storage","buildMvpPolishStableKey","Final polish for the coding MVP demo","Review final demo")){Assert-Contains $allSource $text "marker $text"}
foreach($bad in @("appendEvent\s*\(","saveBrainGraph\s*\(","\.nodes\s*\.\s*push|\.edges\s*\.\s*push","apply-diff\s*\(","write-file\s*\(","run-command\s*\(","broker-execution\s*\(","https?://","fetch\s*\(","OPENAI_API_KEY","localStorage.setItem","process\.env\.","Math\.random","Date\.now","d3-force","[ÃÂ]")){Assert-NotMatches $allSource $bad "blocked marker absent $bad"}
Assert-CountExactly (Get-Content -Raw "scripts\smoke-codexforge-all.ps1") "smoke-codexforge-mvp-polish-demo-final.ps1" 1 "managed smoke suite includes phase exactly once"
Write-Host "[OK] CodexForge MVP Polish Demo Final smoke passed."
