param([string]$BaseUrl = "http://localhost:3000")
$ErrorActionPreference = "Stop"; $root = Split-Path -Parent $PSScriptRoot; Set-Location $root
function Assert-FileExists { param([string]$Path) if (-not (Test-Path $Path)) { throw "[FAIL] Missing file: $Path" } Write-Host "[PASS] file exists: $Path" }
function Assert-DirectoryExists { param([string]$Path) if (-not (Test-Path $Path -PathType Container)) { throw "[FAIL] Missing directory: $Path" } Write-Host "[PASS] directory exists: $Path" }
function Assert-Contains { param([AllowEmptyString()][string]$Haystack,[string]$Needle,[string]$Name) if (-not $Haystack.Contains($Needle)) { throw "[FAIL] Missing $Name`: $Needle" } Write-Host "[PASS] $Name" }
function Assert-NotMatches { param([AllowEmptyString()][string]$Haystack,[string]$Pattern,[string]$Name) if ($Haystack -match $Pattern) { throw "[FAIL] Unexpected $Name`: $Pattern" } Write-Host "[PASS] $Name" }
function Assert-CountExactly { param([AllowEmptyString()][string]$Haystack,[string]$Needle,[int]$Expected,[string]$Name) $count=([regex]::Matches($Haystack,[regex]::Escape($Needle))).Count; if($count -ne $Expected){throw "[FAIL] $Name expected $Expected found $count"} Write-Host "[PASS] $Name" }
Write-Host "=== CodexForge Novice First Task smoke ==="
$domainDir="src\lib\codexforge\novice-first-task"; $componentDir=Join-Path $domainDir "components"; $routePath="src\app\first-task\page.tsx"; $clientPath="src\app\first-task\page-client.tsx"
Assert-DirectoryExists $domainDir; Assert-DirectoryExists $componentDir
foreach($module in @("novice-first-task-types.ts","first-task-scenario.ts","first-task-step.ts","first-task-safe-file.ts","first-task-preview-guide.ts","first-task-apply-review-guide.ts","first-task-validation-guide.ts","first-task-result-guide.ts","first-task-handoff.ts","novice-first-task-summary.ts","index.ts")){Assert-FileExists (Join-Path $domainDir $module)}
foreach($component in @("NoviceFirstTaskPanel.tsx","FirstTaskScenarioPanel.tsx","FirstTaskStepPanel.tsx","FirstTaskSafeFilePanel.tsx","FirstTaskPreviewGuidePanel.tsx","FirstTaskApplyReviewGuidePanel.tsx","FirstTaskValidationGuidePanel.tsx","FirstTaskResultGuidePanel.tsx","FirstTaskHandoffPanel.tsx","NoviceFirstTaskSafetyStrip.tsx","NoviceFirstTaskEmptyState.tsx")){Assert-FileExists (Join-Path $componentDir $component)}
Assert-FileExists $routePath; Assert-FileExists $clientPath
$indexSource=Get-Content -Raw (Join-Path $domainDir "index.ts"); $domainSource=(Get-ChildItem $domainDir -File|%{Get-Content -Raw $_.FullName}) -join "`n"; $uiSource=(Get-ChildItem $componentDir -File|%{Get-Content -Raw $_.FullName}) -join "`n"; $routeSource=(Get-Content -Raw $routePath)+"`n"+(Get-Content -Raw $clientPath); $allSource=$domainSource+"`n"+$uiSource+"`n"+$routeSource
foreach($export in @("buildFirstTaskScenario","buildDefaultFirstTaskScenario","buildFirstTaskStep","buildDefaultFirstTaskSteps","buildFirstTaskSafeFile","buildFirstTaskPreviewGuide","buildFirstTaskApplyReviewGuide","buildFirstTaskValidationGuide","buildFirstTaskResultGuide","buildFirstTaskHandoff","buildNoviceFirstTaskSummary")){Assert-Contains $indexSource $export "index exports $export"}
Assert-Contains $routeSource "NoviceFirstTaskPanel" "route imports/renders main panel"
foreach($text in @("plain English","no auto-apply","no auto-run","approval required","preserve latest-message authority","route uses home-grade/unified shell marker","no duplicate route chip cloud","hero title does not vertically wrap","no giant raw JSON above fold","advanced details collapsed/secondary","no unsafe execution buttons","no direct appendEvent call from UI","no direct saveBrainGraph call from UI","no direct graph mutation from UI","no memory auto-promotion","no direct apply-diff call from UI","no direct write-file call from UI","no direct run-command call from UI","no broker-execution call","no external network dependency","no vector database dependency","no OpenAI/API-key dependency","no hardcoded API keys","no localStorage API key storage","Start first task")){Assert-Contains $allSource $text "marker $text"}
foreach($bad in @("appendEvent\s*\(","saveBrainGraph\s*\(","\.nodes\s*\.\s*push|\.edges\s*\.\s*push","apply-diff\s*\(","write-file\s*\(","run-command\s*\(","broker-execution\s*\(","https?://","fetch\s*\(","OPENAI_API_KEY","localStorage.setItem","process\.env\.","Math\.random","Date\.now","d3-force",([char]0xFFFD))){Assert-NotMatches $allSource $bad "blocked marker absent $bad"}
Assert-NotMatches $uiSource "key=\{[^}]*index" "obvious duplicate React key patterns"
Assert-CountExactly (Get-Content -Raw "scripts\smoke-codexforge-all.ps1") "smoke-codexforge-novice-first-task.ps1" 1 "managed smoke suite includes phase exactly once"
Write-Host "[OK] CodexForge Novice First Task smoke passed."
