param([string]$BaseUrl = "http://localhost:3000")
$ErrorActionPreference = "Stop"; $root = Split-Path -Parent $PSScriptRoot; Set-Location $root
function Assert-FileExists { param([string]$Path) if (-not (Test-Path $Path)) { throw "[FAIL] Missing file: $Path" } Write-Host "[PASS] file exists: $Path" }
function Assert-DirectoryExists { param([string]$Path) if (-not (Test-Path $Path -PathType Container)) { throw "[FAIL] Missing directory: $Path" } Write-Host "[PASS] directory exists: $Path" }
function Assert-Contains { param([AllowEmptyString()][string]$Haystack,[string]$Needle,[string]$Name) if (-not $Haystack.Contains($Needle)) { throw "[FAIL] Missing $Name`: $Needle" } Write-Host "[PASS] $Name" }
function Assert-NotMatches { param([AllowEmptyString()][string]$Haystack,[string]$Pattern,[string]$Name) if ($Haystack -match $Pattern) { throw "[FAIL] Unexpected $Name`: $Pattern" } Write-Host "[PASS] $Name" }
function Assert-CountExactly { param([AllowEmptyString()][string]$Haystack,[string]$Needle,[int]$Expected,[string]$Name) $count=([regex]::Matches($Haystack,[regex]::Escape($Needle))).Count; if($count -ne $Expected){throw "[FAIL] $Name expected $Expected found $count"} Write-Host "[PASS] $Name" }
Write-Host "=== CodexForge Apply Evidence Capture MVP smoke ==="
$domainDir="src\lib\codexforge\apply-evidence-capture-mvp"; $componentDir=Join-Path $domainDir "components"; $routePath="src\app\apply-evidence\page.tsx"; $clientPath="src\app\apply-evidence\page-client.tsx"
Assert-DirectoryExists $domainDir; Assert-DirectoryExists $componentDir
foreach($module in @("apply-evidence-capture-types.ts","apply-evidence-record.ts","apply-evidence-input.ts","apply-evidence-policy-decision.ts","apply-evidence-approval-record.ts","apply-evidence-diff-record.ts","apply-evidence-boundary-record.ts","apply-evidence-rollback-record.ts","apply-evidence-validation-handoff.ts","apply-evidence-export.ts","apply-evidence-summary.ts","index.ts")){Assert-FileExists (Join-Path $domainDir $module)}
foreach($component in @("ApplyEvidenceCapturePanel.tsx","ApplyEvidenceRecordPanel.tsx","ApplyEvidenceInputPanel.tsx","ApplyEvidencePolicyDecisionPanel.tsx","ApplyEvidenceApprovalRecordPanel.tsx","ApplyEvidenceDiffRecordPanel.tsx","ApplyEvidenceBoundaryRecordPanel.tsx","ApplyEvidenceRollbackRecordPanel.tsx","ApplyEvidenceValidationHandoffPanel.tsx","ApplyEvidenceExportPanel.tsx","ApplyEvidenceSafetyStrip.tsx","ApplyEvidenceEmptyState.tsx")){Assert-FileExists (Join-Path $componentDir $component)}
Assert-FileExists $routePath; Assert-FileExists $clientPath
$indexSource=Get-Content -Raw (Join-Path $domainDir "index.ts"); $domainSource=(Get-ChildItem $domainDir -File|%{Get-Content -Raw $_.FullName}) -join "`n"; $uiSource=(Get-ChildItem $componentDir -File|%{Get-Content -Raw $_.FullName}) -join "`n"; $routeSource=(Get-Content -Raw $routePath)+"`n"+(Get-Content -Raw $clientPath); $allSource=$domainSource+"`n"+$uiSource+"`n"+$routeSource
foreach($export in @("buildApplyEvidenceRecord","validateApplyEvidenceRecord","buildApplyEvidenceInput","buildApplyEvidencePolicyDecision","buildApplyEvidenceApprovalRecord","buildApplyEvidenceDiffRecord","buildApplyEvidenceBoundaryRecord","buildApplyEvidenceRollbackRecord","buildApplyEvidenceValidationHandoff","buildApplyEvidenceExport","buildApplyEvidenceSummary")){Assert-Contains $indexSource $export "index exports $export"}
foreach($render in @("ApplyEvidenceCapturePanel renders","ApplyEvidenceRecordPanel renders","ApplyEvidenceInputPanel renders","ApplyEvidencePolicyDecisionPanel renders","ApplyEvidenceApprovalRecordPanel renders","ApplyEvidenceDiffRecordPanel renders","ApplyEvidenceBoundaryRecordPanel renders","ApplyEvidenceRollbackRecordPanel renders","ApplyEvidenceValidationHandoffPanel renders","ApplyEvidenceExportPanel renders","ApplyEvidenceSafetyStrip renders","ApplyEvidenceEmptyState renders")){Assert-Contains $uiSource $render $render}
foreach($text in @("Capture apply evidence","Copy evidence pack","selected file","approval status","policy decision","boundary status","rollback guidance","validation handoff","operator note","no auto-apply","no auto-run","no auto-persistence","no Brain mutation","no memory auto-promotion","no raw huge diff by default","no secrets","cap excerpts","preserve latest-message authority","Focus Mode UX calm workflow layout markers","shell without duplicate route chip cloud","route hero title does not vertically wrap","no giant raw JSON above fold","advanced details are collapsed or visually secondary","no unsafe execution buttons","buildApplyEvidenceStableKey")){Assert-Contains $allSource $text "marker $text"}
Assert-Contains $routeSource "ApplyEvidenceCapturePanel" "route imports/renders main panel"
foreach($bad in @("appendEvent\s*\(","saveBrainGraph\s*\(","\.nodes\s*\.\s*push|\.edges\s*\.\s*push","apply-diff\s*\(","write-file\s*\(","run-command\s*\(","broker-execution\s*\(","https?://","fetch\s*\(","OPENAI_API_KEY","localStorage.setItem","process\.env\.","Math\.random","Date\.now","d3-force","[\u00c3\u00c2]")){Assert-NotMatches $allSource $bad "blocked marker absent $bad"}
Assert-Contains ((Get-Content -Raw "src\app\guarded-apply-mvp\page-client.tsx")+(Get-Content -Raw "src\app\workflow-results\page-client.tsx")+(Get-Content -Raw "src\app\run-history\page-client.tsx")) "/apply-evidence" "integrations mention apply evidence"
Assert-CountExactly (Get-Content -Raw "scripts\smoke-codexforge-all.ps1") "smoke-codexforge-apply-evidence-capture-mvp.ps1" 1 "managed smoke suite includes phase exactly once"
Write-Host "[OK] CodexForge Apply Evidence Capture MVP smoke passed."
