param([string]$BaseUrl = "http://localhost:3000")
$ErrorActionPreference = "Stop"; $root = Split-Path -Parent $PSScriptRoot; Set-Location $root
function Assert-FileExists { param([string]$Path) if (-not (Test-Path $Path)) { throw "[FAIL] Missing file: $Path" } Write-Host "[PASS] file exists: $Path" }
function Assert-DirectoryExists { param([string]$Path) if (-not (Test-Path $Path -PathType Container)) { throw "[FAIL] Missing directory: $Path" } Write-Host "[PASS] directory exists: $Path" }
function Assert-Contains { param([AllowEmptyString()][string]$Haystack,[string]$Needle,[string]$Name) if (-not $Haystack.Contains($Needle)) { throw "[FAIL] Missing $Name`: $Needle" } Write-Host "[PASS] $Name" }
function Assert-NotMatches { param([AllowEmptyString()][string]$Haystack,[string]$Pattern,[string]$Name) if ($Haystack -match $Pattern) { throw "[FAIL] Unexpected $Name`: $Pattern" } Write-Host "[PASS] $Name" }
function Assert-CountExactly { param([AllowEmptyString()][string]$Haystack,[string]$Needle,[int]$Expected,[string]$Name) $count=([regex]::Matches($Haystack,[regex]::Escape($Needle))).Count; if($count -ne $Expected){throw "[FAIL] $Name expected $Expected found $count"} Write-Host "[PASS] $Name" }
Write-Host "=== CodexForge Assisted MVP Quality Sweep smoke ==="
$domainDir="src\lib\codexforge\assisted-mvp-quality-sweep"; $componentDir=Join-Path $domainDir "components"; $routePath="src\app\assisted-quality\page.tsx"; $clientPath="src\app\assisted-quality\page-client.tsx"
Assert-DirectoryExists $domainDir; Assert-DirectoryExists $componentDir
foreach($module in @("assisted-quality-types.ts","assisted-quality-check.ts","assisted-route-quality.ts","assisted-copy-quality.ts","assisted-safety-quality.ts","assisted-empty-state-quality.ts","assisted-nav-quality.ts","assisted-quality-handoff.ts","assisted-mvp-quality-summary.ts","index.ts")){Assert-FileExists (Join-Path $domainDir $module)}
foreach($component in @("AssistedMvpQualitySweepPanel.tsx","AssistedQualityCheckPanel.tsx","AssistedRouteQualityPanel.tsx","AssistedCopyQualityPanel.tsx","AssistedSafetyQualityPanel.tsx","AssistedEmptyStateQualityPanel.tsx","AssistedNavQualityPanel.tsx","AssistedQualityHandoffPanel.tsx","AssistedMvpQualitySafetyStrip.tsx","AssistedMvpQualityEmptyState.tsx")){Assert-FileExists (Join-Path $componentDir $component)}
Assert-FileExists $routePath; Assert-FileExists $clientPath
$indexSource=Get-Content -Raw (Join-Path $domainDir "index.ts"); $domainSource=(Get-ChildItem $domainDir -File|%{Get-Content -Raw $_.FullName}) -join "`n"; $uiSource=(Get-ChildItem $componentDir -File|%{Get-Content -Raw $_.FullName}) -join "`n"; $routeSource=(Get-Content -Raw $routePath)+"`n"+(Get-Content -Raw $clientPath); $allSource=$domainSource+"`n"+$uiSource+"`n"+$routeSource
foreach($export in @("buildAssistedQualityCheck","buildAssistedRouteQuality","buildAssistedCopyQuality","buildAssistedSafetyQuality","buildAssistedEmptyStateQuality","buildAssistedNavQuality","buildAssistedQualityHandoff","buildAssistedMvpQualitySummary")){Assert-Contains $indexSource $export "index exports $export"}
Assert-Contains $routeSource "AssistedMvpQualitySweepPanel" "route imports/renders main panel"
foreach($text in @("plain English","no auto-apply","no auto-run","approval required","preserve latest-message authority","route uses home-grade/unified shell marker","no duplicate route chip cloud","hero title does not vertically wrap","no giant raw JSON above fold","advanced details collapsed/secondary","no unsafe execution buttons","no direct appendEvent call from UI","no direct saveBrainGraph call from UI","no direct graph mutation from UI","no memory auto-promotion","no direct apply-diff call from UI","no direct write-file call from UI","no direct run-command call from UI","no broker-execution call","no external network dependency","no vector database dependency","no OpenAI/API-key dependency","no hardcoded API keys","no localStorage API key storage","Readiness result","Copy quality sweep")){Assert-Contains $allSource $text "marker $text"}
foreach($bad in @("appendEvent\s*\(","saveBrainGraph\s*\(","\.nodes\s*\.\s*push|\.edges\s*\.\s*push","apply-diff\s*\(","write-file\s*\(","run-command\s*\(","broker-execution\s*\(","https?://","fetch\s*\(","OPENAI_API_KEY","localStorage.setItem","process\.env\.","Math\.random","Date\.now","d3-force",([char]0xFFFD))){Assert-NotMatches $allSource $bad "blocked marker absent $bad"}
Assert-NotMatches $uiSource "key=\{[^}]*index" "obvious duplicate React key patterns"
Assert-CountExactly (Get-Content -Raw "scripts\smoke-codexforge-all.ps1") "smoke-codexforge-assisted-mvp-quality-sweep.ps1" 1 "managed smoke suite includes phase exactly once"
Write-Host "[OK] CodexForge Assisted MVP Quality Sweep smoke passed."
