param([string]$BaseUrl = "http://localhost:3000")
$ErrorActionPreference = "Stop"; $root = Split-Path -Parent $PSScriptRoot; Set-Location $root
function Assert-FileExists { param([string]$Path) if (-not (Test-Path $Path)) { throw "[FAIL] Missing file: $Path" } Write-Host "[PASS] file exists: $Path" }
function Assert-DirectoryExists { param([string]$Path) if (-not (Test-Path $Path -PathType Container)) { throw "[FAIL] Missing directory: $Path" } Write-Host "[PASS] directory exists: $Path" }
function Assert-Contains { param([AllowEmptyString()][string]$Haystack,[string]$Needle,[string]$Name) if (-not $Haystack.Contains($Needle)) { throw "[FAIL] Missing $Name`: $Needle" } Write-Host "[PASS] $Name" }
function Assert-NotMatches { param([AllowEmptyString()][string]$Haystack,[string]$Pattern,[string]$Name) if ($Haystack -match $Pattern) { throw "[FAIL] Unexpected $Name`: $Pattern" } Write-Host "[PASS] $Name" }
function Assert-CountExactly { param([AllowEmptyString()][string]$Haystack,[string]$Needle,[int]$Expected,[string]$Name) $count=([regex]::Matches($Haystack,[regex]::Escape($Needle))).Count; if($count -ne $Expected){throw "[FAIL] $Name expected $Expected found $count"} Write-Host "[PASS] $Name" }
Write-Host "=== CodexForge Coding Flow Live Run MVP smoke ==="
$domainDir="src\lib\codexforge\coding-flow-live-run-mvp"; $componentDir=Join-Path $domainDir "components"; $routePath="src\app\code-flow\live-run\page.tsx"; $clientPath="src\app\code-flow\live-run\page-client.tsx"
Assert-DirectoryExists $domainDir; Assert-DirectoryExists $componentDir
foreach($module in @("coding-flow-live-run-types.ts","live-run-input.ts","live-run-step-state.ts","live-run-file-selection.ts","live-run-patch-preview.ts","live-run-apply-request.ts","live-run-validation.ts","live-run-result.ts","live-run-handoff.ts","live-run-summary.ts","index.ts")){Assert-FileExists (Join-Path $domainDir $module)}
foreach($component in @("CodingFlowLiveRunPanel.tsx","LiveRunInputPanel.tsx","LiveRunStepStatePanel.tsx","LiveRunFileSelectionPanel.tsx","LiveRunPatchPreviewPanel.tsx","LiveRunApplyRequestPanel.tsx","LiveRunValidationPanel.tsx","LiveRunResultPanel.tsx","LiveRunHandoffPanel.tsx","LiveRunSafetyStrip.tsx","LiveRunEmptyState.tsx")){Assert-FileExists (Join-Path $componentDir $component)}
Assert-FileExists $routePath; Assert-FileExists $clientPath
$indexSource=Get-Content -Raw (Join-Path $domainDir "index.ts"); $domainSource=(Get-ChildItem $domainDir -File|%{Get-Content -Raw $_.FullName}) -join "`n"; $uiSource=(Get-ChildItem $componentDir -File|%{Get-Content -Raw $_.FullName}) -join "`n"; $routeSource=(Get-Content -Raw $routePath)+"`n"+(Get-Content -Raw $clientPath); $allSource=$domainSource+"`n"+$uiSource+"`n"+$routeSource
foreach($export in @("buildLiveRunInput","validateLiveRunInput","buildLiveRunStepState","updateLiveRunStepState","buildLiveRunFileSelection","buildLiveRunPatchPreview","buildLiveRunApplyRequest","buildLiveRunValidation","buildLiveRunResult","buildLiveRunHandoff","buildLiveRunSummary")){Assert-Contains $indexSource $export "index exports $export"}
foreach($render in @("CodingFlowLiveRunPanel renders","LiveRunInputPanel renders","LiveRunStepStatePanel renders","LiveRunFileSelectionPanel renders","LiveRunPatchPreviewPanel renders","LiveRunApplyRequestPanel renders","LiveRunValidationPanel renders","LiveRunResultPanel renders","LiveRunHandoffPanel renders","LiveRunSafetyStrip renders","LiveRunEmptyState renders")){Assert-Contains $uiSource $render $render}
foreach($text in @("Run the coding flow","Follow one safe path from file to validation result.","Start live run","Pick file","Describe change","Preview patch","Review apply request","Capture apply evidence","Prepare validation","Capture validation result","Review workflow result","Send to run history","If failed route to closed-loop","one primary action at a time","Progress visible","advanced details are collapsed or visually secondary","no auto-apply","no auto-run","no hidden persistence","no Brain mutation","preserve latest-message authority","Focus Mode UX calm workflow layout markers","shell without duplicate route chip cloud","route hero title does not vertically wrap","no giant raw JSON above fold","no unsafe execution buttons","buildLiveRunStableKey")){Assert-Contains $allSource $text "marker $text"}
Assert-Contains $routeSource "CodingFlowLiveRunPanel" "route imports/renders main panel"
foreach($bad in @("appendEvent\s*\(","saveBrainGraph\s*\(","\.nodes\s*\.\s*push|\.edges\s*\.\s*push","apply-diff\s*\(","write-file\s*\(","run-command\s*\(","broker-execution\s*\(","https?://","fetch\s*\(","OPENAI_API_KEY","localStorage.setItem","process\.env\.","Math\.random","Date\.now","d3-force","[\u00c3\u00c2]")){Assert-NotMatches $allSource $bad "blocked marker absent $bad"}
Assert-Contains ((Get-Content -Raw "src\app\start\page-client.tsx")+(Get-Content -Raw "src\app\code-flow\page-client.tsx")+(Get-Content -Raw "src\app\code-flow\trial\page-client.tsx")+(Get-Content -Raw "src\app\workflow-results\page-client.tsx")+(Get-Content -Raw "src\app\run-history\page-client.tsx")) "/code-flow/live-run" "integrations mention live run"
Assert-CountExactly (Get-Content -Raw "scripts\smoke-codexforge-all.ps1") "smoke-codexforge-coding-flow-live-run-mvp.ps1" 1 "managed smoke suite includes phase exactly once"
Write-Host "[OK] CodexForge Coding Flow Live Run MVP smoke passed."
