param([string]$BaseUrl = "http://localhost:3000")
$ErrorActionPreference = "Stop"; $root = Split-Path -Parent $PSScriptRoot; Set-Location $root
function Assert-FileExists { param([string]$Path) if (-not (Test-Path $Path)) { throw "[FAIL] Missing file: $Path" } Write-Host "[PASS] file exists: $Path" }
function Assert-DirectoryExists { param([string]$Path) if (-not (Test-Path $Path -PathType Container)) { throw "[FAIL] Missing directory: $Path" } Write-Host "[PASS] directory exists: $Path" }
function Assert-Contains { param([AllowEmptyString()][string]$Haystack,[string]$Needle,[string]$Name) if (-not $Haystack.Contains($Needle)) { throw "[FAIL] Missing $Name`: $Needle" } Write-Host "[PASS] $Name" }
function Assert-NotMatches { param([AllowEmptyString()][string]$Haystack,[string]$Pattern,[string]$Name) if ($Haystack -match $Pattern) { throw "[FAIL] Unexpected $Name`: $Pattern" } Write-Host "[PASS] $Name" }
function Assert-CountExactly { param([AllowEmptyString()][string]$Haystack,[string]$Needle,[int]$Expected,[string]$Name) $count=([regex]::Matches($Haystack,[regex]::Escape($Needle))).Count; if($count -ne $Expected){throw "[FAIL] $Name expected $Expected found $count"} Write-Host "[PASS] $Name" }
Write-Host "=== CodexForge Release Readiness Smoke Pack smoke ==="
$domainDir="src\lib\codexforge\release-readiness-smoke-pack"; $componentDir=Join-Path $domainDir "components"; $routePath="src\app\release-smoke\page.tsx"; $clientPath="src\app\release-smoke\page-client.tsx"
Assert-DirectoryExists $domainDir; Assert-DirectoryExists $componentDir
foreach($module in @("release-smoke-pack-types.ts","release-smoke-suite.ts","release-smoke-command.ts","release-smoke-checklist.ts","release-smoke-result-capture.ts","release-smoke-failure-routing.ts","release-smoke-coverage-map.ts","release-smoke-handoff.ts","release-smoke-summary.ts","index.ts")){Assert-FileExists (Join-Path $domainDir $module)}
foreach($component in @("ReleaseReadinessSmokePackPanel.tsx","ReleaseSmokeSuitePanel.tsx","ReleaseSmokeCommandPanel.tsx","ReleaseSmokeChecklistPanel.tsx","ReleaseSmokeResultCapturePanel.tsx","ReleaseSmokeFailureRoutingPanel.tsx","ReleaseSmokeCoverageMapPanel.tsx","ReleaseSmokeHandoffPanel.tsx","ReleaseSmokeSafetyStrip.tsx","ReleaseSmokeEmptyState.tsx")){Assert-FileExists (Join-Path $componentDir $component)}
Assert-FileExists $routePath; Assert-FileExists $clientPath
$indexSource=Get-Content -Raw (Join-Path $domainDir "index.ts"); $domainSource=(Get-ChildItem $domainDir -File|%{Get-Content -Raw $_.FullName}) -join "`n"; $uiSource=(Get-ChildItem $componentDir -File|%{Get-Content -Raw $_.FullName}) -join "`n"; $routeSource=(Get-Content -Raw $routePath)+"`n"+(Get-Content -Raw $clientPath); $allSource=$domainSource+"`n"+$uiSource+"`n"+$routeSource
foreach($export in @("buildReleaseSmokeSuite","buildReleaseSmokeCommand","buildReleaseSmokeChecklist","buildReleaseSmokeResultCapture","buildReleaseSmokeFailureRouting","buildReleaseSmokeCoverageMap","buildReleaseSmokeHandoff","buildReleaseSmokeSummary")){Assert-Contains $indexSource $export "index exports $export"}
foreach($render in @("ReleaseReadinessSmokePackPanel renders","ReleaseSmokeSuitePanel renders","ReleaseSmokeCommandPanel renders","ReleaseSmokeChecklistPanel renders","ReleaseSmokeResultCapturePanel renders","ReleaseSmokeFailureRoutingPanel renders","ReleaseSmokeCoverageMapPanel renders","ReleaseSmokeHandoffPanel renders","ReleaseSmokeSafetyStrip renders","ReleaseSmokeEmptyState renders")){Assert-Contains $uiSource $render $render}
foreach($text in @("Release smoke pack","Copy smoke checklist","copy commands only","no auto-run","output capture manual","failure routing to /closed-loop or /validation-results","npm run build","smoke-codexforge-coding-flow-live-manual-trial.ps1","smoke-codexforge-mvp-working-path-lock.ps1","smoke-codexforge-release-readiness-smoke-pack.ps1","smoke-codexforge-guarded-apply-mvp.ps1","smoke-codexforge-validation-result-capture-mvp.ps1","npm run smoke:codexforge:server","git diff --check","git status --short","git diff --stat","approval required","preserve latest-message authority","Focus Mode UX calm workflow layout markers","shell without duplicate route chip cloud","route hero title does not vertically wrap","no giant raw JSON above fold","advanced details are collapsed or visually secondary","no unsafe execution buttons","buildReleaseSmokeStableKey")){Assert-Contains $allSource $text "marker $text"}
Assert-Contains $routeSource "ReleaseReadinessSmokePackPanel" "route imports/renders main panel"
foreach($bad in @("appendEvent\s*\(","saveBrainGraph\s*\(","\.nodes\s*\.\s*push|\.edges\s*\.\s*push","apply-diff\s*\(","write-file\s*\(","run-command\s*\(","broker-execution\s*\(","https?://","fetch\s*\(","OPENAI_API_KEY","localStorage.setItem","process\.env\.","Math\.random","Date\.now","d3-force","[\u00c3\u00c2]")){Assert-NotMatches $allSource $bad "blocked marker absent $bad"}
Assert-Contains ((Get-Content -Raw "src\app\code-flow\release-audit\page-client.tsx")+(Get-Content -Raw "src\lib\codexforge\command-palette\command-registry.ts")) "/release-smoke" "integrations mention release smoke"
Assert-CountExactly (Get-Content -Raw "scripts\smoke-codexforge-all.ps1") "smoke-codexforge-release-readiness-smoke-pack.ps1" 1 "managed smoke suite includes phase exactly once"
Write-Host "[OK] CodexForge Release Readiness Smoke Pack smoke passed."
