param([string]$BaseUrl = "http://localhost:3000")

$ErrorActionPreference = "Stop"
$scriptRoot = $PSScriptRoot
$root = Split-Path -Parent $scriptRoot
$parentRoot = Resolve-Path (Join-Path $root "..")
if (Test-Path (Join-Path $parentRoot "README.md")) {
  $repoRoot = $parentRoot
} else {
  $repoRoot = Resolve-Path $root
}
Set-Location $root

function Assert-FileExists {
  param([string]$Path)
  if (-not (Test-Path $Path)) {
    throw "[FAIL] Missing file: $Path"
  }
  Write-Host "[PASS] file exists: $Path"
}

function Assert-Contains {
  param(
    [AllowEmptyString()][string]$Haystack,
    [string]$Needle,
    [string]$Name
  )
  if ($Haystack.IndexOf($Needle, [StringComparison]::OrdinalIgnoreCase) -lt 0) {
    throw "[FAIL] Missing $Name`: $Needle"
  }
  Write-Host "[PASS] $Name"
}

Write-Host "=== CodexForge Checkpoint Documentation smoke ==="

$rootReadmePath = Join-Path $repoRoot "README.md"
$frontendReadmePath = Join-Path $root "README.md"
$checkpointPath = Join-Path $root "docs\codexforge-checkpoint-current.md"
$runbookPath = Join-Path $root "docs\codexforge-operator-checkpoint-runbook.md"
$allSmokePath = Join-Path $scriptRoot "smoke-codexforge-all.ps1"

foreach ($path in @(
  $rootReadmePath,
  $frontendReadmePath,
  $checkpointPath,
  $runbookPath,
  $allSmokePath
)) {
  Assert-FileExists $path
}

$rootReadme = Get-Content -Raw $rootReadmePath
$frontendReadme = Get-Content -Raw $frontendReadmePath
$checkpointDoc = Get-Content -Raw $checkpointPath
$runbookDoc = Get-Content -Raw $runbookPath
$allSmoke = Get-Content -Raw $allSmokePath
$docsCombined = @($checkpointDoc, $runbookDoc) -join "`n"

$phaseMatches = [regex]::Matches($allSmoke, "Phase\s+(\d+)")
if ($phaseMatches.Count -eq 0) {
  throw "[FAIL] No Phase N entries found in all-smoke"
}

$highestPhase = $phaseMatches |
  ForEach-Object { [int]$_.Groups[1].Value } |
  Sort-Object -Descending |
  Select-Object -First 1

if ($highestPhase -ne 5193) {
  throw "[FAIL] Highest detected phase expected 5193 found $highestPhase"
}
Write-Host "[PASS] highest detected phase from all-smoke: $highestPhase"

foreach ($needle in @(
  "CodexForge",
  "Current State",
  "Current checkpoint"
)) {
  Assert-Contains $rootReadme $needle "root README contains $needle"
}

Assert-Contains $frontendReadme "Operational Checkpoint" "frontend README contains Operational Checkpoint"

foreach ($needle in @(
  'currentReleaseGateBatch = "5162-5193 - Backend-Owned Synthetic Dry-Run Audit and Approval Join Review and Recovery Preview"',
  "Phase 5193 Backend-Owned Synthetic Dry-Run Audit and Approval Join Review and Recovery Preview",
  "smoke-codexforge-backend-owned-synthetic-dry-run-audit-approval-join-review-recovery-preview-mega-batch.ps1",
  'currentReleaseGateBatch = "5130-5161 - Backend-Owned Synthetic Dry-Run Audit and Approval Join Contract"',
  "Phase 5161 Backend-Owned Synthetic Dry-Run Audit and Approval Join Contract",
  "smoke-codexforge-backend-owned-synthetic-dry-run-audit-approval-join-contract-mega-batch.ps1",
  'currentReleaseGateBatch = "5098-5129 - Backend-Owned Synthetic Dry-Run Result Capture Review and Recovery Preview"',
  "Phase 5129 Backend-Owned Synthetic Dry-Run Result Capture Review and Recovery Preview",
  "smoke-codexforge-backend-owned-synthetic-dry-run-result-capture-review-recovery-preview-mega-batch.ps1",
  'currentReleaseGateBatch = "5066-5097 - Backend-Owned Synthetic Dry-Run Result Capture Contract"',
  "Phase 5097 Backend-Owned Synthetic Dry-Run Result Capture Contract",
  "smoke-codexforge-backend-owned-synthetic-dry-run-result-capture-contract-mega-batch.ps1",
  'currentReleaseGateBatch = "5034-5065 - Backend-Owned Model Provider Synthetic Dry-Run Runner Skeleton"',
  "Phase 5065 Backend-Owned Model Provider Synthetic Dry-Run Runner Skeleton",
  "smoke-codexforge-backend-owned-model-provider-synthetic-dry-run-runner-skeleton-mega-batch.ps1",
  'currentReleaseGateBatch = "5002-5033 - Backend-Owned Model Provider Dry-Run Runner Review and Recovery Preview"',
  "Phase 5033 Backend-Owned Model Provider Dry-Run Runner Review and Recovery Preview",
  "smoke-codexforge-backend-owned-model-provider-dry-run-runner-review-recovery-preview-mega-batch.ps1",
  'currentReleaseGateBatch = "4970-5001 - Backend-Owned Model Provider Dry-Run Runner Contract"',
  "Phase 5001 Backend-Owned Model Provider Dry-Run Runner Contract",
  "smoke-codexforge-backend-owned-model-provider-dry-run-runner-contract-mega-batch.ps1",
  'currentReleaseGateBatch = "4938-4969 - Backend-Owned Model Provider Run Admission Contract"',
  "Phase 4969 Backend-Owned Model Provider Run Admission Contract",
  "smoke-codexforge-backend-owned-model-provider-run-admission-contract-mega-batch.ps1",
  'currentReleaseGateBatch = "4906-4937 - Model Provider Run Admission Review and Recovery Preview"',
  "Phase 4937 Model Provider Run Admission Review and Recovery Preview",
  "smoke-codexforge-model-provider-run-admission-review-recovery-preview-mega-batch.ps1",
  "Phase 4905 Manual Gated Model Provider Run Admission Preview",
  "smoke-codexforge-manual-gated-model-provider-run-admission-preview-mega-batch.ps1",
  'currentReleaseGateBatch = "4842-4873 - Model Provider Approval Packet and Run Intent Preview"',
  "Phase 4777 Manual Gated Model Adapter Dry-Run Harness",
  "Phase 4809 Model Adapter Dry-Run Result Review and Recovery",
  "Phase 4841 Athena Model Routing and Provider Selection Preview",
  "Phase 4873 Model Provider Approval Packet and Run Intent Preview",
  "smoke-codexforge-manual-gated-model-adapter-dry-run-harness-mega-batch.ps1",
  "smoke-codexforge-model-adapter-dry-run-result-review-recovery-mega-batch.ps1",
  "smoke-codexforge-athena-model-routing-provider-selection-preview-mega-batch.ps1",
  "smoke-codexforge-model-provider-approval-packet-run-intent-preview-mega-batch.ps1"
)) {
  Assert-Contains $allSmoke $needle "all-smoke contains $needle"
}

foreach ($needle in @(
  "Current checkpoint: Highest detected phase: 5193. Latest completed batch: 5162-5193 - Backend-Owned Synthetic Dry-Run Audit and Approval Join Review and Recovery Preview. Previous completed batch: 5130-5161 - Backend-Owned Synthetic Dry-Run Audit and Approval Join Contract. Next likely batch: 5194-5225 - Backend-Owned Synthetic Dry-Run End-to-End Packet Contract.",
  "Highest detected phase: 5193",
  "Latest completed batch: 5162-5193 - Backend-Owned Synthetic Dry-Run Audit and Approval Join Review and Recovery Preview",
  "Previous completed batch: 5130-5161 - Backend-Owned Synthetic Dry-Run Audit and Approval Join Contract",
  "Next likely batch: 5194-5225 - Backend-Owned Synthetic Dry-Run End-to-End Packet Contract",
  "backend-owned synthetic dry-run audit and approval join review and recovery preview only",
  "audit and approval join review is preview-only",
  "audit and approval join decision review is preview-only",
  "audit and approval join gate failure review is preview-only",
  "audit and approval join recovery plan is preview-only",
  "audit and approval join recovery readiness is preview-only",
  "audit and approval join acceptance posture is preview-only",
  "audit join state is not persisted",
  "approval join state is not persisted",
  "result reference state is not persisted",
  "evidence packet state is preview-only",
  "join request is not created",
  "join invocation is not invoked",
  "join response is not received",
  "join error is not received",
  "audit envelope state is not created",
  "approval envelope state is not created",
  "audit append state is not appended",
  "approval append state is not appended",
  "audit persistence is not implemented",
  "approval persistence is not implemented",
  "result persistence is not implemented",
  "artifact persistence is not implemented",
  "database write is not implemented",
  "file write is not implemented",
  "acceptance state is not accepted / preview-only",
  "recovery is manual review only",
  "no prompt sending",
  "no LLM/model calls",
  "no frontend provider call",
  "no frontend fetch/network call",
  "no provider SDK imports",
  "no provider execution",
  "no plugin execution",
  "no autonomous execution",
  "no live video generation",
  "no queue dispatch",
  "no worker dispatch",
  "no job execution",
  "no retry execution",
  "no fallback execution",
  "no result persistence",
  "no audit persistence",
  "no approval persistence",
  "no persistent memory",
  "no browser storage",
  "no database writes",
  "backend-only execution path required",
  "server-only adapters required",
  "manual approval required",
  "manual confirmation required",
  "kill switch required",
  "audit required",
  "opaque credential references only",
  "no plaintext secrets",
  "backend-owned synthetic dry-run end-to-end packet contract next",
  "Current checkpoint: Highest detected phase: 5129. Latest completed batch: 5098-5129 - Backend-Owned Synthetic Dry-Run Result Capture Review and Recovery Preview. Previous completed batch: 5066-5097 - Backend-Owned Synthetic Dry-Run Result Capture Contract. Next likely batch: 5130-5161 - Backend-Owned Synthetic Dry-Run Audit and Approval Join Contract.",
  "Highest detected phase: 5129",
  "Latest completed batch: 5098-5129 - Backend-Owned Synthetic Dry-Run Result Capture Review and Recovery Preview",
  "Previous completed batch: 5066-5097 - Backend-Owned Synthetic Dry-Run Result Capture Contract",
  "Next likely batch: 5130-5161 - Backend-Owned Synthetic Dry-Run Audit and Approval Join Contract",
  "backend-owned synthetic dry-run result capture review and recovery preview only",
  "synthetic result capture review is preview-only",
  "result capture decision review is preview-only",
  "result capture gate failure review is preview-only",
  "result capture recovery plan is preview-only",
  "result capture recovery readiness is preview-only",
  "result capture acceptance posture is preview-only",
  "result capture state is not captured",
  "result persistence is not implemented",
  "audit persistence is not implemented",
  "approval persistence is not implemented",
  "artifact persistence is not implemented",
  "database write is not implemented",
  "file write is not implemented",
  "provider response is not received",
  "model output is not generated",
  "synthetic fixture result is static placeholder only",
  "result id is not issued",
  "audit and approval joins are not persisted",
  "acceptance state is not accepted / preview-only",
  "recovery is manual review only",
  "no prompt sending",
  "no LLM/model calls",
  "no frontend provider call",
  "no frontend fetch/network call",
  "no provider SDK imports",
  "no provider execution",
  "no plugin execution",
  "no autonomous execution",
  "no live video generation",
  "no queue dispatch",
  "no worker dispatch",
  "no job execution",
  "no retry execution",
  "no fallback execution",
  "no result persistence",
  "no audit persistence",
  "no approval persistence",
  "no persistent memory",
  "no browser storage",
  "no database writes",
  "backend-only execution path required",
  "server-only adapters required",
  "manual approval required",
  "manual confirmation required",
  "kill switch required",
  "audit required",
  "opaque credential references only",
  "no plaintext secrets",
  "backend-owned synthetic dry-run audit and approval join contract next",
  "Highest detected phase: 5097. Latest completed batch: 5066-5097 - Backend-Owned Synthetic Dry-Run Result Capture Contract. Previous completed batch: 5034-5065 - Backend-Owned Model Provider Synthetic Dry-Run Runner Skeleton. Next likely batch: 5098-5129 - Backend-Owned Synthetic Dry-Run Result Capture Review and Recovery Preview.",
  "Highest detected phase: 5097",
  "Latest completed batch: 5066-5097 - Backend-Owned Synthetic Dry-Run Result Capture Contract",
  "Previous completed batch: 5034-5065 - Backend-Owned Model Provider Synthetic Dry-Run Runner Skeleton",
  "Next likely batch: 5098-5129 - Backend-Owned Synthetic Dry-Run Result Capture Review and Recovery Preview",
  "backend-owned synthetic dry-run result capture contract only",
  "synthetic result capture contract is preview-only",
  "result capture state is not captured",
  "result persistence is not implemented",
  "audit persistence is not implemented",
  "approval persistence is not implemented",
  "artifact persistence is not implemented",
  "database write is not implemented",
  "file write is not implemented",
  "provider response is not received",
  "model output is not generated",
  "synthetic fixture result is static placeholder only",
  "result envelope is preview-only",
  "result id is not issued",
  "result digest is deterministic preview only",
  "result capture request/response/error contracts are preview-only",
  "result capture gates are preview-only",
  "result capture readiness matrix is preview-only",
  "audit and approval joins are not persisted",
  "current readiness is capture-contract-only / not persistent",
  "no prompt sending",
  "no LLM/model calls",
  "no frontend provider call",
  "no frontend fetch/network call",
  "no provider SDK imports",
  "no provider execution",
  "no plugin execution",
  "no autonomous execution",
  "no live video generation",
  "no queue dispatch",
  "no worker dispatch",
  "no job execution",
  "no retry execution",
  "no fallback execution",
  "no result persistence",
  "no audit persistence",
  "no approval persistence",
  "no persistent memory",
  "no browser storage",
  "no database writes",
  "backend-only execution path required",
  "server-only adapters required",
  "manual approval required",
  "manual confirmation required",
  "kill switch required",
  "audit required",
  "opaque credential references only",
  "no plaintext secrets",
  "backend-owned synthetic dry-run result capture review and recovery preview next",
  "Current checkpoint: Highest detected phase: 5065. Latest completed batch: 5034-5065 - Backend-Owned Model Provider Synthetic Dry-Run Runner Skeleton. Previous completed batch: 5002-5033 - Backend-Owned Model Provider Dry-Run Runner Review and Recovery Preview. Next likely batch: 5066-5097 - Backend-Owned Synthetic Dry-Run Result Capture Contract.",
  "Highest detected phase: 5065",
  "Latest completed batch: 5034-5065 - Backend-Owned Model Provider Synthetic Dry-Run Runner Skeleton",
  "Previous completed batch: 5002-5033 - Backend-Owned Model Provider Dry-Run Runner Review and Recovery Preview",
  "Next likely batch: 5066-5097 - Backend-Owned Synthetic Dry-Run Result Capture Contract",
  "backend-owned model provider synthetic dry-run runner skeleton only",
  "synthetic runner skeleton is preview-only",
  "runner state is skeleton / not executable",
  "dry-run request is not created",
  "runner invocation is not invoked",
  "dry-run execution is not executed",
  "provider response is not received",
  "model output is not generated",
  "synthetic fixture result is static placeholder only",
  "synthetic input/output/error fixtures are preview-only",
  "synthetic runner gates are preview-only",
  "synthetic runner readiness matrix is preview-only",
  "current readiness is skeleton-only / not executable",
  "backend-owned synthetic dry-run result capture contract next",
  "Current checkpoint: Highest detected phase: 5033. Latest completed batch: 5002-5033 - Backend-Owned Model Provider Dry-Run Runner Review and Recovery Preview. Previous completed batch: 4970-5001 - Backend-Owned Model Provider Dry-Run Runner Contract. Next likely batch: 5034-5065 - Backend-Owned Model Provider Synthetic Dry-Run Runner Skeleton.",
  "Highest detected phase: 5033",
  "Latest completed batch: 5002-5033 - Backend-Owned Model Provider Dry-Run Runner Review and Recovery Preview",
  "Previous completed batch: 4970-5001 - Backend-Owned Model Provider Dry-Run Runner Contract",
  "Next likely batch: 5034-5065 - Backend-Owned Model Provider Synthetic Dry-Run Runner Skeleton",
  "backend-owned model provider dry-run runner review and recovery preview only",
  "dry-run runner review is preview-only",
  "dry-run runner decision review is preview-only",
  "dry-run runner gate failure review is preview-only",
  "dry-run runner recovery plan is preview-only",
  "dry-run runner recovery readiness is preview-only",
  "dry-run runner acceptance posture is preview-only",
  "dry-run invocation is not invoked",
  "dry-run response is not received",
  "dry-run error is not received",
  "fixture result is not produced",
  "acceptance state is not accepted / preview-only",
  "recovery is manual review only",
  "backend-owned synthetic dry-run runner skeleton next",
  "Current checkpoint: Highest detected phase: 4969. Latest completed batch: 4938-4969 - Backend-Owned Model Provider Run Admission Contract. Previous completed batch: 4906-4937 - Model Provider Run Admission Review and Recovery Preview. Next likely batch: 4970-5001 - Backend-Owned Model Provider Dry-Run Runner Contract.",
  "Highest detected phase: 4969",
  "Latest completed batch: 4938-4969 - Backend-Owned Model Provider Run Admission Contract",
  "Previous completed batch: 4906-4937 - Model Provider Run Admission Review and Recovery Preview",
  "Next likely batch: 4970-5001 - Backend-Owned Model Provider Dry-Run Runner Contract",
  "backend-owned model provider run admission contract only",
  "backend-owned contract is preview-only",
  "contract state is draft / preview-only",
  "admission request is not created",
  "backend response is not received",
  "backend error is not received",
  "admission token is not issued",
  "admission lease is not created",
  "admission ticket is not issued",
  "request/response/error contracts are preview-only",
  "gate schema is preview-only",
  "readiness matrix is preview-only",
  "current readiness is not executable / contract-only",
  "backend-owned dry-run runner contract next",
  "Current checkpoint: Highest detected phase: 4937. Latest completed batch: 4906-4937 - Model Provider Run Admission Review and Recovery Preview. Previous completed batch: 4874-4905 - Manual Gated Model Provider Run Admission Preview.",
  "Highest detected phase: 4937",
  "Latest completed batch: 4906-4937 - Model Provider Run Admission Review and Recovery Preview",
  "Previous completed batch: 4874-4905 - Manual Gated Model Provider Run Admission Preview",
  "Next likely batch: 4938-4969 - Backend-Owned Model Provider Run Admission Contract",
  "model provider run admission review and recovery preview only",
  "admission review is preview-only",
  "decision review is preview-only",
  "gate failure review is preview-only",
  "recovery plan is preview-only",
  "recovery readiness is preview-only",
  "run admission state is not admitted",
  "admission decision remains held",
  "admission token is not issued",
  "admission lease is not created",
  "admission ticket is not issued",
  "recovery is manual review only",
  "backend-owned model provider run admission contract next",
  "Current checkpoint: Highest detected phase: 4905. Latest completed batch: 4874-4905 - Manual Gated Model Provider Run Admission Preview. Previous completed batch: 4842-4873 - Model Provider Approval Packet and Run Intent Preview.",
  "Highest detected phase: 4905",
  "Latest completed batch: 4874-4905 - Manual Gated Model Provider Run Admission Preview",
  "Previous completed batch: 4842-4873 - Model Provider Approval Packet and Run Intent Preview",
  "Next likely batch: 4906-4937 - Model Provider Run Admission Review and Recovery Preview",
  "manual gated model provider run admission preview only",
  "run admission is preview-only",
  "run admission state is not admitted",
  "admission decision is held",
  "admission token is not issued",
  "admission lease is not created",
  "admission ticket is preview-only",
  "gate evaluation is preview-only",
  "admission blockers are preview-only",
  "recovery is manual review only",
  "run admission review and recovery preview next",
  "Current checkpoint: Highest detected phase: 4873. Latest completed batch: 4842-4873 - Model Provider Approval Packet and Run Intent Preview. Previous completed batch: 4810-4841 - Athena Model Routing and Provider Selection Preview.",
  "Highest detected phase: 4873",
  "Latest completed batch: 4842-4873 - Model Provider Approval Packet and Run Intent Preview",
  "Previous completed batch: 4810-4841 - Athena Model Routing and Provider Selection Preview",
  "Next likely batch: 4874-4905 - Manual Gated Model Provider Run Admission Preview",
  "model provider approval packet and run intent preview only",
  "approval packet is preview-only",
  "run intent is preview-only",
  "approval gates are preview-only",
  "run intent blockers are preview-only",
  "approval expiry and revocation are preview-only",
  "manual gated run admission preview next",
  "manual gated model provider run admission preview next",
  "Current checkpoint: Highest detected phase: 4841. Latest completed batch: 4810-4841 - Athena Model Routing and Provider Selection Preview. Previous completed batch: 4778-4809 - Model Adapter Dry-Run Result Review and Recovery.",
  "Latest completed batch: 4810-4841 - Athena Model Routing and Provider Selection Preview",
  "Previous completed batch: 4778-4809 - Model Adapter Dry-Run Result Review and Recovery",
  "Next likely batch: 4842-4873 - Model Provider Approval Packet and Run Intent Preview",
  "Athena model routing and provider selection preview only",
  "routing is preview-only",
  "provider selection is static preview only",
  "model routing chains are preview-only",
  "provider selection blockers are preview-only",
  "no prompt sending",
  "no LLM/model calls",
  "no frontend provider call",
  "no frontend fetch/network call",
  "no provider SDK imports",
  "no provider execution",
  "no plugin execution",
  "no autonomous execution",
  "no live video generation",
  "no queue dispatch",
  "no worker dispatch",
  "no job execution",
  "no retry execution",
  "no fallback execution",
  "no result persistence",
  "no audit persistence",
  "no approval persistence",
  "no persistent memory",
  "no browser storage",
  "no database writes",
  "backend-only execution path required",
  "server-only adapters required",
  "manual approval required",
  "manual confirmation required",
  "kill switch required",
  "audit required",
  "opaque credential references only",
  "no plaintext secrets",
  "model provider approval packet and run intent preview next",
  "Current checkpoint: Highest detected phase: 4809. Latest completed batch: 4778-4809 - Model Adapter Dry-Run Result Review and Recovery. Previous completed batch: 4746-4777 - Manual Gated Model Adapter Dry-Run Harness.",
  "Next likely batch: 4810-4841 - Athena Model Routing and Provider Selection Preview"
)) {
  Assert-Contains $docsCombined $needle "checkpoint docs contain $needle"
}

Write-Host "[OK] CodexForge Checkpoint Documentation smoke passed."
