param([string]$BaseUrl = "http://localhost:3000")
$ErrorActionPreference = "Stop"; $root = Split-Path -Parent $PSScriptRoot; Set-Location $root
function Assert-FileExists { param([string]$Path) if (-not (Test-Path $Path)) { throw "[FAIL] Missing file: $Path" } Write-Host "[PASS] file exists: $Path" }
function Assert-DirectoryExists { param([string]$Path) if (-not (Test-Path $Path -PathType Container)) { throw "[FAIL] Missing directory: $Path" } Write-Host "[PASS] directory exists: $Path" }
function Assert-Contains { param([AllowEmptyString()][string]$Haystack,[string]$Needle,[string]$Name) if (-not $Haystack.Contains($Needle)) { throw "[FAIL] Missing $Name`: $Needle" } Write-Host "[PASS] $Name" }
function Assert-NotMatches { param([AllowEmptyString()][string]$Haystack,[string]$Pattern,[string]$Name) if ($Haystack -match $Pattern) { throw "[FAIL] Unexpected $Name`: $Pattern" } Write-Host "[PASS] $Name" }
function Assert-CountExactly { param([AllowEmptyString()][string]$Haystack,[string]$Needle,[int]$Expected,[string]$Name) $count=([regex]::Matches($Haystack,[regex]::Escape($Needle))).Count; if($count -ne $Expected){throw "[FAIL] $Name expected $Expected found $count"} Write-Host "[PASS] $Name" }
Write-Host "=== CodexForge MVP Onboarding smoke ==="
$domainDir="src\lib\codexforge\mvp-onboarding"; $componentDir=Join-Path $domainDir "components"; $routePath="src\app\onboarding\page.tsx"; $clientPath="src\app\onboarding\page-client.tsx"
Assert-DirectoryExists $domainDir; Assert-DirectoryExists $componentDir
foreach($module in @("mvp-onboarding-types.ts","onboarding-step.ts","onboarding-safe-task.ts","onboarding-safety-promise.ts","onboarding-route-guide.ts","onboarding-first-run.ts","onboarding-completion.ts","onboarding-handoff.ts","mvp-onboarding-summary.ts","index.ts")){Assert-FileExists (Join-Path $domainDir $module)}
foreach($component in @("MvpOnboardingPanel.tsx","OnboardingStepPanel.tsx","OnboardingSafeTaskPanel.tsx","OnboardingSafetyPromisePanel.tsx","OnboardingRouteGuidePanel.tsx","OnboardingFirstRunPanel.tsx","OnboardingCompletionPanel.tsx","OnboardingHandoffPanel.tsx","MvpOnboardingSafetyStrip.tsx","MvpOnboardingEmptyState.tsx")){Assert-FileExists (Join-Path $componentDir $component)}
Assert-FileExists $routePath; Assert-FileExists $clientPath
$indexSource=Get-Content -Raw (Join-Path $domainDir "index.ts"); $domainSource=(Get-ChildItem $domainDir -File|%{Get-Content -Raw $_.FullName}) -join "`n"; $uiSource=(Get-ChildItem $componentDir -File|%{Get-Content -Raw $_.FullName}) -join "`n"; $routeSource=(Get-Content -Raw $routePath)+"`n"+(Get-Content -Raw $clientPath); $allSource=$domainSource+"`n"+$uiSource+"`n"+$routeSource
foreach($export in @("buildOnboardingStep","buildDefaultOnboardingSteps","buildOnboardingSafeTask","buildOnboardingSafetyPromise","buildOnboardingRouteGuide","buildOnboardingFirstRun","buildOnboardingCompletion","buildOnboardingHandoff","buildMvpOnboardingSummary")){Assert-Contains $indexSource $export "index exports $export"}
Assert-Contains $routeSource "MvpOnboardingPanel" "route imports/renders main panel"
foreach($text in @("plain English","no auto-apply","no auto-run","approval required","preserve latest-message authority","route uses home-grade/unified shell marker","no duplicate route chip cloud","hero title does not vertically wrap","no giant raw JSON above fold","advanced details collapsed/secondary","no unsafe execution buttons","no direct appendEvent call from UI","no direct saveBrainGraph call from UI","no direct graph mutation from UI","no memory auto-promotion","no direct apply-diff call from UI","no direct write-file call from UI","no direct run-command call from UI","no broker-execution call","no external network dependency","no vector database dependency","no OpenAI/API-key dependency","no hardcoded API keys","no localStorage API key storage")){Assert-Contains $allSource $text "marker $text"}
foreach($bad in @("appendEvent\s*\(","saveBrainGraph\s*\(","\.nodes\s*\.\s*push|\.edges\s*\.\s*push","apply-diff\s*\(","write-file\s*\(","run-command\s*\(","broker-execution\s*\(","https?://","fetch\s*\(","OPENAI_API_KEY","localStorage.setItem","process\.env\.","Math\.random","Date\.now","d3-force",("[{0}{1}{2}]" -f [char]0x00C3, [char]0x00C2, [char]0xFFFD))){Assert-NotMatches $allSource $bad "blocked marker absent $bad"}
Assert-CountExactly (Get-Content -Raw "scripts\smoke-codexforge-all.ps1") "smoke-codexforge-mvp-onboarding.ps1" 1 "managed smoke suite includes phase exactly once"
Write-Host "[OK] CodexForge MVP Onboarding smoke passed."
