import {
  BACKEND_OWNED_MINIMAL_MANUAL_GATED_PROVIDER_ADAPTER_DRY_RUN_EXECUTION_MVP_BATCH,
  BACKEND_OWNED_MINIMAL_MANUAL_GATED_PROVIDER_ADAPTER_DRY_RUN_EXECUTION_MVP_PHASE,
  NEXT_BACKEND_OWNED_MINIMAL_MANUAL_GATED_PROVIDER_ADAPTER_DRY_RUN_EXECUTION_REVIEW_RECOVERY_PREVIEW_BATCH,
  PREVIOUS_COMPLETED_BACKEND_OWNED_MINIMAL_MANUAL_GATED_PROVIDER_ADAPTER_DRY_RUN_ADMISSION_REVIEW_RECOVERY_PREVIEW_BATCH,
  type MinimalManualGatedProviderAdapterDryRunExecutionMvpRecord,
  type MinimalProviderDryRunExecutionServerRunRecord,
  type ProviderDryRunApprovalPreviewRecord,
  type ProviderDryRunAuditPreviewRecord,
  type ProviderDryRunBlockedLiveExecutionSummaryRecord,
  type ProviderDryRunEvidencePreviewRecord,
  type ProviderDryRunExecutionCapabilityFamilyId,
  type ProviderDryRunExecutionCurrentReadiness,
  type ProviderDryRunExecutionErrorRecord,
  type ProviderDryRunExecutionFixtureProviderResponse,
  type ProviderDryRunExecutionGateId,
  type ProviderDryRunExecutionGateRecord,
  type ProviderDryRunExecutionGateSummary,
  type ProviderDryRunExecutionInputRecord,
  type ProviderDryRunExecutionMode,
  type ProviderDryRunExecutionMvpId,
  type ProviderDryRunExecutionOutputRecord,
  type ProviderDryRunExecutionPlanRecord,
  type ProviderDryRunExecutionProviderSlotLabel,
  type ProviderDryRunExecutionReadinessSummary,
  type ProviderDryRunExecutionResponseRecord,
  type ProviderDryRunExecutionReviewRecoveryChecklist,
  type ProviderDryRunExecutionReviewRecoveryNextStatement,
  type ProviderDryRunExecutionSummary,
  type ProviderDryRunFixtureResponseRecord,
  type ProviderDryRunFallbackPosture,
  type ProviderDryRunReadinessId,
  type ProviderDryRunReadinessMatrixRecord,
  type ProviderDryRunSafetyGateSummaryRecord,
  type ProviderDryRunSlotOrder,
  type ProviderDryRunExecutionEnvelopeRecord,
  type ProviderDryRunExecutionRequestRecord,
} from "./min-provider-exec-types";

type ProviderDryRunExecutionSeed = Readonly<{
  stableId: ProviderDryRunExecutionMvpId;
  capabilityFamilyId: ProviderDryRunExecutionCapabilityFamilyId;
  capabilityFamily: "text/chat" | "planning/reasoning";
  providerSlotLabel: ProviderDryRunExecutionProviderSlotLabel;
  backupProviderSlotLabel: ProviderDryRunExecutionProviderSlotLabel;
  localPrivateAlternativeLabel: "local/private text provider dry-run execution slot";
  opaqueCredentialReferenceLabel:
    | "opaque credential reference label / athena dry-run execution text chat primary"
    | "opaque credential reference label / athena dry-run execution planning reasoning primary";
  fixtureProviderResponse: ProviderDryRunExecutionFixtureProviderResponse;
  planSummary: string;
}>;

type GateSeed = Readonly<{
  gateId: ProviderDryRunExecutionGateId;
  label: string;
  owner: string;
  requiredState: string;
  currentState: (seed: ProviderDryRunExecutionSeed) => string;
  evidence: (seed: ProviderDryRunExecutionSeed) => string;
  blockedLiveAction: string;
}>;

type ReadinessSeed = Readonly<{
  readinessId: ProviderDryRunReadinessId;
  label: string;
  state: string;
  evidence: string;
}>;

const CURRENT_READINESS: ProviderDryRunExecutionCurrentReadiness =
  "minimal-provider-dry-run-execution-mvp-only / backend-only / dry-run-fixture-only / credential-reference-only / not-live-provider-executing / not persistent";

const EXECUTION_MODE: ProviderDryRunExecutionMode =
  "deterministic-fixture-only";

const REVIEW_RECOVERY_NEXT_STATEMENT: ProviderDryRunExecutionReviewRecoveryNextStatement =
  "provider adapter dry-run execution review and recovery preview comes next";

const RETRY_POSTURE: ProviderDryRunFallbackPosture = "disabled";
const FALLBACK_POSTURE: ProviderDryRunFallbackPosture = "disabled";

const SUMMARY_LINES = [
  "backend-owned minimal manual-gated provider adapter dry-run execution MVP only",
  "provider adapter dry-run execution is backend-only",
  "server-only provider dry-run execution helper exists",
  "provider dry-run execution is deterministic fixture-only",
  "dry-run fixture response is produced in memory only",
  "live provider execution is blocked",
  "credential reference is opaque label only",
  "credential value is not present",
  "credential value is not read",
  "env vars are not read",
  "provider key is not read",
  "selected provider slot is preview-only",
  "backup provider slot is preview-only",
  "local/private alternative is preview-only",
  "provider adapter dry-run execution is not live provider execution",
  "no frontend request is created",
  "no API route is created",
  "no real approval request",
  "no real approval recording",
  "approval fixture is preview-only",
  "manual confirmation fixture is preview-only",
  "approval token is not issued",
  "approval lease is not created",
  "provider response is not received from provider",
  "model output is not generated by provider/model",
  "no prompt sending",
  "no LLM/model calls",
  "no frontend provider call",
  "no frontend fetch/network call",
  "no provider SDK imports",
  "no live provider execution",
  "no plugin execution",
  "no autonomous execution",
  "no live video generation",
  "no queue dispatch",
  "no worker dispatch",
  "no job execution",
  "no retry execution",
  "no fallback execution",
  "no result persistence",
  "no audit persistence",
  "no approval persistence",
  "no persistent memory",
  "no browser storage",
  "no database writes",
  "no file writes",
  "backend-only execution path required",
  "server-only adapters required",
  "manual approval fixture required",
  "manual confirmation fixture required",
  "kill switch required",
  "audit preview required",
  "opaque credential references only",
  "no plaintext secrets",
  `current readiness is ${CURRENT_READINESS}`,
  "backend-owned minimal manual-gated provider adapter dry-run execution review and recovery preview next",
] as const;

const GATE_SUMMARY_LINES = [
  "backend-only boundary",
  "server-only dry-run execution module boundary",
  "provider dry-run execution fixture mode",
  "provider dry-run admission review dependency",
  "provider dry-run admission output dependency",
  "credential reference opaque-only mode",
  "deterministic dry-run execution id",
  "deterministic dry-run admission id",
  "deterministic provider slot id",
  "deterministic credential reference id",
  "deterministic execution digest",
  "supported capability family",
  "selected provider slot preview-only",
  "backup provider slot preview-only",
  "local/private alternative preview-only",
  "dry-run intent preview-only",
  "fixture response only",
  "live provider execution blocked",
  "credential value absent",
  "credential value not read",
  "env vars not read",
  "provider key not read",
  "redacted prompt envelope present",
  "prompt not sent",
  "provider SDK not imported",
  "provider response not received from provider",
  "model output not generated by provider/model",
  "manual approval fixture",
  "manual confirmation fixture",
  "in-memory only execution reference",
  "no real approval request",
  "no real approval recording",
  "no approval token issuance",
  "no approval lease issuance",
  "no frontend request",
  "no API route",
  "no fetch/network",
  "no provider SDK import",
  "no live provider execution",
  "no model call",
  "no prompt sending",
  "no queue dispatch",
  "no worker dispatch",
  "no job execution",
  "no result persistence",
  "no audit persistence",
  "no approval persistence",
  "no database write",
  "no file write",
  "single-run lock preview",
  "idempotency/replay preview",
  "timeout/cancel preview",
  "privacy/redaction preview",
  "kill switch fixture",
] as const;

const READINESS_SUMMARY_LINES = [
  "server-only dry-run execution helper state",
  "provider dry-run admission review dependency",
  "dry-run execution input state",
  "dry-run execution plan state",
  "dry-run execution output state",
  "dry-run execution envelope state",
  "dry-run fixture response state",
  "dry-run blocked live execution summary state",
  "evidence preview state",
  "audit preview state",
  "approval preview state",
  "credential value boundary state",
  "env var boundary state",
  "provider key boundary state",
  "provider SDK boundary state",
  "live provider execution boundary state",
  "prompt boundary state",
  "model boundary state",
  "frontend request boundary state",
  "API route boundary state",
  "queue boundary state",
  "worker boundary state",
  "job boundary state",
  "result persistence boundary state",
  "audit persistence boundary state",
  "approval persistence boundary state",
  "database boundary state",
  "file boundary state",
  `current readiness: ${CURRENT_READINESS}`,
  "next safe action",
] as const;

const NEXT_REVIEW_RECOVERY_CHECKLIST = [
  "Review the deterministic provider dry-run execution fixture output before adding any review and recovery overlays.",
  "Keep provider adapter dry-run execution backend-only, server-only, deterministic, manual-gated, fixture-only, and in-memory only.",
  "Do not add credential value reads, env var reads, provider key reads, provider SDK imports, provider calls, model calls, or prompt transmission.",
  "Do not add frontend requests, API routes, queue dispatch, worker dispatch, job execution, result persistence, audit persistence, approval persistence, database writes, or file writes.",
  NEXT_BACKEND_OWNED_MINIMAL_MANUAL_GATED_PROVIDER_ADAPTER_DRY_RUN_EXECUTION_REVIEW_RECOVERY_PREVIEW_BATCH,
] as const satisfies ProviderDryRunExecutionReviewRecoveryChecklist;

const BLOCKED_LIVE_ACTIONS = [
  "real approval request",
  "real approval recording",
  "approval token issuance",
  "approval lease issuance",
  "credential value read",
  "env var read",
  "provider key read",
  "prompt sending",
  "provider SDK import",
  "live provider execution",
  "model call",
  "frontend request creation",
  "API route creation",
  "frontend fetch/network call",
  "queue dispatch",
  "worker dispatch",
  "job execution",
  "result persistence",
  "audit persistence",
  "approval persistence",
  "database write",
  "file write",
] as const;

const PROVIDER_DRY_RUN_EXECUTION_SEEDS = [
  {
    stableId: "text-chat-provider-dry-run-execution",
    capabilityFamilyId: "text-chat",
    capabilityFamily: "text/chat",
    providerSlotLabel: "OpenAI-compatible text provider dry-run execution slot",
    backupProviderSlotLabel:
      "Anthropic-compatible text provider dry-run execution slot",
    localPrivateAlternativeLabel:
      "local/private text provider dry-run execution slot",
    opaqueCredentialReferenceLabel:
      "opaque credential reference label / athena dry-run execution text chat primary",
    fixtureProviderResponse:
      "deterministic dry-run fixture response / athena text chat provider preview",
    planSummary:
      "Execute the backend-owned preview fixture only and keep the prompt envelope redacted and unsent.",
  },
  {
    stableId: "planning-reasoning-provider-dry-run-execution",
    capabilityFamilyId: "planning-reasoning",
    capabilityFamily: "planning/reasoning",
    providerSlotLabel: "Gemini-compatible text provider dry-run execution slot",
    backupProviderSlotLabel: "fallback disabled dry-run execution slot",
    localPrivateAlternativeLabel:
      "local/private text provider dry-run execution slot",
    opaqueCredentialReferenceLabel:
      "opaque credential reference label / athena dry-run execution planning reasoning primary",
    fixtureProviderResponse:
      "deterministic dry-run fixture response / athena planning reasoning provider preview",
    planSummary:
      "Execute the backend-owned planning/reasoning preview fixture only and keep live provider execution blocked.",
  },
] as const satisfies readonly ProviderDryRunExecutionSeed[];

function cloneList<T>(items: readonly T[]): readonly T[] {
  return items.map((item) => item);
}

function buildProviderDryRunExecutionPreviewId(
  stableId: ProviderDryRunExecutionMvpId
): `provider-dry-run-execution-preview:${ProviderDryRunExecutionMvpId}` {
  return `provider-dry-run-execution-preview:${stableId}`;
}

function buildProviderDryRunAdmissionPreviewId(
  stableId: ProviderDryRunExecutionMvpId
): `provider-dry-run-admission-preview:${ProviderDryRunExecutionMvpId}` {
  return `provider-dry-run-admission-preview:${stableId}`;
}

function buildProviderDryRunPreviewSlotId(
  stableId: ProviderDryRunExecutionMvpId,
  slotOrder: ProviderDryRunSlotOrder
): `provider-dry-run-execution-slot-preview:${ProviderDryRunExecutionMvpId}:${ProviderDryRunSlotOrder}` {
  return `provider-dry-run-execution-slot-preview:${stableId}:${slotOrder}`;
}

function buildProviderDryRunPreviewCredentialReferenceId(
  stableId: ProviderDryRunExecutionMvpId
): `provider-dry-run-execution-credential-reference-preview:${ProviderDryRunExecutionMvpId}` {
  return `provider-dry-run-execution-credential-reference-preview:${stableId}`;
}

function buildProviderDryRunPreviewDigest(
  stableId: ProviderDryRunExecutionMvpId
): `provider-dry-run-execution-digest-preview:${ProviderDryRunExecutionMvpId}:fixture-only` {
  return `provider-dry-run-execution-digest-preview:${stableId}:fixture-only`;
}

function buildProviderDryRunPreviewResultReference(
  stableId: ProviderDryRunExecutionMvpId
): `provider-dry-run-execution-result-reference-preview:${ProviderDryRunExecutionMvpId}` {
  return `provider-dry-run-execution-result-reference-preview:${stableId}`;
}

function buildProviderDryRunPreviewAuditReference(
  stableId: ProviderDryRunExecutionMvpId
): `provider-dry-run-execution-audit-reference-preview:${ProviderDryRunExecutionMvpId}` {
  return `provider-dry-run-execution-audit-reference-preview:${stableId}`;
}

function buildProviderDryRunPreviewApprovalReference(
  stableId: ProviderDryRunExecutionMvpId
): `provider-dry-run-execution-approval-reference-preview:${ProviderDryRunExecutionMvpId}` {
  return `provider-dry-run-execution-approval-reference-preview:${stableId}`;
}

function buildProviderDryRunPreviewEvidenceReference(
  stableId: ProviderDryRunExecutionMvpId
): `provider-dry-run-execution-evidence-reference-preview:${ProviderDryRunExecutionMvpId}` {
  return `provider-dry-run-execution-evidence-reference-preview:${stableId}`;
}

function buildProviderDryRunPreviewPromptReference(
  stableId: ProviderDryRunExecutionMvpId
): `provider-dry-run-execution-prompt-reference-preview:${ProviderDryRunExecutionMvpId}` {
  return `provider-dry-run-execution-prompt-reference-preview:${stableId}`;
}

function buildCommonRecordFields(seed: ProviderDryRunExecutionSeed) {
  return {
    stableId: seed.stableId,
    capabilityFamily: seed.capabilityFamily,
    workspaceTarget: "Athena Command Center" as const,
    providerSlotLabel: seed.providerSlotLabel,
    backupProviderSlotLabel: seed.backupProviderSlotLabel,
    localPrivateAlternativeLabel: seed.localPrivateAlternativeLabel,
    opaqueCredentialReferenceLabel: seed.opaqueCredentialReferenceLabel,
    credentialReferencePosture: "opaque-reference-only" as const,
    credentialValueState: "not present / not read" as const,
    envVarState: "not read" as const,
    providerKeyState: "not read" as const,
    sourceProviderDryRunAdmissionReviewReference:
      "Backend-owned minimal provider adapter dry-run admission review" as const,
    sourceProviderDryRunAdmissionAcceptancePostureReference:
      "Provider adapter dry-run admission acceptance posture" as const,
    sourceProviderDryRunAdmissionAuditSummaryReference:
      "Provider adapter dry-run admission review audit summary" as const,
    sourceProviderDryRunAdmissionMvpReference:
      "Backend-owned minimal manual-gated provider adapter dry-run admission MVP" as const,
    sourceProviderSelectionCredentialReferenceReviewReference:
      "Backend-owned minimal provider adapter selection and credential reference review" as const,
    sourceTextAdapterAuditApprovalJoinReviewReference:
      "Backend-owned minimal text adapter audit and approval join review" as const,
    sourceManualApprovalDecisionReviewReference:
      "Backend-owned synthetic dry-run manual approval decision review" as const,
    backendOwnedPosture: "backend-owned" as const,
    serverOnlyPosture: "server-only" as const,
    dryRunExecutionPosture: "provider-dry-run-execution" as const,
    manualGatedPosture: "manual-gated" as const,
    fixtureOnlyPosture: "fixture-only" as const,
    inMemoryOnlyPosture: "in-memory-only" as const,
    noProviderSdkImport: "no provider SDK import" as const,
    noLiveProviderExecution: "no live provider execution" as const,
    noModelCalls: "no model calls" as const,
    noPromptSending: "no prompt sending" as const,
    noFrontendRequest: "no frontend request" as const,
    noApiRoute: "no API route" as const,
    noQueueWorkerJobDispatch: "no queue/worker/job dispatch" as const,
    noPersistence: "no persistence" as const,
    noDatabaseWrites: "no database writes" as const,
    noFileWrites: "no file writes" as const,
    noResultPersistence: "no result persistence" as const,
    noAuditPersistence: "no audit persistence" as const,
    noApprovalPersistence: "no approval persistence" as const,
    noApprovalRecording: "no approval recording" as const,
    noApprovalTokenIssuance: "no approval token issuance" as const,
    noApprovalLeaseIssuance: "no approval lease issuance" as const,
    nextReviewRecoveryRequirement:
      "5994-6025 - Backend-Owned Minimal Manual-Gated Provider Adapter Dry-Run Execution Review and Recovery Preview" as const,
  };
}

function getSeed(
  stableId: ProviderDryRunExecutionMvpId
): ProviderDryRunExecutionSeed {
  const seed = PROVIDER_DRY_RUN_EXECUTION_SEEDS.find(
    (candidate) => candidate.stableId === stableId
  );

  if (!seed) {
    throw new Error(`Missing provider dry-run execution seed for ${stableId}.`);
  }

  return seed;
}

export function buildStableProviderDryRunExecutionMvpKey(
  stableId: ProviderDryRunExecutionMvpId
): `backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-mvp:${ProviderDryRunExecutionMvpId}` {
  return `backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-mvp:${stableId}`;
}

function buildExecutionMvpRecord(
  seed: ProviderDryRunExecutionSeed
): MinimalManualGatedProviderAdapterDryRunExecutionMvpRecord {
  return {
    version:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-mvp-v1",
    ...buildCommonRecordFields(seed),
    key: buildStableProviderDryRunExecutionMvpKey(seed.stableId),
    executionMode: EXECUTION_MODE,
    executionState: "executed-provider-dry-run-fixture-in-memory-only",
    providerDryRunExecutionId: buildProviderDryRunExecutionPreviewId(
      seed.stableId
    ),
    providerDryRunAdmissionId: buildProviderDryRunAdmissionPreviewId(
      seed.stableId
    ),
    providerSlotId: buildProviderDryRunPreviewSlotId(seed.stableId, "selected"),
    credentialReferenceId: buildProviderDryRunPreviewCredentialReferenceId(
      seed.stableId
    ),
    executionDigest: buildProviderDryRunPreviewDigest(seed.stableId),
    selectedProviderState: "preview-only / not live-executed",
    credentialReferenceState: "opaque reference only / value not read",
    redactedPromptReference: buildProviderDryRunPreviewPromptReference(
      seed.stableId
    ),
    timestampPosture: "static fixture label only / no real timestamp",
    currentReadiness: CURRENT_READINESS,
    reviewRecoveryPreviewNextStatement: REVIEW_RECOVERY_NEXT_STATEMENT,
  };
}

function buildExecutionInputRecord(
  seed: ProviderDryRunExecutionSeed
): ProviderDryRunExecutionInputRecord {
  return {
    version:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-input-v1",
    ...buildCommonRecordFields(seed),
    key: `backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-input:${seed.stableId}`,
    requestVersion:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-request-v1",
    requestState:
      "deterministic provider dry-run execution fixture request only",
    inputState: "deterministic provider dry-run execution fixture input only",
    executionMode: EXECUTION_MODE,
    frontendRequestState: "not created",
    apiRouteState: "not created",
    dryRunIntentState: "preview-only",
    promptPayloadPosture: "redacted placeholder only",
    promptTransmissionState: "not sent",
    selectedProviderPosture: "preview slot only",
    backupProviderPosture: "preview slot only",
    localPrivateAlternativePosture: "preview slot only",
    credentialValuePosture: "none / not read",
    providerPayloadPosture: "none",
    modelOutputPosture: "none",
    persistenceTargetPosture: "none",
    providerSdkImportState: "not imported",
    explicitNoFrontendRequestNoApiRouteNoProviderCallNoSecretReadStatement:
      "No frontend request. No API route. No provider call. No secret read.",
  };
}

function buildExecutionPlanRecord(
  seed: ProviderDryRunExecutionSeed
): ProviderDryRunExecutionPlanRecord {
  return {
    version:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-plan-v1",
    ...buildCommonRecordFields(seed),
    key: `backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-plan:${seed.stableId}`,
    planVersion:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-plan-v1",
    planState: "preview-only dry-run execution plan",
    executionMode: EXECUTION_MODE,
    supportedCapabilityState: "supported by text adapter boundary",
    dryRunIntentState: "preview-only",
    requiredChecks: [
      "backend-only mode",
      "server-only execution helper",
      "provider dry-run admission review dependency",
      "provider dry-run admission output dependency",
      "preview-only provider slots",
      "opaque credential reference only",
      "redacted prompt envelope only",
      "deterministic fixture response only",
      "manual approval fixture only",
      "manual confirmation fixture only",
      "no live provider execution",
      "no persistence targets",
    ],
    blockedLiveAction: seed.planSummary,
  };
}

function buildExecutionOutputRecord(
  seed: ProviderDryRunExecutionSeed
): ProviderDryRunExecutionOutputRecord {
  return {
    version:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-output-v1",
    ...buildCommonRecordFields(seed),
    key: `backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-output:${seed.stableId}`,
    responseVersion:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-response-v1",
    responseState: "returned by server-only smoke/helper only",
    outputVersion:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-output-v1",
    executionMode: EXECUTION_MODE,
    executionState: "executed-provider-dry-run-fixture-in-memory-only",
    providerDryRunExecutionId: buildProviderDryRunExecutionPreviewId(
      seed.stableId
    ),
    providerDryRunAdmissionId: buildProviderDryRunAdmissionPreviewId(
      seed.stableId
    ),
    providerSlotId: buildProviderDryRunPreviewSlotId(seed.stableId, "selected"),
    credentialReferenceId: buildProviderDryRunPreviewCredentialReferenceId(
      seed.stableId
    ),
    executionDigest: buildProviderDryRunPreviewDigest(seed.stableId),
    selectedProviderState: "preview-only / not live-executed",
    credentialReferenceState: "opaque reference only / value not read",
    providerSdkImportState: "not imported",
    liveProviderExecutionState: "blocked",
    promptTransmissionState: "not sent",
    providerResponseState: "not received from provider",
    modelOutputState: "not generated by provider/model",
    redactedPromptReference: buildProviderDryRunPreviewPromptReference(
      seed.stableId
    ),
    resultReference: buildProviderDryRunPreviewResultReference(seed.stableId),
    auditReference: buildProviderDryRunPreviewAuditReference(seed.stableId),
    approvalReference: buildProviderDryRunPreviewApprovalReference(seed.stableId),
    evidencePacketReference: buildProviderDryRunPreviewEvidenceReference(
      seed.stableId
    ),
    timestampPosture: "static fixture label only / no real timestamp",
    persistenceState: "not implemented",
    explicitDryRunExecutionFixtureOnlyNoProviderOutputNoSecretReadNoPersistenceStatement:
      "Dry-run execution fixture only. No provider output. No secret read. No persistence.",
    currentReadiness: CURRENT_READINESS,
  };
}

function buildExecutionEnvelopeRecord(
  seed: ProviderDryRunExecutionSeed
): ProviderDryRunExecutionEnvelopeRecord {
  return {
    version:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-envelope-v1",
    ...buildCommonRecordFields(seed),
    key: `backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-envelope:${seed.stableId}`,
    envelopeVersion:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-envelope-v1",
    envelopeState: "provider dry-run execution envelope preview only",
    providerDryRunExecutionId: buildProviderDryRunExecutionPreviewId(
      seed.stableId
    ),
    executionDigest: buildProviderDryRunPreviewDigest(seed.stableId),
    redactedPromptEnvelopeLabel:
      "redacted prompt envelope fixture / provider dry-run execution preview",
    promptPayloadPosture: "redacted placeholder only",
    promptTransmissionState: "not sent",
    providerPayloadPosture: "none",
    providerResponseState: "not received from provider",
    modelOutputState: "not generated by provider/model",
    redactedPromptReference: buildProviderDryRunPreviewPromptReference(
      seed.stableId
    ),
    resultReference: buildProviderDryRunPreviewResultReference(seed.stableId),
    auditReference: buildProviderDryRunPreviewAuditReference(seed.stableId),
    approvalReference: buildProviderDryRunPreviewApprovalReference(seed.stableId),
    evidencePacketReference: buildProviderDryRunPreviewEvidenceReference(
      seed.stableId
    ),
  };
}

function buildFixtureResponseRecord(
  seed: ProviderDryRunExecutionSeed
): ProviderDryRunFixtureResponseRecord {
  return {
    version:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-fixture-response-v1",
    ...buildCommonRecordFields(seed),
    key: `backend-owned-minimal-manual-gated-provider-adapter-dry-run-fixture-response:${seed.stableId}`,
    fixtureResponseVersion:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-fixture-response-v1",
    fixtureResponseState: "deterministic dry-run fixture response only",
    providerDryRunExecutionId: buildProviderDryRunExecutionPreviewId(
      seed.stableId
    ),
    executionDigest: buildProviderDryRunPreviewDigest(seed.stableId),
    selectedProviderState: "preview-only / not live-executed",
    fixtureProviderResponse: seed.fixtureProviderResponse,
    providerResponseState: "not received from provider",
    modelOutputState: "not generated by provider/model",
    resultReference: buildProviderDryRunPreviewResultReference(seed.stableId),
  };
}

function buildBlockedLiveExecutionSummaryRecord(
  seed: ProviderDryRunExecutionSeed
): ProviderDryRunBlockedLiveExecutionSummaryRecord {
  return {
    version:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-blocked-live-execution-summary-v1",
    ...buildCommonRecordFields(seed),
    key: `backend-owned-minimal-manual-gated-provider-adapter-dry-run-blocked-live-execution-summary:${seed.stableId}`,
    blockedLiveExecutionVersion:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-blocked-live-execution-summary-v1",
    blockedLiveExecutionState: "preview-only blocked live execution summary",
    executionState: "executed-provider-dry-run-fixture-in-memory-only",
    blockedLiveActions: cloneList(BLOCKED_LIVE_ACTIONS),
  };
}

function buildEvidencePreviewRecord(
  seed: ProviderDryRunExecutionSeed
): ProviderDryRunEvidencePreviewRecord {
  return {
    version:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-evidence-preview-v1",
    ...buildCommonRecordFields(seed),
    key: `backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-evidence-preview:${seed.stableId}`,
    evidenceVersion:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-evidence-preview-v1",
    evidencePreviewState: "preview-only / not persisted",
    evidenceSummaryLines: [
      seed.providerSlotLabel,
      seed.backupProviderSlotLabel,
      seed.localPrivateAlternativeLabel,
      seed.opaqueCredentialReferenceLabel,
      "redacted prompt envelope fixture / provider dry-run execution preview",
      "deterministic dry-run fixture response only",
      "live provider execution is blocked",
      CURRENT_READINESS,
    ],
    evidenceReference: buildProviderDryRunPreviewEvidenceReference(seed.stableId),
  };
}

function buildAuditPreviewRecord(
  seed: ProviderDryRunExecutionSeed
): ProviderDryRunAuditPreviewRecord {
  return {
    version:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-audit-preview-v1",
    ...buildCommonRecordFields(seed),
    key: `backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-audit-preview:${seed.stableId}`,
    auditVersion:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-audit-preview-v1",
    auditPreviewState: "preview-only / not persisted",
    auditSummaryLines: [
      "server-only provider dry-run execution helper exists",
      "provider dry-run admission review dependency exists",
      "provider dry-run admission output dependency exists",
      "no real approval request exists",
      "no real approval recording exists",
      "no provider SDK imports",
      "no live provider execution",
      "no persistence",
    ],
    auditReference: buildProviderDryRunPreviewAuditReference(seed.stableId),
  };
}

function buildApprovalPreviewRecord(
  seed: ProviderDryRunExecutionSeed
): ProviderDryRunApprovalPreviewRecord {
  return {
    version:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-approval-preview-v1",
    ...buildCommonRecordFields(seed),
    key: `backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-approval-preview:${seed.stableId}`,
    approvalVersion:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-approval-preview-v1",
    approvalPreviewState: "preview-only / not persisted",
    approvalSummaryLines: [
      "approval fixture is preview-only",
      "manual confirmation fixture is preview-only",
      "no real approval request exists",
      "no real approval recording exists",
      "approval token is not issued",
      "approval lease is not created",
    ],
    approvalReference: buildProviderDryRunPreviewApprovalReference(seed.stableId),
    approvalFixtureState: "preview-only",
    manualConfirmationFixtureState: "preview-only",
    approvalTokenState: "not issued",
    approvalLeaseState: "not created",
    approvalRecordingState: "not recorded",
  };
}

function buildSafetyGateSummaryRecord(
  seed: ProviderDryRunExecutionSeed
): ProviderDryRunSafetyGateSummaryRecord {
  return {
    version:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-safety-gate-summary-v1",
    ...buildCommonRecordFields(seed),
    key: `backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-safety-gate-summary:${seed.stableId}`,
    gateSummaryVersion:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-safety-gate-summary-v1",
    gateSummaryState: "preview-only blocked dry-run execution summary",
    topGateLabels: cloneList(GATE_SUMMARY_LINES),
    blockedLiveActions: cloneList(BLOCKED_LIVE_ACTIONS),
  };
}

function buildExecutionRequestRecord(
  seed: ProviderDryRunExecutionSeed
): ProviderDryRunExecutionRequestRecord {
  return {
    version:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-request-v1",
    ...buildCommonRecordFields(seed),
    key: `backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-request:${seed.stableId}`,
    requestVersion:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-request-v1",
    requestState:
      "deterministic provider dry-run execution fixture request only",
    providerDryRunExecutionMvpId: seed.stableId,
    executionMode: EXECUTION_MODE,
    frontendRequestState: "not created",
    apiRouteState: "not created",
    promptPayloadPosture: "redacted placeholder only",
    promptTransmissionState: "not sent",
    selectedProviderPosture: "preview slot only",
    credentialReferencePosture: "opaque-reference-only",
    credentialValuePosture: "none / not read",
    providerPayloadPosture: "none",
    modelOutputPosture: "none",
    persistenceTargetPosture: "none",
    explicitNoFrontendRequestNoApiRouteNoProviderCallNoSecretReadStatement:
      "No frontend request. No API route. No provider call. No secret read.",
  };
}

function buildExecutionResponseRecord(
  seed: ProviderDryRunExecutionSeed
): ProviderDryRunExecutionResponseRecord {
  return {
    version:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-response-v1",
    ...buildCommonRecordFields(seed),
    key: `backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-response:${seed.stableId}`,
    responseVersion:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-response-v1",
    providerDryRunExecutionMvpId: seed.stableId,
    responseState: "returned by server-only smoke/helper only",
    executionMode: EXECUTION_MODE,
    executionState: "executed-provider-dry-run-fixture-in-memory-only",
    selectedProviderState: "preview-only / not live-executed",
    credentialReferenceState: "opaque reference only / value not read",
    providerSdkImportState: "not imported",
    providerResponseState: "not received from provider",
    modelOutputState: "not generated by provider/model",
    resultPersistenceState: "not implemented",
    auditPersistenceState: "not implemented",
    approvalPersistenceState: "not implemented",
    databaseWriteState: "not implemented",
    fileWriteState: "not implemented",
    explicitDryRunExecutionFixtureOnlyNoProviderOutputNoSecretReadNoPersistenceStatement:
      "Dry-run execution fixture only. No provider output. No secret read. No persistence.",
  };
}

function buildExecutionErrorRecord(
  seed: ProviderDryRunExecutionSeed
): ProviderDryRunExecutionErrorRecord {
  return {
    version:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-error-v1",
    ...buildCommonRecordFields(seed),
    key: `backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-error:${seed.stableId}`,
    errorVersion:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-error-v1",
    providerDryRunExecutionMvpId: seed.stableId,
    errorState: "deterministic preview only",
    failedGateExamples: [
      "provider-dry-run-admission-review-dependency",
      "provider-dry-run-admission-output-dependency",
      "credential-reference-opaque-only-mode",
      "provider-sdk-not-imported",
      "live-provider-execution-blocked",
    ],
    missingProviderDryRunAdmissionReviewExample:
      "Missing provider dry-run admission review dependency.",
    missingProviderDryRunAdmissionOutputExample:
      "Missing provider dry-run admission output dependency.",
    missingProviderSlotExample: "Missing preview-only provider slot fixture.",
    missingOpaqueCredentialReferenceExample:
      "Missing opaque credential reference label fixture.",
    credentialValueDetectedExample:
      "Credential value detected in deterministic preview input.",
    envVarReadAttemptedExample:
      "Env var read attempted inside provider dry-run execution helper.",
    providerSdkImportAttemptedExample:
      "Provider SDK import attempted inside provider dry-run execution helper.",
    providerCallAttemptedExample:
      "Live provider call attempted inside provider dry-run execution helper.",
    modelCallAttemptedExample:
      "Model call attempted inside provider dry-run execution helper.",
    promptTransmissionAttemptedExample:
      "Prompt transmission attempted outside the redacted preview envelope.",
    persistenceAttemptedExample:
      "Persistence attempted for deterministic dry-run execution preview output.",
    databaseWriteAttemptedExample:
      "Database write attempted for deterministic dry-run execution preview output.",
    fileWriteAttemptedExample:
      "File write attempted for deterministic dry-run execution preview output.",
    queueWorkerJobAttemptedExample:
      "Queue, worker, or job dispatch attempted for deterministic dry-run execution preview output.",
    retryPosture: RETRY_POSTURE,
    fallbackPosture: FALLBACK_POSTURE,
    explicitNoLiveErrorNoRetryNoFallbackStatement:
      "No live error. No retry. No fallback.",
  };
}

const GATE_SEEDS = [
  {
    gateId: "backend-only-boundary",
    label: "backend-only boundary",
    owner: "backend-owned execution MVP",
    requiredState: "backend-only execution path required",
    currentState: () => "backend-only fixture path only",
    evidence: () => "provider adapter dry-run execution is backend-only",
    blockedLiveAction: "frontend-callable execution",
  },
  {
    gateId: "server-only-dry-run-execution-module-boundary",
    label: "server-only dry-run execution module boundary",
    owner: "backend-owned execution MVP",
    requiredState: "server-only adapters required",
    currentState: () => "server-only provider dry-run execution helper exists",
    evidence: () => "server-only provider dry-run execution helper exists",
    blockedLiveAction: "client import of execution helper",
  },
  {
    gateId: "provider-dry-run-execution-fixture-mode",
    label: "provider dry-run execution fixture mode",
    owner: "backend-owned execution MVP",
    requiredState: "deterministic fixture-only execution required",
    currentState: () => "provider dry-run execution is deterministic fixture-only",
    evidence: () => "provider dry-run execution is deterministic fixture-only",
    blockedLiveAction: "live provider execution mode",
  },
  {
    gateId: "provider-dry-run-admission-review-dependency",
    label: "provider dry-run admission review dependency",
    owner: "backend-owned execution MVP",
    requiredState: "provider dry-run admission review dependency exists",
    currentState: () => "provider dry-run admission review dependency exists",
    evidence: () => "Backend-owned minimal provider adapter dry-run admission review",
    blockedLiveAction: "execution without admission review dependency",
  },
  {
    gateId: "provider-dry-run-admission-output-dependency",
    label: "provider dry-run admission output dependency",
    owner: "backend-owned execution MVP",
    requiredState: "provider dry-run admission output dependency exists",
    currentState: () => "provider dry-run admission output dependency exists",
    evidence: () => "Backend-owned minimal manual-gated provider adapter dry-run admission MVP",
    blockedLiveAction: "execution without admission output dependency",
  },
  {
    gateId: "credential-reference-opaque-only-mode",
    label: "credential reference opaque-only mode",
    owner: "backend-owned execution MVP",
    requiredState: "opaque credential references only",
    currentState: () => "credential reference is opaque label only",
    evidence: (seed) => seed.opaqueCredentialReferenceLabel,
    blockedLiveAction: "credential value inspection",
  },
  {
    gateId: "deterministic-provider-dry-run-execution-id",
    label: "deterministic provider dry-run execution id",
    owner: "backend-owned execution MVP",
    requiredState: "deterministic preview id only",
    currentState: (seed) => buildProviderDryRunExecutionPreviewId(seed.stableId),
    evidence: (seed) => buildProviderDryRunExecutionPreviewId(seed.stableId),
    blockedLiveAction: "runtime execution id generation",
  },
  {
    gateId: "deterministic-provider-dry-run-admission-id",
    label: "deterministic provider dry-run admission id",
    owner: "backend-owned execution MVP",
    requiredState: "deterministic preview id only",
    currentState: (seed) => buildProviderDryRunAdmissionPreviewId(seed.stableId),
    evidence: (seed) => buildProviderDryRunAdmissionPreviewId(seed.stableId),
    blockedLiveAction: "runtime admission id generation",
  },
  {
    gateId: "deterministic-provider-slot-id",
    label: "deterministic provider slot id",
    owner: "backend-owned execution MVP",
    requiredState: "deterministic preview id only",
    currentState: (seed) => buildProviderDryRunPreviewSlotId(seed.stableId, "selected"),
    evidence: (seed) => buildProviderDryRunPreviewSlotId(seed.stableId, "selected"),
    blockedLiveAction: "runtime provider slot id generation",
  },
  {
    gateId: "deterministic-credential-reference-id",
    label: "deterministic credential reference id",
    owner: "backend-owned execution MVP",
    requiredState: "deterministic opaque reference id only",
    currentState: (seed) =>
      buildProviderDryRunPreviewCredentialReferenceId(seed.stableId),
    evidence: (seed) =>
      buildProviderDryRunPreviewCredentialReferenceId(seed.stableId),
    blockedLiveAction: "credential value expansion",
  },
  {
    gateId: "deterministic-execution-digest",
    label: "deterministic execution digest",
    owner: "backend-owned execution MVP",
    requiredState: "deterministic preview digest only",
    currentState: (seed) => buildProviderDryRunPreviewDigest(seed.stableId),
    evidence: (seed) => buildProviderDryRunPreviewDigest(seed.stableId),
    blockedLiveAction: "runtime digest generation",
  },
  {
    gateId: "supported-capability-family",
    label: "supported capability family",
    owner: "backend-owned execution MVP",
    requiredState: "supported by text adapter boundary",
    currentState: () => "supported by text adapter boundary",
    evidence: (seed) => seed.capabilityFamily,
    blockedLiveAction: "unsupported capability execution",
  },
  {
    gateId: "selected-provider-slot-preview-only",
    label: "selected provider slot preview-only",
    owner: "backend-owned execution MVP",
    requiredState: "preview-only provider slot required",
    currentState: () => "selected provider slot is preview-only",
    evidence: (seed) => seed.providerSlotLabel,
    blockedLiveAction: "selected provider live execution",
  },
  {
    gateId: "backup-provider-slot-preview-only",
    label: "backup provider slot preview-only",
    owner: "backend-owned execution MVP",
    requiredState: "preview-only backup provider slot required",
    currentState: () => "backup provider slot is preview-only",
    evidence: (seed) => seed.backupProviderSlotLabel,
    blockedLiveAction: "backup provider live execution",
  },
  {
    gateId: "local-private-alternative-preview-only",
    label: "local/private alternative preview-only",
    owner: "backend-owned execution MVP",
    requiredState: "preview-only local/private alternative required",
    currentState: () => "local/private alternative is preview-only",
    evidence: (seed) => seed.localPrivateAlternativeLabel,
    blockedLiveAction: "local/private live execution",
  },
  {
    gateId: "dry-run-intent-preview-only",
    label: "dry-run intent preview-only",
    owner: "backend-owned execution MVP",
    requiredState: "preview-only intent required",
    currentState: () => "preview-only",
    evidence: () => "preview-only intent",
    blockedLiveAction: "non-preview execution intent",
  },
  {
    gateId: "fixture-response-only",
    label: "fixture response only",
    owner: "backend-owned execution MVP",
    requiredState: "deterministic dry-run fixture response only",
    currentState: () => "deterministic dry-run fixture response only",
    evidence: (seed) => seed.fixtureProviderResponse,
    blockedLiveAction: "provider-backed response generation",
  },
  {
    gateId: "live-provider-execution-blocked",
    label: "live provider execution blocked",
    owner: "backend-owned execution MVP",
    requiredState: "blocked live provider execution",
    currentState: () => "blocked",
    evidence: () => "live provider execution is blocked",
    blockedLiveAction: "live provider execution",
  },
  {
    gateId: "credential-value-absent",
    label: "credential value absent",
    owner: "backend-owned execution MVP",
    requiredState: "credential value is not present",
    currentState: () => "not present / not read",
    evidence: () => "credential value is not present",
    blockedLiveAction: "credential value read",
  },
  {
    gateId: "credential-value-not-read",
    label: "credential value not read",
    owner: "backend-owned execution MVP",
    requiredState: "credential value is not read",
    currentState: () => "not present / not read",
    evidence: () => "credential value is not read",
    blockedLiveAction: "credential value read",
  },
  {
    gateId: "env-vars-not-read",
    label: "env vars not read",
    owner: "backend-owned execution MVP",
    requiredState: "env vars are not read",
    currentState: () => "not read",
    evidence: () => "env vars are not read",
    blockedLiveAction: "env var read",
  },
  {
    gateId: "provider-key-not-read",
    label: "provider key not read",
    owner: "backend-owned execution MVP",
    requiredState: "provider key is not read",
    currentState: () => "not read",
    evidence: () => "provider key is not read",
    blockedLiveAction: "provider key read",
  },
  {
    gateId: "redacted-prompt-envelope-present",
    label: "redacted prompt envelope present",
    owner: "backend-owned execution MVP",
    requiredState: "redacted prompt envelope fixture required",
    currentState: () =>
      "redacted prompt envelope fixture / provider dry-run execution preview",
    evidence: () =>
      "redacted prompt envelope fixture / provider dry-run execution preview",
    blockedLiveAction: "plaintext prompt envelope",
  },
  {
    gateId: "prompt-not-sent",
    label: "prompt not sent",
    owner: "backend-owned execution MVP",
    requiredState: "prompt transmission must remain blocked",
    currentState: () => "not sent",
    evidence: () => "no prompt sending",
    blockedLiveAction: "prompt transmission",
  },
  {
    gateId: "provider-sdk-not-imported",
    label: "provider SDK not imported",
    owner: "backend-owned execution MVP",
    requiredState: "provider SDK imports remain absent",
    currentState: () => "not imported",
    evidence: () => "no provider SDK imports",
    blockedLiveAction: "provider SDK import",
  },
  {
    gateId: "provider-response-not-received-from-provider",
    label: "provider response not received from provider",
    owner: "backend-owned execution MVP",
    requiredState: "provider response remains absent",
    currentState: () => "not received from provider",
    evidence: () => "provider response is not received from provider",
    blockedLiveAction: "provider response receipt",
  },
  {
    gateId: "model-output-not-generated-by-provider-model",
    label: "model output not generated by provider/model",
    owner: "backend-owned execution MVP",
    requiredState: "model output remains absent",
    currentState: () => "not generated by provider/model",
    evidence: () => "model output is not generated by provider/model",
    blockedLiveAction: "provider/model output generation",
  },
  {
    gateId: "manual-approval-fixture",
    label: "manual approval fixture",
    owner: "backend-owned execution MVP",
    requiredState: "approval fixture required",
    currentState: () => "preview-only",
    evidence: () => "approval fixture is preview-only",
    blockedLiveAction: "real approval request",
  },
  {
    gateId: "manual-confirmation-fixture",
    label: "manual confirmation fixture",
    owner: "backend-owned execution MVP",
    requiredState: "manual confirmation fixture required",
    currentState: () => "preview-only",
    evidence: () => "manual confirmation fixture is preview-only",
    blockedLiveAction: "real approval confirmation",
  },
  {
    gateId: "in-memory-only-execution-reference",
    label: "in-memory only execution reference",
    owner: "backend-owned execution MVP",
    requiredState: "in-memory only execution reference required",
    currentState: () => "preview-only / not persisted",
    evidence: () => "dry-run fixture response is produced in memory only",
    blockedLiveAction: "persistent execution reference",
  },
  {
    gateId: "no-real-approval-request",
    label: "no real approval request",
    owner: "backend-owned execution MVP",
    requiredState: "no real approval request exists",
    currentState: () => "no real approval request exists",
    evidence: () => "no real approval request exists",
    blockedLiveAction: "real approval request",
  },
  {
    gateId: "no-real-approval-recording",
    label: "no real approval recording",
    owner: "backend-owned execution MVP",
    requiredState: "no real approval recording exists",
    currentState: () => "no real approval recording exists",
    evidence: () => "no real approval recording exists",
    blockedLiveAction: "real approval recording",
  },
  {
    gateId: "no-approval-token-issuance",
    label: "no approval token issuance",
    owner: "backend-owned execution MVP",
    requiredState: "no approval token issuance",
    currentState: () => "not issued",
    evidence: () => "approval token is not issued",
    blockedLiveAction: "approval token issuance",
  },
  {
    gateId: "no-approval-lease-issuance",
    label: "no approval lease issuance",
    owner: "backend-owned execution MVP",
    requiredState: "no approval lease issuance",
    currentState: () => "not created",
    evidence: () => "approval lease is not created",
    blockedLiveAction: "approval lease issuance",
  },
  {
    gateId: "no-frontend-request",
    label: "no frontend request",
    owner: "backend-owned execution MVP",
    requiredState: "no frontend request is created",
    currentState: () => "not created",
    evidence: () => "no frontend request is created",
    blockedLiveAction: "frontend request creation",
  },
  {
    gateId: "no-api-route",
    label: "no API route",
    owner: "backend-owned execution MVP",
    requiredState: "no API route is created",
    currentState: () => "not created",
    evidence: () => "no API route is created",
    blockedLiveAction: "API route creation",
  },
  {
    gateId: "no-fetch-network",
    label: "no fetch/network",
    owner: "backend-owned execution MVP",
    requiredState: "frontend fetch/network blocked",
    currentState: () => "blocked",
    evidence: () => "no frontend fetch/network call",
    blockedLiveAction: "frontend fetch/network call",
  },
  {
    gateId: "no-provider-sdk-import",
    label: "no provider SDK import",
    owner: "backend-owned execution MVP",
    requiredState: "no provider SDK import",
    currentState: () => "not imported",
    evidence: () => "no provider SDK imports",
    blockedLiveAction: "provider SDK import",
  },
  {
    gateId: "no-live-provider-execution",
    label: "no live provider execution",
    owner: "backend-owned execution MVP",
    requiredState: "no live provider execution",
    currentState: () => "blocked",
    evidence: () => "no live provider execution",
    blockedLiveAction: "live provider execution",
  },
  {
    gateId: "no-model-call",
    label: "no model call",
    owner: "backend-owned execution MVP",
    requiredState: "no model call",
    currentState: () => "blocked",
    evidence: () => "no LLM/model calls",
    blockedLiveAction: "model call",
  },
  {
    gateId: "no-prompt-sending",
    label: "no prompt sending",
    owner: "backend-owned execution MVP",
    requiredState: "no prompt sending",
    currentState: () => "blocked",
    evidence: () => "no prompt sending",
    blockedLiveAction: "prompt sending",
  },
  {
    gateId: "no-queue-dispatch",
    label: "no queue dispatch",
    owner: "backend-owned execution MVP",
    requiredState: "no queue dispatch",
    currentState: () => "blocked",
    evidence: () => "no queue dispatch",
    blockedLiveAction: "queue dispatch",
  },
  {
    gateId: "no-worker-dispatch",
    label: "no worker dispatch",
    owner: "backend-owned execution MVP",
    requiredState: "no worker dispatch",
    currentState: () => "blocked",
    evidence: () => "no worker dispatch",
    blockedLiveAction: "worker dispatch",
  },
  {
    gateId: "no-job-execution",
    label: "no job execution",
    owner: "backend-owned execution MVP",
    requiredState: "no job execution",
    currentState: () => "blocked",
    evidence: () => "no job execution",
    blockedLiveAction: "job execution",
  },
  {
    gateId: "no-result-persistence",
    label: "no result persistence",
    owner: "backend-owned execution MVP",
    requiredState: "no result persistence",
    currentState: () => "not implemented",
    evidence: () => "no result persistence",
    blockedLiveAction: "result persistence",
  },
  {
    gateId: "no-audit-persistence",
    label: "no audit persistence",
    owner: "backend-owned execution MVP",
    requiredState: "no audit persistence",
    currentState: () => "not implemented",
    evidence: () => "no audit persistence",
    blockedLiveAction: "audit persistence",
  },
  {
    gateId: "no-approval-persistence",
    label: "no approval persistence",
    owner: "backend-owned execution MVP",
    requiredState: "no approval persistence",
    currentState: () => "not implemented",
    evidence: () => "no approval persistence",
    blockedLiveAction: "approval persistence",
  },
  {
    gateId: "no-database-write",
    label: "no database write",
    owner: "backend-owned execution MVP",
    requiredState: "no database write",
    currentState: () => "not implemented",
    evidence: () => "no database writes",
    blockedLiveAction: "database write",
  },
  {
    gateId: "no-file-write",
    label: "no file write",
    owner: "backend-owned execution MVP",
    requiredState: "no file write",
    currentState: () => "not implemented",
    evidence: () => "no file writes",
    blockedLiveAction: "file write",
  },
  {
    gateId: "single-run-lock-preview",
    label: "single-run lock preview",
    owner: "backend-owned execution MVP",
    requiredState: "single-run lock preview required",
    currentState: () => "preview-only single-run lock marker",
    evidence: () => "single-run lock preview",
    blockedLiveAction: "parallel execution overlap",
  },
  {
    gateId: "idempotency-replay-preview",
    label: "idempotency/replay preview",
    owner: "backend-owned execution MVP",
    requiredState: "idempotency and replay preview required",
    currentState: () => "preview-only idempotency and replay marker",
    evidence: () => "idempotency/replay preview",
    blockedLiveAction: "replay execution",
  },
  {
    gateId: "timeout-cancel-preview",
    label: "timeout/cancel preview",
    owner: "backend-owned execution MVP",
    requiredState: "timeout and cancel preview required",
    currentState: () => "preview-only timeout and cancel marker",
    evidence: () => "timeout/cancel preview",
    blockedLiveAction: "live timeout handling",
  },
  {
    gateId: "privacy-redaction-preview",
    label: "privacy/redaction preview",
    owner: "backend-owned execution MVP",
    requiredState: "privacy and redaction preview required",
    currentState: () => "preview-only privacy and redaction marker",
    evidence: () => "privacy/redaction preview",
    blockedLiveAction: "unredacted prompt transmission",
  },
  {
    gateId: "kill-switch-fixture",
    label: "kill switch fixture",
    owner: "backend-owned execution MVP",
    requiredState: "kill switch required",
    currentState: () => "preview-only kill switch fixture available",
    evidence: () => "kill switch required",
    blockedLiveAction: "unguarded live provider execution",
  },
] as const satisfies readonly GateSeed[];

const READINESS_SEEDS = [
  {
    readinessId: "server-only-dry-run-execution-helper-state",
    label: "server-only dry-run execution helper state",
    state: "implemented / server-only / deterministic",
    evidence: "server-only provider dry-run execution helper exists",
  },
  {
    readinessId: "provider-dry-run-admission-review-dependency-state",
    label: "provider dry-run admission review dependency",
    state: "available / required",
    evidence: "Backend-owned minimal provider adapter dry-run admission review",
  },
  {
    readinessId: "provider-dry-run-execution-input-state",
    label: "dry-run execution input state",
    state: "implemented / deterministic fixture input only",
    evidence: "Provider adapter dry-run execution input",
  },
  {
    readinessId: "provider-dry-run-execution-plan-state",
    label: "dry-run execution plan state",
    state: "implemented / preview-only plan",
    evidence: "Provider adapter dry-run execution plan",
  },
  {
    readinessId: "provider-dry-run-execution-output-state",
    label: "dry-run execution output state",
    state: "implemented / in-memory fixture output only",
    evidence: "Provider adapter dry-run execution output",
  },
  {
    readinessId: "provider-dry-run-execution-envelope-state",
    label: "dry-run execution envelope state",
    state: "implemented / redacted preview only",
    evidence: "Provider adapter dry-run execution envelope",
  },
  {
    readinessId: "provider-dry-run-fixture-response-state",
    label: "dry-run fixture response state",
    state: "implemented / deterministic fixture response only",
    evidence: "Provider adapter dry-run fixture response",
  },
  {
    readinessId: "provider-dry-run-blocked-live-execution-summary-state",
    label: "dry-run blocked live execution summary state",
    state: "implemented / blocked live execution summary only",
    evidence: "Provider adapter dry-run blocked live execution summary",
  },
  {
    readinessId: "provider-dry-run-evidence-preview-state",
    label: "evidence preview state",
    state: "implemented / preview-only",
    evidence: "Provider adapter dry-run execution evidence preview",
  },
  {
    readinessId: "provider-dry-run-audit-preview-state",
    label: "audit preview state",
    state: "implemented / preview-only",
    evidence: "audit preview required",
  },
  {
    readinessId: "provider-dry-run-approval-preview-state",
    label: "approval preview state",
    state: "implemented / preview-only",
    evidence: "approval fixture is preview-only",
  },
  {
    readinessId: "credential-value-boundary-state",
    label: "credential value boundary state",
    state: "blocked / not present / not read",
    evidence: "credential value is not read",
  },
  {
    readinessId: "env-var-boundary-state",
    label: "env var boundary state",
    state: "blocked / not read",
    evidence: "env vars are not read",
  },
  {
    readinessId: "provider-key-boundary-state",
    label: "provider key boundary state",
    state: "blocked / not read",
    evidence: "provider key is not read",
  },
  {
    readinessId: "provider-sdk-boundary-state",
    label: "provider SDK boundary state",
    state: "blocked / not imported",
    evidence: "no provider SDK imports",
  },
  {
    readinessId: "live-provider-execution-boundary-state",
    label: "live provider execution boundary state",
    state: "blocked / not executable",
    evidence: "live provider execution is blocked",
  },
  {
    readinessId: "prompt-boundary-state",
    label: "prompt boundary state",
    state: "blocked / redacted preview only",
    evidence: "no prompt sending",
  },
  {
    readinessId: "model-boundary-state",
    label: "model boundary state",
    state: "blocked / no provider/model output",
    evidence: "no model calls",
  },
  {
    readinessId: "frontend-request-boundary-state",
    label: "frontend request boundary state",
    state: "blocked / not created",
    evidence: "no frontend request is created",
  },
  {
    readinessId: "api-route-boundary-state",
    label: "API route boundary state",
    state: "blocked / not created",
    evidence: "no API route is created",
  },
  {
    readinessId: "queue-boundary-state",
    label: "queue boundary state",
    state: "blocked / not dispatched",
    evidence: "no queue dispatch",
  },
  {
    readinessId: "worker-boundary-state",
    label: "worker boundary state",
    state: "blocked / not dispatched",
    evidence: "no worker dispatch",
  },
  {
    readinessId: "job-boundary-state",
    label: "job boundary state",
    state: "blocked / not executed",
    evidence: "no job execution",
  },
  {
    readinessId: "result-persistence-boundary-state",
    label: "result persistence boundary state",
    state: "blocked / not implemented",
    evidence: "no result persistence",
  },
  {
    readinessId: "audit-persistence-boundary-state",
    label: "audit persistence boundary state",
    state: "blocked / not implemented",
    evidence: "no audit persistence",
  },
  {
    readinessId: "approval-persistence-boundary-state",
    label: "approval persistence boundary state",
    state: "blocked / not implemented",
    evidence: "no approval persistence",
  },
  {
    readinessId: "database-boundary-state",
    label: "database boundary state",
    state: "blocked / not implemented",
    evidence: "no database writes",
  },
  {
    readinessId: "file-boundary-state",
    label: "file boundary state",
    state: "blocked / not implemented",
    evidence: "no file writes",
  },
] as const satisfies readonly ReadinessSeed[];

function buildExecutionGateRecord(
  seed: ProviderDryRunExecutionSeed,
  gateSeed: GateSeed
): ProviderDryRunExecutionGateRecord {
  return {
    version:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-gate-v1",
    ...buildCommonRecordFields(seed),
    key: `backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-gate:${seed.stableId}:${gateSeed.gateId}`,
    gateVersion:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-gate-v1",
    gateId: gateSeed.gateId,
    label: gateSeed.label,
    owner: gateSeed.owner,
    requiredState: gateSeed.requiredState,
    currentState: gateSeed.currentState(seed),
    evidence: gateSeed.evidence(seed),
    blockedLiveAction: gateSeed.blockedLiveAction,
  };
}

function buildReadinessRecord(
  seed: ProviderDryRunExecutionSeed,
  readinessSeed: ReadinessSeed
): ProviderDryRunReadinessMatrixRecord {
  return {
    version:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-readiness-matrix-v1",
    ...buildCommonRecordFields(seed),
    key: `backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-readiness:${seed.stableId}:${readinessSeed.readinessId}`,
    readinessVersion:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-readiness-matrix-v1",
    readinessId: readinessSeed.readinessId,
    label: readinessSeed.label,
    state: readinessSeed.state,
    evidence: readinessSeed.evidence,
    nextSafeAction: REVIEW_RECOVERY_NEXT_STATEMENT,
  };
}

export function listMinimalManualGatedProviderAdapterDryRunExecutionMvpRecords(): readonly MinimalManualGatedProviderAdapterDryRunExecutionMvpRecord[] {
  return cloneList(PROVIDER_DRY_RUN_EXECUTION_SEEDS.map(buildExecutionMvpRecord));
}

export function listProviderDryRunExecutionInputs(): readonly ProviderDryRunExecutionInputRecord[] {
  return cloneList(PROVIDER_DRY_RUN_EXECUTION_SEEDS.map(buildExecutionInputRecord));
}

export function listProviderDryRunExecutionPlans(): readonly ProviderDryRunExecutionPlanRecord[] {
  return cloneList(PROVIDER_DRY_RUN_EXECUTION_SEEDS.map(buildExecutionPlanRecord));
}

export function listProviderDryRunExecutionOutputs(): readonly ProviderDryRunExecutionOutputRecord[] {
  return cloneList(PROVIDER_DRY_RUN_EXECUTION_SEEDS.map(buildExecutionOutputRecord));
}

export function listProviderDryRunExecutionEnvelopes(): readonly ProviderDryRunExecutionEnvelopeRecord[] {
  return cloneList(PROVIDER_DRY_RUN_EXECUTION_SEEDS.map(buildExecutionEnvelopeRecord));
}

export function listProviderDryRunFixtureResponses(): readonly ProviderDryRunFixtureResponseRecord[] {
  return cloneList(PROVIDER_DRY_RUN_EXECUTION_SEEDS.map(buildFixtureResponseRecord));
}

export function listProviderDryRunBlockedLiveExecutionSummaries(): readonly ProviderDryRunBlockedLiveExecutionSummaryRecord[] {
  return cloneList(
    PROVIDER_DRY_RUN_EXECUTION_SEEDS.map(buildBlockedLiveExecutionSummaryRecord)
  );
}

export function listProviderDryRunEvidencePreviews(): readonly ProviderDryRunEvidencePreviewRecord[] {
  return cloneList(PROVIDER_DRY_RUN_EXECUTION_SEEDS.map(buildEvidencePreviewRecord));
}

export function listProviderDryRunAuditPreviews(): readonly ProviderDryRunAuditPreviewRecord[] {
  return cloneList(PROVIDER_DRY_RUN_EXECUTION_SEEDS.map(buildAuditPreviewRecord));
}

export function listProviderDryRunApprovalPreviews(): readonly ProviderDryRunApprovalPreviewRecord[] {
  return cloneList(PROVIDER_DRY_RUN_EXECUTION_SEEDS.map(buildApprovalPreviewRecord));
}

export function listProviderDryRunExecutionGates(): readonly ProviderDryRunExecutionGateRecord[] {
  return cloneList(
    PROVIDER_DRY_RUN_EXECUTION_SEEDS.flatMap((seed) =>
      GATE_SEEDS.map((gateSeed) => buildExecutionGateRecord(seed, gateSeed))
    )
  );
}

export function listProviderDryRunExecutionReadinessMatrixRecords(): readonly ProviderDryRunReadinessMatrixRecord[] {
  return cloneList(
    PROVIDER_DRY_RUN_EXECUTION_SEEDS.flatMap((seed) =>
      READINESS_SEEDS.map((readinessSeed) =>
        buildReadinessRecord(seed, readinessSeed)
      )
    )
  );
}

export function listProviderDryRunExecutionRequestRecords(): readonly ProviderDryRunExecutionRequestRecord[] {
  return cloneList(PROVIDER_DRY_RUN_EXECUTION_SEEDS.map(buildExecutionRequestRecord));
}

export function listProviderDryRunExecutionResponseRecords(): readonly ProviderDryRunExecutionResponseRecord[] {
  return cloneList(PROVIDER_DRY_RUN_EXECUTION_SEEDS.map(buildExecutionResponseRecord));
}

export function listProviderDryRunExecutionErrorRecords(): readonly ProviderDryRunExecutionErrorRecord[] {
  return cloneList(PROVIDER_DRY_RUN_EXECUTION_SEEDS.map(buildExecutionErrorRecord));
}

export function buildProviderDryRunExecutionSummary(): ProviderDryRunExecutionSummary {
  return {
    version:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-summary-v1",
    highestDetectedPhase:
      BACKEND_OWNED_MINIMAL_MANUAL_GATED_PROVIDER_ADAPTER_DRY_RUN_EXECUTION_MVP_PHASE,
    latestCompletedBatch:
      BACKEND_OWNED_MINIMAL_MANUAL_GATED_PROVIDER_ADAPTER_DRY_RUN_EXECUTION_MVP_BATCH,
    previousCompletedBatch:
      PREVIOUS_COMPLETED_BACKEND_OWNED_MINIMAL_MANUAL_GATED_PROVIDER_ADAPTER_DRY_RUN_ADMISSION_REVIEW_RECOVERY_PREVIEW_BATCH,
    nextLikelyBatch:
      NEXT_BACKEND_OWNED_MINIMAL_MANUAL_GATED_PROVIDER_ADAPTER_DRY_RUN_EXECUTION_REVIEW_RECOVERY_PREVIEW_BATCH,
    currentReadiness: CURRENT_READINESS,
    summaryLines: cloneList(SUMMARY_LINES),
  };
}

export function buildProviderDryRunExecutionGateSummary(): ProviderDryRunExecutionGateSummary {
  return {
    version:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-gate-summary-v1",
    gateCount: listProviderDryRunExecutionGates().length,
    summaryLines: cloneList(GATE_SUMMARY_LINES),
    blockedLiveActions: cloneList(BLOCKED_LIVE_ACTIONS),
  };
}

export function buildProviderDryRunExecutionReadinessSummary(): ProviderDryRunExecutionReadinessSummary {
  return {
    version:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-readiness-summary-v1",
    readinessCount: listProviderDryRunExecutionReadinessMatrixRecords().length,
    currentReadiness: CURRENT_READINESS,
    summaryLines: cloneList(READINESS_SUMMARY_LINES),
  };
}

export function buildNextProviderDryRunExecutionReviewRecoveryChecklist(): ProviderDryRunExecutionReviewRecoveryChecklist {
  return cloneList(NEXT_REVIEW_RECOVERY_CHECKLIST);
}

export function buildStaticProviderDryRunExecutionServerRunRecord(
  stableId: ProviderDryRunExecutionMvpId
): MinimalProviderDryRunExecutionServerRunRecord {
  const seed = getSeed(stableId);

  return {
    version:
      "backend-owned-minimal-manual-gated-provider-adapter-dry-run-execution-mvp-v1",
    ...buildCommonRecordFields(seed),
    executionMode: EXECUTION_MODE,
    executionState: "executed-provider-dry-run-fixture-in-memory-only",
    providerDryRunExecutionId: buildProviderDryRunExecutionPreviewId(
      seed.stableId
    ),
    providerDryRunAdmissionId: buildProviderDryRunAdmissionPreviewId(
      seed.stableId
    ),
    providerSlotId: buildProviderDryRunPreviewSlotId(seed.stableId, "selected"),
    credentialReferenceId: buildProviderDryRunPreviewCredentialReferenceId(
      seed.stableId
    ),
    executionDigest: buildProviderDryRunPreviewDigest(seed.stableId),
    selectedProviderState: "preview-only / not live-executed",
    credentialReferenceState: "opaque reference only / value not read",
    redactedPromptReference: buildProviderDryRunPreviewPromptReference(
      seed.stableId
    ),
    fixtureProviderResponse: seed.fixtureProviderResponse,
    providerResponseState: "not received from provider",
    modelOutputState: "not generated by provider/model",
    providerSdkImportState: "not imported",
    liveProviderExecutionState: "blocked",
    resultReference: buildProviderDryRunPreviewResultReference(seed.stableId),
    auditReference: buildProviderDryRunPreviewAuditReference(seed.stableId),
    approvalReference: buildProviderDryRunPreviewApprovalReference(seed.stableId),
    evidencePacketReference: buildProviderDryRunPreviewEvidenceReference(
      seed.stableId
    ),
    approvalFixtureState: "preview-only",
    manualConfirmationFixtureState: "preview-only",
    approvalTokenState: "not issued",
    approvalLeaseState: "not created",
    timestampPosture: "static fixture label only / no real timestamp",
    persistenceState: "not implemented",
    currentReadiness: CURRENT_READINESS,
    noFrontendRequestStatement: "no frontend request is created",
    noApiRouteStatement: "no API route is created",
    noProviderCallStatement: "no provider call exists",
    noModelCallStatement: "no model call exists",
    noRealApprovalRequestStatement: "no real approval request exists",
    noRealApprovalRecordingStatement: "no real approval recording exists",
    noApprovalTokenStatement: "no approval token exists",
    noApprovalLeaseStatement: "no approval lease exists",
    nextReviewRecoveryChecklist: cloneList(NEXT_REVIEW_RECOVERY_CHECKLIST),
  };
}
