"use client";
import type { CSSProperties } from "react";
import { CodexForgeAppShell } from "@/lib/codexforge/navigation-shell";
import { RENDER_QUEUE_CONTRACT_MARKERS, RENDER_WORKER_CONTRACT_MODEL_FIELDS, WORKER_ORCHESTRATION_CONTRACT_MARKERS, buildRenderWorkerOrchestrationContractRouteModel, buildRenderWorkerOrchestrationContractStableKey, type RenderWorkerContractItem, type RenderWorkerContractRouteSlug, type RenderWorkerContractSection, type RenderWorkerContractState } from "../render-worker-orchestration-contract-model";

export function RenderWorkerOrchestrationContractPageClientShell({ routeSlug }: { routeSlug: RenderWorkerContractRouteSlug }) {
  const model = buildRenderWorkerOrchestrationContractRouteModel(routeSlug);
  return <CodexForgeAppShell activePath={model.route.href} workspaceLabel={model.route.title} nextActionContext={{ wantsOperatorOverview: false }} focusMode contentMaxWidth="wide" pageChrome="minimal" showRightRail={false} showSidebarSafetyNotice={false} showHeroRouteChips={false}><RenderWorkerOrchestrationContractRoutePanel routeSlug={routeSlug} /></CodexForgeAppShell>;
}

export function RenderQueueContractBoundaryCockpitSummaryPanel() {
  const model = buildRenderWorkerOrchestrationContractRouteModel("cockpit-render-queue-contract-summary");
  const workspace = model.contract;
  const cards: readonly { section: RenderWorkerContractSection; stateLabel: string }[] = [
    { section: workspace.renderJobSchema, stateLabel: "Render job schema" }, { section: workspace.renderReadinessGate, stateLabel: "Readiness gate" }, { section: workspace.renderQueuePolicy, stateLabel: "Queue policy" }, { section: workspace.renderRetryPolicy, stateLabel: "Retry policy" }, { section: workspace.renderPriorityPolicy, stateLabel: "Priority policy" }, { section: workspace.renderTimeoutPolicy, stateLabel: "Timeout policy" }, { section: workspace.renderCostGuard, stateLabel: "Cost guard" }, { section: workspace.renderJobLeaseContract, stateLabel: "Job lease" }, { section: workspace.renderQueueTelemetry, stateLabel: "Telemetry" }, { section: workspace.renderFailureLedger, stateLabel: "Failure ledger" }, { section: workspace.renderResultHandoffContract, stateLabel: "Result handoff" }, { section: workspace.frontendRenderQueueCreationBlocked, stateLabel: "Frontend blocked" },
  ];
  return (
    <section style={cockpitPanel} aria-label="Render Queue Contract" data-codexforge-render-queue-contract={RENDER_QUEUE_CONTRACT_MARKERS.join(" | ")}>
      <header style={hero}><div style={eyebrowRow}><span style={phaseBadge}>Render Queue Contract</span><span style={surfaceBadge}>Backend Contracts</span><span style={approvalBadge}>Release candidate</span></div><h2 style={titleStyle}>Render Queue Contract</h2><p style={summary}>Review-only render queue contract. Synthetic data only. This summary extends the backend contract lane below Audio Storage Contract and shows render job schema, render readiness gate, queue policy, retry policy, priority policy, timeout policy, cost guard, job lease, queue telemetry, failure ledger, result handoff, frontend queue creation blocked, and denied paths.</p><p style={bodyText}>No render buttons, queue buttons, worker buttons, command buttons, process buttons, port buttons, runtime buttons, service buttons, artifact buttons, provider buttons, model buttons, connector buttons, persistence controls, or hidden execution affordances are present.</p><p style={bodyText}>Backend-owned render queue remains required. Backend-owned job ledger remains required. Backend-owned retry policy remains required. Backend-owned worker orchestration remains required. Backend-owned telemetry remains required. Backend-owned artifact storage remains required. Backend-owned approval capture remains required. Operator review remains required. Explicit operator approval remains required.</p></header>
      <section style={statusBand} aria-label="Render Queue Contract status"><span style={stateStyle("review-only")}>Review-only contract</span><span style={stateStyle("synthetic-only")}>Synthetic data only</span><span style={stateStyle("blocked")}>Frontend queue blocked</span><span style={stateStyle("backend-owned")}>Backend-owned queue required</span><span style={stateStyle("needs-approval")}>Explicit operator approval required</span></section>
      <section style={summaryGrid} aria-label="Render Queue Contract cockpit summary">{workspace.cockpitSummary.slice(0, 7).map((item, index) => <CheckRow key={buildRenderWorkerOrchestrationContractStableKey(["render-summary", String(index), item.id])} item={item} />)}</section>
      <section style={sectionGrid} aria-label="Render Queue Contract cockpit cards">{cards.map((card, index) => <SummaryCard key={buildRenderWorkerOrchestrationContractStableKey(["render-card", String(index), card.section.sectionId])} section={card.section} stateLabel={card.stateLabel} />)}</section>
      <details style={diagnosticsDrawer}><summary style={diagnosticsSummary}>Developer Diagnostics</summary><p style={bodyText}>Phase pages remain dev test diagnostics only. Diagnostic links stay secondary to the normal cockpit surface and do not expose queue, job, worker, render, artifact, command, process, port, runtime, service, provider, model, connector, persistence, browser storage, or file mutation controls.</p><div style={routeGrid}>{model.diagnosticRoutes.filter((route) => route.contractFamily === "render").map((route, index) => <a key={buildRenderWorkerOrchestrationContractStableKey(["render-diagnostic", String(index), route.slug])} style={routeLink} href={route.href}><span style={routePhase}>{route.phase}</span><span style={routeLabel}>{route.title}</span><span style={routeCommand}>{route.commandLabel}</span></a>)}</div></details>
      <a style={safeLink} href="/controlled-render-queue-contract-release-candidate">Review Controlled Render Queue Contract Release Candidate</a>
    </section>
  );
}

export function WorkerOrchestrationContractBoundaryCockpitSummaryPanel() {
  const model = buildRenderWorkerOrchestrationContractRouteModel("cockpit-worker-orchestration-contract-summary");
  const workspace = model.contract;
  const cards: readonly { section: RenderWorkerContractSection; stateLabel: string }[] = [
    { section: workspace.workerLeaseContract, stateLabel: "Worker lease" }, { section: workspace.runtimeIsolationContract, stateLabel: "Runtime isolation" }, { section: workspace.workerSandboxPolicy, stateLabel: "Sandbox policy" }, { section: workspace.commandExecutionBlocked, stateLabel: "Command blocked" }, { section: workspace.processSpawnBlocked, stateLabel: "Process blocked" }, { section: workspace.portBindingBlocked, stateLabel: "Port blocked" }, { section: workspace.workerHealthContract, stateLabel: "Worker health" }, { section: workspace.workerRetryBackoff, stateLabel: "Retry backoff" }, { section: workspace.workerArtifactHandoff, stateLabel: "Artifact handoff" }, { section: workspace.workerAuditEvent, stateLabel: "Audit event" }, { section: workspace.workerFailureQuarantine, stateLabel: "Failure quarantine" }, { section: workspace.frontendWorkerDispatchBlocked, stateLabel: "Frontend blocked" },
  ];
  return (
    <section style={cockpitPanel} aria-label="Worker Orchestration Contract" data-codexforge-worker-orchestration-contract={WORKER_ORCHESTRATION_CONTRACT_MARKERS.join(" | ")}>
      <header style={hero}><div style={eyebrowRow}><span style={phaseBadge}>Worker Orchestration Contract</span><span style={surfaceBadge}>Backend Contracts</span><span style={approvalBadge}>Release candidate</span></div><h2 style={titleStyle}>Worker Orchestration Contract</h2><p style={summary}>Review-only worker orchestration contract. Synthetic data only. This summary extends the backend contract lane below Render Queue Contract and shows worker lease, runtime isolation, sandbox policy, command execution blocked, process spawn blocked, port binding blocked, worker health, retry backoff, artifact handoff, worker audit event, failure quarantine, frontend worker dispatch blocked, and denied paths.</p><p style={bodyText}>No worker buttons, command buttons, process buttons, port buttons, runtime buttons, service buttons, artifact buttons, provider buttons, model buttons, connector buttons, persistence controls, or hidden execution affordances are present.</p><p style={bodyText}>Backend-owned worker orchestration remains required. Backend-owned runtime isolation remains required. Backend-owned sandbox policy remains required. Backend-owned job lease remains required. Backend-owned health monitoring remains required. Backend-owned failure quarantine remains required. Backend-owned audit trail remains required. Backend-owned approval capture remains required. Operator review remains required. Explicit operator approval remains required.</p></header>
      <section style={statusBand} aria-label="Worker Orchestration Contract status"><span style={stateStyle("review-only")}>Review-only contract</span><span style={stateStyle("synthetic-only")}>Synthetic data only</span><span style={stateStyle("blocked")}>Frontend worker dispatch blocked</span><span style={stateStyle("backend-owned")}>Backend-owned workers required</span><span style={stateStyle("needs-approval")}>Explicit operator approval required</span></section>
      <section style={summaryGrid} aria-label="Worker Orchestration Contract cockpit summary">{workspace.cockpitSummary.slice(7).map((item, index) => <CheckRow key={buildRenderWorkerOrchestrationContractStableKey(["worker-summary", String(index), item.id])} item={item} />)}</section>
      <section style={sectionGrid} aria-label="Worker Orchestration Contract cockpit cards">{cards.map((card, index) => <SummaryCard key={buildRenderWorkerOrchestrationContractStableKey(["worker-card", String(index), card.section.sectionId])} section={card.section} stateLabel={card.stateLabel} />)}</section>
      <details style={diagnosticsDrawer}><summary style={diagnosticsSummary}>Developer Diagnostics</summary><p style={bodyText}>Phase pages remain dev test diagnostics only. Diagnostic links stay secondary to the normal cockpit surface and do not expose worker, command, process, port, runtime, service, artifact, provider, model, connector, persistence, browser storage, or file mutation controls.</p><div style={routeGrid}>{model.diagnosticRoutes.filter((route) => route.contractFamily === "worker").map((route, index) => <a key={buildRenderWorkerOrchestrationContractStableKey(["worker-diagnostic", String(index), route.slug])} style={routeLink} href={route.href}><span style={routePhase}>{route.phase}</span><span style={routeLabel}>{route.title}</span><span style={routeCommand}>{route.commandLabel}</span></a>)}</div></details>
      <a style={safeLink} href="/controlled-worker-orchestration-contract-release-candidate">Review Controlled Worker Orchestration Contract Release Candidate</a>
    </section>
  );
}

export function RenderWorkerOrchestrationContractRoutePanel({ routeSlug, embedded = false }: { routeSlug: RenderWorkerContractRouteSlug; embedded?: boolean }) {
  const model = buildRenderWorkerOrchestrationContractRouteModel(routeSlug);
  const workspace = model.contract;
  const title = model.route.contractFamily === "render" ? "Render Queue Contract" : "Worker Orchestration Contract";
  return (
    <section style={embedded ? embeddedPage : page} data-codexforge-render-worker-contract-route={model.route.markerPhrases.join(" | ")}>
      <header style={hero}><div style={eyebrowRow}><span style={phaseBadge}>{embedded ? title : model.route.phase}</span><span style={surfaceBadge}>{model.route.devOnly ? "Dev test diagnostics only" : "Cockpit surface"}</span><span style={approvalBadge}>Review only</span></div>{embedded ? <h2 style={titleStyle}>{title}</h2> : <h1 style={titleStyle}>{model.route.title}</h1>}<p style={summary}>{model.route.summary}</p><p style={bodyText}>This contract surface is review-only and synthetic-only from the frontend. It is not queue creation, job creation, job persistence, worker dispatch, command execution, process spawning, port binding, runtime deployment, service deployment, artifact creation, artifact persistence, provider execution, model execution, connector execution, prompt sending, telemetry persistence, audit persistence, browser storage, file mutation, or frontend persistence.</p><p style={bodyText}>Backend-owned render queue remains required. Backend-owned worker orchestration remains required. Backend-owned runtime isolation remains required. Backend-owned sandbox policy remains required. Backend-owned telemetry remains required. Backend-owned failure ledger remains required. Backend-owned artifact storage remains required. Backend-owned approval capture remains required. Operator review remains required. Explicit operator approval remains required.</p></header>
      <section style={markerBand} aria-label="Render worker contract page markers">{model.route.markerPhrases.map((marker, index) => <span key={buildRenderWorkerOrchestrationContractStableKey(["marker", model.route.slug, String(index), marker])} style={markerPill}>{marker}</span>)}</section>
      <section style={identityBand} aria-label="Render worker contract model fields"><div><p style={panelEyebrow}>Render worker contract model</p><h2 style={sectionTitle}>renderQueueContractId: {workspace.renderQueueContractId}</h2></div><p style={bodyText}>renderQueueContractKind: {workspace.renderQueueContractKind}</p><p style={bodyText}>workerOrchestrationContractId: {workspace.workerOrchestrationContractId}</p><p style={bodyText}>workerOrchestrationContractKind: {workspace.workerOrchestrationContractKind}</p><div style={chipRow}>{RENDER_WORKER_CONTRACT_MODEL_FIELDS.map((field, index) => <span key={buildRenderWorkerOrchestrationContractStableKey(["field", String(index), field])} style={chip}>{field}</span>)}</div></section>
      <section style={sectionGrid} aria-label="Render worker contract route sections">{model.sections.map((section, index) => <SectionCard key={buildRenderWorkerOrchestrationContractStableKey(["section", model.route.slug, String(index), section.sectionId])} section={section} />)}</section>
      <section style={splitBand} aria-label="Render worker contract summary and safety limits"><article style={panel}><div style={panelHeader}><div><p style={panelEyebrow}>Cockpit</p><h3 style={sectionTitle}>cockpitSummary</h3></div><span style={stateStyle("review-only")}>Review only</span></div><div style={checklistGrid}>{workspace.cockpitSummary.map((item, index) => <CheckRow key={buildRenderWorkerOrchestrationContractStableKey(["route-summary", String(index), item.id])} item={item} />)}</div></article><article style={panel}><div style={panelHeader}><div><p style={panelEyebrow}>Safety</p><h3 style={sectionTitle}>explicitSafetyLimits</h3></div><span style={stateStyle("blocked")}>Blocked</span></div><div style={chipRow}>{workspace.explicitSafetyLimits.map((limit, index) => <span key={buildRenderWorkerOrchestrationContractStableKey(["limit", String(index), limit])} style={dangerChip}>{limit}</span>)}</div></article></section>
      <section style={continuityBand} aria-label="Render worker contract continuity"><div style={panelHeader}><div><p style={panelEyebrow}>Controlled release candidate</p><h2 style={sectionTitle}>Review-only render queue and worker orchestration lane</h2></div><span style={stateStyle("blocked")}>No frontend queue, worker, command, runtime, artifact, telemetry, audit, or persistence</span></div><p style={bodyText}>{model.summary}</p></section>
      <a style={safeLink} href="/codexforge-cockpit">Back to CodexForge Cockpit</a>
    </section>
  );
}

function SummaryCard({ section, stateLabel }: { section: RenderWorkerContractSection; stateLabel: string }) { return <article style={summaryCard}><div style={panelHeader}><div><p style={panelEyebrow}>{stateLabel}</p><h3 style={sectionTitle}>{section.label}</h3></div><span style={stateStyle(section.state)}>{formatState(section.state)}</span></div><p style={bodyText}>{section.humanReadableSummary}</p></article>; }
function SectionCard({ section }: { section: RenderWorkerContractSection }) { return <article style={panel}><div style={panelHeader}><div><p style={panelEyebrow}>{section.label}</p><h2 style={sectionTitle}>{section.title}</h2></div><span style={stateStyle(section.state)}>{formatState(section.state)}</span></div><p style={bodyText}>{section.humanReadableSummary}</p><TextList title="Planned inputs" values={section.plannedInputs} /><TextList title="Planned outputs" values={section.plannedOutputs} /><div style={checklistGrid}>{section.checklist.map((item, index) => <CheckRow key={buildRenderWorkerOrchestrationContractStableKey(["check", section.sectionId, String(index), item.id])} item={item} />)}</div><div style={chipRow}>{section.safetyNotes.map((note, index) => <span key={buildRenderWorkerOrchestrationContractStableKey(["safety", section.sectionId, String(index), note])} style={chip}>{note}</span>)}</div></article>; }
function TextList({ title, values }: { title: string; values: readonly string[] }) { return <div style={listBlock}><p style={panelEyebrow}>{title}</p><div style={chipRow}>{values.map((value, index) => <span key={buildRenderWorkerOrchestrationContractStableKey(["list", title, String(index), value])} style={chip}>{value}</span>)}</div></div>; }
function CheckRow({ item }: { item: RenderWorkerContractItem }) { return <article style={checkRow}><span style={stateStyle(item.state)}>{formatState(item.state)}</span><div><p style={checkLabel}>{item.label}</p><p style={checkDetail}>{item.detail}</p></div></article>; }
function formatState(state: RenderWorkerContractState): string { if (state === "review-only") return "Review only"; if (state === "synthetic-only") return "Synthetic"; if (state === "backend-owned") return "Backend-owned"; if (state === "needs-approval") return "Needs approval"; if (state === "candidate") return "Candidate"; if (state === "release-candidate") return "Release candidate"; return "Blocked"; }
function stateStyle(state: RenderWorkerContractState): CSSProperties { return { ...stateBadge, ...(state === "blocked" ? blockedBadge : state === "needs-approval" ? approvalStateBadge : state === "backend-owned" ? backendBadge : state === "release-candidate" || state === "candidate" ? candidateBadge : reviewBadge) }; }
const page: CSSProperties = { display: "flex", flexDirection: "column", gap: 18, padding: "28px", color: "#172026" };
const embeddedPage: CSSProperties = { display: "flex", flexDirection: "column", gap: 16 };
const cockpitPanel: CSSProperties = { ...page, border: "1px solid #c8d4d1", borderRadius: 8, background: "#f8faf9" };
const hero: CSSProperties = { display: "flex", flexDirection: "column", gap: 12 };
const eyebrowRow: CSSProperties = { display: "flex", flexWrap: "wrap", gap: 8 };
const titleStyle: CSSProperties = { margin: 0, fontSize: 32, lineHeight: 1.08, letterSpacing: 0, color: "#10211d" };
const summary: CSSProperties = { margin: 0, maxWidth: 1100, color: "#354842", fontSize: 15, lineHeight: 1.65 };
const bodyText: CSSProperties = { margin: 0, color: "#43544e", fontSize: 14, lineHeight: 1.6 };
const phaseBadge: CSSProperties = { padding: "6px 10px", borderRadius: 999, background: "#16352f", color: "#f7fbfa", fontSize: 12, fontWeight: 700 };
const surfaceBadge: CSSProperties = { ...phaseBadge, background: "#e0ebe7", color: "#16352f" };
const approvalBadge: CSSProperties = { ...phaseBadge, background: "#fff0cc", color: "#654710" };
const markerBand: CSSProperties = { display: "flex", flexWrap: "wrap", gap: 8 };
const markerPill: CSSProperties = { padding: "7px 9px", borderRadius: 6, background: "#eef5f2", border: "1px solid #c9d9d4", color: "#283a35", fontSize: 12, lineHeight: 1.35 };
const identityBand: CSSProperties = { display: "flex", flexDirection: "column", gap: 12, padding: 16, border: "1px solid #c9d9d4", borderRadius: 8, background: "#ffffff" };
const statusBand: CSSProperties = { display: "flex", flexWrap: "wrap", gap: 8, padding: 12, border: "1px solid #c9d9d4", borderRadius: 8, background: "#ffffff" };
const summaryGrid: CSSProperties = { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 12 };
const sectionGrid: CSSProperties = { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 14 };
const splitBand: CSSProperties = { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))", gap: 14 };
const panel: CSSProperties = { display: "flex", flexDirection: "column", gap: 12, padding: 16, border: "1px solid #c9d9d4", borderRadius: 8, background: "#ffffff" };
const summaryCard: CSSProperties = { ...panel, minHeight: 168 };
const panelHeader: CSSProperties = { display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 12 };
const panelEyebrow: CSSProperties = { margin: "0 0 4px", color: "#60736d", fontSize: 11, fontWeight: 800, letterSpacing: 0, textTransform: "uppercase" };
const sectionTitle: CSSProperties = { margin: 0, color: "#10211d", fontSize: 18, lineHeight: 1.25, letterSpacing: 0 };
const listBlock: CSSProperties = { display: "flex", flexDirection: "column", gap: 8 };
const checklistGrid: CSSProperties = { display: "grid", gap: 10 };
const checkRow: CSSProperties = { display: "grid", gridTemplateColumns: "auto 1fr", gap: 10, alignItems: "start", padding: 10, border: "1px solid #d8e5e0", borderRadius: 8, background: "#f9fbfa" };
const checkLabel: CSSProperties = { margin: 0, color: "#10211d", fontWeight: 800, fontSize: 13 };
const checkDetail: CSSProperties = { margin: "3px 0 0", color: "#43544e", fontSize: 12, lineHeight: 1.45 };
const chipRow: CSSProperties = { display: "flex", flexWrap: "wrap", gap: 8 };
const chip: CSSProperties = { padding: "6px 8px", borderRadius: 6, background: "#eef5f2", border: "1px solid #c9d9d4", color: "#283a35", fontSize: 12, lineHeight: 1.35 };
const stateBadge: CSSProperties = { display: "inline-flex", alignItems: "center", justifyContent: "center", width: "fit-content", maxWidth: 250, padding: "5px 8px", borderRadius: 999, fontSize: 11, fontWeight: 800, lineHeight: 1.2, whiteSpace: "normal" };
const reviewBadge: CSSProperties = { background: "#e8f4f0", color: "#174c3d", border: "1px solid #b8dacf" };
const backendBadge: CSSProperties = { background: "#edf0fb", color: "#263b73", border: "1px solid #c3cbea" };
const approvalStateBadge: CSSProperties = { background: "#fff3d4", color: "#6a4b0f", border: "1px solid #efd28f" };
const blockedBadge: CSSProperties = { background: "#fae8e8", color: "#702121", border: "1px solid #e5b8b8" };
const candidateBadge: CSSProperties = { background: "#eef1f7", color: "#2f3a51", border: "1px solid #cbd3df" };
const dangerChip: CSSProperties = { ...chip, background: "#fff7ed", borderColor: "#efd3b3", color: "#663f14" };
const continuityBand: CSSProperties = { ...panel, background: "#f8fbfa" };
const diagnosticsDrawer: CSSProperties = { ...panel, background: "#fbfcfc" };
const diagnosticsSummary: CSSProperties = { cursor: "pointer", color: "#10211d", fontWeight: 800 };
const routeGrid: CSSProperties = { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))", gap: 10 };
const routeLink: CSSProperties = { display: "flex", flexDirection: "column", gap: 4, padding: 12, borderRadius: 8, border: "1px solid #d5e1dd", background: "#ffffff", color: "#10211d", textDecoration: "none" };
const routePhase: CSSProperties = { color: "#60736d", fontSize: 11, fontWeight: 800 };
const routeLabel: CSSProperties = { color: "#10211d", fontSize: 13, fontWeight: 800 };
const routeCommand: CSSProperties = { color: "#43544e", fontSize: 12 };
const safeLink: CSSProperties = { display: "inline-flex", alignItems: "center", justifyContent: "center", width: "fit-content", padding: "9px 12px", borderRadius: 8, background: "#16352f", color: "#ffffff", textDecoration: "none", fontSize: 13, fontWeight: 800 };
