import type {
  CodexForgeCommand,
  CodexForgeCommandInput,
  CodexForgeCommandRegistryOptions,
  CodexForgeCommandRouteAvailability,
} from "./command-palette-types";
import {
  buildCodexForgeContinuityHandoffPromptPayload,
  buildCodexForgeContinuityValidationChecklistPayload,
  buildCodexForgeApplyGateHandoffPromptPayload,
  buildCodexForgeApprovedPatchApplyReviewPromptPayload,
  buildCodexForgeBlenderAdapterPreviewPromptPayload,
  buildCodexForgeBlenderFutureExecutorPacketPayload,
  buildCodexForgeCreativeBridgeHandoffPayload,
  buildCodexForgeFileInspectionPromptPayload,
  buildCodexForgeProjectReaderPatchPreviewPromptPayload,
  buildCodexForgeRealPatchReviewPromptPayload,
  buildCodexForgeSafePatchPromptPayload,
  buildCodexForgeStabilizationHandoffPayload,
  buildCodexForgeValidationChecklistPayload,
} from "./command-copy-payloads";
import { isCodexForgeCommandMutationBlocked } from "./command-safety";

const DEFAULT_ROUTE_AVAILABILITY: CodexForgeCommandRouteAvailability = {
  "/": true,
  "/ai": true,
  "/ai-router": true,
  "/brain": true,
  "/files": true,
  "/tasks": true,
  "/closed-loop": true,
  "/memory": true,
  "/memory-inbox": true,
  "/runtime-journal": true,
  "/runtime-replay": true,
  "/brain-snapshots": true,
  "/snapshot-restore": true,
  "/brain-continuity": true,
  "/handoff": true,
  "/brain-governance": true,
  "/creative": true,
  "/blender": true,
  "/comfyui": true,
  "/creative-bridge": true,
  "/capabilities": true,
  "/activity": true,
  "/readiness": true,
  "/consolidation": true,
  "/validation": true,
  "/stabilization": true,
};

export function buildCodexForgeCommand(input: CodexForgeCommandInput): CodexForgeCommand {
  const noMutation = input.noMutation ?? true;
  const disabledReason =
    input.disabledReason ??
    (noMutation ? undefined : "Mutation commands are blocked from the global command palette.");

  return {
    description: "",
    group: "Safety",
    kind: "safe-action",
    safetyLevel: disabledReason ? "blocked" : "safe",
    requiresReview: false,
    keywords: [],
    priority: 1000,
    ...input,
    noMutation,
    disabledReason,
  };
}

function routeAvailable(
  availability: CodexForgeCommandRouteAvailability,
  href: NonNullable<CodexForgeCommand["href"]>
): boolean {
  return availability[href] === true;
}

function buildRouteCommand(
  availability: CodexForgeCommandRouteAvailability,
  input: CodexForgeCommandInput & { href: NonNullable<CodexForgeCommand["href"]> }
): CodexForgeCommand | null {
  if (!routeAvailable(availability, input.href)) return null;
  return buildCodexForgeCommand({
    group: "Navigate",
    kind: "route",
    safetyLevel: "safe",
    requiresReview: false,
    noMutation: true,
    ...input,
  });
}

export function buildCodexForgeCommands(
  options: CodexForgeCommandRegistryOptions = {}
): CodexForgeCommand[] {
  const availability = { ...DEFAULT_ROUTE_AVAILABILITY, ...options.routeAvailability };
  const routeCommands = [
    buildRouteCommand(availability, {
      id: "go-operator-home",
      label: "Go to Operator Home",
      description: "Navigate to the operator dashboard.",
      href: "/",
      keywords: ["home", "dashboard", "operator", "route"],
      priority: 10,
    }),
    buildRouteCommand(availability, {
      id: "go-ai-workspace",
      label: "Go to AI Workspace",
      description: "Navigate to planning, chat, and reviewed handoffs.",
      href: "/ai",
      keywords: ["ai", "workspace", "chat", "route"],
      priority: 20,
    }),
    buildRouteCommand(availability, {
      id: "go-ai-router",
      label: "Go to AI Router",
      description: "Navigate to preview-only model routing guidance.",
      href: "/ai-router",
      keywords: ["ai", "router", "model routing", "route"],
      priority: 25,
    }),
    buildRouteCommand(availability, {
      id: "go-brain",
      label: "Go to Brain",
      description: "Navigate to Brain graph inspection without mutation.",
      href: "/brain",
      keywords: ["brain", "graph", "recall", "route"],
      priority: 30,
    }),
    buildRouteCommand(availability, {
      id: "go-files",
      label: "Go to Project Reader",
      description: "Go to Files route for File Reader v1 functional/read-only.",
      href: "/files",
      keywords: ["files", "project reader", "source", "workflow", "route"],
      priority: 40,
    }),
    buildRouteCommand(availability, {
      id: "go-real-patch-preview",
      label: "Go to Real Patch Preview",
      description: "Go to /files for selected file context and Real Patch Preview v1 functional/preview-only diffs.",
      href: "/files",
      keywords: ["real patch preview", "patch preview", "preview-only diff", "files", "route"],
      priority: 41,
    }),
    buildRouteCommand(availability, {
      id: "go-approved-patch-apply",
      label: "Go to Approved Patch Apply",
      description: "Go to /files for Approved Patch Apply v1 approval-gated/request-ready review.",
      href: "/files",
      keywords: ["approved patch apply", "apply request", "approval packet", "validation checklist", "route"],
      priority: 42,
    }),
    buildRouteCommand(availability, {
      id: "go-tasks",
      label: "Go to Tasks",
      description: "Navigate to reviewed task workflow.",
      href: "/tasks",
      keywords: ["tasks", "activation", "route"],
      priority: 50,
    }),
    buildRouteCommand(availability, {
      id: "go-closed-loop",
      label: "Go to Closed Loop Fix",
      description: "Navigate to preview-only closed-loop fix workflow guidance.",
      href: "/closed-loop",
      keywords: ["closed loop", "fix", "regression", "validation", "route"],
      priority: 55,
    }),
    buildRouteCommand(availability, {
      id: "go-memory",
      label: "Go to Memory",
      description: "Navigate to memory review candidates.",
      href: "/memory",
      keywords: ["memory", "review", "route"],
      priority: 60,
    }),
    buildRouteCommand(availability, {
      id: "go-memory-inbox",
      label: "Go to Memory Inbox",
      description: "Navigate to Personal Operator Memory Inbox review cards.",
      href: "/memory-inbox",
      keywords: ["memory", "inbox", "operator", "review", "promotion preview"],
      priority: 65,
    }),
    buildRouteCommand(availability, {
      id: "go-runtime-event-journal",
      label: "Go to Runtime Event Journal",
      description: "Navigate to the read-only Runtime Event Journal.",
      href: "/runtime-journal",
      keywords: ["runtime", "event", "journal", "audit", "route"],
      priority: 67,
    }),
    buildRouteCommand(availability, {
      id: "go-runtime-event-replay",
      label: "Go to Runtime Event Replay",
      description: "Navigate to the preview-only Runtime Event Replay Simulator.",
      href: "/runtime-replay",
      keywords: ["runtime", "event", "replay", "simulator", "reducer preview", "route"],
      priority: 67.5,
    }),
    buildRouteCommand(availability, {
      id: "go-brain-mutation-governance",
      label: "Go to Brain Mutation Governance",
      description: "Navigate to the read-only Brain Mutation Governance Console.",
      href: "/brain-governance",
      keywords: ["brain", "mutation", "governance", "boundary", "audit", "route"],
      priority: 68,
    }),
    buildRouteCommand(availability, {
      id: "go-brain-snapshots",
      label: "Go to Brain Snapshots",
      description: "Navigate to the read-only Brain Snapshot Manager.",
      href: "/brain-snapshots",
      keywords: ["brain", "snapshot", "comparison", "replay source", "rollback planning", "route"],
      priority: 68.5,
    }),
    buildRouteCommand(availability, {
      id: "go-snapshot-restore-gate",
      label: "Go to Snapshot Restore Gate",
      description: "Navigate to the preview-only Snapshot Restore Approval Gate.",
      href: "/snapshot-restore",
      keywords: ["snapshot", "restore", "approval gate", "request preview", "route"],
      priority: 68.7,
    }),
    buildRouteCommand(availability, {
      id: "go-brain-continuity",
      label: "Go to Brain Continuity",
      description: "Navigate to the read-only Brain Continuity Dashboard.",
      href: "/brain-continuity",
      keywords: ["brain", "continuity", "dashboard", "memory growth", "journal health", "route"],
      priority: 68.8,
    }),
    buildRouteCommand(availability, {
      id: "go-continuity-handoff",
      label: "Go to Continuity Handoff",
      description: "Navigate to the read-only Continuity Handoff Packet.",
      href: "/handoff",
      keywords: ["continuity", "handoff", "packet", "next session", "route"],
      priority: 68.9,
    }),
    buildRouteCommand(availability, {
      id: "go-creative",
      label: "Go to Creative",
      description: "Navigate to Creative Production Studio previews.",
      href: "/creative",
      keywords: ["creative", "preview", "studio", "route"],
      priority: 70,
    }),
    buildRouteCommand(availability, {
      id: "go-blender-adapter-preview",
      label: "Go to Blender Adapter Preview",
      description: "Navigate to Blender Adapter Preview v1 scene model and Python preview.",
      href: "/blender",
      keywords: ["blender", "adapter", "preview", "scene", "route"],
      priority: 70.5,
    }),
    buildRouteCommand(availability, {
      id: "go-comfyui-adapter-preview",
      label: "Go to ComfyUI Adapter Preview",
      description: "Navigate to ComfyUI Adapter Preview v1 workflow manifest and approval packet.",
      href: "/comfyui",
      keywords: ["comfyui", "adapter", "workflow", "preview", "route"],
      priority: 70.75,
    }),
    buildRouteCommand(availability, {
      id: "go-creative-local-bridge",
      label: "Go to Creative Local Bridge",
      description: "Navigate to Creative Local Bridge v1 preview-only/request-ready control plane.",
      href: "/creative-bridge",
      keywords: ["creative", "bridge", "blender", "comfyui", "unreal", "artifact capture", "route"],
      priority: 71,
    }),
    buildRouteCommand(availability, {
      id: "go-capabilities",
      label: "Go to Capabilities",
      description: "Navigate to Capability Cockpit.",
      href: "/capabilities",
      keywords: ["capabilities", "tools", "policy", "route"],
      priority: 80,
    }),
    buildRouteCommand(availability, {
      id: "go-activity-feed",
      label: "Go to Activity Feed",
      description: "Navigate to the read-only Global Activity Feed.",
      href: "/activity",
      keywords: ["activity", "feed", "global", "route"],
      priority: 85,
    }),
    buildRouteCommand(availability, {
      id: "go-product-readiness",
      label: "Go to Product Readiness",
      description: "Navigate to the read-only Product Readiness Audit cockpit.",
      href: "/readiness",
      keywords: ["product readiness", "readiness", "audit", "route", "Phase 54"],
      priority: 87,
    }),
    buildRouteCommand(availability, {
      id: "go-consolidation",
      label: "Go to Consolidation",
      description: "Navigate to the read-only Phase 55 Consolidation Pass cockpit.",
      href: "/consolidation",
      keywords: ["consolidation", "phase 55", "route", "surface map", "workflow entrypoints"],
      priority: 88,
    }),
    buildRouteCommand(availability, {
      id: "go-validation-runner",
      label: "Go to Validation Runner",
      description: "Go to /validation for approval-gated Validation Runner v1 request-ready/manual-only review.",
      href: "/validation",
      keywords: ["validation runner", "approval", "allowlist", "build", "smoke", "route"],
      priority: 89,
    }),
    buildRouteCommand(availability, {
      id: "go-stabilization",
      label: "Go to Stabilization",
      description: "Navigate to Stabilization Command Center.",
      href: "/stabilization",
      keywords: ["stabilization", "smoke", "build", "route"],
      priority: 90,
    }),
  ].filter((command): command is CodexForgeCommand => command !== null);

  const commands: CodexForgeCommand[] = [
    ...routeCommands,
    buildCodexForgeCommand({
      id: "copy-full-validation-checklist",
      label: "Copy full validation checklist",
      description: "Copy build, smoke, diff, and status checks without running them.",
      group: "Validation",
      kind: "copy-command",
      copyPayload: buildCodexForgeValidationChecklistPayload(),
      safetyLevel: "copy-only",
      requiresReview: false,
      keywords: ["validation", "checklist", "build", "smoke", "git diff check"],
      priority: 110,
    }),
    buildCodexForgeCommand({
      id: "copy-build-command",
      label: "Copy build validation command",
      description: "Copy npm run build.",
      group: "Validation",
      kind: "copy-command",
      copyPayload: "npm run build",
      safetyLevel: "copy-only",
      requiresReview: false,
      keywords: ["build", "command", "validation"],
      priority: 120,
    }),
    buildCodexForgeCommand({
      id: "copy-managed-smoke-command",
      label: "Copy managed smoke command",
      description: "Copy npm run smoke:codexforge:server.",
      group: "Validation",
      kind: "copy-command",
      copyPayload: "npm run smoke:codexforge:server",
      safetyLevel: "copy-only",
      requiresReview: false,
      keywords: ["smoke", "server", "validation"],
      priority: 130,
    }),
    buildCodexForgeCommand({
      id: "copy-git-diff-check",
      label: "Copy git diff check",
      description: "Copy git diff --check.",
      group: "Validation",
      kind: "copy-command",
      copyPayload: "git diff --check",
      safetyLevel: "copy-only",
      requiresReview: false,
      keywords: ["git", "diff", "check"],
      priority: 140,
    }),
    buildCodexForgeCommand({
      id: "review-regression-triage",
      label: "Review regression triage",
      description: "Open the review flow for regression signals before fix queue work.",
      group: "Stabilize",
      kind: "review",
      href: routeAvailable(availability, "/stabilization") ? "/stabilization" : undefined,
      safetyLevel: "review-gated",
      requiresReview: true,
      keywords: ["regression", "triage", "stabilization"],
      priority: 150,
    }),
    buildCodexForgeCommand({
      id: "review-regression-fix-queue",
      label: "Review regression fix queue",
      description: "Review queued fixes before patch preview.",
      group: "Stabilize",
      kind: "review",
      href: routeAvailable(availability, "/stabilization") ? "/stabilization" : undefined,
      safetyLevel: "review-gated",
      requiresReview: true,
      keywords: ["regression", "fix queue", "review"],
      priority: 160,
    }),
    buildCodexForgeCommand({
      id: "copy-file-inspection-prompt",
      label: "Copy file inspection prompt",
      description: "Copy a Project Reader prompt for inspect-first read-only file review.",
      group: "Patch workflow",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeFileInspectionPromptPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["project reader", "file inspection", "inspect first", "read-only"],
      priority: 165,
    }),
    buildCodexForgeCommand({
      id: "copy-safe-patch-preview-prompt",
      label: "Copy safe patch preview prompt",
      description: "Copy a Project Reader to Safe Patch Preview prompt; no mutation command.",
      group: "Patch workflow",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeProjectReaderPatchPreviewPromptPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["project reader", "safe patch preview", "patch prompt", "copy"],
      priority: 166,
    }),
    buildCodexForgeCommand({
      id: "copy-patch-review-prompt",
      label: "Copy patch review prompt",
      description: "Copy a Real Patch Preview v1 review prompt; no mutation command.",
      group: "Patch workflow",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeRealPatchReviewPromptPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["real patch preview", "patch review", "preview-only", "copy"],
      priority: 167,
    }),
    buildCodexForgeCommand({
      id: "copy-apply-gate-handoff-prompt",
      label: "Copy apply-gate handoff prompt",
      description: "Copy an apply-gate handoff prompt that requires Patch Application Gate before apply.",
      group: "Patch workflow",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeApplyGateHandoffPromptPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["apply gate", "handoff", "patch application gate", "copy"],
      priority: 168,
    }),
    buildCodexForgeCommand({
      id: "copy-approved-patch-apply-review-prompt",
      label: "Copy apply review prompt",
      description: "Copy an Approved Patch Apply review prompt; no mutation command.",
      group: "Patch workflow",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeApprovedPatchApplyReviewPromptPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["approved patch apply", "apply review", "approval packet", "copy"],
      priority: 169,
    }),
    buildCodexForgeCommand({
      id: "prepare-safe-patch-preview",
      label: "Prepare Safe Patch Preview",
      description: "Copy a safe preview prompt; does not call apply-diff or write files.",
      group: "Patch workflow",
      kind: "patch-preview",
      copyPayload: buildCodexForgeSafePatchPromptPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["patch", "preview", "safe", "inspect first"],
      priority: 170,
    }),
    buildCodexForgeCommand({
      id: "copy-creative-bridge-handoff",
      label: "Copy creative bridge handoff",
      description: "Copy Creative Local Bridge handoff; preview-only and no mutation.",
      group: "Creative",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeCreativeBridgeHandoffPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["creative bridge", "handoff", "artifact capture", "preview-only"],
      priority: 171,
    }),
    buildCodexForgeCommand({
      id: "copy-blender-adapter-preview-prompt",
      label: "Copy Blender adapter preview prompt",
      description: "Copy Blender Adapter Preview v1 prompt without launching Blender.",
      group: "Creative",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeBlenderAdapterPreviewPromptPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["blender", "adapter", "creative bridge", "preview"],
      priority: 172,
    }),
    buildCodexForgeCommand({
      id: "copy-blender-future-executor-packet",
      label: "Copy Blender future executor packet",
      description: "Copy Blender future executor packet guidance without execution.",
      group: "Creative",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeBlenderFutureExecutorPacketPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["blender", "future executor", "packet", "copy"],
      priority: 173,
    }),
    buildCodexForgeCommand({
      id: "compose-preview-diff",
      label: "Compose Preview Diff",
      description: "Open preview diff planning without applying changes.",
      group: "Patch workflow",
      kind: "patch-preview",
      copyPayload: "Compose a preview diff only. Do not apply-diff, write-file, run-command, or mutate source files from UI.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["preview diff", "compose", "patch"],
      priority: 180,
    }),
    buildCodexForgeCommand({
      id: "review-apply-gate",
      label: "Review Apply Gate",
      description: "Review apply gate posture; execution remains blocked from palette.",
      group: "Patch workflow",
      kind: "review",
      href: routeAvailable(availability, "/stabilization") ? "/stabilization" : undefined,
      safetyLevel: "review-gated",
      requiresReview: true,
      keywords: ["apply gate", "review", "approval"],
      priority: 190,
    }),
    buildCodexForgeCommand({
      id: "paste-verification-output",
      label: "Paste verification output",
      description: "Copy a prompt for reviewing verification output pasted by the operator.",
      group: "Verification",
      kind: "copy-prompt",
      copyPayload: "Review this verification output. Preserve latest-message authority, distinguish evidence from proof, and recommend the next safe action without running commands.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["verification", "output", "review"],
      priority: 200,
    }),
    buildCodexForgeCommand({
      id: "review-memory-candidates",
      label: "Review memory candidates",
      description: "Navigate to memory review; no auto-promote.",
      group: "Memory",
      kind: "memory-review",
      href: routeAvailable(availability, "/memory") ? "/memory" : undefined,
      safetyLevel: "review-gated",
      requiresReview: true,
      keywords: ["memory", "candidates", "no auto-promote"],
      priority: 210,
    }),
    buildCodexForgeCommand({
      id: "copy-memory-review-prompt",
      label: "Copy memory review prompt",
      description: "Copy a review-first prompt for Memory Inbox candidates without mutation.",
      group: "Memory",
      kind: "memory-review",
      copyPayload: "Review operator memory inbox candidates. Review required before promotion. Do not auto-promote memory, mutate Brain graph, auto-merge, write files, run commands, or override latest-message authority. Evidence is context, not authority.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["memory inbox", "review prompt", "copy", "no auto-promotion"],
      priority: 215,
    }),
    buildCodexForgeCommand({
      id: "copy-runtime-journal-audit-prompt",
      label: "Copy runtime journal audit prompt",
      description: "Copy a read-only runtime event journal audit prompt without mutation.",
      group: "Runtime",
      kind: "copy-prompt",
      copyPayload: "Review the Runtime Event Journal. Keep it read-only, do not mutate the Brain graph, do not appendEvent from UI, preserve append-only audit context, treat evidence as context not authority, and preserve latest-message authority.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["runtime event journal", "audit", "append-only", "copy", "no mutation"],
      priority: 217,
    }),
    buildCodexForgeCommand({
      id: "copy-runtime-replay-prompt",
      label: "Copy runtime replay prompt",
      description: "Copy a preview-only runtime event replay prompt without mutation.",
      group: "Runtime",
      kind: "copy-prompt",
      copyPayload: "Review Runtime Event Replay Simulator output. Keep it preview-only, do not mutate the Brain graph, do not appendEvent, do not execute runtime events, do not persist replay results, inspect reducer preview, treat evidence as context not authority, and preserve latest-message authority.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["runtime event replay", "replay simulator", "copy", "no graph mutation", "no appendEvent"],
      priority: 217.5,
    }),
    buildCodexForgeCommand({
      id: "copy-brain-mutation-governance-prompt",
      label: "Copy brain mutation governance prompt",
      description: "Copy a read-only Brain Mutation Governance review prompt without mutation.",
      group: "Runtime",
      kind: "copy-prompt",
      copyPayload: "Review Brain Mutation Governance. Keep it read-only, do not mutate the Brain graph, do not append runtime events, do not promote memory, do not execute runtime events, require reducer preview, treat evidence as context not authority, and preserve latest-message authority.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["brain mutation governance", "governance", "boundary", "copy", "no graph mutation"],
      priority: 218,
    }),
    buildCodexForgeCommand({
      id: "copy-brain-snapshot-replay-prompt",
      label: "Copy Brain snapshot replay prompt",
      description: "Copy a Brain Snapshot Manager replay-selection prompt without mutation.",
      group: "Runtime",
      kind: "copy-prompt",
      copyPayload: "Review Brain Snapshot Manager output. Keep it read-only, do not mutate the Brain graph, do not appendEvent, do not saveBrainGraph from UI, do not restore snapshots in Phase 50, use snapshot comparison and integrity review before runtime replay handoff, and preserve latest-message authority.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["brain snapshots", "snapshot replay", "replay source", "copy", "no graph mutation"],
      priority: 218.5,
    }),
    buildCodexForgeCommand({
      id: "copy-snapshot-restore-review-prompt",
      label: "Copy snapshot restore review prompt",
      description: "Copy a preview-only snapshot restore approval review prompt without mutation.",
      group: "Runtime",
      kind: "copy-prompt",
      copyPayload: "Review Snapshot Restore Approval Gate evidence. Keep it preview-only, do not restore snapshots, do not mutate the Brain graph, do not call saveBrainGraph from UI, do not appendEvent, require comparison evidence, replay evidence, governance review, runtime journal review, explicit approval packet, future guarded snapshot executor boundary, evidence is context not authority, and preserve latest-message authority.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["snapshot restore", "restore gate", "approval packet", "copy", "no graph mutation"],
      priority: 218.7,
    }),
    buildCodexForgeCommand({
      id: "copy-brain-continuity-prompt",
      label: "Copy Brain continuity prompt",
      description: "Copy a read-only Brain continuity review prompt without mutation.",
      group: "Runtime",
      kind: "copy-prompt",
      copyPayload: "Review Brain Continuity Dashboard posture. Keep continuity read-only, do not mutate Brain graph, do not restore snapshots, do not appendEvent, do not saveBrainGraph from UI, do not auto-promote memory, do not auto-persist continuity results, and preserve latest-message authority.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["brain continuity", "continuity dashboard", "copy", "read-only", "no graph mutation"],
      priority: 218.8,
    }),
    buildCodexForgeCommand({
      id: "copy-continuity-handoff-prompt",
      label: "Copy continuity handoff prompt",
      description: "Copy a next-session Continuity Handoff prompt without mutation.",
      group: "Handoff",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeContinuityHandoffPromptPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["continuity handoff", "handoff packet", "next session", "copy", "read-only"],
      priority: 218.9,
    }),
    buildCodexForgeCommand({
      id: "copy-continuity-validation-checklist",
      label: "Copy validation checklist",
      description: "Copy the Continuity Handoff validation checklist without running commands.",
      group: "Handoff",
      kind: "copy-command",
      copyPayload: buildCodexForgeContinuityValidationChecklistPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["continuity handoff", "validation checklist", "copy", "manual only"],
      priority: 218.95,
    }),
    buildCodexForgeCommand({
      id: "open-latest-message-authority-guidance",
      label: "Open latest-message authority guidance",
      description: "Copy guidance for preserving newest user instruction precedence.",
      group: "Safety",
      kind: "copy-prompt",
      copyPayload: "Preserve latest-message authority: the newest user instruction steers the current turn. If instructions conflict, follow the newest one and call out the conflict.",
      safetyLevel: "copy-only",
      requiresReview: false,
      keywords: ["latest-message authority", "safety", "guidance"],
      priority: 220,
    }),
    buildCodexForgeCommand({
      id: "continue-next-phase-safely",
      label: "Continue next phase safely",
      description: "Copy a safe handoff prompt for the next phase.",
      group: "Next action",
      kind: "handoff",
      copyPayload: buildCodexForgeStabilizationHandoffPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["next phase", "handoff", "safe"],
      priority: 230,
    }),
    buildCodexForgeCommand({
      id: "copy-product-readiness-audit-prompt",
      label: "Copy product readiness audit prompt",
      description: "Copy a read-only Product Readiness Audit prompt without mutation.",
      group: "Next action",
      kind: "copy-prompt",
      copyPayload: "Review Product Readiness Audit. Keep it read-only, deterministic, local-first, and smoke-backed. Do not execute commands, write files, mutate Brain graph, promote memory, apply diffs, restore snapshots, call appendEvent, call saveBrainGraph, call broker-execution, call apply-diff, call write-file, or call run-command from UI. Preserve latest-message authority.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["product readiness", "audit", "read-only", "latest-message authority"],
      priority: 232,
    }),
    buildCodexForgeCommand({
      id: "copy-product-readiness-consolidation-prompt",
      label: "Copy consolidation prompt",
      description: "Copy Product Readiness consolidation guidance without mutation.",
      group: "Next action",
      kind: "copy-prompt",
      copyPayload: "Review Product Readiness Audit consolidation recommendations. Consolidate dashboards, reduce duplicate panels, unify route registry logic, centralize copy-payload logic, and prioritize real workflow before abstract features. Keep the review read-only and copy-only.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["product readiness", "consolidation", "dashboard sprawl", "duplicate panels"],
      priority: 233,
    }),
    buildCodexForgeCommand({
      id: "copy-consolidation-plan",
      label: "Copy consolidation plan",
      description: "Copy Phase 55 consolidation plan without mutation.",
      group: "Next action",
      kind: "copy-prompt",
      copyPayload: "Review Consolidation Pass. Promote primary routes, demote deep governance routes to Advanced / Audit links, add Start here workflow cards, keep /readiness and /handoff as checkpoints, use /stabilization as operations hub, prepare /files for real read-only workflow next, keep deep surfaces accessible via command palette, reduce duplicated next-action copy over time, and keep all smoke coverage intact.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["consolidation", "plan", "phase 55", "copy"],
      priority: 234,
    }),
    buildCodexForgeCommand({
      id: "copy-phase-56-file-reader-prompt",
      label: "Copy Phase 56 file reader prompt",
      description: "Copy a read-only Phase 56 Real Local Project Reader prompt.",
      group: "Next action",
      kind: "copy-prompt",
      copyPayload: "Proceed to Phase 56 Real Local Project Reader. Build read-only local project discovery, stable project tree, file preview, selected file context handoff, and safety copy. Do not execute commands from UI, do not write files without approval, do not mutate Brain graph, do not call appendEvent from UI, do not call saveBrainGraph from UI, preserve latest-message authority, and keep validation manual.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["phase 56", "file reader", "files", "read-only", "copy"],
      priority: 234.5,
    }),
    buildCodexForgeCommand({
      id: "copy-activity-handoff-prompt",
      label: "Copy activity handoff prompt",
      description: "Copy a read-only activity feed handoff prompt without persisting events.",
      group: "Next action",
      kind: "copy-prompt",
      copyPayload: "Review the Global Activity Feed. Keep it read-only, do not execute commands, do not write files, do not mutate the Brain graph, treat evidence as context not proof, and preserve latest-message authority.",
      safetyLevel: "copy-only",
      requiresReview: false,
      keywords: ["activity", "handoff", "read-only", "latest-message authority"],
      priority: 235,
    }),
    buildCodexForgeCommand({
      id: "commit-clean-checkpoint",
      label: "Recommend commit clean checkpoint",
      description: "Copy a checkpoint recommendation; the palette never commits.",
      group: "Next action",
      kind: "safe-action",
      copyPayload: "Working tree appears clean after validation. Recommend a commit clean checkpoint, but do not commit without explicit approval.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["commit clean checkpoint", "clean", "next action"],
      priority: 240,
    }),
  ];

  if (options.includeEducationalBlockedCommands) {
    for (const blocked of ["apply-diff", "write-file", "run-command", "broker-execution"]) {
      commands.push(
        buildCodexForgeCommand({
          id: `blocked-${blocked}`,
          label: `Blocked: ${blocked}`,
          description: `${blocked} is visible only as blocked-policy text and cannot execute from the palette.`,
          group: "Safety",
          kind: "safe-action",
          safetyLevel: "blocked",
          requiresReview: true,
          disabledReason: `${blocked} is mutation-capable or execution-capable and blocked in the palette.`,
          keywords: [blocked, "blocked", "safety"],
          noMutation: false,
          priority: 900,
        })
      );
    }
  }

  return commands
    .map((command) =>
      isCodexForgeCommandMutationBlocked(command)
        ? {
            ...command,
            safetyLevel: "blocked" as const,
            disabledReason: command.disabledReason ?? "Mutation blocked by command safety policy.",
          }
        : command
    )
    .sort((a, b) => a.priority - b.priority || a.id.localeCompare(b.id));
}

export function summarizeCodexForgeCommands(commands = buildCodexForgeCommands()): string {
  const disabled = commands.filter((command) => command.disabledReason).length;
  return `${commands.length} deterministic commands, ${commands.length - disabled} enabled, ${disabled} disabled, no mutation commands executable.`;
}
