import type {
  CodexForgeCommand,
  CodexForgeCommandInput,
  CodexForgeCommandRegistryOptions,
  CodexForgeCommandRouteAvailability,
} from "./command-palette-types";
import {
  buildCodexForgeContinuityHandoffPromptPayload,
  buildCodexForgeContinuityValidationChecklistPayload,
  buildCodexForgeApplyGateHandoffPromptPayload,
  buildCodexForgeApprovedPatchApplyReviewPromptPayload,
  buildCodexForgeApplyGuardRequiredFixesPayload,
  buildCodexForgeApplyGuardReviewPayload,
  buildCodexForgeBlenderAdapterPreviewPromptPayload,
  buildCodexForgeBlenderFutureExecutorPacketPayload,
  buildCodexForgeCreativeExecutorDryRunPayload,
  buildCodexForgeCreativeExecutorFuturePacketPayload,
  buildCodexForgeCreativeReadinessHealthProbePacketPayload,
  buildCodexForgeCreativeReadinessReportPayload,
  buildCodexForgeCreativeMvpDesignPacketPayload,
  buildCodexForgeCreativeMvpUserFlowPayload,
  buildCodexForgeFutureHealthProbePacketPayload,
  buildCodexForgeLocalBridgeSetupGuidePayload,
  buildCodexForgeVideoRenderFutureExecutorPacketPayload,
  buildCodexForgeVideoRenderPlanPayload,
  buildCodexForgeVideoRenderQueuePayload,
  buildCodexForgeUnrealCommandPreviewPromptPayload,
  buildCodexForgeUnrealFutureExecutorPacketPayload,
  buildCodexForgeCreativeBridgeHandoffPayload,
  buildCodexForgeCreativeSandboxReportPayload,
  buildCodexForgeCreativeSandboxReviewHandoffPayload,
  buildCodexForgeFileInspectionPromptPayload,
  buildCodexForgeProjectReaderPatchPreviewPromptPayload,
  buildCodexForgeRealPatchReviewPromptPayload,
  buildCodexForgeSafePatchPromptPayload,
  buildCodexForgeStabilizationHandoffPayload,
  buildCodexForgeValidationChecklistPayload,
  buildCodexForgeHardenedValidationChecklistPayload,
  buildCodexForgeHardenedRollbackPlanPayload,
  buildCodexForgeCompletionGuidancePayload,
  buildCodexForgeWorkflowHandoffPayload,
  buildCodexForgeValidationResultSummaryPayload,
  buildCodexForgeMemoryReviewCandidatePayload,
  buildCodexForgeCodingUxFixChecklistPayload,
  buildCodexForgeSimplifiedValidationCopyPayload,
  buildCodexForgeRouteHandoffChecklistPayload,
  buildCodexForgeGuardedApplyCandidateBriefPayload,
  buildCodexForgeGuardedApplyCandidatePlanPayload,
  buildCodexForgeGuardedApplyImplementationGapsPayload,
  buildCodexForgeGuardedApplyNextPromptPayload,
} from "./command-copy-payloads";
import { isCodexForgeCommandMutationBlocked } from "./command-safety";

const DEFAULT_ROUTE_AVAILABILITY: CodexForgeCommandRouteAvailability = {
  "/": true,
  "/start": true,
  "/onboarding": true,
  "/first-task": true,
  "/safety-coach": true,
  "/help-empty-states": true,
  "/assisted-quality": true,
  "/assist": true,
  "/code-flow": true,
  "/code-flow/live-run": true,
  "/code-flow/manual-trial": true,
  "/code-flow/friction-fixes": true,
  "/code-flow/mvp-path": true,
  "/code-flow/release-audit": true,
  "/code-flow/trial": true,
  "/code-flow/trial-review": true,
  "/code-flow/ux-fixes": true,
  "/apply-guard-review": true,
  "/guarded-apply-candidate": true,
  "/guarded-apply-mvp": true,
  "/guarded-apply-mvp/trial-hardening": true,
  "/apply-evidence": true,
  "/validation-results": true,
  "/review-inbox": true,
  "/recovery": true,
  "/apply-validation": true,
  "/workflow-results": true,
  "/run-history": true,
  "/release-smoke": true,
  "/demo": true,
  "/product-trial": true,
  "/runbook": true,
  "/mvp-experience": true,
  "/ai": true,
  "/ai-router": true,
  "/ai-providers": true,
  "/provider-adapters": true,
  "/provider-health": true,
  "/local-machine": true,
  "/local-creative": true,
  "/comfyui-health": true,
  "/video-workflows": true,
  "/video-jobs": true,
  "/video-prompt": true,
  "/storyboard": true,
  "/keyframes": true,
  "/local-draft-review": true,
  "/comfyui-workflows/import": true,
  "/comfyui-workflows/safety": true,
  "/comfyui-workflows/parameters": true,
  "/comfyui-jobs/package": true,
  "/video-artifacts": true,
  "/video-review": true,
  "/video-recovery": true,
  "/video-compare": true,
  "/video-upscale": true,
  "/video-interpolation": true,
  "/video-finishing": true,
  "/video-final-render": true,
  "/creative-cost-router": true,
  "/gpu-scheduler": true,
  "/dual-gpu": true,
  "/render-queue": true,
  "/env-readiness": true,
  "/local-provider-probes": true,
  "/provider-tests": true,
  "/model-capabilities": true,
  "/task-router": true,
  "/credentials": true,
  "/provider-setup": true,
  "/token-router": true,
  "/brain": true,
  "/files": true,
  "/tasks": true,
  "/closed-loop": true,
  "/memory": true,
  "/memory-inbox": true,
  "/runtime-journal": true,
  "/runtime-replay": true,
  "/brain-snapshots": true,
  "/snapshot-restore": true,
  "/brain-continuity": true,
  "/handoff": true,
  "/brain-governance": true,
  "/creative": true,
  "/video-render": true,
  "/creative-executor": true,
  "/creative-sandbox": true,
  "/creative-readiness": true,
  "/creative-mvp": true,
  "/health-probe": true,
  "/local-bridge-health": true,
  "/blender": true,
  "/unreal": true,
  "/comfyui": true,
  "/creative-bridge": true,
  "/capabilities": true,
  "/activity": true,
  "/readiness": true,
  "/quality-audit": true,
  "/consolidation": true,
  "/validation": true,
  "/stabilization": true,
};

export function buildCodexForgeCommand(input: CodexForgeCommandInput): CodexForgeCommand {
  const noMutation = input.noMutation ?? true;
  const disabledReason =
    input.disabledReason ??
    (noMutation ? undefined : "Mutation commands are blocked from the global command palette.");

  return {
    description: "",
    group: "Safety",
    kind: "safe-action",
    safetyLevel: disabledReason ? "blocked" : "safe",
    requiresReview: false,
    keywords: [],
    priority: 1000,
    ...input,
    noMutation,
    disabledReason,
  };
}

function routeAvailable(
  availability: CodexForgeCommandRouteAvailability,
  href: NonNullable<CodexForgeCommand["href"]>
): boolean {
  return availability[href] === true;
}

function buildRouteCommand(
  availability: CodexForgeCommandRouteAvailability,
  input: CodexForgeCommandInput & { href: NonNullable<CodexForgeCommand["href"]> }
): CodexForgeCommand | null {
  if (!routeAvailable(availability, input.href)) return null;
  return buildCodexForgeCommand({
    group: "Navigate",
    kind: "route",
    safetyLevel: "safe",
    requiresReview: false,
    noMutation: true,
    ...input,
  });
}

export function buildCodexForgeCommands(
  options: CodexForgeCommandRegistryOptions = {}
): CodexForgeCommand[] {
  const availability = { ...DEFAULT_ROUTE_AVAILABILITY, ...options.routeAvailability };
  const routeCommands = [
    buildRouteCommand(availability, {
      id: "go-operator-home",
      label: "Go to Operator Home",
      description: "Navigate to the operator dashboard.",
      href: "/",
      keywords: ["home", "dashboard", "operator", "route"],
      priority: 10,
    }),
    buildRouteCommand(availability, {
      id: "go-start",
      label: "Go to Start",
      description: "Open the plain-English guided start page.",
      href: "/start",
      keywords: ["start", "guided", "what do i do", "route"],
      priority: 12,
    }),
    buildRouteCommand(availability, {
      id: "go-onboarding",
      label: "Go to Onboarding",
      description: "Open the first-run safe coding guide; no execution command.",
      href: "/onboarding",
      keywords: ["onboarding", "first run", "start with codexforge", "safe coding flow"],
      priority: 12.02,
    }),
    buildRouteCommand(availability, {
      id: "go-first-task",
      label: "Go to First Task",
      description: "Open the novice first safe task guide; no auto-apply or auto-run.",
      href: "/first-task",
      keywords: ["first task", "first safe task", "novice", "preview", "approval"],
      priority: 12.025,
    }),
    buildRouteCommand(availability, {
      id: "go-safety-coach",
      label: "Go to Safety Coach",
      description: "Open plain-English safety explanations for preview, apply, evidence, validation, and rollback.",
      href: "/safety-coach",
      keywords: ["safety coach", "plain english", "preview", "apply", "evidence", "validation"],
      priority: 12.026,
    }),
    buildRouteCommand(availability, {
      id: "go-helpful-empty-states",
      label: "Go to Helpful Empty States",
      description: "Open the empty-state checklist for novice-friendly help.",
      href: "/help-empty-states",
      keywords: ["empty states", "help", "blank", "what next"],
      priority: 12.027,
    }),
    buildRouteCommand(availability, {
      id: "go-assisted-quality",
      label: "Go to Assisted MVP Quality",
      description: "Open the assisted MVP quality sweep.",
      href: "/assisted-quality",
      keywords: ["assisted quality", "quality sweep", "novice path", "mvp"],
      priority: 12.028,
    }),
    buildRouteCommand(availability, {
      id: "go-assisted-coding",
      label: "Go to Assisted Coding",
      description: "Choose a coding goal and see the next safe step; no auto-run or auto-apply.",
      href: "/assist",
      keywords: ["assist", "assisted coding", "next safe step", "goal"],
      priority: 12.03,
    }),
    buildRouteCommand(availability, {
      id: "open-workflow-wizard",
      label: "Open workflow wizard",
      description: "Open the guided workflow wizard; no execution command.",
      href: "/start",
      keywords: ["workflow wizard", "wizard", "start", "guided"],
      priority: 12.1,
    }),
    buildRouteCommand(availability, {
      id: "go-code-flow",
      label: "Go to Code Flow",
      description: "Open the end-to-end safe code fix flow; no execution command.",
      href: "/code-flow",
      keywords: ["code flow", "fix code safely", "real coding flow", "route"],
      priority: 13,
    }),
    buildRouteCommand(availability, {
      id: "open-coding-mvp-path",
      label: "Open Coding MVP Path",
      description: "Open the locked coding MVP path; no execution command.",
      href: "/code-flow/mvp-path",
      keywords: ["coding mvp path", "locked path", "mvp working path", "route"],
      priority: 13.01,
    }),
    buildRouteCommand(availability, {
      id: "go-code-flow-live-run",
      label: "Go to Coding Live Run",
      description: "Open the guided live coding run; no execution command.",
      href: "/code-flow/live-run",
      keywords: ["live run", "coding flow", "guided path", "route"],
      priority: 13.02,
    }),
    buildRouteCommand(availability, {
      id: "go-manual-coding-trial",
      label: "Run manual coding trial",
      description: "Open the manual coding trial checklist; copy-only and no execution command.",
      href: "/code-flow/manual-trial",
      keywords: ["manual trial", "coding trial", "checklist", "route"],
      priority: 13.03,
    }),
    buildRouteCommand(availability, {
      id: "go-friction-fixes",
      label: "Fix trial friction",
      description: "Open the friction fix plan; no execution command.",
      href: "/code-flow/friction-fixes",
      keywords: ["friction fixes", "trial friction", "copy plan", "route"],
      priority: 13.04,
    }),
    buildRouteCommand(availability, {
      id: "go-coding-trial",
      label: "Go to Coding Trial",
      description: "Open the guided Coding Flow Live Trial Pack; no execution command.",
      href: "/code-flow/trial",
      keywords: ["coding trial", "code flow trial", "live trial", "route"],
      priority: 13.05,
    }),
    buildRouteCommand(availability, {
      id: "open-demo-mode",
      label: "Open Demo Mode",
      description: "Open the operator demo mode for the coding MVP; no execution command.",
      href: "/demo",
      keywords: ["demo", "operator demo", "coding mvp", "route"],
      priority: 13.051,
    }),
    buildRouteCommand(availability, {
      id: "go-release-smoke",
      label: "Go to Release Smoke Pack",
      description: "Open the copy-only release smoke checklist.",
      href: "/release-smoke",
      keywords: ["release smoke", "smoke checklist", "manual validation", "route"],
      priority: 13.052,
    }),
    buildRouteCommand(availability, {
      id: "start-coding-trial",
      label: "Start coding trial",
      description: "Start the guided coding trial with checklist and manual validation guidance.",
      href: "/code-flow/trial",
      keywords: ["start coding trial", "trial checklist", "manual validation", "no auto-run"],
      priority: 13.06,
    }),
    buildRouteCommand(availability, {
      id: "go-coding-trial-review",
      label: "Go to Coding Trial Review",
      description: "Open the copy-only trial run review with friction, pass/fail, UX fixes, and go/no-go.",
      href: "/code-flow/trial-review",
      keywords: ["coding trial review", "trial review", "go no go", "ux fix", "route"],
      priority: 13.07,
    }),
    buildRouteCommand(availability, {
      id: "go-coding-ux-fixes",
      label: "Go to Coding UX Fixes",
      description: "Open the copy-only Coding Flow UX Fix Pack; no execution command.",
      href: "/code-flow/ux-fixes",
      keywords: ["coding ux fixes", "ux fix checklist", "code flow friction", "route"],
      priority: 13.08,
    }),
    buildRouteCommand(availability, {
      id: "go-apply-validation",
      label: "Go to Apply and Validation",
      description: "Open Apply Validation Hardening for reviewable diff, approval policy, rollback, validation output, and result routing.",
      href: "/apply-validation",
      keywords: ["apply validation", "apply safely", "validate", "hardening", "route"],
      priority: 13.2,
    }),
    buildRouteCommand(availability, {
      id: "go-apply-guard-review",
      label: "Go to Apply Guard Review",
      description: "Open Real Apply Guard Review; no execution command.",
      href: "/apply-guard-review",
      keywords: ["apply guard review", "real apply guard", "approval packet", "rollback", "go no go"],
      priority: 13.19,
    }),
    buildRouteCommand(availability, {
      id: "go-guarded-apply-candidate",
      label: "Go to Guarded Apply Candidate",
      description: "Open the design-only first guarded apply candidate plan; no execution command.",
      href: "/guarded-apply-candidate",
      keywords: ["guarded apply candidate", "one file", "one diff", "approval", "route"],
      priority: 13.195,
    }),
    buildRouteCommand(availability, {
      id: "go-guarded-apply-mvp",
      label: "Go to Guarded Apply MVP",
      description: "Open the one-file, one-diff, explicit-approval apply review; no execution command.",
      href: "/guarded-apply-mvp",
      keywords: ["guarded apply", "one file", "one diff", "approval", "route"],
      priority: 13.2,
    }),
    buildRouteCommand(availability, {
      id: "go-first-apply-trial-hardening",
      label: "Go to First Apply Trial Hardening",
      description: "Review first guarded apply readiness, rollback, evidence, and validation handoff.",
      href: "/guarded-apply-mvp/trial-hardening",
      keywords: ["first apply", "trial hardening", "guarded apply", "rollback", "route"],
      priority: 13.205,
    }),
    buildRouteCommand(availability, {
      id: "go-apply-evidence",
      label: "Go to Apply Evidence",
      description: "Capture apply evidence manually after approval; no auto-apply or auto-run.",
      href: "/apply-evidence",
      keywords: ["apply evidence", "evidence capture", "approval", "route"],
      priority: 13.25,
    }),
    buildRouteCommand(availability, {
      id: "go-validation-results",
      label: "Go to Validation Results",
      description: "Paste validation output and classify the result separately from apply.",
      href: "/validation-results",
      keywords: ["validation results", "paste output", "manual validation", "route"],
      priority: 13.28,
    }),
    buildRouteCommand(availability, {
      id: "go-review-inbox",
      label: "Go to Review Inbox",
      description: "Review evidence, validation, recovery, run history, and demo handoffs.",
      href: "/review-inbox",
      keywords: ["review inbox", "needs review", "evidence", "validation", "recovery"],
      priority: 13.285,
    }),
    buildRouteCommand(availability, {
      id: "go-recovery",
      label: "Go to Recovery",
      description: "Open guided recovery for failed validation, blocked apply, or unknown results.",
      href: "/recovery",
      keywords: ["recovery", "retry", "rollback", "failed validation", "blocked apply"],
      priority: 13.286,
    }),
    buildRouteCommand(availability, {
      id: "go-workflow-results",
      label: "Go to Workflow Results",
      description: "Open Workflow Result Persistence for reviewed records, handoffs, validation summaries, and memory candidates.",
      href: "/workflow-results",
      keywords: ["workflow results", "result persistence", "handoff", "validation summary", "memory candidate"],
      priority: 13.3,
    }),
    buildRouteCommand(availability, {
      id: "go-run-history",
      label: "Go to Run History",
      description: "Open the reviewed run history timeline; no persistence or execution command.",
      href: "/run-history",
      keywords: ["run history", "timeline", "recent runs", "handoff", "review"],
      priority: 13.35,
    }),
    buildRouteCommand(availability, {
      id: "review-recent-runs",
      label: "Review recent runs",
      description: "Review recent workflow runs and choose the next safe action.",
      href: "/run-history",
      keywords: ["review recent runs", "run history", "workflow timeline"],
      priority: 13.36,
    }),
    buildRouteCommand(availability, {
      id: "go-product-trial",
      label: "Go to Product Trial",
      description: "Run the real MVP path manually and capture route friction, validation, result, and handoff.",
      href: "/product-trial",
      keywords: ["product trial", "manual trial", "friction", "mvp path", "route"],
      priority: 13.37,
    }),
    buildRouteCommand(availability, {
      id: "go-runbook",
      label: "Go to Runbook",
      description: "Open the operator runbook and recovery playbook; copy-only and no command execution.",
      href: "/runbook",
      keywords: ["runbook", "recovery", "rollback", "operator guide", "route"],
      priority: 13.38,
    }),
    buildRouteCommand(availability, {
      id: "go-mvp-experience-lock",
      label: "Go to MVP Experience Lock",
      description: "Review the release demo readiness decision and copy the handoff.",
      href: "/mvp-experience",
      keywords: ["mvp experience", "demo ready", "release handoff", "route"],
      priority: 13.39,
    }),
    buildRouteCommand(availability, {
      id: "start-safe-code-fix",
      label: "Start safe code fix",
      description: "Start the code fix flow with file inspection, patch preview, apply review, and validation handoff.",
      href: "/code-flow",
      keywords: ["start safe code fix", "fix code", "preview patch", "approval"],
      priority: 13.1,
    }),
    buildRouteCommand(availability, {
      id: "go-ai-workspace",
      label: "Go to AI Workspace",
      description: "Navigate to planning, chat, and reviewed handoffs.",
      href: "/ai",
      keywords: ["ai", "workspace", "chat", "route"],
      priority: 20,
    }),
    buildRouteCommand(availability, {
      id: "go-ai-router",
      label: "Go to AI Router",
      description: "Navigate to preview-only model routing guidance.",
      href: "/ai-router",
      keywords: ["ai", "router", "model routing", "route"],
      priority: 25,
    }),
    buildRouteCommand(availability, {
      id: "go-ai-provider-registry",
      label: "Go to AI Provider Registry",
      description: "Open provider account profiles; manual handoff only and no credential storage.",
      href: "/ai-providers",
      keywords: ["ai", "provider", "registry", "manual handoff", "profile"],
      priority: 25.1,
    }),
    buildRouteCommand(availability, {
      id: "go-provider-adapters",
      label: "Go to Provider Adapters",
      description: "Open provider adapter definitions, readiness, and safety boundaries with no provider calls.",
      href: "/provider-adapters",
      keywords: ["provider adapters", "adapter readiness", "openai-compatible", "claude", "gemini", "deepseek", "ollama", "lm studio"],
      priority: 25.15,
    }),
    buildRouteCommand(availability, {
      id: "go-provider-health",
      label: "Go to Provider Health",
      description: "Open provider readiness states with no provider calls and no secret display.",
      href: "/provider-health",
      keywords: ["provider health", "configured", "manual only", "missing key", "planned"],
      priority: 25.16,
    }),
    buildRouteCommand(availability, {
      id: "go-local-machine",
      label: "Go to Local Machine",
      description: "Open the manual local workstation capability profile.",
      href: "/local-machine",
      keywords: ["local machine", "workstation", "gpu", "local first", "video"],
      priority: 25.161,
    }),
    buildRouteCommand(availability, {
      id: "go-local-creative",
      label: "Go to Local Creative",
      description: "Open local creative provider planning with no generation and no cloud spend.",
      href: "/local-creative",
      keywords: ["local creative", "creative providers", "comfyui", "video drafts", "cloud credits"],
      priority: 25.1615,
    }),
    buildRouteCommand(availability, {
      id: "go-comfyui-health",
      label: "Go to ComfyUI Health",
      description: "Open the preview-only ComfyUI health check plan with no workflow run.",
      href: "/comfyui-health",
      keywords: ["comfyui health", "local health", "workflow blocked", "localhost"],
      priority: 25.1616,
    }),
    buildRouteCommand(availability, {
      id: "go-video-workflows",
      label: "Go to Video Workflows",
      description: "Open local-first video workflow planning before cloud credits are spent.",
      href: "/video-workflows",
      keywords: ["video workflows", "local draft", "keyframes", "workflow catalog"],
      priority: 25.1617,
    }),
    buildRouteCommand(availability, {
      id: "go-video-jobs",
      label: "Go to Video Jobs",
      description: "Open the video job queue preview with no render execution.",
      href: "/video-jobs",
      keywords: ["video jobs", "queue preview", "no auto run", "local draft"],
      priority: 25.1618,
    }),
    buildRouteCommand(availability, {
      id: "go-video-prompt-builder",
      label: "Go to Video Prompt Builder",
      description: "Build a clear video prompt before anything renders.",
      href: "/video-prompt",
      keywords: ["video prompt", "prompt builder", "storyboard handoff", "nothing generated"],
      priority: 25.1619,
    }),
    buildRouteCommand(availability, {
      id: "go-storyboard",
      label: "Go to Storyboard",
      description: "Plan video shots before keyframes or local drafts.",
      href: "/storyboard",
      keywords: ["storyboard", "shots", "timing", "keyframe handoff"],
      priority: 25.162,
    }),
    buildRouteCommand(availability, {
      id: "go-keyframes",
      label: "Go to Keyframes",
      description: "Plan still-frame anchors without generating images.",
      href: "/keyframes",
      keywords: ["keyframes", "still frames", "image generation later", "draft handoff"],
      priority: 25.1621,
    }),
    buildRouteCommand(availability, {
      id: "go-local-draft-review",
      label: "Go to Local Draft Review",
      description: "Review a future local video draft before anything renders.",
      href: "/local-draft-review",
      keywords: ["local draft review", "video draft", "approval", "no auto run"],
      priority: 25.1622,
    }),
    buildRouteCommand(availability, {
      id: "go-comfyui-workflow-import",
      label: "Go to ComfyUI Workflow Import",
      description: "Preview workflow metadata safely before safety inspection or parameter mapping.",
      href: "/comfyui-workflows/import",
      keywords: ["comfyui workflow import", "workflow import", "workflow json", "preview only"],
      priority: 25.1623,
    }),
    buildRouteCommand(availability, {
      id: "go-workflow-safety",
      label: "Go to Workflow Safety",
      description: "Inspect workflow risks before any render is allowed.",
      href: "/comfyui-workflows/safety",
      keywords: ["workflow safety", "comfyui safety", "unknown nodes", "missing models"],
      priority: 25.1624,
    }),
    buildRouteCommand(availability, {
      id: "go-workflow-parameters",
      label: "Go to Workflow Parameters",
      description: "Map technical workflow settings into safe choices.",
      href: "/comfyui-workflows/parameters",
      keywords: ["workflow parameters", "parameter mapper", "prompt", "seed", "resolution"],
      priority: 25.1625,
    }),
    buildRouteCommand(availability, {
      id: "go-comfyui-job-package",
      label: "Go to ComfyUI Job Package",
      description: "Build a reviewed local video job package without submitting it.",
      href: "/comfyui-jobs/package",
      keywords: ["comfyui job package", "package builder", "future submit", "no auto run"],
      priority: 25.1626,
    }),
    buildRouteCommand(availability, {
      id: "go-video-artifacts",
      label: "Go to Video Artifacts",
      description: "Review future local creative outputs and handoffs without file browsing.",
      href: "/video-artifacts",
      keywords: ["video artifacts", "artifact gallery", "outputs", "review"],
      priority: 25.1627,
    }),
    buildRouteCommand(availability, {
      id: "go-video-review",
      label: "Go to Video Review",
      description: "Review future video drafts and choose keep, retry, compare, or recovery.",
      href: "/video-review",
      keywords: ["video review", "review inbox", "keep", "retry", "compare"],
      priority: 25.1628,
    }),
    buildRouteCommand(availability, {
      id: "go-video-recovery",
      label: "Go to Video Recovery",
      description: "Find safe next steps for failed or confusing video results.",
      href: "/video-recovery",
      keywords: ["video recovery", "failure recovery", "missing model", "retry plan"],
      priority: 25.1629,
    }),
    buildRouteCommand(availability, {
      id: "go-video-compare",
      label: "Go to Video Compare",
      description: "Compare future drafts by prompt, workflow, keyframes, quality, artifacts, and next action.",
      href: "/video-compare",
      keywords: ["video compare", "compare drafts", "draft comparison", "scorecard"],
      priority: 25.163,
    }),
    buildRouteCommand(availability, {
      id: "go-video-upscale",
      label: "Go to Video Upscale",
      description: "Plan local draft upscaling before any future approved final-quality video work.",
      href: "/video-upscale",
      keywords: ["video upscale", "upscale plan", "higher quality", "local gpu"],
      priority: 25.1631,
    }),
    buildRouteCommand(availability, {
      id: "go-video-interpolation",
      label: "Go to Video Interpolation",
      description: "Plan FPS and motion smoothing choices without creating frames.",
      href: "/video-interpolation",
      keywords: ["video interpolation", "frame interpolation", "fps", "motion smoothing"],
      priority: 25.1632,
    }),
    buildRouteCommand(availability, {
      id: "go-video-finishing",
      label: "Go to Video Finishing",
      description: "Plan final polish after choosing a reviewed draft; no render or export command.",
      href: "/video-finishing",
      keywords: ["video finishing", "final polish", "upscale", "interpolation"],
      priority: 25.1633,
    }),
    buildRouteCommand(availability, {
      id: "go-draft-to-final",
      label: "Go to Draft to Final",
      description: "Review readiness for a future approved final render without calling ComfyUI or providers.",
      href: "/video-final-render",
      keywords: ["draft to final", "final render readiness", "future approved execution", "video final"],
      priority: 25.1634,
    }),
    buildRouteCommand(availability, {
      id: "go-creative-cost-saver",
      label: "Go to Creative Cost Saver",
      description: "Choose a local-first creative route before cloud credits are spent.",
      href: "/creative-cost-router",
      keywords: ["creative cost saver", "cost", "cloud credits", "local draft", "route"],
      priority: 25.1635,
    }),
    buildRouteCommand(availability, {
      id: "go-gpu-scheduler",
      label: "Go to GPU Scheduler",
      description: "Preview local GPU job ordering without scheduling or running jobs.",
      href: "/gpu-scheduler",
      keywords: ["gpu scheduler", "queue", "local gpu", "heavy jobs", "route"],
      priority: 25.1636,
    }),
    buildRouteCommand(availability, {
      id: "go-dual-gpu-strategy",
      label: "Go to Dual-GPU Strategy",
      description: "Review two local GPUs as explicit parallel workers with no automatic selection.",
      href: "/dual-gpu",
      keywords: ["dual gpu", "parallel workers", "rtx 5090", "worker strategy", "route"],
      priority: 25.1637,
    }),
    buildRouteCommand(availability, {
      id: "go-render-queue",
      label: "Go to Render Queue",
      description: "Preview render queue states and controls before anything runs.",
      href: "/render-queue",
      keywords: ["render queue", "pause", "resume", "cancel", "retry", "hold", "prioritize"],
      priority: 25.1638,
    }),
    buildRouteCommand(availability, {
      id: "go-env-readiness",
      label: "Go to Env Readiness",
      description: "Open safe env-key readiness labels without showing secrets.",
      href: "/env-readiness",
      keywords: ["env readiness", "api key", "provider key", "secrets"],
      priority: 25.162,
    }),
    buildRouteCommand(availability, {
      id: "go-local-provider-probes",
      label: "Go to Local Provider Probes",
      description: "Open preview-only local provider probe plans.",
      href: "/local-provider-probes",
      keywords: ["local provider probes", "ollama", "lm studio", "comfyui", "localhost"],
      priority: 25.163,
    }),
    buildRouteCommand(availability, {
      id: "go-provider-tests",
      label: "Go to Provider Tests",
      description: "Open safe provider connection test planning.",
      href: "/provider-tests",
      keywords: ["provider tests", "connection test", "health", "readiness"],
      priority: 25.164,
    }),
    buildRouteCommand(availability, {
      id: "go-model-capabilities",
      label: "Go to Model Capabilities",
      description: "Compare approximate model strengths without live pricing claims.",
      href: "/model-capabilities",
      keywords: ["model capabilities", "matrix", "coding", "reasoning", "long context"],
      priority: 25.17,
    }),
    buildRouteCommand(availability, {
      id: "go-task-router",
      label: "Go to Task Router",
      description: "Open deterministic task-to-model recommendations with no provider execution.",
      href: "/task-router",
      keywords: ["task router", "recommend ai route", "model route", "cheap local first"],
      priority: 25.18,
    }),
    buildRouteCommand(availability, {
      id: "go-secure-credential-strategy",
      label: "Go to Credential Strategy",
      description: "Open secure credential rules for profile metadata and blocked secret storage.",
      href: "/credentials",
      keywords: ["credentials", "secure credential strategy", "no secrets", "provider"],
      priority: 25.2,
    }),
    buildRouteCommand(availability, {
      id: "go-provider-setup-wizard",
      label: "Go to Provider Setup Wizard",
      description: "Open the provider setup wizard; profile planning only and no provider calls.",
      href: "/provider-setup",
      keywords: ["provider setup", "wizard", "account setup", "manual"],
      priority: 25.3,
    }),
    buildRouteCommand(availability, {
      id: "go-token-efficiency-router",
      label: "Go to Token Efficiency Router",
      description: "Open deterministic token routing recommendations with manual handoff.",
      href: "/token-router",
      keywords: ["token", "token efficiency", "routing", "cost", "manual premium"],
      priority: 25.4,
    }),
    buildRouteCommand(availability, {
      id: "go-brain",
      label: "Go to Brain",
      description: "Navigate to Brain graph inspection without mutation.",
      href: "/brain",
      keywords: ["brain", "graph", "recall", "route"],
      priority: 30,
    }),
    buildRouteCommand(availability, {
      id: "go-files",
      label: "Go to Project Reader",
      description: "Go to Files route for File Reader v1 functional/read-only.",
      href: "/files",
      keywords: ["files", "project reader", "source", "workflow", "route"],
      priority: 40,
    }),
    buildRouteCommand(availability, {
      id: "go-real-patch-preview",
      label: "Go to Real Patch Preview",
      description: "Go to /files for selected file context and Real Patch Preview v1 functional/preview-only diffs.",
      href: "/files",
      keywords: ["real patch preview", "patch preview", "preview-only diff", "files", "route"],
      priority: 41,
    }),
    buildRouteCommand(availability, {
      id: "go-approved-patch-apply",
      label: "Go to Approved Patch Apply",
      description: "Go to /files for Approved Patch Apply v1 approval-gated/request-ready review.",
      href: "/files",
      keywords: ["approved patch apply", "apply request", "approval packet", "validation checklist", "route"],
      priority: 42,
    }),
    buildRouteCommand(availability, {
      id: "go-tasks",
      label: "Go to Tasks",
      description: "Navigate to reviewed task workflow.",
      href: "/tasks",
      keywords: ["tasks", "activation", "route"],
      priority: 50,
    }),
    buildRouteCommand(availability, {
      id: "go-closed-loop",
      label: "Go to Closed Loop Fix",
      description: "Navigate to preview-only closed-loop fix workflow guidance.",
      href: "/closed-loop",
      keywords: ["closed loop", "fix", "regression", "validation", "route"],
      priority: 55,
    }),
    buildRouteCommand(availability, {
      id: "start-code-fix",
      label: "Start code fix",
      description: "Navigate to the guided code fix path; no execution command.",
      href: "/code-flow",
      keywords: ["start code fix", "fix code", "guided", "files"],
      priority: 56,
    }),
    buildRouteCommand(availability, {
      id: "start-code-fix-wizard",
      label: "Start code fix wizard",
      description: "Open the code fix wizard; no execution command.",
      href: "/start",
      keywords: ["start code fix wizard", "fix code", "guided", "files"],
      priority: 56.1,
    }),
    buildRouteCommand(availability, {
      id: "start-validation",
      label: "Start validation",
      description: "Navigate to validation planning; no command runs from the palette.",
      href: "/validation",
      keywords: ["start validation", "run checks", "prepare checks"],
      priority: 57,
    }),
    buildRouteCommand(availability, {
      id: "start-validation-wizard",
      label: "Start validation wizard",
      description: "Open the validation wizard; no command runs from the palette.",
      href: "/start",
      keywords: ["start validation wizard", "run checks", "prepare checks"],
      priority: 57.1,
    }),
    buildRouteCommand(availability, {
      id: "go-memory",
      label: "Go to Memory",
      description: "Navigate to memory review candidates.",
      href: "/memory",
      keywords: ["memory", "review", "route"],
      priority: 60,
    }),
    buildRouteCommand(availability, {
      id: "go-memory-inbox",
      label: "Go to Memory Inbox",
      description: "Navigate to Personal Operator Memory Inbox review cards.",
      href: "/memory-inbox",
      keywords: ["memory", "inbox", "operator", "review", "promotion preview"],
      priority: 65,
    }),
    buildRouteCommand(availability, {
      id: "go-runtime-event-journal",
      label: "Go to Runtime Event Journal",
      description: "Navigate to the read-only Runtime Event Journal.",
      href: "/runtime-journal",
      keywords: ["runtime", "event", "journal", "audit", "route"],
      priority: 67,
    }),
    buildRouteCommand(availability, {
      id: "go-runtime-event-replay",
      label: "Go to Runtime Event Replay",
      description: "Navigate to the preview-only Runtime Event Replay Simulator.",
      href: "/runtime-replay",
      keywords: ["runtime", "event", "replay", "simulator", "reducer preview", "route"],
      priority: 67.5,
    }),
    buildRouteCommand(availability, {
      id: "go-brain-mutation-governance",
      label: "Go to Brain Mutation Governance",
      description: "Navigate to the read-only Brain Mutation Governance Console.",
      href: "/brain-governance",
      keywords: ["brain", "mutation", "governance", "boundary", "audit", "route"],
      priority: 68,
    }),
    buildRouteCommand(availability, {
      id: "go-brain-snapshots",
      label: "Go to Brain Snapshots",
      description: "Navigate to the read-only Brain Snapshot Manager.",
      href: "/brain-snapshots",
      keywords: ["brain", "snapshot", "comparison", "replay source", "rollback planning", "route"],
      priority: 68.5,
    }),
    buildRouteCommand(availability, {
      id: "go-snapshot-restore-gate",
      label: "Go to Snapshot Restore Gate",
      description: "Navigate to the preview-only Snapshot Restore Approval Gate.",
      href: "/snapshot-restore",
      keywords: ["snapshot", "restore", "approval gate", "request preview", "route"],
      priority: 68.7,
    }),
    buildRouteCommand(availability, {
      id: "go-brain-continuity",
      label: "Go to Brain Continuity",
      description: "Navigate to the read-only Brain Continuity Dashboard.",
      href: "/brain-continuity",
      keywords: ["brain", "continuity", "dashboard", "memory growth", "journal health", "route"],
      priority: 68.8,
    }),
    buildRouteCommand(availability, {
      id: "go-continuity-handoff",
      label: "Go to Continuity Handoff",
      description: "Navigate to the read-only Continuity Handoff Packet.",
      href: "/handoff",
      keywords: ["continuity", "handoff", "packet", "next session", "route"],
      priority: 68.9,
    }),
    buildRouteCommand(availability, {
      id: "go-creative",
      label: "Go to Creative",
      description: "Navigate to Creative Production Studio previews.",
      href: "/creative",
      keywords: ["creative", "preview", "studio", "route"],
      priority: 70,
    }),
    buildRouteCommand(availability, {
      id: "start-creative-plan",
      label: "Start creative plan",
      description: "Navigate to guided creative planning; no render or tool execution.",
      href: "/start",
      keywords: ["start creative plan", "plan creative render", "creative work"],
      priority: 70.1,
    }),
    buildRouteCommand(availability, {
      id: "start-creative-wizard",
      label: "Start creative wizard",
      description: "Open the creative wizard; no render or tool execution.",
      href: "/start",
      keywords: ["start creative wizard", "plan creative render", "creative work"],
      priority: 70.11,
    }),
    buildRouteCommand(availability, {
      id: "go-video-render-job-preview",
      label: "Go to Video Render Job Preview",
      description: "Navigate to Video Render Job Preview v1 queue, artifact, approval, and policy preview.",
      href: "/video-render",
      keywords: ["video render", "render job", "queue", "future executor", "route"],
      priority: 70.35,
    }),
    buildRouteCommand(availability, {
      id: "go-creative-executor",
      label: "Go to Creative Executor",
      description: "Navigate to Guarded Creative Executor dry-run-first/request-ready control plane.",
      href: "/creative-executor",
      keywords: ["creative executor", "guarded executor", "dry-run", "future packet", "route"],
      priority: 70.4,
    }),
    buildRouteCommand(availability, {
      id: "go-creative-execution-sandbox",
      label: "Go to Creative Execution Sandbox",
      description: "Navigate to simulation-only creative execution sandbox lifecycle, fake artifact, verification, and review handoff.",
      href: "/creative-sandbox",
      keywords: ["creative execution sandbox", "creative sandbox", "sandbox", "fake artifacts", "verification", "route"],
      priority: 70.42,
    }),
    buildRouteCommand(availability, {
      id: "go-creative-readiness",
      label: "Go to Creative Readiness",
      description: "Navigate to Real Creative Executor Readiness Audit, audit-only with execution allowed false.",
      href: "/creative-readiness",
      keywords: ["creative readiness", "real creative executor readiness", "readiness audit", "phase 70", "route"],
      priority: 70.43,
    }),
    buildRouteCommand(availability, {
      id: "go-creative-mvp-design",
      label: "Go to Creative MVP Design",
      description: "Navigate to Real Creative Executor MVP Design, design-only with execution allowed false.",
      href: "/creative-mvp",
      keywords: ["creative mvp", "real creative executor mvp", "phase 72", "route"],
      priority: 70.435,
    }),
    buildRouteCommand(availability, {
      id: "setup-local-tools",
      label: "Setup local tools",
      description: "Navigate to local tool readiness review; no probes run from the palette.",
      href: "/local-bridge-health",
      keywords: ["setup local tools", "local bridge", "check setup"],
      priority: 70.437,
    }),
    buildRouteCommand(availability, {
      id: "start-local-setup-wizard",
      label: "Start local setup wizard",
      description: "Open the local setup wizard; no probes run from the palette.",
      href: "/start",
      keywords: ["start local setup wizard", "local bridge", "check setup"],
      priority: 70.4372,
    }),
    buildRouteCommand(availability, {
      id: "start-artifact-review-wizard",
      label: "Start artifact review wizard",
      description: "Navigate to artifact review guidance; no execution command.",
      href: "/start",
      keywords: ["artifact review wizard", "review artifacts", "creative artifact"],
      priority: 70.4375,
    }),
    buildRouteCommand(availability, {
      id: "review-creative-mvp",
      label: "Review creative MVP",
      description: "Navigate to the design-only creative MVP candidate.",
      href: "/creative-mvp",
      keywords: ["review creative mvp", "mvp candidate", "design only"],
      priority: 70.438,
    }),
    buildRouteCommand(availability, {
      id: "go-local-bridge-health",
      label: "Go to Local Bridge Health",
      description: "Navigate to Local Bridge Health Check v1 preview-only/manual-only readiness.",
      href: "/local-bridge-health",
      keywords: ["local bridge health", "bridge health", "health check", "setup", "route"],
      priority: 70.45,
    }),
    buildRouteCommand(availability, {
      id: "go-health-probe",
      label: "Go to Health Probe",
      description: "Navigate to Future Guarded Health Probe metadata/manual-first review.",
      href: "/health-probe",
      keywords: ["health probe", "future guarded", "metadata-only", "manual-first", "route"],
      priority: 70.46,
    }),
    buildRouteCommand(availability, {
      id: "go-blender-adapter-preview",
      label: "Go to Blender Adapter Preview",
      description: "Navigate to Blender Adapter Preview v1 scene model and Python preview.",
      href: "/blender",
      keywords: ["blender", "adapter", "preview", "scene", "route"],
      priority: 70.5,
    }),
    buildRouteCommand(availability, {
      id: "go-unreal-adapter-preview",
      label: "Go to Unreal Adapter Preview",
      description: "Navigate to Unreal Adapter Preview v1 level model and command preview.",
      href: "/unreal",
      keywords: ["unreal", "adapter", "preview", "level", "cinematic", "route"],
      priority: 70.62,
    }),
    buildRouteCommand(availability, {
      id: "go-comfyui-adapter-preview",
      label: "Go to ComfyUI Adapter Preview",
      description: "Navigate to ComfyUI Adapter Preview v1 workflow manifest and approval packet.",
      href: "/comfyui",
      keywords: ["comfyui", "adapter", "workflow", "preview", "route"],
      priority: 70.75,
    }),
    buildRouteCommand(availability, {
      id: "go-creative-local-bridge",
      label: "Go to Creative Local Bridge",
      description: "Navigate to Creative Local Bridge v1 preview-only/request-ready control plane.",
      href: "/creative-bridge",
      keywords: ["creative", "bridge", "blender", "comfyui", "unreal", "artifact capture", "route"],
      priority: 71,
    }),
    buildRouteCommand(availability, {
      id: "go-capabilities",
      label: "Go to Capabilities",
      description: "Navigate to Capability Cockpit.",
      href: "/capabilities",
      keywords: ["capabilities", "tools", "policy", "route"],
      priority: 80,
    }),
    buildRouteCommand(availability, {
      id: "go-activity-feed",
      label: "Go to Activity Feed",
      description: "Navigate to the read-only Global Activity Feed.",
      href: "/activity",
      keywords: ["activity", "feed", "global", "route"],
      priority: 85,
    }),
    buildRouteCommand(availability, {
      id: "go-product-readiness",
      label: "Go to Product Readiness",
      description: "Navigate to the read-only Product Readiness Audit cockpit.",
      href: "/readiness",
      keywords: ["product readiness", "readiness", "audit", "route", "Phase 54"],
      priority: 87,
    }),
    buildRouteCommand(availability, {
      id: "go-system-quality-audit",
      label: "Go to System Quality Audit",
      description: "Navigate to the read-only full system quality audit.",
      href: "/quality-audit",
      keywords: ["system quality audit", "quality audit", "bugs", "routes", "smoke", "coding mvp", "route"],
      priority: 87.5,
    }),
    buildRouteCommand(availability, {
      id: "go-consolidation",
      label: "Go to Consolidation",
      description: "Navigate to the read-only Phase 55 Consolidation Pass cockpit.",
      href: "/consolidation",
      keywords: ["consolidation", "phase 55", "route", "surface map", "workflow entrypoints"],
      priority: 88,
    }),
    buildRouteCommand(availability, {
      id: "go-validation-runner",
      label: "Go to Validation Runner",
      description: "Go to /validation for approval-gated Validation Runner v1 request-ready/manual-only review.",
      href: "/validation",
      keywords: ["validation runner", "approval", "allowlist", "build", "smoke", "route"],
      priority: 89,
    }),
    buildRouteCommand(availability, {
      id: "go-stabilization",
      label: "Go to Stabilization",
      description: "Navigate to Stabilization Command Center.",
      href: "/stabilization",
      keywords: ["stabilization", "smoke", "build", "route"],
      priority: 90,
    }),
  ].filter((command): command is CodexForgeCommand => command !== null);

  const commands: CodexForgeCommand[] = [
    ...routeCommands,
    buildCodexForgeCommand({
      id: "copy-full-validation-checklist",
      label: "Copy full validation checklist",
      description: "Copy build, smoke, diff, and status checks without running them.",
      group: "Validation",
      kind: "copy-command",
      copyPayload: buildCodexForgeValidationChecklistPayload(),
      safetyLevel: "copy-only",
      requiresReview: false,
      keywords: ["validation", "checklist", "build", "smoke", "git diff check"],
      priority: 110,
    }),
    buildCodexForgeCommand({
      id: "copy-coding-ux-fix-checklist",
      label: "Copy coding UX fix checklist",
      description: "Copy coding-flow UX fixes without running or applying anything.",
      group: "Patch workflow",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeCodingUxFixChecklistPayload(),
      safetyLevel: "copy-only",
      requiresReview: false,
      keywords: ["coding ux fixes", "ux checklist", "friction", "copy"],
      priority: 111,
    }),
    buildCodexForgeCommand({
      id: "copy-simplified-validation-copy",
      label: "Copy simplified validation copy",
      description: "Copy plain-English validation guidance; no command execution.",
      group: "Validation",
      kind: "copy-command",
      copyPayload: buildCodexForgeSimplifiedValidationCopyPayload(),
      safetyLevel: "copy-only",
      requiresReview: false,
      keywords: ["validation copy", "copy these checks", "run them in terminal", "paste output"],
      priority: 112,
    }),
    buildCodexForgeCommand({
      id: "copy-route-handoff-checklist",
      label: "Copy route handoff checklist",
      description: "Copy simplified coding-flow route handoffs.",
      group: "Handoff",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeRouteHandoffChecklistPayload(),
      safetyLevel: "copy-only",
      requiresReview: false,
      keywords: ["route handoff", "code flow handoff", "workflow results", "run history"],
      priority: 113,
    }),
    buildCodexForgeCommand({
      id: "copy-build-command",
      label: "Copy build validation command",
      description: "Copy npm run build.",
      group: "Validation",
      kind: "copy-command",
      copyPayload: "npm run build",
      safetyLevel: "copy-only",
      requiresReview: false,
      keywords: ["build", "command", "validation"],
      priority: 120,
    }),
    buildCodexForgeCommand({
      id: "copy-managed-smoke-command",
      label: "Copy managed smoke command",
      description: "Copy npm run smoke:codexforge:server.",
      group: "Validation",
      kind: "copy-command",
      copyPayload: "npm run smoke:codexforge:server",
      safetyLevel: "copy-only",
      requiresReview: false,
      keywords: ["smoke", "server", "validation"],
      priority: 130,
    }),
    buildCodexForgeCommand({
      id: "copy-git-diff-check",
      label: "Copy git diff check",
      description: "Copy git diff --check.",
      group: "Validation",
      kind: "copy-command",
      copyPayload: "git diff --check",
      safetyLevel: "copy-only",
      requiresReview: false,
      keywords: ["git", "diff", "check"],
      priority: 140,
    }),
    buildCodexForgeCommand({
      id: "review-regression-triage",
      label: "Review regression triage",
      description: "Open the review flow for regression signals before fix queue work.",
      group: "Stabilize",
      kind: "review",
      href: routeAvailable(availability, "/stabilization") ? "/stabilization" : undefined,
      safetyLevel: "review-gated",
      requiresReview: true,
      keywords: ["regression", "triage", "stabilization"],
      priority: 150,
    }),
    buildCodexForgeCommand({
      id: "review-regression-fix-queue",
      label: "Review regression fix queue",
      description: "Review queued fixes before patch preview.",
      group: "Stabilize",
      kind: "review",
      href: routeAvailable(availability, "/stabilization") ? "/stabilization" : undefined,
      safetyLevel: "review-gated",
      requiresReview: true,
      keywords: ["regression", "fix queue", "review"],
      priority: 160,
    }),
    buildCodexForgeCommand({
      id: "copy-file-inspection-prompt",
      label: "Copy file inspection prompt",
      description: "Copy a Project Reader prompt for inspect-first read-only file review.",
      group: "Patch workflow",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeFileInspectionPromptPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["project reader", "file inspection", "inspect first", "read-only"],
      priority: 165,
    }),
    buildCodexForgeCommand({
      id: "copy-safe-patch-preview-prompt",
      label: "Copy safe patch preview prompt",
      description: "Copy a Project Reader to Safe Patch Preview prompt; no mutation command.",
      group: "Patch workflow",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeProjectReaderPatchPreviewPromptPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["project reader", "safe patch preview", "patch prompt", "copy"],
      priority: 166,
    }),
    buildCodexForgeCommand({
      id: "copy-patch-review-prompt",
      label: "Copy patch review prompt",
      description: "Copy a Real Patch Preview v1 review prompt; no mutation command.",
      group: "Patch workflow",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeRealPatchReviewPromptPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["real patch preview", "patch review", "preview-only", "copy"],
      priority: 167,
    }),
    buildCodexForgeCommand({
      id: "copy-apply-gate-handoff-prompt",
      label: "Copy apply-gate handoff prompt",
      description: "Copy an apply-gate handoff prompt that requires Patch Application Gate before apply.",
      group: "Patch workflow",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeApplyGateHandoffPromptPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["apply gate", "handoff", "patch application gate", "copy"],
      priority: 168,
    }),
    buildCodexForgeCommand({
      id: "copy-approved-patch-apply-review-prompt",
      label: "Copy apply review prompt",
      description: "Copy an Approved Patch Apply review prompt; no mutation command.",
      group: "Patch workflow",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeApprovedPatchApplyReviewPromptPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["approved patch apply", "apply review", "approval packet", "copy"],
      priority: 169,
    }),
    buildCodexForgeCommand({
      id: "copy-apply-guard-review",
      label: "Copy apply guard review",
      description: "Copy the Real Apply Guard Review report prompt without executing anything.",
      group: "Patch workflow",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeApplyGuardReviewPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["apply guard review", "guard report", "copy"],
      priority: 169.1,
    }),
    buildCodexForgeCommand({
      id: "copy-apply-guard-required-fixes",
      label: "Copy apply guard required fixes",
      description: "Copy required fixes for apply guard blockers without mutating files.",
      group: "Patch workflow",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeApplyGuardRequiredFixesPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["apply guard required fixes", "safety blockers", "copy"],
      priority: 169.2,
    }),
    buildCodexForgeCommand({
      id: "copy-guarded-apply-candidate-brief",
      label: "Copy guarded apply candidate brief",
      description: "Copy a guarded apply candidate brief; execution remains disabled.",
      group: "Patch workflow",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeGuardedApplyCandidateBriefPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["guarded apply candidate brief", "go no go", "copy"],
      priority: 169.3,
    }),
    buildCodexForgeCommand({
      id: "copy-guarded-apply-candidate-plan",
      label: "Copy guarded apply candidate plan",
      description: "Copy the Phase 83 one-file guarded apply candidate plan without execution.",
      group: "Patch workflow",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeGuardedApplyCandidatePlanPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["guarded apply candidate", "copy", "one file", "one diff"],
      priority: 169.31,
    }),
    buildCodexForgeCommand({
      id: "copy-guarded-apply-implementation-gaps",
      label: "Copy guarded apply implementation gaps",
      description: "Copy blocker and high-priority gaps for the guarded apply candidate path.",
      group: "Patch workflow",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeGuardedApplyImplementationGapsPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["guarded apply gaps", "approval not tied to exact diff", "apply evidence"],
      priority: 169.32,
    }),
    buildCodexForgeCommand({
      id: "copy-guarded-apply-next-prompt",
      label: "Copy guarded apply next prompt",
      description: "Copy the next safe implementation prompt for the guarded apply candidate path.",
      group: "Next action",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeGuardedApplyNextPromptPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["guarded apply next prompt", "phase 83", "copy"],
      priority: 169.33,
    }),
    buildCodexForgeCommand({
      id: "prepare-safe-patch-preview",
      label: "Prepare Safe Patch Preview",
      description: "Copy a safe preview prompt; does not call apply-diff or write files.",
      group: "Patch workflow",
      kind: "patch-preview",
      copyPayload: buildCodexForgeSafePatchPromptPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["patch", "preview", "safe", "inspect first"],
      priority: 170,
    }),
    buildCodexForgeCommand({
      id: "copy-creative-bridge-handoff",
      label: "Copy creative bridge handoff",
      description: "Copy Creative Local Bridge handoff; preview-only and no mutation.",
      group: "Creative",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeCreativeBridgeHandoffPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["creative bridge", "handoff", "artifact capture", "preview-only"],
      priority: 171,
    }),
    buildCodexForgeCommand({
      id: "copy-video-render-plan",
      label: "Copy video render plan",
      description: "Copy Video Render Job Preview v1 plan without rendering or writing files.",
      group: "Creative",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeVideoRenderPlanPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["video render", "render plan", "copy", "preview-only"],
      priority: 171.2,
    }),
    buildCodexForgeCommand({
      id: "copy-video-render-queue-preview",
      label: "Copy video render queue",
      description: "Copy Video Render Job Preview v1 queue preview without execution.",
      group: "Creative",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeVideoRenderQueuePayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["video render", "queue", "ffmpeg blocked", "copy"],
      priority: 171.3,
    }),
    buildCodexForgeCommand({
      id: "copy-video-future-executor-packet",
      label: "Copy video future executor packet",
      description: "Copy Video Render future executor packet; no execution command.",
      group: "Creative",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeVideoRenderFutureExecutorPacketPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["video render", "future executor", "packet", "copy"],
      priority: 171.4,
    }),
    buildCodexForgeCommand({
      id: "copy-creative-executor-dry-run",
      label: "Copy creative executor dry-run",
      description: "Copy Guarded Creative Executor dry-run plan; no execution command.",
      group: "Creative",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeCreativeExecutorDryRunPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["creative executor", "dry-run", "copy", "no execution"],
      priority: 171.5,
    }),
    buildCodexForgeCommand({
      id: "copy-creative-executor-future-packet",
      label: "Copy creative executor future packet",
      description: "Copy Guarded Creative Executor future packet; execution disabled.",
      group: "Creative",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeCreativeExecutorFuturePacketPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["creative executor", "future packet", "guarded", "copy"],
      priority: 171.6,
    }),
    buildCodexForgeCommand({
      id: "copy-creative-sandbox-report",
      label: "Copy sandbox report",
      description: "Copy Creative Execution Sandbox report; simulation-only and no execution command.",
      group: "Creative",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeCreativeSandboxReportPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["creative execution sandbox", "sandbox report", "simulation-only", "copy"],
      priority: 171.62,
    }),
    buildCodexForgeCommand({
      id: "copy-creative-sandbox-review-handoff",
      label: "Copy sandbox-to-review handoff",
      description: "Copy Creative Execution Sandbox to Creative Artifact Review handoff; placeholders only.",
      group: "Creative",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeCreativeSandboxReviewHandoffPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["creative execution sandbox", "sandbox handoff", "artifact review", "copy"],
      priority: 171.64,
    }),
    buildCodexForgeCommand({
      id: "copy-creative-readiness-report",
      label: "Copy creative readiness report",
      description: "Copy Real Creative Executor Readiness Audit report; audit-only and no execution command.",
      group: "Creative",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeCreativeReadinessReportPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["creative readiness", "real creative executor readiness", "audit-only", "copy"],
      priority: 171.66,
    }),
    buildCodexForgeCommand({
      id: "copy-health-probe-readiness-packet",
      label: "Copy health probe readiness packet",
      description: "Copy Phase 71 Future Guarded Health Probe readiness packet; no probe or execution command.",
      group: "Creative",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeCreativeReadinessHealthProbePacketPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["creative readiness", "health probe", "phase 71", "future guarded", "copy"],
      priority: 171.68,
    }),
    buildCodexForgeCommand({
      id: "copy-creative-mvp-design-packet",
      label: "Copy creative MVP design packet",
      description: "Copy Real Creative Executor MVP Design packet; design-only and no execution command.",
      group: "Creative",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeCreativeMvpDesignPacketPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["creative mvp", "mvp design", "artifact capture", "copy"],
      priority: 171.69,
    }),
    buildCodexForgeCommand({
      id: "copy-user-friendly-creative-mvp-flow",
      label: "Copy user-friendly creative MVP flow",
      description: "Copy plain English Creative MVP flow; no execution command.",
      group: "Creative",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeCreativeMvpUserFlowPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["creative mvp", "user flow", "plain English", "copy"],
      priority: 171.695,
    }),
    buildCodexForgeCommand({
      id: "copy-local-bridge-setup-guide",
      label: "Copy local bridge setup guide",
      description: "Copy Local Bridge Health setup guide; no execution command.",
      group: "Creative",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeLocalBridgeSetupGuidePayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["local bridge health", "setup guide", "manual-only", "copy"],
      priority: 171.7,
    }),
    buildCodexForgeCommand({
      id: "copy-future-health-probe-packet",
      label: "Copy future health probe packet",
      description: "Copy Future Guarded Health Probe packet; no probe or execution command.",
      group: "Creative",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeFutureHealthProbePacketPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["local bridge health", "future health probe", "probe packet", "copy"],
      priority: 171.8,
    }),
    buildCodexForgeCommand({
      id: "copy-blender-adapter-preview-prompt",
      label: "Copy Blender adapter preview prompt",
      description: "Copy Blender Adapter Preview v1 prompt without launching Blender.",
      group: "Creative",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeBlenderAdapterPreviewPromptPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["blender", "adapter", "creative bridge", "preview"],
      priority: 172,
    }),
    buildCodexForgeCommand({
      id: "copy-blender-future-executor-packet",
      label: "Copy Blender future executor packet",
      description: "Copy Blender future executor packet guidance without execution.",
      group: "Creative",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeBlenderFutureExecutorPacketPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["blender", "future executor", "packet", "copy"],
      priority: 173,
    }),
    buildCodexForgeCommand({
      id: "copy-unreal-command-preview-prompt",
      label: "Copy Unreal command preview prompt",
      description: "Copy Unreal Adapter Preview v1 command preview guidance without launching Unreal.",
      group: "Creative",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeUnrealCommandPreviewPromptPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["unreal", "command preview", "cinematic", "level", "copy"],
      priority: 174,
    }),
    buildCodexForgeCommand({
      id: "copy-unreal-future-executor-packet",
      label: "Copy Unreal future executor packet",
      description: "Copy Unreal future executor packet guidance without execution.",
      group: "Creative",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeUnrealFutureExecutorPacketPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["unreal", "future executor", "packet", "copy"],
      priority: 175,
    }),
    buildCodexForgeCommand({
      id: "copy-code-flow-patch-request",
      label: "Copy code-flow patch request",
      description: "Copy a reviewed patch request handoff without applying anything.",
      group: "Patch workflow",
      kind: "copy-prompt",
      copyPayload: "Code Flow patch request: selected file, inspected context, requested change, constraints, acceptance criteria, preview-first, approval required, no auto-apply, no auto-run, preserve latest-message authority.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["code flow", "patch request", "copy", "preview"],
      priority: 179,
    }),
    buildCodexForgeCommand({
      id: "copy-code-flow-validation-checklist",
      label: "Copy code-flow validation checklist",
      description: "Copy validation commands without running them.",
      group: "Validation",
      kind: "copy-command",
      copyPayload: "npm run build\nnpm run smoke:codexforge:server\ngit diff --check\ngit status --short",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["code flow", "validation checklist", "copy", "no auto-run"],
      priority: 179.1,
    }),
    buildCodexForgeCommand({
      id: "copy-hardened-validation-checklist",
      label: "Copy hardened validation checklist",
      description: "Copy apply-validation hardening checks without running commands.",
      group: "Validation",
      kind: "copy-command",
      copyPayload: buildCodexForgeHardenedValidationChecklistPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["apply validation", "hardened validation checklist", "copy", "no auto-run"],
      priority: 179.2,
    }),
    buildCodexForgeCommand({
      id: "copy-coding-trial-checklist",
      label: "Copy coding trial checklist",
      description: "Copy the Coding Flow Live Trial checklist without running commands.",
      group: "Validation",
      kind: "copy-command",
      copyPayload: "Coding Flow Live Trial checklist: Before you start, Pick a safe file, Describe the change, Preview the patch, Review apply, Prepare validation, Capture result, Review run history, Troubleshoot if needed. No auto-apply, no auto-run, approval required, preserve latest-message authority.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["coding trial", "checklist", "copy", "no auto-apply"],
      priority: 179.21,
    }),
    buildCodexForgeCommand({
      id: "copy-coding-trial-validation-commands",
      label: "Copy coding trial validation commands",
      description: "Copy the Coding Flow Live Trial validation commands without executing them.",
      group: "Validation",
      kind: "copy-command",
      copyPayload: "Coding Flow Live Trial validation commands:\nnpm run build\npowershell -ExecutionPolicy Bypass -File .\\scripts\\smoke-codexforge-<touched-feature>.ps1\nnpm run smoke:codexforge:server\ngit diff --check\ngit status --short\ngit diff --stat\nCopy only. Run manually outside the UI.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["coding trial", "validation commands", "copy", "no auto-run"],
      priority: 179.22,
    }),
    buildCodexForgeCommand({
      id: "copy-hardened-rollback-plan",
      label: "Copy rollback plan",
      description: "Copy rollback guidance without restoring files.",
      group: "Patch workflow",
      kind: "copy-command",
      copyPayload: buildCodexForgeHardenedRollbackPlanPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["apply validation", "rollback", "git restore", "git revert", "copy"],
      priority: 179.3,
    }),
    buildCodexForgeCommand({
      id: "copy-completion-guidance",
      label: "Copy completion guidance",
      description: "Copy commit, tag, and push guidance without executing git commands.",
      group: "Next action",
      kind: "copy-command",
      copyPayload: buildCodexForgeCompletionGuidancePayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["apply validation", "completion", "commit", "tag", "push", "copy"],
      priority: 179.4,
    }),
    buildCodexForgeCommand({
      id: "copy-workflow-handoff",
      label: "Copy workflow handoff",
      description: "Copy a reviewed workflow result handoff template without persistence.",
      group: "Handoff",
      kind: "handoff",
      copyPayload: buildCodexForgeWorkflowHandoffPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["workflow handoff", "workflow results", "copy", "result persistence"],
      priority: 179.5,
    }),
    buildCodexForgeCommand({
      id: "copy-run-handoff",
      label: "Copy run handoff",
      description: "Copy a reviewed run history handoff template without persistence.",
      group: "Handoff",
      kind: "handoff",
      copyPayload: "Run history handoff: run summary, workflow status, file/change summary, validation result, failure route, next action, commit guidance, memory candidate, and review notes. Copy-only, no file writes, no Brain auto-mutation, no auto-promotion, preserve latest-message authority.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["run history", "run handoff", "copy", "handoff"],
      priority: 179.55,
    }),
    buildCodexForgeCommand({
      id: "copy-run-memory-candidate",
      label: "Copy run memory candidate",
      description: "Copy a reviewed run history memory candidate; no auto-promotion.",
      group: "Memory",
      kind: "memory-review",
      copyPayload: "Run history memory candidate: title, summary, reusable lesson, project context, excluded sensitive details, promotion readiness, suggested category. Review required, no secrets, no huge logs, no-auto-promotion, no Brain mutation.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["run history", "memory candidate", "copy", "no auto-promotion"],
      priority: 179.56,
    }),
    buildCodexForgeCommand({
      id: "copy-coding-trial-review",
      label: "Copy coding trial review",
      description: "Copy the Coding Flow Trial Review report without writing files.",
      group: "Handoff",
      kind: "copy-command",
      copyPayload: "Coding trial review: trial summary, screens visited, validation reviewed, friction, safety, pass/fail checklist, UX fixes, and go/no-go. Copy-only, no auto-apply, no auto-run, approval required, preserve latest-message authority.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["coding trial review", "trial report", "copy", "go no go"],
      priority: 179.565,
    }),
    buildCodexForgeCommand({
      id: "copy-coding-trial-ux-fix-plan",
      label: "Copy coding trial UX fix plan",
      description: "Copy the top Coding Trial UX fixes without mutation.",
      group: "Next action",
      kind: "copy-prompt",
      copyPayload: "Coding trial UX fix plan: prioritize unclear primary action, validation clarity, result capture handoff, compact safety copy, and route handoff polish. Prefer small user-facing fixes; no execution, no file writes from UI.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["coding trial", "ux fix plan", "primary action", "copy"],
      priority: 179.566,
    }),
    buildCodexForgeCommand({
      id: "copy-coding-trial-go-no-go-report",
      label: "Copy coding trial go/no-go report",
      description: "Copy the Coding Trial go/no-go report without applying or running anything.",
      group: "Next action",
      kind: "copy-prompt",
      copyPayload: "Coding trial go/no-go report: go, go-with-fixes, no-go, blocked, or unknown. No-go for safety blockers or unclear /code-flow primary action. Go-with-fixes for minor copy/layout issues. Go only when checklist mostly passes.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["coding trial", "go no go", "go-with-fixes", "copy"],
      priority: 179.567,
    }),
    buildCodexForgeCommand({
      id: "copy-validation-result-summary",
      label: "Copy validation result summary",
      description: "Copy a capped validation result summary template without running commands.",
      group: "Validation",
      kind: "validation",
      copyPayload: buildCodexForgeValidationResultSummaryPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["validation result", "workflow results", "copy", "summary"],
      priority: 179.6,
    }),
    buildCodexForgeCommand({
      id: "copy-memory-review-candidate",
      label: "Copy memory review candidate",
      description: "Copy a reviewed memory candidate template; no auto-promotion.",
      group: "Memory",
      kind: "memory-review",
      copyPayload: buildCodexForgeMemoryReviewCandidatePayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["memory review candidate", "workflow results", "copy", "no auto-promotion"],
      priority: 179.7,
    }),
    buildCodexForgeCommand({
      id: "compose-preview-diff",
      label: "Compose Preview Diff",
      description: "Open preview diff planning without applying changes.",
      group: "Patch workflow",
      kind: "patch-preview",
      copyPayload: "Compose a preview diff only. Do not apply-diff, write-file, run-command, or mutate source files from UI.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["preview diff", "compose", "patch"],
      priority: 180,
    }),
    buildCodexForgeCommand({
      id: "review-apply-gate",
      label: "Review Apply Gate",
      description: "Review apply gate posture; execution remains blocked from palette.",
      group: "Patch workflow",
      kind: "review",
      href: routeAvailable(availability, "/stabilization") ? "/stabilization" : undefined,
      safetyLevel: "review-gated",
      requiresReview: true,
      keywords: ["apply gate", "review", "approval"],
      priority: 190,
    }),
    buildCodexForgeCommand({
      id: "paste-verification-output",
      label: "Paste verification output",
      description: "Copy a prompt for reviewing verification output pasted by the operator.",
      group: "Verification",
      kind: "copy-prompt",
      copyPayload: "Review this verification output. Preserve latest-message authority, distinguish evidence from proof, and recommend the next safe action without running commands.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["verification", "output", "review"],
      priority: 200,
    }),
    buildCodexForgeCommand({
      id: "review-memory-candidates",
      label: "Review memory candidates",
      description: "Navigate to memory review; no auto-promote.",
      group: "Memory",
      kind: "memory-review",
      href: routeAvailable(availability, "/memory") ? "/memory" : undefined,
      safetyLevel: "review-gated",
      requiresReview: true,
      keywords: ["memory", "candidates", "no auto-promote"],
      priority: 210,
    }),
    buildCodexForgeCommand({
      id: "copy-memory-review-prompt",
      label: "Copy memory review prompt",
      description: "Copy a review-first prompt for Memory Inbox candidates without mutation.",
      group: "Memory",
      kind: "memory-review",
      copyPayload: "Review operator memory inbox candidates. Review required before promotion. Do not auto-promote memory, mutate Brain graph, auto-merge, write files, run commands, or override latest-message authority. Evidence is context, not authority.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["memory inbox", "review prompt", "copy", "no auto-promotion"],
      priority: 215,
    }),
    buildCodexForgeCommand({
      id: "copy-runtime-journal-audit-prompt",
      label: "Copy runtime journal audit prompt",
      description: "Copy a read-only runtime event journal audit prompt without mutation.",
      group: "Runtime",
      kind: "copy-prompt",
      copyPayload: "Review the Runtime Event Journal. Keep it read-only, do not mutate the Brain graph, do not appendEvent from UI, preserve append-only audit context, treat evidence as context not authority, and preserve latest-message authority.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["runtime event journal", "audit", "append-only", "copy", "no mutation"],
      priority: 217,
    }),
    buildCodexForgeCommand({
      id: "copy-runtime-replay-prompt",
      label: "Copy runtime replay prompt",
      description: "Copy a preview-only runtime event replay prompt without mutation.",
      group: "Runtime",
      kind: "copy-prompt",
      copyPayload: "Review Runtime Event Replay Simulator output. Keep it preview-only, do not mutate the Brain graph, do not appendEvent, do not execute runtime events, do not persist replay results, inspect reducer preview, treat evidence as context not authority, and preserve latest-message authority.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["runtime event replay", "replay simulator", "copy", "no graph mutation", "no appendEvent"],
      priority: 217.5,
    }),
    buildCodexForgeCommand({
      id: "copy-brain-mutation-governance-prompt",
      label: "Copy brain mutation governance prompt",
      description: "Copy a read-only Brain Mutation Governance review prompt without mutation.",
      group: "Runtime",
      kind: "copy-prompt",
      copyPayload: "Review Brain Mutation Governance. Keep it read-only, do not mutate the Brain graph, do not append runtime events, do not promote memory, do not execute runtime events, require reducer preview, treat evidence as context not authority, and preserve latest-message authority.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["brain mutation governance", "governance", "boundary", "copy", "no graph mutation"],
      priority: 218,
    }),
    buildCodexForgeCommand({
      id: "copy-brain-snapshot-replay-prompt",
      label: "Copy Brain snapshot replay prompt",
      description: "Copy a Brain Snapshot Manager replay-selection prompt without mutation.",
      group: "Runtime",
      kind: "copy-prompt",
      copyPayload: "Review Brain Snapshot Manager output. Keep it read-only, do not mutate the Brain graph, do not appendEvent, do not saveBrainGraph from UI, do not restore snapshots in Phase 50, use snapshot comparison and integrity review before runtime replay handoff, and preserve latest-message authority.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["brain snapshots", "snapshot replay", "replay source", "copy", "no graph mutation"],
      priority: 218.5,
    }),
    buildCodexForgeCommand({
      id: "copy-snapshot-restore-review-prompt",
      label: "Copy snapshot restore review prompt",
      description: "Copy a preview-only snapshot restore approval review prompt without mutation.",
      group: "Runtime",
      kind: "copy-prompt",
      copyPayload: "Review Snapshot Restore Approval Gate evidence. Keep it preview-only, do not restore snapshots, do not mutate the Brain graph, do not call saveBrainGraph from UI, do not appendEvent, require comparison evidence, replay evidence, governance review, runtime journal review, explicit approval packet, future guarded snapshot executor boundary, evidence is context not authority, and preserve latest-message authority.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["snapshot restore", "restore gate", "approval packet", "copy", "no graph mutation"],
      priority: 218.7,
    }),
    buildCodexForgeCommand({
      id: "copy-brain-continuity-prompt",
      label: "Copy Brain continuity prompt",
      description: "Copy a read-only Brain continuity review prompt without mutation.",
      group: "Runtime",
      kind: "copy-prompt",
      copyPayload: "Review Brain Continuity Dashboard posture. Keep continuity read-only, do not mutate Brain graph, do not restore snapshots, do not appendEvent, do not saveBrainGraph from UI, do not auto-promote memory, do not auto-persist continuity results, and preserve latest-message authority.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["brain continuity", "continuity dashboard", "copy", "read-only", "no graph mutation"],
      priority: 218.8,
    }),
    buildCodexForgeCommand({
      id: "copy-continuity-handoff-prompt",
      label: "Copy continuity handoff prompt",
      description: "Copy a next-session Continuity Handoff prompt without mutation.",
      group: "Handoff",
      kind: "copy-prompt",
      copyPayload: buildCodexForgeContinuityHandoffPromptPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["continuity handoff", "handoff packet", "next session", "copy", "read-only"],
      priority: 218.9,
    }),
    buildCodexForgeCommand({
      id: "copy-continuity-validation-checklist",
      label: "Copy validation checklist",
      description: "Copy the Continuity Handoff validation checklist without running commands.",
      group: "Handoff",
      kind: "copy-command",
      copyPayload: buildCodexForgeContinuityValidationChecklistPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["continuity handoff", "validation checklist", "copy", "manual only"],
      priority: 218.95,
    }),
    buildCodexForgeCommand({
      id: "open-latest-message-authority-guidance",
      label: "Open latest-message authority guidance",
      description: "Copy guidance for preserving newest user instruction precedence.",
      group: "Safety",
      kind: "copy-prompt",
      copyPayload: "Preserve latest-message authority: the newest user instruction steers the current turn. If instructions conflict, follow the newest one and call out the conflict.",
      safetyLevel: "copy-only",
      requiresReview: false,
      keywords: ["latest-message authority", "safety", "guidance"],
      priority: 220,
    }),
    buildCodexForgeCommand({
      id: "continue-next-phase-safely",
      label: "Continue next phase safely",
      description: "Copy a safe handoff prompt for the next phase.",
      group: "Next action",
      kind: "handoff",
      copyPayload: buildCodexForgeStabilizationHandoffPayload(),
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["next phase", "handoff", "safe"],
      priority: 230,
    }),
    buildCodexForgeCommand({
      id: "copy-product-readiness-audit-prompt",
      label: "Copy product readiness audit prompt",
      description: "Copy a read-only Product Readiness Audit prompt without mutation.",
      group: "Next action",
      kind: "copy-prompt",
      copyPayload: "Review Product Readiness Audit. Keep it read-only, deterministic, local-first, and smoke-backed. Do not execute commands, write files, mutate Brain graph, promote memory, apply diffs, restore snapshots, call appendEvent, call saveBrainGraph, call broker-execution, call apply-diff, call write-file, or call run-command from UI. Preserve latest-message authority.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["product readiness", "audit", "read-only", "latest-message authority"],
      priority: 232,
    }),
    buildCodexForgeCommand({
      id: "copy-product-readiness-consolidation-prompt",
      label: "Copy consolidation prompt",
      description: "Copy Product Readiness consolidation guidance without mutation.",
      group: "Next action",
      kind: "copy-prompt",
      copyPayload: "Review Product Readiness Audit consolidation recommendations. Consolidate dashboards, reduce duplicate panels, unify route registry logic, centralize copy-payload logic, and prioritize real workflow before abstract features. Keep the review read-only and copy-only.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["product readiness", "consolidation", "dashboard sprawl", "duplicate panels"],
      priority: 233,
    }),
    buildCodexForgeCommand({
      id: "copy-consolidation-plan",
      label: "Copy consolidation plan",
      description: "Copy Phase 55 consolidation plan without mutation.",
      group: "Next action",
      kind: "copy-prompt",
      copyPayload: "Review Consolidation Pass. Promote primary routes, demote deep governance routes to Advanced / Audit links, add Start here workflow cards, keep /readiness and /handoff as checkpoints, use /stabilization as operations hub, prepare /files for real read-only workflow next, keep deep surfaces accessible via command palette, reduce duplicated next-action copy over time, and keep all smoke coverage intact.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["consolidation", "plan", "phase 55", "copy"],
      priority: 234,
    }),
    buildCodexForgeCommand({
      id: "copy-phase-56-file-reader-prompt",
      label: "Copy Phase 56 file reader prompt",
      description: "Copy a read-only Phase 56 Real Local Project Reader prompt.",
      group: "Next action",
      kind: "copy-prompt",
      copyPayload: "Proceed to Phase 56 Real Local Project Reader. Build read-only local project discovery, stable project tree, file preview, selected file context handoff, and safety copy. Do not execute commands from UI, do not write files without approval, do not mutate Brain graph, do not call appendEvent from UI, do not call saveBrainGraph from UI, preserve latest-message authority, and keep validation manual.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["phase 56", "file reader", "files", "read-only", "copy"],
      priority: 234.5,
    }),
    buildCodexForgeCommand({
      id: "copy-activity-handoff-prompt",
      label: "Copy activity handoff prompt",
      description: "Copy a read-only activity feed handoff prompt without persisting events.",
      group: "Next action",
      kind: "copy-prompt",
      copyPayload: "Review the Global Activity Feed. Keep it read-only, do not execute commands, do not write files, do not mutate the Brain graph, treat evidence as context not proof, and preserve latest-message authority.",
      safetyLevel: "copy-only",
      requiresReview: false,
      keywords: ["activity", "handoff", "read-only", "latest-message authority"],
      priority: 235,
    }),
    buildCodexForgeCommand({
      id: "commit-clean-checkpoint",
      label: "Recommend commit clean checkpoint",
      description: "Copy a checkpoint recommendation; the palette never commits.",
      group: "Next action",
      kind: "safe-action",
      copyPayload: "Working tree appears clean after validation. Recommend a commit clean checkpoint, but do not commit without explicit approval.",
      safetyLevel: "copy-only",
      requiresReview: true,
      keywords: ["commit clean checkpoint", "clean", "next action"],
      priority: 240,
    }),
  ];

  if (options.includeEducationalBlockedCommands) {
    for (const blocked of ["apply-diff", "write-file", "run-command", "broker-execution"]) {
      commands.push(
        buildCodexForgeCommand({
          id: `blocked-${blocked}`,
          label: `Blocked: ${blocked}`,
          description: `${blocked} is visible only as blocked-policy text and cannot execute from the palette.`,
          group: "Safety",
          kind: "safe-action",
          safetyLevel: "blocked",
          requiresReview: true,
          disabledReason: `${blocked} is mutation-capable or execution-capable and blocked in the palette.`,
          keywords: [blocked, "blocked", "safety"],
          noMutation: false,
          priority: 900,
        })
      );
    }
  }

  return commands
    .map((command) =>
      isCodexForgeCommandMutationBlocked(command)
        ? {
            ...command,
            safetyLevel: "blocked" as const,
            disabledReason: command.disabledReason ?? "Mutation blocked by command safety policy.",
          }
        : command
    )
    .sort((a, b) => a.priority - b.priority || a.id.localeCompare(b.id));
}

export function summarizeCodexForgeCommands(commands = buildCodexForgeCommands()): string {
  const disabled = commands.filter((command) => command.disabledReason).length;
  return `${commands.length} deterministic commands, ${commands.length - disabled} enabled, ${disabled} disabled, no mutation commands executable.`;
}
