import type { ModelCapabilityDimension, ModelCapabilityEntry } from "./model-capability-types";
const dims: ModelCapabilityDimension[] = ["coding", "reasoning", "summarization", "extraction", "long-context", "privacy-local", "speed", "cost-efficiency", "tool-use", "vision", "reliability", "manual-browser-only", "api-automation-capable"];
function scores(overrides: Partial<Record<ModelCapabilityDimension, number>>): Record<ModelCapabilityDimension, number> { return Object.fromEntries(dims.map((dim) => [dim, overrides[dim] ?? 2])) as Record<ModelCapabilityDimension, number>; }
export function buildModelCapabilityEntry(input: Omit<ModelCapabilityEntry, "scores"> & { scores?: Partial<Record<ModelCapabilityDimension, number>> }): ModelCapabilityEntry { return { ...input, scores: scores(input.scores ?? {}) }; }
export function buildDefaultModelCapabilityEntries(): ModelCapabilityEntry[] { return [
 buildModelCapabilityEntry({ id:"local-small", family:"local small", provider:"Ollama or LM Studio", description:"Private, quick drafts for low-risk text.", labels:["cheap/local first","private"], manualOnly:false, apiCapable:true, scores:{"privacy-local":5, speed:4, "cost-efficiency":5, summarization:3} }),
 buildModelCapabilityEntry({ id:"local-coding", family:"local coding", provider:"Ollama or LM Studio", description:"Private code prepass when a local coding model is loaded.", labels:["local/private alternative"], manualOnly:false, apiCapable:true, scores:{coding:4, "privacy-local":5, "cost-efficiency":4} }),
 buildModelCapabilityEntry({ id:"openai-fast", family:"OpenAI-compatible fast", provider:"OpenAI-compatible API", description:"Fast general automation when an API key exists.", labels:["fast","api automation capable"], manualOnly:false, apiCapable:true, scores:{speed:5, summarization:4, extraction:4, "tool-use":4, "api-automation-capable":5} }),
 buildModelCapabilityEntry({ id:"openai-reasoning", family:"OpenAI-compatible reasoning", provider:"OpenAI-compatible API", description:"Premium reasoning route for hard bugs and planning.", labels:["premium escalation route"], manualOnly:false, apiCapable:true, scores:{reasoning:5, coding:4, reliability:4, "api-automation-capable":5} }),
 buildModelCapabilityEntry({ id:"claude-reasoning", family:"Claude-compatible reasoning", provider:"Claude-compatible API", description:"Strong review and explanation path.", labels:["review","reasoning"], manualOnly:false, apiCapable:true, scores:{reasoning:5, coding:4, summarization:4, reliability:4} }),
 buildModelCapabilityEntry({ id:"gemini-long", family:"Gemini long-context", provider:"Gemini API", description:"Long context and multimodal planning without exact pricing claims.", labels:["long context","vision"], manualOnly:false, apiCapable:true, scores:{"long-context":5, vision:4, summarization:4} }),
 buildModelCapabilityEntry({ id:"deepseek-value", family:"DeepSeek coding/value", provider:"DeepSeek API", description:"Coding and value-oriented drafts when configured.", labels:["coding/value"], manualOnly:false, apiCapable:true, scores:{coding:4, "cost-efficiency":4, reasoning:3} }),
 buildModelCapabilityEntry({ id:"openrouter", family:"OpenRouter aggregator", provider:"OpenRouter API", description:"Aggregator path when you want one configured endpoint for several families.", labels:["aggregator"], manualOnly:false, apiCapable:true, scores:{"api-automation-capable":4, "cost-efficiency":3, reliability:3} }),
 buildModelCapabilityEntry({ id:"manual-chatgpt", family:"manual ChatGPT subscription", provider:"ChatGPT website", description:"Manual browser-only premium help. Copy prompts yourself.", labels:["manual/browser only"], manualOnly:true, apiCapable:false, scores:{reasoning:4, coding:4, "manual-browser-only":5} }),
 buildModelCapabilityEntry({ id:"manual-claude", family:"manual Claude subscription", provider:"Claude website", description:"Manual browser-only review and writing help. No password storage.", labels:["manual/browser only"], manualOnly:true, apiCapable:false, scores:{reasoning:5, summarization:4, "manual-browser-only":5} }),
]; }
