"use client";

import { CodexForgeAppShell } from "@/lib/codexforge/navigation-shell";
import { MULTI_PROVIDER_CAPABILITY_ROUTING_BLOCKED_ACTION_ITEMS, MULTI_PROVIDER_CAPABILITY_ROUTING_PIPELINE_ITEMS, MULTI_PROVIDER_CAPABILITY_ROUTING_PROTECTED_BOUNDARY_ITEMS, MULTI_PROVIDER_CAPABILITY_ROUTING_SHARED_MARKERS, buildMultiProviderCapabilityRoutingModel, buildMultiProviderCapabilityRoutingStableKey, type MultiProviderCapabilityRoutingRouteSlug } from "../multi-provider-capability-routing-model";
import styles from "../../jarvis-cockpit-visual-system/components/JarvisCockpitVisualPanel.module.css";

export function MultiProviderCapabilityRoutingPageClientShell({ routeSlug }: { routeSlug: MultiProviderCapabilityRoutingRouteSlug }) {
  const model = buildMultiProviderCapabilityRoutingModel(routeSlug);
  return (
    <CodexForgeAppShell activePath={model.route.href} workspaceLabel={model.route.title} nextActionContext={{ wantsOperatorOverview: false }} focusMode contentMaxWidth="wide" pageChrome="minimal" showRightRail={false} showSidebarSafetyNotice={false} showHeroRouteChips={false}>
      <MultiProviderCapabilityRoutingRoutePanel routeSlug={routeSlug} />
    </CodexForgeAppShell>
  );
}

export function MultiProviderCapabilityRoutingCockpitSection() {
  return <MultiProviderCapabilityRoutingRoutePanel routeSlug="multi-provider-capability-routing-completion" embedded />;
}

export function MultiProviderCapabilityRoutingRoutePanel({ routeSlug, embedded = false }: { routeSlug: MultiProviderCapabilityRoutingRouteSlug; embedded?: boolean }) {
  const model = buildMultiProviderCapabilityRoutingModel(routeSlug);
  return (
    <section className={embedded ? styles.cockpitShell : styles.routeShell} data-codexforge-multi-provider-capability-routing={MULTI_PROVIDER_CAPABILITY_ROUTING_SHARED_MARKERS.join(" | ")} data-codexforge-multi-provider-capability-routing-route={model.route.markerPhrases.join(" | ")} data-codexforge-multi-provider-capability-routing-pipeline={MULTI_PROVIDER_CAPABILITY_ROUTING_PIPELINE_ITEMS.map((item) => item.label).join(" | ")}>
      <header className={styles.heroPanel}>
        <div className={styles.heroGlow} aria-hidden="true" />
        <div className={styles.heroContent}>
          <div className={styles.eyebrowRow}><span className={styles.phaseBadge}>{embedded ? "Multi-Provider Capability Routing" : model.route.phase}</span><span className={styles.safeBadge}>review-only multi-provider capability routing</span><span className={styles.blockedBadge}>operator-approved only</span></div>
          <h1 className={styles.heroTitle}>{embedded ? "Multi-Provider Capability Routing" : model.route.title}</h1>
          <p className={styles.heroLead}>This route is a review-only multi-provider capability routing surface with synthetic multi-provider routing data only. Multi-provider routing remains disabled until explicit operator approval. It defines provider capability request, provider capability response, disabled text image audio video transcription editing metadata and safety provider routing, synthetic provider scorecards, cost rate privacy region data retention approval audit redaction observability retry fallback timeout routing, disabled provider route candidate, runner and execution bridge handoffs, operator review, readiness gate, and completion checks without live provider calls, model calls, prompt sending, streaming, provider SDK imports, network egress, frontend persistence, credential storage, token storage, provider key storage, worker dispatch, render execution, exports, publishing, or runtime deploy.</p>
          <div className={styles.heroMetricGrid}><MetricCard label="Route slug" value={model.route.slug} detail={model.route.href} /><MetricCard label="Data" value="Synthetic" detail="synthetic multi-provider routing data only" /><MetricCard label="Approval" value="Required" detail="multi-provider routing remains disabled until explicit operator approval" /><MetricCard label="Execution" value="Blocked" detail="multi-provider capability routing completion does not call providers" /></div>
        </div>
        <div className={styles.missionPreview} aria-label="Multi-Provider Capability Routing preview"><p className={styles.missionLabel}>Routing contract</p><p className={styles.missionDetail}>Review-only. Disabled by default. No live provider calls. No model calls. No prompt sending. No streaming. No provider SDK imports. No network egress. No frontend persistence. No credential storage. No token storage. No provider key storage.</p></div>
      </header>
      <section className={styles.markerBand} aria-label="Multi-Provider Capability Routing shared markers">{model.safetyMarkers.map((marker, index) => <span key={buildMultiProviderCapabilityRoutingStableKey(["shared-marker", String(index), marker])} className={styles.markerPill}>{marker}</span>)}</section>
      <section className={styles.glassPanel} aria-label="Review-only multi-provider capability routing pipeline"><PanelHeading eyebrow="Review-only multi-provider capability routing" title="Future backend-owned multi-provider routing remains disabled until explicit operator approval" badge="Static only" /><p className={styles.bodyText}>This multi-provider capability routing surface is synthetic multi-provider routing data only. It does not call providers, call models, send prompts, stream tokens, import provider SDKs, upload or download files, execute render queues, dispatch workers, export artifacts, publish content, store credentials, store tokens, store provider keys, write browser storage, call connectors, create APIs, bind ports, deploy runtimes, or use network egress.</p><div className={styles.systemsGrid}>{MULTI_PROVIDER_CAPABILITY_ROUTING_PIPELINE_ITEMS.map((item) => <article key={buildMultiProviderCapabilityRoutingStableKey(["pipeline", item.id])} className={styles.systemCard}><span className={styles.systemTier}>Multi-provider routing path</span><strong>{item.label}</strong><p className={styles.systemStatus}>{item.state}</p></article>)}</div></section>
      <section className={styles.glassPanel} aria-label="Multi-Provider Capability Routing route map"><PanelHeading eyebrow="Multi-Provider Capability Routing" title={model.route.title} badge={model.route.phase} /><p className={styles.bodyText}>{model.route.summary}</p><div className={styles.contractGrid}>{model.route.markerPhrases.map((marker, index) => <span key={buildMultiProviderCapabilityRoutingStableKey(["route-marker", model.route.slug, String(index), marker])} className={styles.contractChip}>{marker}</span>)}</div></section>
      <section className={styles.glassPanel} aria-label="Multi-provider routing blocked execution matrix"><PanelHeading eyebrow="Blocked Execution Matrix" title="Provider model prompt network storage media worker export publish runtime and credential execution stay blocked" badge="Actions disabled" /><div className={styles.blockedDeckGrid}>{MULTI_PROVIDER_CAPABILITY_ROUTING_BLOCKED_ACTION_ITEMS.map((item) => <button key={buildMultiProviderCapabilityRoutingStableKey(["blocked", item.id])} type="button" disabled className={styles.blockedCommandButton}><strong>{item.label}</strong><span>{item.state}</span><small>review-only multi-provider capability routing</small></button>)}</div></section>
      <section className={styles.cockpitGrid} aria-label="Multi-provider routing protected boundaries"><CatalogPanel eyebrow="Protected Multi-Provider Boundaries" title="Capability request response scorecard policy routing handoff review and readiness controls" items={MULTI_PROVIDER_CAPABILITY_ROUTING_PROTECTED_BOUNDARY_ITEMS} /><CatalogPanel eyebrow="Multi-Provider Control Coverage" title="Blocked provider model prompt SDK network storage render worker export publish runtime credential and token controls" items={MULTI_PROVIDER_CAPABILITY_ROUTING_BLOCKED_ACTION_ITEMS} /></section>
      <section className={styles.glassPanel} aria-label="Multi-Provider Capability Routing completion guard"><PanelHeading eyebrow="Completion Guard" title="2986-3017 - Multi-Provider Capability Routing" badge="Phase 3017" /><p className={styles.mutedText}>Multi-Provider Capability Routing is a review-only multi-provider capability routing surface with synthetic multi-provider routing data only. Multi-provider routing remains disabled until explicit operator approval. The provider capability request, provider capability response, text provider routing remains disabled, image provider routing remains disabled, audio provider routing remains disabled, video provider routing remains disabled, transcription provider routing remains disabled, editing provider routing remains disabled, metadata provider routing remains disabled, safety provider routing remains disabled, provider scorecard remains synthetic, cost rate privacy region data retention approval audit redaction observability retry fallback timeout routing remains review-only, disabled provider route candidate, multi-provider runner handoff remains review-only, execution bridge handoff remains review-only, multi-provider operator review remains required, multi-provider readiness gate, and multi-provider capability routing completion does not call providers. Next likely batch: 3018-3049 - First Real Provider Call Guard.</p></section>
      <section className={styles.diagnosticPanel} aria-label="Multi-Provider Capability Routing diagnostics"><PanelHeading eyebrow="Diagnostics" title="2986-3017 multi-provider capability routing coverage" badge="Phase pages secondary" /><div className={styles.diagnosticGrid}>{model.routes.map((item) => <a key={buildMultiProviderCapabilityRoutingStableKey(["multi-provider-capability-routing-route", item.slug])} className={styles.diagnosticLink} href={item.href}><span>{item.phase}</span><strong>{item.title}</strong></a>)}</div></section>
    </section>
  );
}

function MetricCard({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className={styles.metricCard}><span className={styles.metricLabel}>{label}</span><strong className={styles.metricValue}>{value}</strong><span className={styles.metricDetail}>{detail}</span></article>; }

function CatalogPanel({ eyebrow, title, items }: { eyebrow: string; title: string; items: readonly { id: string; label: string; state: string }[] }) { return <article className={styles.glassPanel}><PanelHeading eyebrow={eyebrow} title={title} badge="Review only" /><div className={styles.systemsGrid}>{items.map((item) => <article key={buildMultiProviderCapabilityRoutingStableKey(["catalog", eyebrow, item.id])} className={styles.systemCard}><span className={styles.systemTier}>Protected boundary</span><strong>{item.label}</strong><p className={styles.systemStatus}>{item.state}</p></article>)}</div></article>; }

function PanelHeading({ eyebrow, title, badge }: { eyebrow: string; title: string; badge: string }) { return <div className={styles.panelHeader}><div><p className={styles.eyebrow}>{eyebrow}</p><h2 className={styles.sectionTitle}>{title}</h2></div><span className={styles.safeBadge}>{badge}</span></div>; }
