export const DAILY_BETA_ONE_RELEASE_REVIEW_SAFETY_MARKERS = [
  "review-only",
  "approval required",
  "no action execution from UI",
  "no workflow execution",
  "no workflow execution from UI",
  "no workflow runs automatically",
  "no trial launch",
  "no Daily Beta 1 launch",
  "no live workflow launch",
  "no go-live action",
  "no go-live behavior",
  "no activation execution",
  "no Daily Beta 1 activation execution",
  "no Daily Beta activation from UI",
  "no Daily Beta 1 activation from UI",
  "no activation dry-run execution",
  "no activation data persistence",
  "no final gate auto-pass",
  "no final gate automation",
  "no controlled operator trial execution",
  "no readiness lock automation",
  "no audit-lock automation",
  "no release handoff send behavior",
  "no live traffic routing",
  "no boundary probe execution",
  "no controlled trial execution",
  "no controlled trial data persistence",
  "no rollout execution",
  "no controlled rollout execution",
  "no rollout auto-proceed",
  "no rollout regression/test execution",
  "no rollout hardening apply behavior",
  "no live boundary signoff automation",
  "no release signoff automation",
  "no release candidate signoff automation",
  "no operator readiness signoff automation",
  "no final safety signoff automation",
  "no release approval automation",
  "no release summary approval automation",
  "no approval automation",
  "no auto-approval",
  "no approval is granted",
  "no action approval from UI",
  "no approval decision persistence",
  "no final operator signoff automation",
  "no final regression/test execution",
  "no regression/test execution from UI",
  "no regression replay execution",
  "no test/build/smoke execution from UI",
  "no test execution from UI",
  "no build execution from UI",
  "no smoke execution from UI",
  "no documentation publish behavior",
  "no docs publish behavior",
  "no release notes publish behavior",
  "no release notes publishing",
  "no handoff send behavior",
  "no feedback auto-ingestion",
  "no feedback ingestion automation",
  "no evidence ingestion",
  "no evidence ingestion automation",
  "no result ingestion",
  "no output persistence",
  "no recovery trigger",
  "no fix application",
  "no patch apply behavior",
  "no hardening apply behavior",
  "no command execution",
  "no shell/git/test/build/smoke execution from UI",
  "no git command execution from UI",
  "no shell command execution from UI",
  "no provider API calls",
  "no provider traffic routing",
  "no live provider/local/connector/automation traffic routing",
  "no prompt sending to providers",
  "no provider output persistence",
  "no local model calls",
  "no local bridge endpoint calls",
  "no local bridge endpoint calls from arbitrary UI",
  "no connector API calls",
  "no connector account connection",
  "no connector data fetch",
  "no connector data persistence",
  "no connector data storage",
  "no automation execution",
  "no automation creation",
  "no automation rule persistence",
  "no reminder creation",
  "no task scheduling",
  "no schedule creation",
  "no scheduled task creation",
  "no conditional watch creation",
  "no watch creation",
  "no polling loop creation",
  "no polling loops from UI",
  "no background job creation",
  "no background jobs",
  "no notification sending",
  "no policy auto-apply",
  "no settings persistence",
  "no preference persistence",
  "no creative asset generation",
  "no research execution",
  "no coding workflow execution",
  "no web/search API calls",
  "no GitHub API calls from UI",
  "no prompt/file/project/connector/provider/model/output/audit/evidence/automation/live/beta/policy/settings/daily/rollout/release data sending without approval",
  "no prompt/file/project/connector/provider/model/output/audit/evidence/automation/live/beta/policy/settings/daily/rollout/release/boundary data sending without approval",
  "no prompt/file/project/connector/provider/model/output/audit/evidence/automation/live/beta/policy/settings/daily/rollout/release/boundary/e2e data sending without approval",
  "no prompt/file/project/connector/provider/model/output/audit/evidence/automation/live/beta/policy/settings/daily/rollout/release/boundary/e2e/activation data sending without approval",
  "no prompt/file/project/connector/provider/model/output/audit/evidence/automation/live/beta/policy/settings/daily/rollout data sending without approval",
  "no prompt/file/project/connector/provider/model/output/audit/evidence/automation/live/beta/policy/settings data sending without approval",
  "no prompt/file/project/connector/provider/model/output data sending without approval",
  "no prompt/file/project/connector/provider/model data sending without approval",
  "no prompt/file/project/connector data sending without approval",
  "no prompt/file/project data sending without approval",
  "no arbitrary project scanning",
  "no arbitrary local file browsing",
  "no arbitrary path crawling",
  "no arbitrary file read/open from UI",
  "no auto-open local files",
  "no file mutation",
  "no file write",
  "no file export/write behavior",
  "no export/write behavior",
  "no file deletion",
  "no memory/RAG ingestion",
  "no memory auto-promotion",
  "no Brain graph mutation",
  "no appendEvent/saveBrainGraph calls from UI",
  "no direct appendEvent call from UI",
  "no direct saveBrainGraph call from UI",
  "no direct apply-diff call from UI",
  "no direct write-file call from UI",
  "no direct run-command call from UI",
  "no plugin execution",
  "no tool execution",
  "no agent execution",
  "no extension runtime executor",
  "no MCP runtime",
  "no MCP tool calls",
  "no localStorage API key storage",
  "no sessionStorage API key storage",
  "no localStorage/sessionStorage token storage",
  "no localStorage writes",
  "no sessionStorage writes",
  "no token storage",
  "no endpoint storage",
  "no credential storage",
  "no output storage",
  "no automation data storage",
  "no process.env printing",
  "no API keys or secrets displayed",
  "no example real key/token/endpoint values",
  "no route coverage removal",
  "no duplicate route hrefs",
  "no duplicate shortLabel values",
  "no duplicate menus",
  "no Ruflo/Odysseus vendoring",
  "no package install behavior",
  "checkpoint documentation smoke still exists and remains registered",
  "server-only path boundary markers remain intact",
  "plain English",
  "no giant raw JSON above fold",
  "advanced details collapsed/secondary",
  "no unsafe execution buttons",
  "no automatic local action",
  "no raw fetch from arbitrary UI",
  "no prompt payload sent to providers",
  "no cloud provider API calls",
  "no password storage",
  "no API key localStorage",
  "no raw secret display",
  "no process.env value printed in UI",
  "no hardcoded API keys",
  "no broker-execution call except blocked-policy text",
  "no Math.random",
  "no Date.now",
  "no Date.now for deterministic layout/ids",
  "no mojibake",
  "no obvious duplicate React key patterns",
] as const;
