"use client";

import { CodexForgeAppShell } from "@/lib/codexforge/navigation-shell";
import { FIRST_CONTROLLED_VIDEO_WORKFLOW_TRIAL_BLOCKED_ACTION_ITEMS, FIRST_CONTROLLED_VIDEO_WORKFLOW_TRIAL_PIPELINE_ITEMS, FIRST_CONTROLLED_VIDEO_WORKFLOW_TRIAL_PROTECTED_BOUNDARY_ITEMS, FIRST_CONTROLLED_VIDEO_WORKFLOW_TRIAL_SHARED_MARKERS, buildFirstControlledVideoWorkflowTrialModel, buildFirstControlledVideoWorkflowTrialStableKey, type FirstControlledVideoWorkflowTrialRouteSlug } from "../first-controlled-video-workflow-trial-model";
import styles from "../../jarvis-cockpit-visual-system/components/JarvisCockpitVisualPanel.module.css";

export function FirstControlledVideoWorkflowTrialPageClientShell({ routeSlug }: { routeSlug: FirstControlledVideoWorkflowTrialRouteSlug }) {
  const model = buildFirstControlledVideoWorkflowTrialModel(routeSlug);
  return (
    <CodexForgeAppShell activePath={model.route.href} workspaceLabel={model.route.title} nextActionContext={{ wantsOperatorOverview: false }} focusMode contentMaxWidth="wide" pageChrome="minimal" showRightRail={false} showSidebarSafetyNotice={false} showHeroRouteChips={false}>
      <FirstControlledVideoWorkflowTrialRoutePanel routeSlug={routeSlug} />
    </CodexForgeAppShell>
  );
}

export function FirstControlledVideoWorkflowTrialCockpitSection() {
  return <FirstControlledVideoWorkflowTrialRoutePanel routeSlug="first-controlled-video-workflow-trial-completion" embedded />;
}

export function FirstControlledVideoWorkflowTrialRoutePanel({ routeSlug, embedded = false }: { routeSlug: FirstControlledVideoWorkflowTrialRouteSlug; embedded?: boolean }) {
  const model = buildFirstControlledVideoWorkflowTrialModel(routeSlug);
  return (
    <section className={embedded ? styles.cockpitShell : styles.routeShell} data-codexforge-first-controlled-video-workflow-trial={FIRST_CONTROLLED_VIDEO_WORKFLOW_TRIAL_SHARED_MARKERS.join(" | ")} data-codexforge-first-controlled-video-workflow-trial-route={model.route.markerPhrases.join(" | ")} data-codexforge-first-controlled-video-workflow-trial-pipeline={FIRST_CONTROLLED_VIDEO_WORKFLOW_TRIAL_PIPELINE_ITEMS.map((item) => item.label).join(" | ")}>
      <header className={styles.heroPanel}>
        <div className={styles.heroGlow} aria-hidden="true" />
        <div className={styles.heroContent}>
          <div className={styles.eyebrowRow}><span className={styles.phaseBadge}>{embedded ? "First Controlled Video Workflow Trial" : model.route.phase}</span><span className={styles.safeBadge}>review-only controlled video workflow trial</span><span className={styles.blockedBadge}>operator-approved only</span></div>
          <h1 className={styles.heroTitle}>{embedded ? "First Controlled Video Workflow Trial" : model.route.title}</h1>
          <p className={styles.heroLead}>This route is a review-only controlled video workflow trial with synthetic controlled video trial data only. The controlled video workflow trial remains blocked until explicit operator approval. It shows how a first controlled internal private alpha video workflow trial would be reviewed, gated, approved, audited, blocked, and handed off across provider gateway, asset storage, audio storage, render queue, worker orchestration, artifact export, and publish gateway boundaries. No live video creation, no live end-to-end execution, no live provider calls, no model calls, no prompt sending, no video rendering, no worker execution, no artifact export execution, no publish gateway execution, no platform upload, no network egress, and no frontend persistence exist.</p>
          <div className={styles.heroMetricGrid}><MetricCard label="Route slug" value={model.route.slug} detail={model.route.href} /><MetricCard label="Data" value="Synthetic" detail="synthetic controlled video trial data only" /><MetricCard label="Approval" value="Required" detail="operator approval checkpoint remains required" /><MetricCard label="Completion" value="Blocked" detail="controlled trial completion does not execute video workflow" /></div>
        </div>
        <div className={styles.missionPreview} aria-label="First Controlled Video Workflow Trial preview"><p className={styles.missionLabel}>Controlled video trial</p><p className={styles.missionDetail}>Review-only. No live video creation. No live end-to-end execution. Provider gateway handoff remains review-only. Render queue handoff remains review-only. Worker orchestration handoff remains review-only. Publish gateway handoff remains review-only.</p></div>
      </header>
      <section className={styles.markerBand} aria-label="First Controlled Video Workflow Trial shared markers">{model.safetyMarkers.map((marker, index) => <span key={buildFirstControlledVideoWorkflowTrialStableKey(["shared-marker", String(index), marker])} className={styles.markerPill}>{marker}</span>)}</section>
      <section className={styles.glassPanel} aria-label="Review-only controlled video workflow trial pipeline"><PanelHeading eyebrow="Review-only controlled video workflow trial" title="Reviewed gated approved audited blocked handoff path" badge="Static only" /><p className={styles.bodyText}>This controlled trial surface is synthetic controlled video trial data only. It does not send prompts, call models, dispatch render queues, execute workers, export artifacts, create files, create signed URLs, execute publish gateways, upload to platforms, store credentials or tokens, write browser storage, call connectors, or use network egress.</p><div className={styles.systemsGrid}>{FIRST_CONTROLLED_VIDEO_WORKFLOW_TRIAL_PIPELINE_ITEMS.map((item) => <article key={buildFirstControlledVideoWorkflowTrialStableKey(["pipeline", item.id])} className={styles.systemCard}><span className={styles.systemTier}>Controlled trial path</span><strong>{item.label}</strong><p className={styles.systemStatus}>{item.state}</p></article>)}</div></section>
      <section className={styles.glassPanel} aria-label="First Controlled Video Workflow Trial route map"><PanelHeading eyebrow="First Controlled Video Workflow Trial" title={model.route.title} badge={model.route.phase} /><p className={styles.bodyText}>{model.route.summary}</p><div className={styles.contractGrid}>{model.route.markerPhrases.map((marker, index) => <span key={buildFirstControlledVideoWorkflowTrialStableKey(["route-marker", model.route.slug, String(index), marker])} className={styles.contractChip}>{marker}</span>)}</div></section>
      <section className={styles.glassPanel} aria-label="Controlled video trial blocked action matrix"><PanelHeading eyebrow="Blocked Action Matrix" title="Provider model prompt storage render worker export publish network persistence runtime and credential execution stay blocked" badge="Actions disabled" /><div className={styles.blockedDeckGrid}>{FIRST_CONTROLLED_VIDEO_WORKFLOW_TRIAL_BLOCKED_ACTION_ITEMS.map((item) => <button key={buildFirstControlledVideoWorkflowTrialStableKey(["blocked", item.id])} type="button" disabled className={styles.blockedCommandButton}><strong>{item.label}</strong><span>{item.state}</span><small>review-only controlled video workflow trial</small></button>)}</div></section>
      <section className={styles.cockpitGrid} aria-label="Controlled video trial protected boundaries"><CatalogPanel eyebrow="Protected Trial Boundaries" title="Operator approval audit redaction privacy safety cost and review-only handoff controls" items={FIRST_CONTROLLED_VIDEO_WORKFLOW_TRIAL_PROTECTED_BOUNDARY_ITEMS} /><CatalogPanel eyebrow="Trial Control Coverage" title="Blocked live video provider prompt render worker export publish network persistence storage credential token service and runtime controls" items={FIRST_CONTROLLED_VIDEO_WORKFLOW_TRIAL_BLOCKED_ACTION_ITEMS} /></section>
      <section className={styles.glassPanel} aria-label="First Controlled Video Workflow Trial completion guard"><PanelHeading eyebrow="Completion Guard" title="2858-2889 - First Controlled Video Workflow Trial" badge="Phase 2889" /><p className={styles.mutedText}>First Controlled Video Workflow Trial is a review-only controlled video workflow trial with synthetic controlled video trial data only. The controlled video workflow trial remains blocked until explicit operator approval. Provider gateway handoff remains review-only, asset storage handoff remains review-only, audio storage handoff remains review-only, render queue handoff remains review-only, worker orchestration handoff remains review-only, artifact export handoff remains review-only, publish gateway handoff remains review-only, operator approval checkpoint remains required, audit boundary remains required, redaction boundary remains required, privacy safety cost guard remains required, and controlled trial completion does not execute video workflow. Next likely batch: 2890-2921 - roadmap follow-up after First Controlled Video Workflow Trial, not implemented here.</p></section>
      <section className={styles.diagnosticPanel} aria-label="First Controlled Video Workflow Trial diagnostics"><PanelHeading eyebrow="Diagnostics" title="2858-2889 controlled video trial coverage" badge="Phase pages secondary" /><div className={styles.diagnosticGrid}>{model.routes.map((item) => <a key={buildFirstControlledVideoWorkflowTrialStableKey(["controlled-video-trial-route", item.slug])} className={styles.diagnosticLink} href={item.href}><span>{item.phase}</span><strong>{item.title}</strong></a>)}</div></section>
    </section>
  );
}

function MetricCard({ label, value, detail }: { label: string; value: string; detail: string }) { return <article className={styles.metricCard}><span className={styles.metricLabel}>{label}</span><strong className={styles.metricValue}>{value}</strong><span className={styles.metricDetail}>{detail}</span></article>; }

function CatalogPanel({ eyebrow, title, items }: { eyebrow: string; title: string; items: readonly { id: string; label: string; state: string }[] }) { return <article className={styles.glassPanel}><PanelHeading eyebrow={eyebrow} title={title} badge="Review only" /><div className={styles.systemsGrid}>{items.map((item) => <article key={buildFirstControlledVideoWorkflowTrialStableKey(["catalog", eyebrow, item.id])} className={styles.systemCard}><span className={styles.systemTier}>Protected boundary</span><strong>{item.label}</strong><p className={styles.systemStatus}>{item.state}</p></article>)}</div></article>; }

function PanelHeading({ eyebrow, title, badge }: { eyebrow: string; title: string; badge: string }) { return <div className={styles.panelHeader}><div><p className={styles.eyebrow}>{eyebrow}</p><h2 className={styles.sectionTitle}>{title}</h2></div><span className={styles.safeBadge}>{badge}</span></div>; }
