import type {
  JarvisPermissionApprovalEnginePolicyRecord,
} from "./jarvis-permission-approval-engine-model";

export const JARVIS_PERMISSION_APPROVAL_ENGINE_POLICIES = [
  {
    capabilityId: "video.generate",
    featureDomain: "video",
    riskTier: "operator-high",
    permissionPosture: "approval-required",
    approvalMode: "manual-approval-required",
    dryRunRequirement: "dry-run-required-before-execution",
    backendOnlyRequirement: "backend-only-required",
    humanApprovalRequirement: "human approval gate required",
    operatorRoles: ["operator", "approver", "human-reviewer"],
    blockedActionCategories: [
      "provider execution",
      "network execution",
      "render export publish execution",
    ],
    denialReasons: [
      "no direct frontend execution",
      "backend-owned adapter required",
      "no provider execution",
      "no video provider execution",
      "operator review required before any execution",
    ],
    approvalPacketReadiness: "approval-packet-operator-review-required",
    costLimitPosture: "cost limit posture required",
    rateLimitPosture: "rate limit posture required",
    timeoutPosture: "timeout posture required",
    dataSensitivityPosture: "data sensitivity posture required",
    secretBoundaryPosture: "secret boundary posture required",
    auditHookPosture: "audit hook readiness only",
    resultLedgerHookPosture: "result ledger hook readiness only",
    memoryBoundaryPosture: "memory boundary hook readiness only",
    killSwitchPosture: "kill switch hook required",
    replayBlockPosture: "replay block hook required",
    operatorReviewPosture: "operator review required before any execution",
    notes: [
      "approval required decision",
      "provider risk remains approval-gated",
    ],
  },
  {
    capabilityId: "website.create",
    featureDomain: "website",
    riskTier: "operator-high",
    permissionPosture: "needs-human-operator-review",
    approvalMode: "manual-human-review-required",
    dryRunRequirement: "dry-run-required-before-execution",
    backendOnlyRequirement: "backend-only-required",
    humanApprovalRequirement: "human approval gate required",
    operatorRoles: ["operator", "approver", "human-reviewer"],
    blockedActionCategories: [
      "website creation execution",
      "network execution",
      "provider execution",
    ],
    denialReasons: [
      "no direct frontend execution",
      "backend-owned adapter required",
      "human operator review required",
      "no website creation execution",
      "operator review required before any execution",
    ],
    approvalPacketReadiness: "approval-packet-operator-review-required",
    costLimitPosture: "cost limit posture required",
    rateLimitPosture: "rate limit posture required",
    timeoutPosture: "timeout posture required",
    dataSensitivityPosture: "data sensitivity posture required",
    secretBoundaryPosture: "secret boundary posture required",
    auditHookPosture: "audit hook readiness only",
    resultLedgerHookPosture: "result ledger hook readiness only",
    memoryBoundaryPosture: "memory boundary hook readiness only",
    killSwitchPosture: "kill switch hook required",
    replayBlockPosture: "replay block hook required",
    operatorReviewPosture: "operator review required before any execution",
    notes: [
      "human operator review required",
      "website creation risk remains approval-gated",
    ],
  },
  {
    capabilityId: "avatar.prepare",
    featureDomain: "avatar",
    riskTier: "operator-high",
    permissionPosture: "dry-run-only",
    approvalMode: "dry-run-only",
    dryRunRequirement: "dry-run-required-before-execution",
    backendOnlyRequirement: "backend-only-required",
    humanApprovalRequirement: "human approval gate required",
    operatorRoles: ["operator", "approver"],
    blockedActionCategories: [
      "avatar generation execution",
      "provider execution",
      "network execution",
    ],
    denialReasons: [
      "no direct frontend execution",
      "backend-owned adapter required",
      "no avatar generation execution",
      "no provider execution",
      "operator review required before any execution",
    ],
    approvalPacketReadiness: "approval-packet-ready-for-review",
    costLimitPosture: "cost limit posture required",
    rateLimitPosture: "rate limit posture required",
    timeoutPosture: "timeout posture required",
    dataSensitivityPosture: "data sensitivity posture required",
    secretBoundaryPosture: "secret boundary posture required",
    auditHookPosture: "audit hook readiness only",
    resultLedgerHookPosture: "result ledger hook readiness only",
    memoryBoundaryPosture: "memory boundary hook readiness only",
    killSwitchPosture: "kill switch hook required",
    replayBlockPosture: "replay block hook required",
    operatorReviewPosture: "operator review required before any execution",
    notes: [
      "dry-run only decision",
      "avatar risk remains approval-gated",
    ],
  },
  {
    capabilityId: "chatbot.plan",
    featureDomain: "chatbot-brain",
    riskTier: "operator-moderate",
    permissionPosture: "allowed-for-review",
    approvalMode: "review-only",
    dryRunRequirement: "dry-run-review-only",
    backendOnlyRequirement: "backend-only-required",
    humanApprovalRequirement: "human approval gate optional",
    operatorRoles: ["operator", "auditor"],
    blockedActionCategories: [
      "chatbot autonomous execution",
      "provider execution",
      "network execution",
    ],
    denialReasons: [
      "no direct frontend execution",
      "backend-owned adapter required",
      "no chatbot autonomous execution",
      "no provider execution",
      "operator review required before any execution",
    ],
    approvalPacketReadiness: "approval-packet-ready-for-review",
    costLimitPosture: "cost limit posture required",
    rateLimitPosture: "rate limit posture required",
    timeoutPosture: "timeout posture required",
    dataSensitivityPosture: "data sensitivity posture required",
    secretBoundaryPosture: "secret boundary posture required",
    auditHookPosture: "audit hook readiness only",
    resultLedgerHookPosture: "result ledger hook readiness only",
    memoryBoundaryPosture: "memory boundary hook readiness only",
    killSwitchPosture: "kill switch hook required",
    replayBlockPosture: "replay block hook required",
    operatorReviewPosture: "operator review required before any execution",
    notes: [
      "allowed for review only",
      "centralized permission decision model",
    ],
  },
  {
    capabilityId: "trading.paperReview",
    featureDomain: "trading",
    riskTier: "operator-critical",
    permissionPosture: "blocked",
    approvalMode: "blocked-until-backend-owned-adapter",
    dryRunRequirement: "dry-run-required-before-execution",
    backendOnlyRequirement: "backend-only-required",
    humanApprovalRequirement: "human approval gate required",
    operatorRoles: ["operator", "approver", "auditor", "human-reviewer"],
    blockedActionCategories: [
      "trading execution",
      "network execution",
      "provider execution",
    ],
    denialReasons: [
      "no direct frontend execution",
      "backend-owned adapter required",
      "no trading execution",
      "no paper trading execution",
      "no real-money trading execution",
      "operator review required before any execution",
    ],
    approvalPacketReadiness: "approval-packet-blocked",
    costLimitPosture: "cost limit posture required",
    rateLimitPosture: "rate limit posture required",
    timeoutPosture: "timeout posture required",
    dataSensitivityPosture: "data sensitivity posture required",
    secretBoundaryPosture: "secret boundary posture required",
    auditHookPosture: "audit hook readiness only",
    resultLedgerHookPosture: "result ledger hook readiness only",
    memoryBoundaryPosture: "memory boundary hook readiness only",
    killSwitchPosture: "kill switch hook required",
    replayBlockPosture: "replay block hook required",
    operatorReviewPosture: "operator review required before any execution",
    notes: [
      "blocked decision",
      "trading risk remains critical",
    ],
  },
  {
    capabilityId: "workflow.prepare",
    featureDomain: "workflow",
    riskTier: "operator-high",
    permissionPosture: "approval-required",
    approvalMode: "manual-approval-and-audit-required",
    dryRunRequirement: "dry-run-required-before-execution",
    backendOnlyRequirement: "backend-only-required",
    humanApprovalRequirement: "human approval gate required",
    operatorRoles: ["operator", "approver", "auditor"],
    blockedActionCategories: [
      "worker dispatch",
      "network execution",
      "provider execution",
    ],
    denialReasons: [
      "no direct frontend execution",
      "backend-owned adapter required",
      "no worker dispatch",
      "no provider execution",
      "operator review required before any execution",
    ],
    approvalPacketReadiness: "approval-packet-operator-review-required",
    costLimitPosture: "cost limit posture required",
    rateLimitPosture: "rate limit posture required",
    timeoutPosture: "timeout posture required",
    dataSensitivityPosture: "data sensitivity posture required",
    secretBoundaryPosture: "secret boundary posture required",
    auditHookPosture: "audit hook readiness only",
    resultLedgerHookPosture: "result ledger hook readiness only",
    memoryBoundaryPosture: "memory boundary hook readiness only",
    killSwitchPosture: "kill switch hook required",
    replayBlockPosture: "replay block hook required",
    operatorReviewPosture: "operator review required before any execution",
    notes: [
      "approval required decision",
      "workflow risk remains approval-gated",
    ],
  },
  {
    capabilityId: "render.publishReview",
    featureDomain: "render-publish",
    riskTier: "operator-high",
    permissionPosture: "kill-switch-blocked",
    approvalMode: "blocked-until-backend-owned-adapter",
    dryRunRequirement: "dry-run-required-before-execution",
    backendOnlyRequirement: "backend-only-required",
    humanApprovalRequirement: "human approval gate required",
    operatorRoles: ["operator", "approver", "auditor", "human-reviewer"],
    blockedActionCategories: [
      "render export publish execution",
      "worker dispatch",
      "network execution",
    ],
    denialReasons: [
      "no direct frontend execution",
      "backend-owned adapter required",
      "no render execution",
      "no export execution",
      "no publish execution",
      "hard kill switch",
      "operator review required before any execution",
    ],
    approvalPacketReadiness: "approval-packet-blocked",
    costLimitPosture: "cost limit posture required",
    rateLimitPosture: "rate limit posture required",
    timeoutPosture: "timeout posture required",
    dataSensitivityPosture: "data sensitivity posture required",
    secretBoundaryPosture: "secret boundary posture required",
    auditHookPosture: "audit hook readiness only",
    resultLedgerHookPosture: "result ledger hook readiness only",
    memoryBoundaryPosture: "memory boundary hook readiness only",
    killSwitchPosture: "kill-switch blocked decision",
    replayBlockPosture: "replay block hook required",
    operatorReviewPosture: "operator review required before any execution",
    notes: [
      "kill-switch blocked decision",
      "approval engine foundation",
    ],
  },
] satisfies readonly JarvisPermissionApprovalEnginePolicyRecord[];

export const JARVIS_PERMISSION_APPROVAL_ENGINE_POLICY_SUMMARY =
  JARVIS_PERMISSION_APPROVAL_ENGINE_POLICIES.map(
    (policy) =>
      policy.capabilityId +
      " -> " +
      policy.permissionPosture +
      " / " +
      policy.riskTier
  );

export function getJarvisPermissionApprovalEnginePolicy(capabilityId: string) {
  return JARVIS_PERMISSION_APPROVAL_ENGINE_POLICIES.find(
    (policy) => policy.capabilityId === capabilityId
  );
}
