import type { MissionNextAction } from "./mission-control-types";

export function buildMissionNextActions(): MissionNextAction[] {
  return [
    {
      id: "review-stabilization-command-center",
      label: "Review stabilization command center",
      href: "/stabilization",
      priority: "primary",
      readiness: "needs-review",
      safetyNote: "Stabilization Command Center rolls build and smoke posture, verification signals, regression triage, fix queue, patch queue, apply gates, post-apply verification, and next safest action into a read-only operator review; no auto-fix, no auto-rollback, no command execution, no file writes, and preserve latest-message authority.",
    },
    {
      id: "return-to-operator-home",
      label: "Return to Operator Home",
      href: "/",
      priority: "secondary",
      readiness: "ready",
      safetyNote: "Operator Home Dashboard readiness gives the full launch deck, route status, local-first safety posture, validation checklist, and next safe action without command execution or file writes.",
    },
    {
      id: "review-regression-triage",
      label: "Review regression triage",
      href: "/ai",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Self-Healing Regression Triage turns failed or warning verification signals into reviewed regression cards, suspected causes, impacted files, rollback advice, fix recommendations, and Safe Patch Preview handoff only; no auto-fix, no auto-rollback, no command execution, no file writes, and preserve latest-message authority.",
    },
    {
      id: "review-regression-fix-queue",
      label: "Review regression fix queue",
      href: "/ai",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Regression Fix Queue turns reviewed regression triage cards into prioritized repair queue handoffs for Safe Patch Preview and Preview Diff Composer only; no auto-fix, no auto-rollback, no command execution, no file writes, and preserve latest-message authority.",
    },
    {
      id: "compose-preview-diff",
      label: "Compose preview diff",
      href: "/ai",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Preview Diff Composer readiness packages queued patch preview items into human-reviewable pseudo-diffs; preview-only, not an applyable patch, current file content is authority, evidence is context not proof, and no file writes without approval.",
    },
    {
      id: "review-apply-gate",
      label: "Review apply gate",
      href: "/ai",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Patch Application Gate readiness prepares explicit human approval packets and display-only apply request previews; actual mutation remains blocked, apply-diff requires tool-policy approval, current files must be verified, rollback plan required, and preserve latest-message authority.",
    },
    {
      id: "build-apply-evidence-pack",
      label: "Build apply evidence pack",
      href: "/ai",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Apply Evidence Pack readiness bundles current file verification, rollback plan, test plan, operator approval note, evidence refs, smoke placeholders, mutation firewall, and final readiness; it does not apply changes and is future guarded apply only.",
    },
    {
      id: "review-apply-diff-dry-run-result",
      label: "Review dry-run result",
      href: "/ai",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Apply-Diff Dry Run readiness simulates apply-diff policy, affected file validation, conflict checks, result, and ledger only; simulation only, no mutation, actual apply-diff remains blocked, current file verification required, rollback plan required, and preserve latest-message authority.",
    },
    {
      id: "review-approved-apply-request",
      label: "Review approved apply request",
      href: "/ai",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Apply-Diff Execution Gate readiness prepares an approval-gated apply-diff request packet and guarded execute route bridge; explicit operator approval required, no silent execution, rollback plan required, verification required after dispatch, and preserve latest-message authority.",
    },
    {
      id: "review-patch-preview-queue",
      label: "Review queued patch preview",
      href: "/ai",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Patch Preview Queue readiness packages reviewed fix recommendations for Safe Patch Preview; preview diff only, verify current files, no file writes without approval, no command execution without approval, and preserve latest-message authority.",
    },
    {
      id: "review-grounded-fix-recommendation",
      label: "Review grounded fix recommendation",
      href: "/ai",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Grounded Fix Recommendation reviews evidence and file context, then prepares Safe Patch Preview handoff only; no command execution, no apply, and no file mutation.",
    },
    {
      id: "use-reviewed-evidence-in-chat",
      label: "Use reviewed evidence in chat",
      href: "/ai",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Evidence-Grounded Chat uses selected evidence only, shows local citations and stale or weak warnings, and allows copy/use prompt handoff without hidden context injection.",
    },
    {
      id: "review-read-only-evidence-memory",
      label: "Review read-only evidence memory",
      href: "/memory",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Evidence Memory converts read-only execution evidence into reviewable candidates only; Review required before memory promotion, Brain merge review required, and no graph mutation.",
    },
    {
      id: "execute-approved-read-only-step",
      label: "Execute approved read-only step",
      href: "/tasks",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Read-Only Step Execution runs only approved local read-only tools, captures visible evidence, and keeps mutation tools blocked.",
    },
    {
      id: "preview-task-step-run",
      label: "Preview a task step run",
      href: "/tasks",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Step Runner Preview prepares policy posture, approval packet, dry run plan, and result preview only; No step execution in Phase 25 and Future run requires approval.",
    },
    {
      id: "review-execution-readiness",
      label: "Review execution readiness",
      href: "/tasks",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Execution Readiness reviews step preflight, tool posture, risk, tests, and approval gates; execution blocked until approval.",
    },
    {
      id: "activate-reviewed-task",
      label: "Activate reviewed task",
      href: "/tasks",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Reviewed Task Activation creates a plan preview and /ai handoff only; no auto-run and no file mutation.",
    },
    {
      id: "review-task-suggestions",
      label: "Review task suggestions",
      href: "/tasks",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Task Autopilot is review required, preview-only, and never auto-runs tasks.",
    },
    {
      id: "review-system-health",
      label: "Review system health",
      href: "/mission",
      priority: "secondary",
      readiness: "ready",
      safetyNote: "Readonly review inside Mission Control.",
    },
    {
      id: "open-files-command-center",
      label: "Open Files Command Center",
      href: "/files",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Preview file context before any external action.",
    },
    {
      id: "search-brain-memory",
      label: "Search Brain memory",
      href: "/brain",
      priority: "secondary",
      readiness: "ready",
      safetyNote: "Deterministic local recall only; no graph mutation and inspect before editing.",
    },
    {
      id: "use-recalled-memory-in-chat",
      label: "Use recalled memory in chat",
      href: "/ai",
      priority: "secondary",
      readiness: "ready",
      safetyNote: "Chat recall context is opt-in, visible, and no hidden context injection is allowed.",
    },
    {
      id: "prepare-patch-preview",
      label: "Prepare patch preview",
      href: "/files",
      priority: "secondary",
      readiness: "preview-only",
      safetyNote: "Patch preparation remains preview-only here.",
    },
    {
      id: "build-production-pack",
      label: "Build production pack",
      href: "/production",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Pack export remains approval gated.",
    },
    {
      id: "review-artifact-workspace",
      label: "Review artifact workspace",
      href: "/artifacts",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Artifact workspace export requires explicit approval.",
    },
    {
      id: "review-artifact-ingestion-candidates",
      label: "Review artifact ingestion candidates",
      href: "/memory",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Read-only memory candidates and brain signals require review before promotion.",
    },
    {
      id: "review-memory-candidates",
      label: "Review memory candidates",
      href: "/memory",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Memory promotion requires explicit review state and produces preview events only.",
    },
    {
      id: "review-approved-memory-events",
      label: "Review approved memory events",
      href: "/memory",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Approved memory persistence writes only local event JSON and does not merge graph memory.",
    },
    {
      id: "review-brain-event-merge",
      label: "Review Brain event merge",
      href: "/memory",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Brain merge review is preview-only; explicit merge approval required before any future graph mutation.",
    },
    {
      id: "apply-approved-brain-merge",
      label: "Apply approved Brain merge",
      href: "/memory",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Approved Brain merge updates the local graph only after explicit approval, policy validation, and graph diff review.",
    },
    {
      id: "inspect-bridge-readiness",
      label: "Inspect bridge readiness",
      href: "/bridge",
      priority: "secondary",
      readiness: "future-gated",
      safetyNote: "Bridge consent remains guarded.",
    },
    {
      id: "open-operator-run-center",
      label: "Open Operator Run Center",
      href: "/runs",
      priority: "secondary",
      readiness: "preview-only",
      safetyNote: "No execution action is launched from Mission Control.",
    },
  ];
}

export function selectPrimaryMissionAction(
  actions: MissionNextAction[] = buildMissionNextActions()
): MissionNextAction {
  return actions.find((action) => action.priority === "primary") ?? actions[0];
}

export function summarizeMissionNextActions(
  actions: MissionNextAction[] = buildMissionNextActions()
): string[] {
  return [
    `${actions.length} safe next actions are available.`,
    "Every action navigates to a review surface instead of executing work.",
  ];
}
