import type {
  MissionSurface,
  MissionSurfaceId,
  MissionSurfaceRegistry,
  MissionSurfaceStatus,
  MissionReadinessLevel,
  MissionRiskPosture,
} from "./mission-control-types";

export function buildMissionSurface(args: {
  id: MissionSurfaceId;
  label: string;
  href: string;
  status: MissionSurfaceStatus;
  role: string;
  riskPosture: MissionRiskPosture;
  nextAction: string;
  readiness: MissionReadinessLevel;
  relatedPhase: string;
}): MissionSurface {
  return { ...args };
}

export function buildMissionSurfaceRegistry(): MissionSurfaceRegistry {
  const surfaces: MissionSurface[] = [
    buildMissionSurface({
      id: "operator-home",
      label: "Operator Home Dashboard",
      href: "/",
      status: "online",
      role: "Read-only CodexForge operator launch dashboard for route status, local-first safety posture, launch grid, system map, validation checklist, and next safe action handoff.",
      riskPosture: "readonly",
      nextAction: "Return to Operator Home Dashboard for launch and status review.",
      readiness: "ready",
      relatedPhase: "Phase 40 Operator Home Dashboard",
    }),
    buildMissionSurface({
      id: "stabilization",
      label: "Stabilization Command Center",
      href: "/stabilization",
      status: "review-needed",
      role: "Read-only operator stabilization dashboard for build and smoke posture, verification signals, regression triage, fix queue, patch queue, apply gates, post-apply verification, next safest action, and copy-only handoff.",
      riskPosture: "readonly",
      nextAction: "Review stabilization command center.",
      readiness: "needs-review",
      relatedPhase: "Phase 39 Stabilization Command Center",
    }),
    buildMissionSurface({
      id: "activity",
      label: "Global Activity Feed",
      href: "/activity",
      status: "online",
      role: "Read-only Global Activity Feed for verification events, regression triage, fix queue, patch preview, apply gates, memory review, creative planning, stabilization, and next safe action.",
      riskPosture: "readonly",
      nextAction: "Review activity feed.",
      readiness: "ready",
      relatedPhase: "Phase 43 Global Activity Feed",
    }),
    buildMissionSurface({
      id: "readiness",
      label: "Product Readiness Audit",
      href: "/readiness",
      status: "review-needed",
      role: "Read-only Product Readiness Audit readiness for route audit, smoke audit, safety audit, UX consistency audit, duplicate/dead-module audit, consolidation recommendations, and next functional workflow plan.",
      riskPosture: "readonly",
      nextAction: "Review product readiness before adding new feature surfaces.",
      readiness: "needs-review",
      relatedPhase: "Phase 54 Product Readiness Audit",
    }),
    buildMissionSurface({
      id: "consolidation",
      label: "Consolidation Pass",
      href: "/consolidation",
      status: "review-needed",
      role: "Read-only Phase 55 Consolidation Pass readiness for surface map, route consolidation, cockpit overlap audit, shared readiness, shared next action, shared safety copy, workflow entrypoints, and Phase 56 file reader planning.",
      riskPosture: "readonly",
      nextAction: "Review consolidation before Phase 56 Real Local Project Reader.",
      readiness: "needs-review",
      relatedPhase: "Phase 55 Consolidation Pass",
    }),
    buildMissionSurface({
      id: "tasks",
      label: "Task Autopilot, Reviewed Task Activation, Execution Readiness, Step Runner Preview, Read-Only Step Execution, and Evidence Memory",
      href: "/tasks",
      status: "review-needed",
      role: "Task suggestions from recalled memory, active context, file risk, patch preview posture, mission readiness, reviewed activation requests, execution readiness review, approval-ready Step Runner Preview packets, approved Read-Only Step Execution evidence capture, and Evidence Memory candidate previews.",
      riskPosture: "preview-only",
      nextAction: "Review read-only evidence memory.",
      readiness: "needs-review",
      relatedPhase: "Task Memory Autopilot, Reviewed Task Activation, Active Task Execution Readiness, Approved Step Runner Preview, Read-Only Step Execution, and Evidence Memory",
    }),
    buildMissionSurface({
      id: "video-render",
      label: "Video Render Job Preview",
      href: "/video-render",
      status: "preview-ready",
      role: "Preview-only video render job model, timeline, shot plan, provider plan, queue preview, artifact expectations, approval packet, policy, and future executor packet.",
      riskPosture: "preview-only",
      nextAction: "Review video render job preview.",
      readiness: "preview-only",
      relatedPhase: "Phase 66 Video Render Job Preview v1",
    }),
    buildMissionSurface({
      id: "creative-executor",
      label: "Guarded Creative Executor",
      href: "/creative-executor",
      status: "preview-ready",
      role: "Dry-run-first creative execution boundary for request, adapter allowlist, approval, preflight, dry-run plan, kill-switch policy, artifact capture, result, and future guarded executor packet.",
      riskPosture: "preview-only",
      nextAction: "Review creative executor dry-run.",
      readiness: "preview-only",
      relatedPhase: "Phase 67 Future Guarded Creative Executor",
    }),
    buildMissionSurface({
      id: "brain",
      label: "Brain",
      href: "/brain",
      status: "online",
      role: "Runtime memory, context continuity, approved Brain memory search, and deterministic local recall signals.",
      riskPosture: "readonly",
      nextAction: "Search Brain memory.",
      readiness: "ready",
      relatedPhase: "Brain Command Center and Brain Memory Search + Recall",
    }),
    buildMissionSurface({
      id: "memory",
      label: "Evidence Memory, Memory Review, and Persistence",
      href: "/memory",
      status: "review-needed",
      role: "Read-only evidence memory candidates, confidence, contradiction risk review, explicit approval, local event persistence, Brain merge readiness, graph diff previews, and approved local graph merge.",
      riskPosture: "preview-only",
      nextAction: "Review read-only evidence memory.",
      readiness: "needs-review",
      relatedPhase: "Evidence Memory, Memory Promotion Review Queue, Approved Memory Persistence, Brain Event Merge Review, and Approved Brain Graph Merge",
    }),
    buildMissionSurface({
      id: "memory-inbox",
      label: "Personal Operator Memory Inbox",
      href: "/memory-inbox",
      status: "review-needed",
      role: "Review-first inbox for activity, evidence, regression, patch, stabilization, creative, and manual operator notes before any memory promotion preview.",
      riskPosture: "preview-only",
      nextAction: "Review memory inbox.",
      readiness: "needs-review",
      relatedPhase: "Phase 44 Personal Operator Memory Inbox",
    }),
    buildMissionSurface({
      id: "runtime-journal",
      label: "Runtime Event Journal",
      href: "/runtime-journal",
      status: "review-needed",
      role: "Read-only journal for runtime event requests, approvals, policy checks, validation, dry-runs, reducer previews, blocked or ready results, append-only audit refs, and source handoffs.",
      riskPosture: "readonly",
      nextAction: "Review runtime event journal.",
      readiness: "needs-review",
      relatedPhase: "Phase 47 Runtime Event Journal",
    }),
    buildMissionSurface({
      id: "runtime-replay",
      label: "Runtime Event Replay Simulator",
      href: "/runtime-replay",
      status: "preview-ready",
      role: "Preview-only replay simulator for selected runtime journal events against a selected graph snapshot with reducer preview, impact analysis, risk detection, and rollback guidance.",
      riskPosture: "preview-only",
      nextAction: "Review runtime event replay.",
      readiness: "needs-review",
      relatedPhase: "Phase 49 Runtime Event Replay Simulator",
    }),
    buildMissionSurface({
      id: "brain-snapshots",
      label: "Brain Snapshot Manager",
      href: "/brain-snapshots",
      status: "preview-ready",
      role: "Read-only Brain Snapshot Manager readiness for deterministic snapshot summary, comparison, compact diff, integrity review, replay source selection, rollback planning, and memory governance review.",
      riskPosture: "preview-only",
      nextAction: "Review Brain snapshots.",
      readiness: "needs-review",
      relatedPhase: "Phase 50 Brain Snapshot Manager",
    }),
    buildMissionSurface({
      id: "snapshot-restore",
      label: "Snapshot Restore Approval Gate",
      href: "/snapshot-restore",
      status: "preview-ready",
      role: "Preview-only restore approval gate for selected Brain snapshot candidate modeling, comparison evidence, replay evidence, governance review, runtime journal review, approval packet, request preview, and blocked future executor boundary.",
      riskPosture: "preview-only",
      nextAction: "Review snapshot restore gate.",
      readiness: "needs-review",
      relatedPhase: "Phase 51 Snapshot Restore Approval Gate",
    }),
    buildMissionSurface({
      id: "brain-continuity",
      label: "Brain Continuity Dashboard",
      href: "/brain-continuity",
      status: "review-needed",
      role: "Read-only Brain Continuity Dashboard readiness for memory growth, runtime event journal health, snapshot posture, replay readiness, restore risk, governance posture, and next safe action.",
      riskPosture: "readonly",
      nextAction: "Review Brain continuity.",
      readiness: "needs-review",
      relatedPhase: "Phase 52 Brain Continuity Dashboard",
    }),
    buildMissionSurface({
      id: "handoff",
      label: "Continuity Handoff Packet",
      href: "/handoff",
      status: "review-needed",
      role: "Read-only Continuity Handoff Packet readiness for current state, risks, validation, rollback posture, memory posture, Brain continuity posture, runtime event posture, snapshot restore posture, commands to run manually, do-not-do rules, and next safe actions.",
      riskPosture: "readonly",
      nextAction: "Create continuity handoff.",
      readiness: "needs-review",
      relatedPhase: "Phase 53 Continuity Handoff Packet",
    }),
    buildMissionSurface({
      id: "brain-governance",
      label: "Brain Mutation Governance",
      href: "/brain-governance",
      status: "review-needed",
      role: "Read-only governance console for approved mutation boundaries, blocked direct mutation visibility, reducer impact governance, runtime journal integrity posture, risk board, and next safe action.",
      riskPosture: "readonly",
      nextAction: "Review brain mutation governance.",
      readiness: "needs-review",
      relatedPhase: "Phase 48 Brain Mutation Governance Console",
    }),
    buildMissionSurface({
      id: "files",
      label: "Project Reader + Real Patch Preview + Approved Patch Apply",
      href: "/files",
      status: "online",
      role: "Real Local Project Reader readiness plus Real Patch Preview readiness and Approved Patch Apply readiness for file tree, read-only file preview, preview-only unified diff artifacts, approval packet, preflight, dry-run preview, rollback, validation capture, and request-ready/blocked bridge state.",
      riskPosture: "preview-only",
      nextAction: "Review approved patch apply.",
      readiness: "needs-review",
      relatedPhase: "Phase 56 Real Local Project Reader, Phase 57 Real Patch Preview v1, and Phase 58 Approved Patch Apply v1",
    }),
    buildMissionSurface({
      id: "approved-patch-apply",
      label: "Approved Patch Apply",
      href: "/files",
      status: "approval-gated",
      role: "Approved Patch Apply v1 request-ready surface for preview diff to approval packet, policy, preflight, dry-run preview, rollback plan, validation commands, and guarded bridge state; no command execution, no direct apply-diff from UI, and no file writes without approval.",
      riskPosture: "approval-required",
      nextAction: "Review approved patch apply.",
      readiness: "needs-review",
      relatedPhase: "Phase 58 Approved Patch Apply v1",
    }),
    buildMissionSurface({
      id: "validation-runner",
      label: "Validation Runner",
      href: "/validation",
      status: "approval-gated",
      role: "Validation Runner readiness for allowlisted build, smoke, and git-check commands with explicit approval, policy checks, preflight, guarded bridge request-ready/manual-only status, output capture, and result routing.",
      riskPosture: "approval-required",
      nextAction: "Run approved validation.",
      readiness: "needs-review",
      relatedPhase: "Phase 59 Validation Runner v1",
    }),
    buildMissionSurface({
      id: "capabilities",
      label: "Capabilities",
      href: "/capabilities",
      status: "review-needed",
      role: "Tool posture, adapter readiness, and policy boundaries.",
      riskPosture: "approval-required",
      nextAction: "Review capability readiness.",
      readiness: "needs-review",
      relatedPhase: "Capability Cockpit",
    }),
    buildMissionSurface({
      id: "runs",
      label: "Runs",
      href: "/runs",
      status: "approval-gated",
      role: "Operator run queues, replay packets, and guarded execution state.",
      riskPosture: "approval-required",
      nextAction: "Open Operator Run Center.",
      readiness: "preview-only",
      relatedPhase: "Operator Run Center",
    }),
    buildMissionSurface({
      id: "bridge",
      label: "Bridge",
      href: "/bridge",
      status: "approval-gated",
      role: "Local bridge consent, adapter handshake, and run handoff posture.",
      riskPosture: "guarded-handoff",
      nextAction: "Inspect bridge readiness.",
      readiness: "future-gated",
      relatedPhase: "Jarvis Local Bridge",
    }),
    buildMissionSurface({
      id: "creative",
      label: "Creative",
      href: "/creative",
      status: "preview-ready",
      role: "Creative briefs, production planning, and artifact handoffs.",
      riskPosture: "preview-only",
      nextAction: "Review creative production queue.",
      readiness: "ready",
      relatedPhase: "Creative Production Studio",
    }),
    buildMissionSurface({
      id: "blender",
      label: "Blender Adapter Preview",
      href: "/blender",
      status: "preview-ready",
      role: "Blender Adapter Preview v1 readiness for scene input, typed scene model, object/material/light/camera/render plans, Python script preview, safety policy, and future executor packet.",
      riskPosture: "preview-only",
      nextAction: "Review Blender adapter preview.",
      readiness: "preview-only",
      relatedPhase: "Phase 62 Blender Adapter Preview v1",
    }),
    buildMissionSurface({
      id: "unreal",
      label: "Unreal Adapter Preview",
      href: "/unreal",
      status: "preview-ready",
      role: "Unreal Adapter Preview v1 readiness for project input, typed level model, actor/asset/material/Blueprint/Sequencer plans, build settings, command preview, safety policy, and future executor packet.",
      riskPosture: "preview-only",
      nextAction: "Review Unreal adapter preview.",
      readiness: "preview-only",
      relatedPhase: "Phase 65 Unreal Adapter Preview v1",
    }),
    buildMissionSurface({
      id: "creative-bridge",
      label: "Creative Local Bridge",
      href: "/creative-bridge",
      status: "preview-ready",
      role: "Creative bridge profiles, adapter readiness, job request preview, approval packet, artifact capture plan, and future executor handoff.",
      riskPosture: "preview-only",
      nextAction: "Review creative bridge readiness.",
      readiness: "preview-only",
      relatedPhase: "Creative Local Bridge v1",
    }),
    buildMissionSurface({
      id: "artifacts",
      label: "Artifacts",
      href: "/artifacts",
      status: "approval-gated",
      role: "Executor previews and guarded artifact workspace review.",
      riskPosture: "approval-required",
      nextAction: "Review artifact workspace.",
      readiness: "needs-review",
      relatedPhase: "Artifact Executor and Guarded Artifact Workspace",
    }),
    buildMissionSurface({
      id: "production",
      label: "Production",
      href: "/production",
      status: "approval-gated",
      role: "Preview packs, manifests, validation, and export readiness.",
      riskPosture: "approval-required",
      nextAction: "Build production pack.",
      readiness: "needs-review",
      relatedPhase: "Production Pack Builder",
    }),
    buildMissionSurface({
      id: "patch-preview",
      label: "Real Patch Preview, Approved Patch Apply, Regression Fix Queue, Patch Preview Queue, Preview Diff Composer, Patch Application Gate, Apply-Diff Dry Run, Apply-Diff Execution Gate, and Grounded Fix Recommendation",
      href: "/files",
      status: "preview-ready",
      role: "Real Patch Preview v1 functional/preview-only before any file mutation path, Approved Patch Apply v1 approval-gated/request-ready, grounded fix recommendations that route edits to preview-only handoff, queued patch preview items, Preview Diff Composer pseudo-diff packages, Patch Application Gate approval packets, Apply-Diff Dry Run result ledgers, and Apply-Diff Execution Gate request readiness.",
      riskPosture: "preview-only",
      nextAction: "Prepare preview diff.",
      readiness: "preview-only",
      relatedPhase: "Phase 57 Real Patch Preview v1, Regression Fix Queue, Patch Preview Queue, Preview Diff Composer, Patch Application Gate, Apply-Diff Dry Run, Apply-Diff Execution Gate, and Grounded Fix Recommendation",
    }),
    buildMissionSurface({
      id: "chat",
      label: "Chat and Evidence-Grounded Chat",
      href: "/ai",
      status: "online",
      role: "Primary workspace for planning, operator context, replies, visible chat recall context cards, Evidence-Grounded Chat readiness with selected evidence only, and Grounded Fix Recommendation readiness.",
      riskPosture: "readonly",
      nextAction: "Review grounded fix recommendation.",
      readiness: "ready",
      relatedPhase: "Chat Context Injection from Brain Recall, Evidence-Grounded Chat, and Grounded Fix Recommendation",
    }),
  ];

  return {
    id: "mission-surface-registry",
    surfaces,
    summary: summarizeMissionSurfaces(surfaces),
  };
}

export function summarizeMissionSurfaces(surfaces: MissionSurface[]): string[] {
  const readyCount = surfaces.filter((surface) => surface.readiness === "ready").length;
  const gatedCount = surfaces.filter(
    (surface) =>
      surface.riskPosture === "approval-required" ||
      surface.riskPosture === "guarded-handoff"
  ).length;

  return [
    `${surfaces.length} mission surfaces registered.`,
    `${readyCount} surfaces are ready for readonly review.`,
    `${gatedCount} surfaces are approval gated or guarded handoffs.`,
  ];
}
