import type { MissionNextAction } from "./mission-control-types";

export function buildMissionNextActions(): MissionNextAction[] {
  return [
    {
      id: "open-product-simplification-start",
      label: "Open guided Start",
      href: "/start",
      priority: "primary",
      readiness: "ready",
      safetyNote: "Product Simplification readiness is a UX/product layer only: choose a user intent, follow guided workflows, keep advanced details collapsed, and recommend Real Workflow Wizard v1; no execution, no file writes, and no Brain graph mutation.",
    },
    {
      id: "configure-ai-router",
      label: "Configure AI subscriptions/local models",
      href: "/ai-router",
      priority: "primary",
      readiness: "needs-review",
      safetyNote: "AI Router stores metadata only: no secrets stored, route recommendations are deterministic, token estimates are approximate, and provider execution remains outside this control plane.",
    },
    {
      id: "inspect-project-files",
      label: "Inspect project files",
      href: "/files",
      priority: "secondary",
      readiness: "ready",
      safetyNote: "Project Reader is File Reader v1 functional/read-only: inspect local project files, capped previews, metadata, purpose, risk, and Safe Patch Preview handoff without file writes or command execution.",
    },
    {
      id: "prepare-real-patch-preview-diff",
      label: "Prepare preview diff",
      href: "/files",
      priority: "secondary",
      readiness: "preview-only",
      safetyNote: "Real Patch Preview readiness is functional/preview-only: prepare preview diff from selected read file context and requested change; no file writes, no apply, no command execution, and use Patch Application Gate before apply.",
    },
    {
      id: "review-approved-patch-apply",
      label: "Review approved patch apply",
      href: "/files",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Approved Patch Apply readiness converts preview diff into approval packet, preflight, dry-run preview, rollback, validation checklist, and request-ready/blocked bridge state; no command execution, no direct apply-diff from UI, no file writes without approval, and Phase 59 Validation Runner v1 is next.",
    },
    {
      id: "review-real-apply-guard",
      label: "Review apply guard",
      href: "/apply-guard-review",
      priority: "primary",
      readiness: "needs-review",
      safetyNote: "Real Apply Guard Review readiness checks approval, diff/path boundaries, rollback, command/write separation, validation, blocked failure routing, and go/no-go before any apply automation increase; executionAllowed false, no auto-apply, no auto-run, and preserve latest-message authority.",
    },
    {
      id: "review-guarded-apply-candidate",
      label: "Clear guarded apply blocker gaps",
      href: "/guarded-apply-candidate",
      priority: "primary",
      readiness: "needs-review",
      safetyNote: "Guarded Apply Candidate readiness keeps the first candidate to one file, one diff, one approval, one rollback, one validation checklist, and result handoff. Next action: clear blocker gaps before implementation. Execution allowed false in Phase 83.",
    },
    {
      id: "run-approved-validation",
      label: "Run approved validation",
      href: "/validation",
      priority: "primary",
      readiness: "needs-review",
      safetyNote: "Validation Runner readiness is approval-gated/request-ready/manual-only: copy allowlisted commands or use guarded bridge only after approval, policy, and preflight; no arbitrary shell, no file writes, no Brain graph mutation, and preserve latest-message authority.",
    },
    {
      id: "review-stabilization-command-center",
      label: "Review stabilization command center",
      href: "/stabilization",
      priority: "primary",
      readiness: "needs-review",
      safetyNote: "Stabilization Command Center rolls build and smoke posture, verification signals, regression triage, fix queue, patch queue, apply gates, post-apply verification, and next safest action into a read-only operator review; no auto-fix, no auto-rollback, no command execution, no file writes, and preserve latest-message authority.",
    },
    {
      id: "review-activity-feed",
      label: "Review activity feed",
      href: "/activity",
      priority: "secondary",
      readiness: "ready",
      safetyNote: "Global Activity Feed is read-only and deterministic; no command execution, no file writes, no Brain graph mutation, no auto-persistence, and preserve latest-message authority.",
    },
    {
      id: "review-runtime-event-executor",
      label: "Review runtime event executor",
      href: "/memory-inbox",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Guarded Runtime Event Executor readiness requires request, policy, validation, explicit approval, reducer preview, audit ledger, and result review; no mutation command and no auto-promotion.",
    },
    {
      id: "review-runtime-event-journal",
      label: "Review runtime event journal",
      href: "/runtime-journal",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Runtime Event Journal is read-only lifecycle visibility for requests, approvals, policy, validation, reducer previews, blocked or ready results, and append-only audit handoff; no graph mutation and no event append from UI.",
    },
    {
      id: "review-runtime-event-replay",
      label: "Review runtime event replay",
      href: "/runtime-replay",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Runtime Event Replay Simulator is preview-only reducer-backed simulation for selected journal events and graph snapshots; no graph mutation, no appendEvent, no event execution, no auto-persistence, and preserve latest-message authority.",
    },
    {
      id: "review-brain-mutation-governance",
      label: "Review brain mutation governance",
      href: "/brain-governance",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Brain Mutation Governance is read-only mutation boundary visibility for direct mutation signals, reducer impact, runtime journal integrity, and risk review; no graph mutation from UI and no auto-promotion.",
    },
    {
      id: "review-brain-snapshots",
      label: "Review Brain snapshots",
      href: "/brain-snapshots",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Brain Snapshot Manager readiness covers read-only snapshot comparison, integrity review, replay source selection, rollback planning, and memory governance review; no graph mutation, no appendEvent, no saveBrainGraph from UI, and no snapshot restore in Phase 50.",
    },
    {
      id: "review-snapshot-restore-gate",
      label: "Review snapshot restore gate",
      href: "/snapshot-restore",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Snapshot Restore Approval Gate readiness covers restore candidate, comparison evidence, replay evidence, governance review, runtime journal review, approval packet, and request preview; restore blocked by default, no graph mutation, no appendEvent, no saveBrainGraph from UI, and future guarded snapshot executor required.",
    },
    {
      id: "review-brain-continuity",
      label: "Review Brain continuity",
      href: "/brain-continuity",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Brain Continuity Dashboard readiness covers memory growth, runtime event journal health, snapshot posture, replay readiness, restore risk, governance posture, and next safe action; read-only, no graph mutation, no snapshot restore, no appendEvent, and no saveBrainGraph from UI.",
    },
    {
      id: "create-continuity-handoff",
      label: "Create continuity handoff",
      href: "/handoff",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Continuity Handoff Packet readiness combines current state, risks, validation, rollback, memory, Brain continuity, runtime event, snapshot restore posture, and next safe actions; copy-only, no graph mutation, no command execution, no file writes, and preserve latest-message authority.",
    },
    {
      id: "review-memory-inbox",
      label: "Review memory inbox",
      href: "/memory-inbox",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Personal Operator Memory Inbox is review-first and preview-only; no auto-promotion, no Brain graph mutation, no auto-merge, no file writes, no command execution, and preserve latest-message authority.",
    },
    {
      id: "return-to-operator-home",
      label: "Return to Operator Home",
      href: "/",
      priority: "secondary",
      readiness: "ready",
      safetyNote: "Operator Home Dashboard readiness gives the full launch deck, route status, local-first safety posture, validation checklist, and next safe action without command execution or file writes.",
    },
    {
      id: "review-regression-triage",
      label: "Review regression triage",
      href: "/files",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Self-Healing Regression Triage turns failed or warning verification signals into reviewed regression cards, suspected causes, impacted files, rollback advice, fix recommendations, and Safe Patch Preview handoff only; no auto-fix, no auto-rollback, no command execution, no file writes, and preserve latest-message authority.",
    },
    {
      id: "review-regression-fix-queue",
      label: "Review regression fix queue",
      href: "/files",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Regression Fix Queue turns reviewed regression triage cards into prioritized repair queue handoffs for Safe Patch Preview and Preview Diff Composer only; no auto-fix, no auto-rollback, no command execution, no file writes, and preserve latest-message authority.",
    },
    {
      id: "compose-preview-diff",
      label: "Compose preview diff",
      href: "/files",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Preview Diff Composer readiness packages queued patch preview items into human-reviewable pseudo-diffs; preview-only, not an applyable patch, current file content is authority, evidence is context not proof, and no file writes without approval.",
    },
    {
      id: "review-apply-gate",
      label: "Review apply gate",
      href: "/files",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Patch Application Gate readiness prepares explicit human approval packets and display-only apply request previews; actual mutation remains blocked, apply-diff requires tool-policy approval, current files must be verified, rollback plan required, and preserve latest-message authority.",
    },
    {
      id: "build-apply-evidence-pack",
      label: "Build apply evidence pack",
      href: "/files",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Apply Evidence Pack readiness bundles current file verification, rollback plan, test plan, operator approval note, evidence refs, smoke placeholders, mutation firewall, and final readiness; it does not apply changes and is future guarded apply only.",
    },
    {
      id: "review-apply-diff-dry-run-result",
      label: "Review dry-run result",
      href: "/files",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Apply-Diff Dry Run readiness simulates apply-diff policy, affected file validation, conflict checks, result, and ledger only; simulation only, no mutation, actual apply-diff remains blocked, current file verification required, rollback plan required, and preserve latest-message authority.",
    },
    {
      id: "review-approved-apply-request",
      label: "Review approved apply request",
      href: "/files",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Apply-Diff Execution Gate readiness prepares an approval-gated apply-diff request packet and guarded execute route bridge; explicit operator approval required, no silent execution, rollback plan required, verification required after dispatch, and preserve latest-message authority.",
    },
    {
      id: "review-patch-preview-queue",
      label: "Review queued patch preview",
      href: "/files",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Patch Preview Queue readiness packages reviewed fix recommendations for Safe Patch Preview; preview diff only, verify current files, no file writes without approval, no command execution without approval, and preserve latest-message authority.",
    },
    {
      id: "review-grounded-fix-recommendation",
      label: "Review grounded fix recommendation",
      href: "/files",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Grounded Fix Recommendation reviews evidence and file context, then prepares Safe Patch Preview handoff only; no command execution, no apply, and no file mutation.",
    },
    {
      id: "use-reviewed-evidence-in-chat",
      label: "Use reviewed evidence in chat",
      href: "/jarvis",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Evidence-Grounded Chat uses selected evidence only, shows local citations and stale or weak warnings, and allows copy/use prompt handoff without hidden context injection.",
    },
    {
      id: "review-read-only-evidence-memory",
      label: "Review read-only evidence memory",
      href: "/memory",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Evidence Memory converts read-only execution evidence into reviewable candidates only; Review required before memory promotion, Brain merge review required, and no graph mutation.",
    },
    {
      id: "execute-approved-read-only-step",
      label: "Execute approved read-only step",
      href: "/tasks",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Read-Only Step Execution runs only approved local read-only tools, captures visible evidence, and keeps mutation tools blocked.",
    },
    {
      id: "preview-task-step-run",
      label: "Preview a task step run",
      href: "/tasks",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Step Runner Preview prepares policy posture, approval packet, dry run plan, and result preview only; No step execution in Phase 25 and Future run requires approval.",
    },
    {
      id: "review-execution-readiness",
      label: "Review execution readiness",
      href: "/tasks",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Execution Readiness reviews step preflight, tool posture, risk, tests, and approval gates; execution blocked until approval.",
    },
    {
      id: "activate-reviewed-task",
      label: "Activate reviewed task",
      href: "/tasks",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Reviewed Task Activation creates a plan preview and visible copy-only Jarvis handoff; no hidden injection, no auto-run, and no file mutation.",
    },
    {
      id: "review-task-suggestions",
      label: "Review task suggestions",
      href: "/tasks",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Task Autopilot is review required, preview-only, and never auto-runs tasks.",
    },
    {
      id: "review-system-health",
      label: "Review system health",
      href: "/mission",
      priority: "secondary",
      readiness: "ready",
      safetyNote: "Readonly review inside Mission Control.",
    },
    {
      id: "open-files-command-center",
      label: "Open Files Command Center",
      href: "/files",
      priority: "secondary",
      readiness: "ready",
      safetyNote: "Open Project Reader to inspect project files before any external action.",
    },
    {
      id: "search-brain-memory",
      label: "Search Brain memory",
      href: "/brain",
      priority: "secondary",
      readiness: "ready",
      safetyNote: "Deterministic local recall only; no graph mutation and inspect before editing.",
    },
    {
      id: "use-recalled-memory-in-chat",
      label: "Use recalled memory in chat",
      href: "/jarvis",
      priority: "secondary",
      readiness: "ready",
      safetyNote: "Chat recall context is opt-in, visible, and no hidden context injection is allowed.",
    },
    {
      id: "prepare-patch-preview",
      label: "Prepare patch preview",
      href: "/files",
      priority: "secondary",
      readiness: "preview-only",
      safetyNote: "Use Project Reader selected file evidence to prepare Real Patch Preview v1 preview-only diffs.",
    },
    {
      id: "build-production-pack",
      label: "Build production pack",
      href: "/production",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Pack export remains approval gated.",
    },
    {
      id: "review-artifact-workspace",
      label: "Review artifact workspace",
      href: "/artifacts",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Artifact workspace export requires explicit approval.",
    },
    {
      id: "review-artifact-ingestion-candidates",
      label: "Review artifact ingestion candidates",
      href: "/memory",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Read-only memory candidates and brain signals require review before promotion.",
    },
    {
      id: "review-memory-candidates",
      label: "Review memory candidates",
      href: "/memory",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Memory promotion requires explicit review state and produces preview events only.",
    },
    {
      id: "review-approved-memory-events",
      label: "Review approved memory events",
      href: "/memory",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Approved memory persistence writes only local event JSON and does not merge graph memory.",
    },
    {
      id: "review-brain-event-merge",
      label: "Review Brain event merge",
      href: "/memory",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Brain merge review is preview-only; explicit merge approval required before any future graph mutation.",
    },
    {
      id: "apply-approved-brain-merge",
      label: "Apply approved Brain merge",
      href: "/memory",
      priority: "secondary",
      readiness: "needs-review",
      safetyNote: "Approved Brain merge updates the local graph only after explicit approval, policy validation, and graph diff review.",
    },
    {
      id: "inspect-bridge-readiness",
      label: "Inspect bridge readiness",
      href: "/bridge",
      priority: "secondary",
      readiness: "future-gated",
      safetyNote: "Bridge consent remains guarded.",
    },
    {
      id: "review-creative-bridge",
      label: "Review creative bridge",
      href: "/creative-bridge",
      priority: "secondary",
      readiness: "preview-only",
      safetyNote: "Creative Local Bridge is preview-only/request-ready; no local render app, command, provider, or artifact file execution is launched from Mission Control.",
    },
    {
      id: "review-video-render-job-preview",
      label: "Review video render job preview",
      href: "/video-render",
      priority: "secondary",
      readiness: "preview-only",
      safetyNote: "Video Render Job Preview readiness is preview-only/request-ready for render queue and future executor packet review; no render execution, no Blender execution, no ComfyUI execution, no Unreal execution, no ffmpeg execution, no file writes, and preserve latest-message authority.",
    },
    {
      id: "review-guarded-creative-executor",
      label: "Review creative executor dry-run",
      href: "/creative-executor",
      priority: "secondary",
      readiness: "preview-only",
      safetyNote: "Guarded Creative Executor readiness is dry-run-first/request-ready; review creative executor dry-run, adapter allowlist, approval, kill-switch policy, and artifact capture while execution remains disabled.",
    },
    {
      id: "run-creative-execution-sandbox",
      label: "Run sandbox simulation",
      href: "/creative-sandbox",
      priority: "secondary",
      readiness: "preview-only",
      safetyNote: "Creative Execution Sandbox readiness is simulation-only: run sandbox simulation for fake lifecycle, cancellation, artifact placeholders, logs, verification, and review handoff. No real execution, no command execution, no render execution, no local HTTP calls, no file writes, and preserve latest-message authority.",
    },
    {
      id: "review-creative-readiness",
      label: "Review creative readiness",
      href: "/creative-readiness",
      priority: "secondary",
      readiness: "preview-only",
      safetyNote: "Real Creative Executor Readiness Audit readiness is audit-only: review creative readiness before Phase 71 Future Guarded Health Probe. No real execution, no command execution, no render execution, no local HTTP calls, no provider calls, no file writes, execution allowed false, and preserve latest-message authority.",
    },
    {
      id: "review-local-bridge-health",
      label: "Review local bridge health",
      href: "/local-bridge-health",
      priority: "secondary",
      readiness: "preview-only",
      safetyNote: "Local Bridge Health readiness is preview/manual-only/future-guarded; review local bridge health before creative executor handoff. No command execution, no local HTTP calls by default, no file writes, and no render execution.",
    },
    {
      id: "review-future-guarded-health-probe",
      label: "Review guarded health probe",
      href: "/health-probe",
      priority: "secondary",
      readiness: "preview-only",
      safetyNote: "Future Guarded Health Probe readiness is metadata/manual-first/request-ready; review guarded health probe evidence only. Real probes disabled by default, no creative job execution, no render execution, no arbitrary command, no arbitrary endpoint, no file writes, and preserve latest-message authority.",
    },
    {
      id: "review-real-creative-executor-mvp-design",
      label: "Review MVP candidate",
      href: "/creative-mvp",
      priority: "secondary",
      readiness: "preview-only",
      safetyNote: "Real Creative Executor MVP Design readiness is design-only: review MVP candidate artifact-capture-only, output boundary, approval packet, kill-switch posture, artifact review loop, and user-friendly flow. Execution allowed false, no real execution, no render execution, no command execution, no local HTTP calls, no file writes, and preserve latest-message authority.",
    },
    {
      id: "review-blender-adapter-preview",
      label: "Review Blender adapter preview",
      href: "/blender",
      priority: "secondary",
      readiness: "preview-only",
      safetyNote: "Blender Adapter Preview readiness is preview-only/request-ready for scene model, Python preview, and future executor packet review; no Blender execution, no render execution, no file writes, and preserve latest-message authority.",
    },
    {
      id: "review-unreal-adapter-preview",
      label: "Review Unreal adapter preview",
      href: "/unreal",
      priority: "secondary",
      readiness: "preview-only",
      safetyNote: "Unreal Adapter Preview readiness is preview-only/request-ready for level model, command preview, and future executor packet review; no Unreal execution, no Unreal Editor launch, no render execution, no package/build, no file writes, and preserve latest-message authority.",
    },
    {
      id: "open-operator-run-center",
      label: "Open Operator Run Center",
      href: "/runs",
      priority: "secondary",
      readiness: "preview-only",
      safetyNote: "No execution action is launched from Mission Control.",
    },
  ];
}

export function selectPrimaryMissionAction(
  actions: MissionNextAction[] = buildMissionNextActions()
): MissionNextAction {
  return actions.find((action) => action.priority === "primary") ?? actions[0];
}

export function summarizeMissionNextActions(
  actions: MissionNextAction[] = buildMissionNextActions()
): string[] {
  return [
    `${actions.length} safe next actions are available.`,
    "Every action navigates to a review surface instead of executing work.",
  ];
}
